In [1]:
# Core libraries
from pathlib import Path
import sys

import pandas as pd
from google.cloud import bigquery

In [2]:
# Setting project paths and loading helper functions for configuration, credentials and SQL execution

project_root = Path.cwd().resolve().parent if Path.cwd().name == "notebooks" else Path.cwd().resolve()
scripts_directory = project_root / "scripts"

if str(scripts_directory) not in sys.path:
    sys.path.append(str(scripts_directory))

from run_sql_scripts import load_project_configuration
from run_sql_scripts import configure_google_credentials
from run_sql_scripts import execute_sql_file

In [3]:
# Loading project configuration and creating a BigQuery client for running analysis queries

configuration = load_project_configuration()
configure_google_credentials(credentials_path_value = configuration["credentials_path"])

bigquery_client = bigquery.Client(project = configuration["gcp_project_id"])


def run_query(sql_text):
    return bigquery_client.query(sql_text).to_dataframe()

#### Run the ingestion pipeline to generate the raw dataset fully first : python3 scripts/run_ingestion_pipeline.py

In [4]:
# Inspecting 'Home and Kitchen' category values to validate category filtering rules

home_and_kitchen_main_category_query = f"""
SELECT
    main_category,
    COUNT(*) AS product_count
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_raw_dataset_id"]}.meta_home_and_kitchen_raw`
GROUP BY main_category
ORDER BY product_count DESC, main_category
"""

home_and_kitchen_category_values_query = f"""
SELECT DISTINCT
    category_element
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_raw_dataset_id"]}.meta_home_and_kitchen_raw`,
UNNEST(JSON_VALUE_ARRAY(categories)) AS category_element
WHERE category_element IS NOT NULL
  AND TRIM(category_element) <> ''
ORDER BY category_element
"""

home_and_kitchen_main_category_dataframe = run_query(home_and_kitchen_main_category_query)
display(home_and_kitchen_main_category_dataframe)

home_and_kitchen_category_values_dataframe = run_query(home_and_kitchen_category_values_query)
home_and_kitchen_category_values_list = home_and_kitchen_category_values_dataframe["category_element"].tolist()
for category_value in home_and_kitchen_category_values_list:
    print(category_value)

                   main_category  product_count
0                    Amazon Home        2914556
1                           None         363310
2       Tools & Home Improvement         168402
3                   Toys & Games          52371
4        Industrial & Scientific          36016
5         Health & Personal Care          31922
6                 AMAZON FASHION          28291
7                Office Products          27624
8              Sports & Outdoors          16632
9                     Appliances          15534
10         Arts, Crafts & Sewing          14677
11                      Handmade          14599
12                          Baby           9436
13                    All Beauty           8861
14               All Electronics           7767
15                    Automotive           4897
16     Cell Phones & Accessories           4409
17                       Grocery           4134
18          Home Audio & Theater           3495
19                  Pet Supplies           2639
20           Musical Instruments           2090
21                Camera & Photo           1589
22                     Computers           1414
23                   Video Games            248
24                 Entertainment            142
25                      Software            127
26               Car Electronics            118
27                Premium Beauty             88
28  Portable Audio & Accessories             66
29             Collectible Coins             25
30           Sports Collectibles             25
31            Audible Audiobooks             24
32                         Books             23
33                Amazon Devices             12
34              GPS & Navigation              8
35                    Gift Cards              5
36                   Movies & TV              3
37                      Fine Art              2
38            SUBSCRIPTION BOXES              2
39                  Unique Finds              1

$30 Off Silhouette CAMEO Bundles
30% off Handicrafts & Home Decor
40 Pint Dehumidifiers
:USE
A sustainable mindset
Above $50
Accent Furniture
Accent furniture
Accents
Accessories
Accessory Organizers
Accessory organization
Ace Bayou
Acid-Free & Archival Page Albums
Adesso
Adjustable Bases
Adult Novelty
Advent Calendars
Aeration Equipment
Air Conditioner Parts & Accessories
Air Conditioners
Air Fryers
Air Ionizers
Air Mattresses
Air Mattresses & Accessories
Air Purifier Parts & Accessories
Air Purifiers
Air purifiers, humidifiers & essential oil diffusers
Air purifying plants & planters
Airlocks
Aisle Runners
Alarm Clocks
Alen T500 Air Purifiers
All Great Point Light Products
All Kurt Adler
All Lacrosse Technology Products
All Products
All SINGER
Amazon Financing Offers in Home & Garden
Amazon Store Card Promotion
An Organized Home: Garage
Andirons
Angel Food
Anna Buechin
Appetizer Plates
Appetizers
Aprons
Area Rug Sets
Area Rugs
Armchair Slipcovers
Armchairs
Armoires & Dressers
Art & Home Decor
Art, Décor and Accessories
Artificial Flowers
Artificial Fruit
Artificial Plants & Flowers
Artificial Plants & Greenery
Artificial Shrubs
Artificial Shrubs & Topiaries
Artificial Snow
Artificial Topiaries
Artificial Trees
Artificial Vegetables
Arts, Craft, & Sewing Best Sellers
Arts, Crafts & Sewing
Arts, Crafts, & Sewing
Artwork
Ashtrays
Asian
Asian Knives
Asparagus Servers
At-Home Espresso
Attachments
Attachments & Brushes
Au Gratin Pans
Audio-Visual Shelving
Avery
BYOC Customer's Favorite ASIN Input #3
Baby Shower
Baby's 1st Birthday
Backpacks & Lunch Boxes
Bagel Slicers
Bags
Bake & Serve Sets
Baker's Racks
Bakers
Bakers & Casseroles
Bakeware
Bakeware Sets
Baking & Cookie Sheets
Baking & Pastry Utensils
Baking Cups
Baking Mats
Baking Tools & Accessories
Ball Ornaments
Balloon Shades
Balloons
Banners
Bar & Serving Carts
Bar & Wine Tools
Bar Cabinets
Bar Sets
Bar Strainers
Bar Tables
Bar Tools
Bar Tools & Drinkware
Barrels
Bars & Wine Cabinets
Barstools
Barware
Bases & Foundations
Baskets
Baskets & Bins
Baskets & Shelves
Baskets & bins
Baskets & hampers
Baskets, Bins & Containers
Basters
Bath
Bath Accessories
Bath Linen Sets
Bath Mats & Treads
Bath Rugs
Bath Sheets
Bath Suction Storage
Bath Towels
Bathroom Accessories
Bathroom Accessory Sets
Bathroom Furniture
Bathroom Mirrors
Bathroom Sets
Bathroom Storage & Organization
Bathroom Trays
Bathroom organization
Bathtub Accessories
Bathtub Appliques
Bathtub Mats
Bathtub Trays
Batter Dispensers
Batteries
Beach Towels
Bean Bags
Bean Bags, Covers & Refills
Beaters
Bed Blankets
Bed Canopies & Drapes
Bed Frames
Bed Frames, Headboards & Footboards
Bed In A Bag
Bed Parts
Bed Pillows
Bed Pillows & Positioners
Bed Risers
Bed Runners & Scarves
Bed Skirt Pins
Bed Skirts
Bed Slats
Bed, Bath & Laundry
Bed_Frame
Bedding
Bedding & Bath
Bedding Accessories
Bedding Collections
Bedding Sets & Collections
Bedrests & Throw Pillows
Bedroom Armoires
Bedroom Furniture
Bedroom Sets
Beds
Beds & Mattresses
Beds and Nightstands
Beds, Frames & Bases
Bedsheets store
Bedspread & Coverlet Sets
Bedspreads & Coverlets
Bedspreads, Coverlets & Sets
Beer Brewing
Beer Glasses
Beer Mugs & Steins
Bellows
Bells & Sleigh Bells
Belt Racks
Belts
Benches
Benches & Cubbies
Bento Boxes
Berry Spoons
Best Deal on Kitchen accessories
Best sellers in Patio, Lawn & Garden
Beverage Serveware
Beverage Tubs
Beverage Warmers
Bins
Bins & Baskets
Birthday Candles
Birthday Party
Blankets & Throws
Blender Replacement Parts
Blenders
Blinds & Shades
Body Pillows
Boho style
Bold Eclectic
Bold natural palette
Boning Knives
Bookcases
Bookcases, Cabinets & Shelves
Bookends
Bookshelf Albums
Bookshelves & cubbies
Boot & Shoe Boxes
Bottle Openers
Bottle Pourer Spouts
Bottles
Bottles & Bottling
Bottling & Corking
Bouillon Cups
Bowl Candleholders
Bowl Sets
Bowls
Bows & Ribbons
Box Packs
Box Springs
Boxes & Bags
Boxes & Baskets
Boxes & Bins
Boxes & bins
Boxes & trays
Bracelet Packs
Braisers
Brass & gold accents
Bread & Butter Plates
Bread & Loaf Pans
Bread & Serving Baskets
Bread Boxes
Bread Knives
Bread Machine Parts & Accessories
Bread Machines
Bread Proofing Baskets
Breakfast
Breakfast Trays
Breakfast, Lunch, Dinner, Dessert
Brew Pots, Kettles & Accessories
Bridal Shower
Brioche Pans
Brushes
Buffet Tongs
Buffets & Sideboards
Built-In Wine Cellars
Bundt Pans
Bunk Beds
Bunkie Boards
Burners
Bush Entertainment Furniture
Business Pricing: Furniture
Business Pricing: Home
Business Pricing: Kitchen
Busts
Butter Dishes
Butter Knives
Butter Warmers
Buy Any 3 Get the 4th Free
CML Placeholder Furniture
CML Placeholder Kitchen
Cabinet & Drawer Organization
Cabinet & Pantry Organizers
Cabinet Accessories
Cabinet Door Organizers
Cabinets
Cabinets & Shelves
Café Curtain Rings
Café Rods
Cake Carriers
Cake Decorating Kits
Cake Decorating Supplies
Cake Decorating Tools
Cake Knives
Cake Pans
Cake Pop Makers
Cake Pop Molds
Cake Rings
Cake Stands
Cake Testers
Cake, Pie & Pastry Servers
California Casual
California Design Den
Calvin Klein Home
Can Crushers
Can Openers
Candelabras
Candle Chandeliers
Candle Lamps
Candle Sconces
Candle Sets
Candle Shades
Candle Sleeves
Candleholder Sets
Candleholders
Candles
Candles & Holders
Candles and candle holders
Candles in fresh scents
Candlesnuffers
Candlestick Holders
Candy
Candy Bottles
Candy Making Accessories
Candy Making Supplies
Candy Molds
Candy Servers
Canister Bags
Canister Filters
Canister Vacuums
Canisters
Canning
Canning Store New
Canopies
Cans
Carafes
Carboys
Card Boxes
Cardboard Cutouts
Carpet & Upholstery Cleaners & Accessories
Carpet Cleaning
Carpet Cleaning Machine Accessories
Carpet Cleaning Machines
Carving Knives
Carving Sets
Caspari
Casserole Spoons
Casserole dishes
Casseroles
Cassette Storage
Caviar Spoons
Celebration Essentials
Celestial pumpkins
Celestial-inspired decor
Cellular Shades
Centerpiece Bowls
Centerpieces
Central Vacuum Bags
Central Vacuum Filters
Central Vacuum Installation Parts
Central Vacuum Systems
Central Vacuums
Centrifugal Juicers
Ceramics Made in Italy
Cereal Bowls
Cereal Containers
Ceremony Supplies
Chafing Dishes
Chair Pads
Chairs
Chairs & Recliners
Chairs & Seats
Chaise Lounges
Champagne Glasses
Chantal Trudel
Charcoal Air Purifiers
Charger Plates
Chargers
Cheese Knives
Cheese Makers
Cheese Markers
Cheese Servers
Cheese Slicers
Cheese Tools
Chef's Knives
Chef's Pans
Chests & Trunks
Children's Clothes Hangers
Chimney Brushes
Chimney Caps
Chinese Chef's Knives & Cleavers
Chinese Spoons
Chinese Vegetable Knives
Chip & Dip Sets
Chocolate Fountains
Chocolate Molds
Choppers
Choppers & Mincers
Chopstick & Cutlery Rests
Chopstick Rests & Holders
Chopsticks
Christmas
Christmas Lights
Christmas Store
Christmas Tree Skirts
Christmas Trees
Citrus Juicers
Clara Clark Sheets
Classic holiday wreath materials
Classic mantle décor
Clean lines
Cleaning & Sanitizing
Cleaning Brushes
Cleaning Solutions
Cleaning Supplies
Cleaning essentials
Cleavers
Clip Photo Holders
Clip Rings
Clocks
Closet
Closet Rods
Closet Rods & Shelves
Closet Shelf & Rod Brackets
Closet Shelves
Cloth Napkins
Clothes Hangers
Clothes Pins
Clotheslines
Clothing & Closet Storage
Coastal Cowgirl
Coastal Vibes: Indigo Accents
Coasters
Coat Hangers
Coat Hooks
Coat Racks
Cocktail Drinkware
Cocktail Forks
Cocktail Napkins
Cocktail Party
Cocktail Picks
Cocktail Shakers
Coffee & Espresso Machine Cleaning Products
Coffee & Espresso Machine Parts & Accessories
Coffee & Espresso Spoons
Coffee & Tea
Coffee Containers
Coffee Cups & Mugs
Coffee Filters
Coffee Grinders
Coffee Machine Accessories
Coffee Machines
Coffee Makers
Coffee Mugs
Coffee Pod Holders
Coffee Scoops
Coffee Servers
Coffee Serving Sets
Coffee Tables
Coffee Urns
Coffee and tea makers
Coffee, Tea & Espresso
Coffee, Tea & Espresso Appliances
Coffeemaker Pots
Colanders
Colanders & Food Strainers
Cold Brew Coffee Makers
Cold-Meat Forks
Collectible Buildings
Collectible Buildings & Accessories
Collectible Dolls
Collectible Figurines
Collectible Vehicles
Collection Curation
Collections
College Living
College Living - Kitchen & Dining
Collins Glasses
Color of the year
Color story: cobalt blue & cement gray
Color story: dark moss & terra cotta
Color story: dusty pink & bone white
Color story: tomato red & ice blue
Colorful beds & bedding
Colorful holiday wreath materials
Combination Water Boilers & Warmers
Comfort Mats
Comforter Sets
Comforters
Comforters & Sets
Commemorative & Decorative Plates
Compact Microwave Ovens
Compact Refrigerators
Computer Armoires & Hutches
Computer Gaming Chairs
Condiment Pots
Condiment Racks
Condiment Squeeze Bottles
Confetti
Consoles
Container Sets
Containers
Containers & planters
Contemporary sideboards and bar carts
Convection Ovens
Cookbook Stands
Cookbook Stands & Recipe Holders
Cookie Cutters
Cookie Exchange
Cookie Jars
Cookie Presses
Cookie Stamps
Cooking
Cooking & Entertaining
Cooking Dredges
Cooking Spoons
Cooking Torches
Cooking Utensils
Cookware
Cookware Accessories
Cookware Sets
Cookware, Bakeware & Dinnerware
Cooling & Air Quality
Cooling Products
Cooling Racks
Cordial Glasses
Cordless Vacuums
Corers
Corers & Pitters
Corkscrews & Openers
Corner Baker's Racks
Corner Shelves
Cosmetic & Vanity Organizers
Cosmetic Organizers
Cotton Candy Makers
Counter Accessories
Countertop Blenders
Countertop Burners
Countertop Microwave Ovens
Countertop Organizers
Countertop Pizza Ovens
Countertop Soap Dispensers
Country Style Accessories
Courtyard
Covers
Cozy at home
Cozy bedroom from @truehome_
Cozy comfort
Cozy holiday décor
Cozy throws
Cracker Spoons
Crafting for Valentine's Day
Cream
Cream & Sugar
Cream & Sugar Sets
Cream Chargers & Whippers
Cream Ladles
Creamers
Create a serene sanctuary
Creepy cloches
Crepe Makers
Crepe Pans
Cribs, Beds & Mattresses
Cricut March Crafting Month Deals
Crockery and tableware Made in Italy
Crushing, Pressing & Stemming
Cuckoo Clocks
Cuisinart Products
Cup & Saucer Sets
Cup Holders
Cupcake Carriers
Cupcake Makers
Cupcake Stands
Cups
Cups & Mugs
Cups, Mugs, & Saucers
Curio Cabinets
Current Trends in Home, Kitchen & Garden
Curtain Liners
Curtain Panels
Curtain Rods
Curtains & Drapes
Customers Keep It - 70%
Customers' Most-Loved Home & Kitchen v2
Customers' Most-Loved Home Decor
Customers' Most-Loved Home_Temp
Customers' Most-Loved: Home & Kitchen
Customers' Most-Loved: Home Upgrade
Customers' Most-Loved: Workout Picks
Customers' favorite air conditioners
Customers' favorite decor
Customizable Dining & Entertaining
Cutlery
Cutlery & Utensil Holders
Cutting Boards
DANSK
DIY_ACS
DVD Cases
DYRP Catalog
Damper Hooks
David Quan
Daybed Sets
Daybeds
Deals & Savings
Deals in Home, Kitchen, and Furniture
Deals in Restaurant supplies and Food Service Equipment
Deba Knives
Decor
Decorating & Pastry Bags
Decorating Tools
Decoration
Decorations
Decorative Accessories
Decorative Balls
Decorative Bells
Decorative Bookends
Decorative Bottles
Decorative Bowls
Decorative Boxes
Decorative Bulletin Boards
Decorative Candle Lanterns
Decorative Chalkboards
Decorative Folding Fans
Decorative Jars
Decorative Masks
Decorative Pillows
Decorative Pillows & Covers
Decorative Pillows, Inserts & Covers
Decorative Pitchers
Decorative Shower Curtain Hooks
Decorative Signs & Plaques
Decorative Stones
Decorative Swags
Decorative Telephones
Decorative Telescopes
Decorative Trays
Decorative Urns
Decorative Wreath Storage
Deep Fryer Parts & Accessories
Deep Fryers
Dehumidifier Parts & Accessories
Dehumidifiers
Dehydrators
Desert decor
Desert style decorative pillows
Design 101: Pairing desks & chairs
Design 101: counter & bar stools
Design 101: how to choose a lightbulb
Design 101: pairing floor & table lamps
Design 101: styling coffee table by shape
Design 101: styling throw pillows
Design Textures
Designer Picks: Art
Designer Picks: California Casual Accessories
Designer Picks: Chairs
Designer Picks: Decor
Designer Picks: Glam Accessories
Designer Picks: Lighting
Designer Picks: Sofas
Designer Rakhis
Designers
Desk & Shelf Clocks
Desk Chairs
Desk Supplies, Organizers & Dispensers
Desks
Desks & Desk Sets
Desks & Office Chairs
Dessert Bowls
Dessert Forks
Dessert Knives
Dessert Plates
Dessert Spoons
Deviled Egg Plates
Devotional Candles
Diffuse your space
Digital Scales
Dining & Entertaining
Dining Chair Slipcovers
Dining Room Furniture
Dinner Forks
Dinner Knives
Dinner Plates
Dinnerware
Dinnerware & Serveware
Dinnerware Sets
Directors Chairs
Discover Free One-Day Shipping Promotion
Dish Cloths & Dish Towels
Dish Drainers & Drying Mats
Dish Drying Mats
Dish Racks
Disney Frozen Home & Kitchen
Dispensers
Display Stands
Disposable Cookware
Disposable Table Covers
Divide and conquer
Divided Dishes, Trays & Platters
Diya & Puja
Document Frames
Doilies
Donut Pans
Dorel Furniture - All Brands/Student
Dorm Eating Essentials
Dorm Room Décor
Dorm Room HQ
Double Boilers
Double Rods
Dough Blenders
Draft Stoppers
Drafting Tables
Drain Stoppers
Drawer Handles & Pulls
Drawer Organizers
Drawer organizers
Drawers
Drawers, Trays & Bins
Drawers, Trays, & Bins
Drawings
Drawstring Bag Packs
Dream Catchers
Dress the part
Dressers
Dried & Preserved Flora
Dried Flowers
Dried Plants
Drink Stirrers
Drink buckets and dispensers
Drinking
Drinking Jars
Drinks & Desserts
Drinkware
Drip Coffee Makers
Drying Racks
Dutch Ovens
Dutch ovens
Duvet Cover Sets
Duvet Covers
Duvet Covers & Sets
Duvets & Down Comforters
Dyson Accessories
Dyson Upright Vacuums
Décor
Décor Accents
EF-Home-All
ELLE Decor picks
Easels
Easter
Easter 2019
Easter Bakeware
Easter décor
Easy upgrades
Eating
Edible Ink Printers
Egg Baskets
Egg Cookers
Egg Cups
Egg Poachers
Egg Separators
Egg Slicers
Egg Spoons
Egyptian Cotton
Egyptian-Themed
Electric
Electric Blade Grinders
Electric Blankets
Electric Burr Grinders
Electric Cake Pop & Mini Cake Makers
Electric Coffee Percolators
Electric Fireplaces
Electric Fondue Pots
Electric Griddles
Electric Grills
Electric Kettles
Electric Knives
Electric Mattress Pads
Electric Pasta Makers
Electric Pressure Cookers
Electric Skillets
Electric Slicers
Electric Space Heaters
Electric Stone Grills
Electric Stoves
Electric Throws
Electric Utensils
Electric Wine Bottle Openers
Electric Woks
Electrostatic Air Purifiers
Elegant Selection from Pulaski Furniture
Elevated entertainment
Elevating everywhere
End Tables
End Tables_set_3
End Tables_set_4
Entertainment Armoires
Entertainment Centers
Entryway
Entryway Essentials: Mirrors
Entryway Furniture
Entryway Organization
Entryway organization
Ergonomic workspace essentials
Espresso Cups
Espresso Machine & Coffeemaker Combos
Espresso Machine Accessories
Espresso Machine Replacement Parts
Espresso Machines
Ethnic Cookware
Evaporative Coolers
Event & Party Supplies
Exclusive: Home Outlet
Fabric
Fabric.com
Fajita Pans
Fall Cooking: Cake pans, pie plates & baking tools
Fall Cooking: Tabletop
Fancy Molds for Food & Ice
Fans
Farmhouse: Industrial Lighting
Fashion Bedding
Father's Day
Father's Day Gifts
Favors
Featured Colored Pencils
Featured Dehumidifiers
Featured Portable Air Conditioners
Feed Your Fans
Fermentation & More
Fermenters
Figurine Ornaments
Figurines
Figurines & Collectibles
Fillet Knives
Filters
Filters & Straining
Fingertip Towels
Finials
Fire pits & patio heaters
Fireplace Back Plates
Fireplace Fans
Fireplace Fenders
Fireplace Grates
Fireplace Screens
Fireplace Tools
Fireplaces
First Apartment Essentials: Bath
First Apartment Essentials: Cleaning
First Apartment Essentials: Entryway
First Apartment Essentials: Garden
First Apartment Essentials: Kitchen
First Apartment Essentials: Living Room
Fish Forks
Fish Poachers
Fish Servers
Fiskars
Fitted Sheets
Flannel Bedding
Flannel Duvet Sets & Covers
Flannel Pillowcases & Shams
Flannel Sheet Sets
Flasks
Flat Servers
Flat Sheets
Flatware
Flatware & Utensil Storage
Flatware Chests
Flatware Organizers
Flatware Sets
Floating Candles
Floating Shelves
Floor & Full Length Mirrors
Floor & Grandfather Clocks
Floor Buffers & Parts
Floor Fans
Floor Pillows & Cushions
Floor-Standing Fountains
Floral arrangements must-haves
Flower Girl Baskets
Folding Chairs
Folding Shoe Racks
Folding Stools
Folding Tables
Folding Tables & Chairs
Fondant & Gum Paste Molds
Fondue
Food Containers
Food Dispensers
Food Grinders & Mills
Food Jars & Canisters
Food Mills
Food Processor Parts & Accessories
Food Processors
Food Storage
Food Storage Bins & Trays
Food Strainers
Footboards
For Him
For Kids
For the Grill Master
For the High-Tech Homemaker
For the Home Perfectionist
For the Hostess with the Mostest
Forks
Fourth of July
Fragrant Drawer Liners
Fragrant Room Sprays
Freckles
Free One-Day Shipping I Home
Free Standing
Free Standing Baskets & Shelves
Free Standing Shoe Racks
Free-Standing
Freestanding Wine Cellars
Freestanding Wine Racks & Cabinets
French Bread & Baguette Pans
French Memo Boards
French Presses
French press
Freshen up your air with a new Air Purifier
Freshen up your space for spring
Fridge & Freezer Organizers
Fridge organization
Fruit & Vegetable Tools
Fruit Bowls
Fruit Forks
Fruit Knives
Frustration-Free Packaging: Home & Kitchen Features - US
Frustration-Free Packaging: Kitchen & Dining Features - US
Fryers
Fuels
Fun & Games
Functional Decor
Functional style
Funkins
Funnels
Furniture
Furniture & Decor
Furniture & accessories
Furniture Deal
Furniture Favorites
Furniture by Design Toscano
Futon Frames
Futon Mattresses
Futon Sets
Futon Slipcovers
Futons
Gadgets Galore
Game & Recreation Room Furniture
Game Day
Game Tables
Gaming Chairs
Garage
Garage organization
Gardening essentials
Gardening tools
Garlands
Garlic Keepers
Garlic Peelers
Garlic Presses
Garlic Roasters
Garlic Tools
Garment Covers
Garment Racks
Garment Steamer Accessories
Garment Steamers
Garnishing Knives
Gas Fireplaces
Gas Logs
Gas Stoves
Gel & Ethanol Fireplaces
Geometric forms
Get a $50 Gift Card with the Purchase of Select Dyson Hair Tools
Get organized
Get the Look: Desert Modern Style
Gift Items
Gift Wrap Storage
Gifts Under $200
Gifts Under $25
Gifts by Type
Glass Display Cabinets
Glass Markers & Charms
Glassware
Glassware & Drinkware
Gliders
Go green
Goblets & Chalices
Gold Box Deal Of The Day: More Than 60% Off Select Shoes Of Soul Boots For Women & Kids
Good Tidings
Gothic & Medieval-Themed
Graduation
Grain Mills
Grapefruit Knives
Grapefruit Spoons
Grapefruit Utensils
Graters
Graters, Peelers & Slicers
Gravy & Sauce Ladles
Gravy Boat Stands
Gravy Boats
Great Point Light Book Lights
Great Savings on Select Sewing Machines
Greeting Cards
Griddles
Grill Pans
Grill essentials
Growlers
Guest Towel Trays
Guest room linens
Guestbooks
Gyutou Knives
HEPA Air Purifiers
HITSearch
HIX Paint ASINs
Hair Care Organizers
Hall Trees
Hallmark Seasonal Décor
Halloween
Halloween Event & Party Supplies
Halloween Tabletop
Halloween Treats
Hammocks & hanging chairs
Hand Blenders
Hand Dryers
Hand Mixers
Hand Towels
Handheld Bags
Handheld Filters
Handheld Steamers
Handheld Vacuums
Handicrafts & Decor
Hangers
Hanging Baskets
Hanging Decorative Tiles
Hanging Hook Stands
Hanging Ornaments
Hanging Shelves
Hanging Shoe Organizers
Hanging storage
Hanging wall storage
Hanukkah Candles
Hard Floor Cleaners
Harry Potter Home & Kitchen
Harvest-Inspired Palette
Hat Boxes
Hat Racks
Head Sculptures
Headboards
Headboards & Footboards
Headwear
Heater & Humidifier Deals
Heaters Up To 40% Off
Heating & Temperature Control
Heating, Cooling & Air Quality
Henry Huang
Herb & Spice Mills
Hidden Gems
Highball Glasses
Holdbacks
Holders
Holders & Dispensers
Holiday 2014
Holiday Cocktail Party
Holiday Coupons | Home
Holiday Coupons | Home & Electronics
Holiday Décor Storage
Holiday Entertaining
Holiday Home & Kitchen Gift Guide: Family Chef
Holiday Light Storage
Holiday Picks Home
Holiday Tabletop
Holmes Heaters & Humidifiers
Home & Entertaining
Home & Kitchen
Home & Kitchen Prime Day Deals
Home Bar Furniture
Home Brewing & Wine Making
Home Brewing Starter Sets
Home Decor
Home Décor Accents
Home Décor Made in Italy
Home Décor Products
Home Electrics & Home Décor
Home Environment
Home Essentials
Home Essentials Deal of the Day
Home Fragrance
Home Fragrance Accessories
Home Furnishing

In [5]:
# Inspecting 'Beauty and Personal Care' category values to validate category filtering rules

beauty_and_personal_care_main_category_query = f"""
SELECT
    main_category,
    COUNT(*) AS product_count
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_raw_dataset_id"]}.meta_beauty_and_personal_care_raw`
GROUP BY main_category
ORDER BY product_count DESC, main_category
"""

beauty_and_personal_care_category_values_query = f"""
SELECT DISTINCT
    category_element
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_raw_dataset_id"]}.meta_beauty_and_personal_care_raw`,
UNNEST(JSON_VALUE_ARRAY(categories)) AS category_element
WHERE category_element IS NOT NULL
  AND TRIM(category_element) <> ''
ORDER BY category_element
"""

beauty_and_personal_care_main_category_dataframe = run_query(beauty_and_personal_care_main_category_query)
display(beauty_and_personal_care_main_category_dataframe)

beauty_and_personal_care_category_values_dataframe = run_query(beauty_and_personal_care_category_values_query)
beauty_and_personal_care_category_values_list = beauty_and_personal_care_category_values_dataframe["category_element"].tolist()
for category_value in beauty_and_personal_care_category_values_list:
    print(category_value)

                   main_category  product_count
0                     All Beauty         737549
1                           None         102896
2         Health & Personal Care          71800
3                 Premium Beauty          34898
4                    Amazon Home          32143
5       Tools & Home Improvement          14387
6                 AMAZON FASHION          13055
7        Industrial & Scientific           4901
8              Sports & Outdoors           2425
9                        Grocery           2181
10                  Toys & Games           2066
11         Arts, Crafts & Sewing           2049
12               Office Products           1696
13     Cell Phones & Accessories           1222
14               All Electronics           1003
15                          Baby            855
16                  Pet Supplies            764
17                     Computers            629
18           Musical Instruments            599
19                    Automotive            374
20                   Movies & TV            323
21                         Books            246
22          Home Audio & Theater            207
23                 Digital Music            183
24                      Handmade            148
25                Camera & Photo            141
26                    Appliances             91
27                  Buy a Kindle             29
28               Car Electronics             16
29                   Video Games             14
30  Portable Audio & Accessories             10
31                      Software              5
32             Collectible Coins              4
33              GPS & Navigation              2
34                Amazon Devices              1
35       Collectibles & Fine Art              1
36                 Entertainment              1

$10 Off $30 on Simple, Pond's, St. Ives & More
$5 Off $15: Hair Products from L'Oreal Paris, Garnier, & Soft Sheen Carson
+10% Off - Beauty & Personal Care
2-in-1 Shampoo & Conditioner
20% Off Hair Care
2022 BFCM Premium Preview
2022 BFCM Preview
3-in-1 Shampoo
3-in-1 Shampoo, Conditioner & Body Wash
30% Off Select Luxury Beauty
Accessories
Acne Treatment Devices
Acrylic Liquids
Acrylic Nail Kits
Acrylic Nail Tools
Acrylic Powders
Acrylic Powders & Liquids
Adhesives
After Shaves
After Sun
Aftercare Products
All Products
Allure Best of Beauty v3
Alum
Antica Farmacista Bath & Shower Wash Gift with Purchase
Antiperspirant Deodorant
Antiperspirants
Applicator Bottles
Aveeno Sample Box
Award Winners
Award Winning Beauty
B1G50% Off 2nd Hair Care Item
BB Creams
Bags & Cases
Balms
Balms & Moisturizers
Barrettes
Bars
Base & Top Coats
Base Coat
Bath
Bath & Bathing Accessories
Bath & Body
Bath & Body Brushes
Bath Bombs
Bath Oils
Bath Pillows
Bath Salts
Bath Sponges
Bathing Accessories
Beard & Mustache Care
Beard & Mustache Combs
Beard & Mustache Trimmers
Beard Care
Beard Conditioners & Oils
Beauty $5 Store
Beauty & Personal Care
Beauty & Personal Care for Women
Beauty & Skincare
Beauty Back to School
Beauty Coupons
Beauty Gifts for Her
Beauty Markdowns
Beauty New Arrivals
Beauty Off to College
Beauty Outlet
Beauty Sales & Deals
Beauty Sample Box
Beauty Summer Sun Care
Beauty and wellness Made in Italy
Best of Body
Bikini Trimmers
Biore Mother's Day
Blackhead & Blemish Removers
Blade Storage
Bleaching
Blenders & Sponges
Blotting Paper
Blush
Blush Brushes
Body
Body Butters
Body Care
Body Glitter
Body Groomers
Body Lotion
Body Lotions and Skin Care Sample Credit
Body Mud
Body Paint
Body Scrubs
Body Self-Tanners
Body Sprays
Body Sunscreens
Body Washes
Braids: Favorite Hair Ties
Bronzers
Brow Brushes
Browse Gift with Purchase Promotion Qualifying Items
Browse Gift with Purchase Qualifying Items
Browse Luxury Beauty Gift with Purchase Qualifying Items
Brush Cleaners
Brush Sets
Brushes, Combs & Needles
Bubble Bath
Bun & Crown Shapers
Buy 2, Get 1 From Your Herbal Essences & Pantene Favorites
CC Creams
Calvin Klein
Caps, Foils & Wraps
Care for Your Hair with Herbal Essences
Cartridge Razors
Cartridges & Refills
Chemical Hair Straighteners
Children's
Classic Holiday Look
Claws
Clays
Cleaners
Cleansers
Clipper Combs & Guides
Clippers & Trimmers
Clips
Clips & Barrettes
Cloths & Towelettes
Cologne
Color Additives & Fillers
Color Conditioners
Color Correctors
Color Glazes
Color Refreshers
Color Refreshing Masks
Color Removers
Coloring & Highlighting Tools
Combination Base & Top Coats
Compact & Travel Mirrors
Concealer
Concealer Brushes
Concealers & Neutralizers
Concentrator Nozzles
Conditioners
Contour Brushes
Cosmetic Bags
Cosmetic Display Cases
Cotton Balls
Cotton Balls & Swabs
Cotton Pads & Rounds
Cotton Swabs
Creams
Creams & Lotions
Creams & Moisturizers
Crimpers
Curing Lamps
Curling Irons & Wands
Curling Tongs
Curling Wands
Customers' Most-Loved Beauty
Customers' Most-Loved Beauty v2
Customers' Most-Loved Beauty_Temp
Customers' Most-Loved: Beauty
Cuticle Care
Cuticle Nippers
Cuticle Oils
Cuticle Protectors
Cuticle Pushers
Cuticle Removing Fluids
Cuticle Repair Creams
Cuticle Scissors
Cuticle Tool Sets
Cuticle Tools
DD Creams
Daily Shampoo
Decoration Kits
Deep Conditioners
Deodorant
Deodorants
Deodorants & Antiperspirants
Depilatories
Detanglers
Developers
Diffusers
Dip Manicure
Dip Manicure Kits
Dip Powder
Dip Powder Liquids
Disposable Razors
Dotting Tools
Droppers
Dry Shampoos
Dryer Attachments
Drying Hoods
Dusting Powders
EF-Beauty-All
Eau Fraiche
Eau de Parfum
Eau de Toilette
Elastics & Ties
Electric Shavers
Electrolysis
Elizabeth Arden
Emerald Tones
Epilators
Epilators, Groomers & Trimmers
Essential Oils
Eye
Eyebrow Color
Eyebrow Scissors
Eyebrow Trimmers
Eyelash Adhesives
Eyelash Curlers
Eyeliner
Eyeliner Brushes
Eyes
Eyeshadow
Eyeshadow Bases & Primers
Eyeshadow Brushes
FHI Gift with Purchase
Face
Face Belts
Face Brushes
Face Cleansing Foaming Nets
Face Mists
Face Moisturizers
Face Oil
Facial Cleansing Brushes
Facial Peels
Facial Rollers
Facial Self Tanners
Facial Steamers
Facial Sunscreens
Fall Colors
False Eyelashes & Adhesives
False Lashes
False Nails & Accessories
Fan Brushes
Father's Day 2021
Feather Extensions
Fiberglass & Silk Wraps
Fimo
Finishing Trimmers
Floss & Oral Irrigators
Foams
Foil Shavers
Foot & Hand Care
Foot Baths & Spas
Foot Creams & Lotions
Foot Files
Foot Lotions
Foot Masks
Foot Pumices
Foot, Hand & Nail Care
Foot, Hand & Nail Tools
Foundation
Foundation Brushes
Foundation Primers
Fragrance
Fragrance Gifts
Free $10 Amazon Gift Card with Qualifying Purchase
Frustration-Free Packaging: Beauty - US
Galvanic Machines
Garnier Whole Blends
Gel
Gel Polish
Gels
Gift Sets
Glitters
Glosses
Groom with Dove Men + Care, Axe, & More
Growth Formula
Hair & Scalp Care
Hair & Scalp Treatments
Hair Accessories
Hair Bleach
Hair Brushes
Hair Building Fibers
Hair Care
Hair Care Gifts
Hair Chalk
Hair Clippers
Hair Clippers & Accessories
Hair Color
Hair Color Mixing Bowls
Hair Coloring
Hair Coloring Products
Hair Combs
Hair Cutting Kits
Hair Cutting Tools
Hair Dryers
Hair Dryers & Accessories
Hair Drying Towels
Hair Extensions
Hair Extensions, Wigs & Accessories
Hair Fragrances
Hair Loss Products
Hair Mascaras & Root Touch Ups
Hair Masks
Hair Perms, Relaxers & Texturizers
Hair Pins
Hair Regrowth Conditioners
Hair Regrowth Devices
Hair Regrowth Shampoos
Hair Regrowth Tonics
Hair Regrowth Treatments
Hair Relaxers
Hair Rollers
Hair Sprays
Hair Tonics
Hair Treatment Oils
Hairpieces
Hand Creams & Lotions
Hand Lotions
Hand Masks
Hand Rests
Hand Wash
Handheld Mirrors
Hands & Feet
Headbands
Henna
Hennas
Herbal Beauty & Personal Care
High Frequency Machines
Highlight Kits
Highlighters & Luminizers
Holiday Coupons | Beauty & Personal Care
Home Fragrances
Home Perm Kits
Hot Lather Machines
Hot-Air Brushes
IB_DOTD
INGS_Consumables
Indie Beauty
Indie Beauty | Beauty under $20
Indie Beauty | Beauty under $30
Indie Beauty | Black-owned brands
Indie Beauty | Color
Indie Beauty | Discover more
Indie Beauty | Female-owned brands
Indie Beauty | Fragrance
Indie Beauty | Hair
Indie Beauty | Hair care
Indie Beauty | Men's Grooming
Indie Beauty | New to Indie Beauty
Indie Beauty | Self-care essentials
Indie Beauty | Skin care
Indie Lee
Ingrown Toenail Tools
Irons
Jars
Jouer
Kabuki Brushes
Karuna
Kits
Kits & Gift Sets
Klorane
Korean Beauty Makeup
LONDONTOWN
Laser, Light & Electrolysis Hair Removal
Lash Enhancers & Primers
Light Hair Removal
Linens
Liner & Shadow Combinations
Lip Brushes
Lip Butters
Lip Care
Lip Glosses
Lip Liners
Lip Plumpers
Lip Plumping Devices
Lip Stains
Lip Sunscreens
Lips
Lipstick
Lipstick Primers
Loofahs
Lotions
Luxury Beauty Gifts
Luxury Beauty Holiday Promotion
Luxury Beauty Mother's Day Gifts
Luxury Beauty Valentine's Day
Makeup
Makeup Airbrushes
Makeup Brushes & Tools
Makeup Cleansing Creams
Makeup Cleansing Foams
Makeup Cleansing Gels
Makeup Cleansing Milk
Makeup Cleansing Oils
Makeup Cleansing Water
Makeup Cleansing Wipes
Makeup Mirrors
Makeup Palettes
Makeup Remover
Makeup Sets
Manicure Tables
Manual Facial Cleansing Brushes
Manual Toothbrushes
Mascara
Mascara Brushes
Masks
Maternity
Men's
Men's Grooming
Men's Grooming & Personal Care
Microdermabrasion
Microdermabrasion Devices
Mirrors
Moisturizers
Moisturizers & Treatments
Moisturizing Gloves
Moisturizing Socks
Mousses
Mousses & Foams
Mouthwash & Breath Fresheners
Multi-Stylers
Mustache Scissors
Mustache Waxes
Nail Art & Polish
Nail Art Accessories
Nail Art Brushes
Nail Art Glue
Nail Art Pens
Nail Care
Nail Cleaning Brushes
Nail Clippers
Nail Drill Bits
Nail Drills
Nail Dryers
Nail Files & Buffers
Nail Forms
Nail Glue
Nail Polish
Nail Polish Remover
Nail Repair
Nail Strengthening
Nail Studio Sets
Nail Thickening Solution
Nail Tips
Nail Tool Sterilizers
Nail Tools
Nail Whitening
National Lipstick Day
Natural Store
Neck & Décolleté
New to SnS: Beauty
Nexxus Hair Products
Night Creams
Nose & Ear Hair Trimmers
Nurse Jamie
Oils
Oils & Serums
Oral Care
Osmotics Cosmeceuticals
Paraffin Baths
Parfums de Marly
Patanjali Ayurved
Pearls
Perfumes & Fragrances
Perm Accessories
Personal Care
Personal Groomers
Peter Thomas Roth
Piercing & Tattoo Supplies
Piercing Guns
Piercing Kits
Piercing Needles
Piercing Supplies
Polish Correctors
Polishes
Polishes & Scrubs
Pomades
Pomades & Waxes
Popular Accessories
Pore Cleansing Strips
Powder
Powder Puffs
Powders
Power Toothbrushes
Powered Facial Cleansing Brushes & Devices
Practice Hands & Fingers
Practice Nail Tips
Premium Beauty finds from Elemis, Crepe Erase, and more
Press On Nails
Prime Day 2016 Up to 50% Off Select Luxury Beauty Products
Prime Day 2017: Up to 40% Off Select Luxury Beauty
Prime Day 50% Off Select Luxury Beauty Products
Professional Massage Equipment
Professional Skin Care
Pump Dispensers
Putties
Putties & Clays
Razor & Brush Stands
Razor Strops
Razors & Blades
Razors with Soap Bars
Red Flower
Refillable Containers
Relaxed
Replacement Cleansing Brush Heads
Replacement Heads
Rhinestones
Ridge Filler
Robes
Roller Bottles
Root Lifting Powders
Rotary Shavers
Safety Razors
Salon & Spa
Salon & Spa Chairs
Salon & Spa Equipment
Salon & Spa Stools
Salt Water Sprays
Salts & Soaks
Save $10 on select Beauty
Save up to 30% on beauty & personal care products
Scalp Treatments
Scrubs
Scrubs & Body Treatments
Self-Tanners
Serums
Sets
Sets & Kits
Shampoo
Shampoo & Conditioner
Shampoo & Conditioner Sets
Shampoo Plus Conditioner
Shampoos
Sharpeners
Shave & Hair Removal
Shaving
Shaving & Grooming Sets
Shaving & Hair Removal
Shaving Accessories
Shaving Brushes
Shaving Creams
Shaving Creams, Lotions & Gels
Shaving Gels
Shaving Lotions
Shaving Soap Bowls
Shaving Soaps
Shear & Razor Cases
Shears
Shower Accessories
Shower Brushes
Shower Caps
Shower Gels & Washes
Shower Mirrors
Shower Steamers
Side Combs
Site Merch Beauty ASINs
Skin Care
Skin Care Gifts
Skin Care Products
Skin Care Tools
Skin Cleansers
SnS
Soaps
Spa Beds & Tables
Spa Slippers
Spa Storage Systems
Spatulas
Spray Bottles
Squeeze Bottles
Stains
Stampers & Scrapers
Stickers & Decals
Straight Razors
Straighteners
Striping Tape Lines
Strips
Studs
Styling Products
Styling Tools & Appliances
Styling Treatments
Styptic
Summer Sun Care
Sunscreens
Sunscreens & Tanning Products
Table Pads
Tanning Oils & Lotions
Tattoo Inks
Tattoo Kits
Tattoo Machine Parts
Tattoo Machines
Tattoo Needles
Tattoo Supplies
Teen Scents
Templates
Temporary Tattoos
Texturizers
The BrowGal
Thermal Styling Gloves
Tinted Moisturizers
Toe Separators
Toiletry Bags
Toiletry Kits
Toners & Astringents
Tools
Tools & Accessories
Tools & Appliances
Tools & Brushes
Toothpaste
Top Coat
Towel Warmers
Train Cases
Travel Cases
Treatments & Masks
Trimmer & Clipper Blades
Trimmers & Clippers
Tub Tea
Tweezers
Up to 20% off Essential Oils
Valentine's Day beauty & grooming gifts
Virtual Try On
WEN by CD Gift with Purchase Qualifying Items
WEN by Chaz Dean
WEN by Chaz Dean Gift with Purchase
WEN by Chaz Dean Wen Boar Bristle Brush Gift with Purchase
Washes
Wavers
Wavy
Wax
Wax Warmers & Accessories
Waxes
Waxing
Waxing Kits
Whiteners
Wig Caps
Wig Head Stands
Wigs
Wisp
Women's
Women's Shave and Hair Removal Sample Credit
Wraps
Wrinkle & Anti-Aging Devices
Wrinkle Pads & Patches
Zeitgeist Stop List - Fresh – Beauty
bath and body
bliss
cosmetics
elf
under25-textured

In [6]:
# Inspecting 'Electronics' category values to validate category filtering rules

electronics_main_category_query = f"""
SELECT
    main_category,
    COUNT(*) AS product_count
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_raw_dataset_id"]}.meta_electronics_raw`
GROUP BY main_category
ORDER BY product_count DESC, main_category
"""

electronics_category_values_query = f"""
SELECT DISTINCT
    category_element
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_raw_dataset_id"]}.meta_electronics_raw`,
UNNEST(JSON_VALUE_ARRAY(categories)) AS category_element
WHERE category_element IS NOT NULL
  AND TRIM(category_element) <> ''
ORDER BY category_element
"""

electronics_main_category_dataframe = run_query(electronics_main_category_query)
display(electronics_main_category_dataframe)

electronics_category_values_dataframe = run_query(electronics_category_values_query)
electronics_category_values_list = electronics_category_values_dataframe["category_element"].to_list()
for category_value in electronics_category_values_list:
    print(category_value)

                   main_category  product_count
0                      Computers         418868
1                All Electronics         376435
2                 Camera & Photo         223690
3      Cell Phones & Accessories         138237
4           Home Audio & Theater         106516
5                           None         106334
6        Industrial & Scientific          50555
7                Car Electronics          27332
8       Tools & Home Improvement          24042
9                    Amazon Home          21299
10               Office Products          21250
11                AMAZON FASHION          18391
12             Sports & Outdoors          14581
13                    Automotive          13956
14              GPS & Navigation           9339
15                Amazon Devices           8484
16  Portable Audio & Accessories           8050
17           Musical Instruments           6668
18                  Toys & Games           3944
19        Health & Personal Care           3073
20                    All Beauty           1848
21         Arts, Crafts & Sewing           1496
22                Apple Products           1078
23                   Video Games           1042
24                         Books            994
25                          Baby            797
26                  Pet Supplies            415
27                      Software            388
28                Amazon Fire TV            248
29                    Appliances            236
30                       Grocery            195
31                   Movies & TV             75
32                  Buy a Kindle             67
33                      Handmade             34
34                    Fire Phone             31
35                Premium Beauty              6
36             Collectible Coins              5
37                    Gift Cards              5
38                 Digital Music              3
39        Magazine Subscriptions              2
40            Audible Audiobooks              1
41       Collectibles & Fine Art              1
42                  Unique Finds              1

12-Month Financing on Computers
16-20 Inches
2 in 1 Laptops
2 in 1 PCs
20-25.9 Inches
2014
2014 Samsung Holiday TV Deals
3-CCD
30% off on Caseology iPhone Cases for iPhone X, iPhone 8/7 and iPhone 8Plus/7Plus Smartphones
35mm Compact
3D Glasses
3P ASINs 1400
3P ASINs 1500
4-Camera Kits
4th of July Deals 2013-Electronics On the Go
6 Month Financing
8-Camera Kits
8-Channel
AC Adapters
ASUS PC
ASUS Transformer Tablet Accessories
AV Receivers & Amplifiers
Access-Control Keypads
Accessories
Accessories & Peripherals
Accessories & Supplies
Accessories and Mounts
Accessory Bundles
Accessory Kits
Acer Certified Refurbished Deals
Acer Clearance Sale
Acer Laptops & Desktops Event
Acer Savings
Adapter Rings
Adapters
Adapters & Connectors
Adapters & Converters
Adzinia CE Node
Aircraft Accessories
Alarm Systems
All
All Camera & Photo
All Canon
All Sony Camera & Photo
All-in-Ones
Amazon Cloud Drive T&C Offer
Amazon Device Accessories
Amazon Device Accessories under $20
Amazon Devices
Amazon Devices & Accessories
Amazon Locker Eligible Camera Products
Amazon Pro Portal
Amazon Unlimited Storage + Laptop Promotion
AmazonBasics Accessories
Amplifier Installation
Amplifier Wiring Kits
Amplifiers
Analog-to-Digital (DTV) Converters
Android Accessories
Antennas
Anti-Glare & Privacy Filters
Apple
Apple Accessories
Apple Bands
Archival Boxes
Archival Storage Binders
Arkon Dynamic Coop
Arm & Wristband Accessories
Armbands
Audio
Audio & Video Accessories
Audio Deal
Audio Docks
Audio and Accessories
Audio-Video Components
Auxiliary Input Adapters
Aviation Electronics
Aviation GPS
Aviation Handheld Radios
BD-R
BD-RE
Back to School Tech Accessories
Back to School in TV, Video & Audio
Back to School-Electronics On the Go
Background Support Equipment
Backgrounds
Backpacks
Bag & Case Accessories
Bags
Bags & Cases
Bags, Cases & Sleeves
Barlow Lenses
Barn Doors
Bases & Stands
Bass Blockers
Batteries
Batteries & Adapters
Batteries & Battery Packs
Batteries & Chargers
Battery & Charger Sets
Battery Chargers
Battery Grips
Battery Holders
Battery Packs
Battery Storage Containers
Battery Testers
Battery Wiring & Terminals
Bazooka Dynamic Coop
Belkin Dynamic Coop
Bestselling Renewed Home Entertainment
Bestselling Renewed Smartphones
Big Markdowns in TV, Video & Audio
Big Savings in Home Audio & Headphones
Biking
Binding Machine Supplies
Binocular Accessories
Binocular Cases
Binocular, Camera & Camcorder Straps
Binoculars
Binoculars & Scopes
Biometrics
Black & White Contrast Filters
Blank Media
Blank Video Media
Blu-ray Drives
Blu-ray Players
Blu-ray Players & Recorders
Blu-ray Recorders
Bluetooth
Bluetooth & FM Transmitters
Bluetooth Car Kits
Bluetooth Headsets
Bluetooth Network Adapters
Bluetooth Speakers
Bluetooth Transmitters
Body Mounted Cameras
Bogen
Bookshelf Speakers
Boomboxes
Booms & Stands
Bose Stereos & Speakers
Bose Store
Boss Audio Dynamic Coop
Boston Acoustics Speakers
Bounceback
Briefcases
Brushes
Bulbs
Bullet Cameras
Bundles
Business Projectors
Buy Samsung at as low as 0% APR
CB & Two-Way Radios
CB Radios & Scanners
CD & DVD Drives
CD & DVD Racks
CD & Tape Players
CD Players
CD Racks
CD Recorders
CD-R
CD-RW
CPU Cooling Fans
CPU Processors
Cable Connection Protectors
Cable Organizer Bags & Cases
Cable Raceways
Cable Security Devices
Cable Sleeves
Cable Straps
Cable Ties
Cables
Cables & Accessories
Cables & Cords
Cables & Interconnects
Caddies
Calculator Accessories
Caller ID Displays
Camcorder
Camcorder Accessories
Camcorder Batteries
Camcorder Battery & Charger Sets
Camcorder Bundles
Camcorder Cases
Camcorder Lenses
Camcorder Tripods
Camcorders
Camera
Camera & Camcorder Lens Bundles
Camera & Photo
Camera Accessories
Camera Batteries
Camera Battery & Charger Sets
Camera Brackets
Camera Cases
Camera Chest Supports
Camera Cine Dollies
Camera Cranes
Camera Lenses
Camera Mounts & Clamps
Camera Privacy Covers
Camera Shoulder Supports
Camera Sliders
Camera Supports & Stabilizers
Camera Tripods
Camera and Printer Docks
Cameras
Canon
Capacitors
Car & Vehicle Electronics
Car Audio
Car Dash Mounting Kits
Car Electronics
Car Electronics Bundles
Car Electronics OEM
Car Electronics for College
Car Headphones
Car Safety & Security
Car Stereo Receivers
Car Video
Carpet
Carpet & Vinyl
Case Fans
Case Hardware & Latches
Cases
Cases & Bags
Cases & Covers
Cases with Band
Cases, Covers & Sleeves
Cassette Player Adapters
Cassette Players & Recorders
Cat 5 Cables
Cat 5e Cables
Cat 6 Cables
Cat 7 Cables
Catadioptric
Ceiling & In-Wall Speakers
Celestron
Cell Phone Headsets
Cell Phones & Accessories
Center Columns
Center-Channel Speakers
Changers
Chargers
Chargers & Adapters
Chargers & Cables
Charging Docks
Chemicals
Chromebook Savings
Cleaning
Cleaning & Repair
Cleaning Equipment
Cleaning Kits
Clips, Arm & Wristbands
Clock Radios
Cloths
Coaxial
Coaxial Cables
Coaxial Speakers
Color Calibration Charts
Color Correction & Compensation Filters
Compact Radios & Stereos
CompactFlash Cards
Complete Tripods
Component Cables
Component Speakers
Component Subwoofers
Composite Cables
Compound Binocular Microscopes
Compound Microscopes
Compound Monocular Microscopes
Compound Trinocular Microscopes
Compressed Air
Compressed Air Dusters
Computer & Tablet Accessories
Computer Accessories & Peripherals
Computer Accessories & Peripherals Deal of the Day
Computer Add-Ons
Computer Cable Adapters
Computer Cases
Computer Component Bundles
Computer Components
Computer Equipment Warranties
Computer Headsets
Computer Headsets and Mics
Computer Microphones
Computer Screws
Computer Speakers
Computer Vacuums
Computers
Computers & Accessories
Computers & Accessories Overstock Event
Computers & Tablets
Computers Low Return Rate Alert
Computers and Accessories Business Pricing
Computers and Accessories Quantity Pricing
Connecting Blocks
Connectivity
Connectors & Adapters
Context of Use
Continuous Lights
Continuous Output Lighting
Contour
Convertibles
Cool & Quirky Tech Accessories
Cooling Fans
Cooling Pads
Cooling Pads & External Fans
Copying Equipment
Cord Management
Cord Reels
Corsair
Covers
Crossover Parts
Cycling GPS Units
DATs
DLT Cleaning Cartridges
DSLR Cameras
DVD Players
DVD Players & Recorders
DVD Recorders
DVD+R
DVD+RW
DVD-R
DVD-RAM
DVD-RW
DVD-VCR Combos
DVI
DVI-HDMI Adapters
Darkroom Supplies
Data Cables & Chargers
Data Cartridges
Data Storage
Deal of the Day | New Year, New Tech Gear
Deal of the Day: Up to 50% Off Select Tech Accessories
Decals
Deep Discounts in Camera, Photo & Video
Deep Discounts in Car Electronics and GPS & Navigation
Deep Discounts in Portable Audio & Accessories
Dell Accessories
Dell Deals
Dell Monitor Promotion
Dell Tablet Accessories
Denon Receivers
Designed for Flip
Desktop
Desktop Barebones
Desktops
Desktops & Monitors
Detachables
Device Bundles
Device Servers
Devices
Devices with Enhanced Amazon Instant Video Viewing Experience
Dew Caps
Diagonals
Diffusers
Digital Camcorders
Digital Camera & Camcorder Accessories
Digital Camera Accessories
Digital Cameras
Digital Imaging
Digital Media Receivers
Digital Pens
Digital Picture Frames
Digital Video Recorders
Digital Voice Recorders
Digital-Analog Converters
Digitizers
Diopters
Disc Cleaners
Disc Duplicators
Disc Repair Kits
Discover Holiday - MP3 & Media Players
Discover Holiday - TV & Video
Distribution
Distribution Panels
Docking Stations
Dome Cameras
Doorbells & Chimes
Drone Store | Accessories
Dual-Channel Amplifiers
Duo Series 2-in-1s Ultrabooks
Earbud Headphones
Earpads
Echo Holiday Skins
Echo Protection Plans
Echo Smart Speaker & Display Bundles
Effects Filters
Electronic Flashes
Electronics
Electronics $5 Store
Electronics & Wireless Outlet
Electronics Emergency Preparedness
Electronics Gift Guide - Top Tech for Gifting
Electronics Holiday Shopping
Electronics International Versions
Electronics Outlet
Electronics Top Holiday Deals
Electronics Warranties
Emerging Technologies
Enclosed Subwoofer Systems
Enclosures
Enlarger Accessories
Enlargers
Entertainment Networking
Equalizers
Ethernet Cables
Extension Cords
Extension Tubes
External Components
External Cooling Fans
External Hard Drives
External Solid State Drives
External Sound Cards
External TV Tuners
External Zip Drives
Eyepieces
FM Transmitters
FREE One Day Shipping with Citi-Electronics On the Go
FREE One-Day Shipping in TV, Video & Audio with your Citi Card
FREE One-Day Shipping on Select Electronics with your Discover Card
FREE Two-Day Shipping in Camera, Photo & Video
Fall Outlet Deals in Computers & Accessories
Fall Outlet Event in Computers & Accessories
Fans & Cooling
Featured Overstock in Mobile Electronics
Featured Windows 7 PCs
Featured Windows 8 PCs
Featured iPad Accessories
Film
Film Cameras
Film Photography
Film Processing Equipment
Filter Accessories
Filter Cases
Filter Sets
Filters
Filters & Accessories
Finder Scopes
Fire Tablets
FireWire
FireWire Port Cards
Firewire Adapters
Firewire Cables
Fish Finders & Depth Finders
Fitness GPS Accessories from Garmin
Fitness Headphones
Fixed-mount CB Radios
Flash Accessories
Flash Tubes
Flashes
Flat Ribbon Cables
Flex Cables
Flip Video
Flip Video Accessories
Floor Cord Covers
Floorstanding Speakers
Floppy & Tape Drives
Floppy Diskettes
Follow-Focus Levers
Free One Day Shipping | Mobile Electronics
Free One-Day Shipping I Audio & Accessories
Free Photo Book
Frustration-Free Packaging: Electronics > Camera & Photo Features - US
Frustration-Free Packaging: Electronics > Computer Features - US
Frustration-Free Packaging: Electronics > Electronic Features - US
Fujifilm
Fuse Holders
GPS & Navigation Holiday Deals
GPS System Accessories
GPS Trackers
GPS, Finders & Accessories
Game Hardware
Gamepads and Controllers
Gaming Accessories
Gaming Computers
Gaming Desktops
Gaming Keyboards
Gaming Laptops
Gaming Mice
Gaming Monitors
Gaming PC
Gaming Projectors
Gear for the Urban Commuter
Gender Changers
Get Your Boat Ready for Summer
Get up to 3 free game codes
Gift Ideas
Gifts
Gifts for Dads
Gifts for Dads & Grads in Electronics
Gifts for Grads
Glasses
GoPro Accessories
Gobos
Golf Course GPS Units
Graduated Color Filters
Graphics Card Fans
Graphics Cards
Graphics Tablets
Grey Cards
Grill Cloth
Grills
Guiders & Wedges
HD DVD Players
HDD Cooling Fans
HDMI Cables
HDMI-to-VGA Adapters
HP
HP Desktops
HP Inkjet Printers
HP Laptop Bags/Cases
HP Laptop Sleeves
HP Laptops
HP LaserJet Printers
HP Monochrome LaserJets
HP PC Accessories
HP Projectors
HP Scanners
HP Single-Function Inkjet Printers
Handheld CB Radios
Handheld GPS Units
Handles
Hands-Free Action Cameras
Hard Drive Accessories
Hard Drive Bags & Cases
Hard Drives & Digital Storage
Hard Shell Cases
Head Cleaners
Headphones
Headphones & Components
Headphones & Earbuds
Headphones, Earbuds & Accessories
Headrest Video
Headsets
Headsets & Intercoms
Headsets & Microphones
Heat-Shrink Tubing
Heatsinks
Heavy Items
Hero Quick Promotion
Hewlett-Packard
Hi-8
Hidden Cameras
High-Tech Stocking Stuffers
Home Audio
Home Audio Accessories
Home Audio Crossovers & Parts
Home Audio Outlet
Home Entertainment
Home Entertainment Deals
Home Security Decals & Signs
Home Security Systems
Home Theater
Home Theater Projectors
Home Theater Systems
Horns & Sirens
Household Batteries, Chargers & Accessories
Housings
Hubs
Hunting and Fishing
I/O Port Cards
IR Illuminators
Image Scanners
In-Dash DVD & Video Receivers
In-Dash Navigation
In-Mirror Video
In-Visor Video
Infrared Filters
Innovative Gadget Gifts for Techies
Input Devices
Installation Services
Instant Cameras
Intel Components
Intel Mother's Day Event
Intel-Powered Tablets
Interconnect Cables
Internal Blu-ray Drives
Internal CD & DVD Drives
Internal Components
Internal Hard Drives
Internal Memory Card Readers
Internal Modems
Internal Optical Drives
Internal Power Supplies
Internal Solid State Drives
Internal Sound Cards
Internal TV Tuner & Capture Cards
Internet Radios
Isolation Transformers
Item Finders
JVC
June Audio Month Featured Deals
KVM Switches
Kensington Security Locks
Keyboard & Mice Accessories
Keyboard & Mouse Combos
Keyboard Cases
Keyboard Skins
Keyboards
Keyboards, Mice & Accessories
Keycaps
Kick-Panel Enclosures
Kids Character Cameras
Kindle Gear Gift Bundles
Kodak
Konica Minolta
LCD Displays
LED & LCD TVs
LG
Labeling Tapes
Lamps
Laptop Accessories
Laptop Backpacks & Bags
Laptop Network Adapters
Laptop Replacement Parts
Laptop Travel Accessories
Laptops
Leica
Lens Accessories
Lens Caps
Lens Cases
Lens Cleaners
Lens Hoods
Lens Supports
Lenses
Lenses & Adapters
Lenses & Filters
LifeProof Brand Store
Light Boxes & Loupes
Light Meters
Light Meters & Accessories
Lighting
Lighting & Studio
Lighting Controls & Modifiers
Lightning Cables
Line Conditioners
Liquid Cleaners
Logitech
Logitech Universal Remotes
Loupes
MP3 & MP4 Player Accessories
MP3 & MP4 Players
MP3 Father's Day Guide
MP3 Player Accessories
MP3 Players & Accessories
MP3 Players with Android
Macro & Ringlight Flashes
Mad Catz
Marantz Reference Components
Marine Amplifiers
Marine Antennas
Marine Autopilots
Marine Electronics
Marine GPS Accessories
Marine GPS Chartplotters
Marine Speakers
Marine Stereos
Marine Subwoofers
Marine Two-Way Radios
Matte Boxes
Media Storage
Media Storage Sleeves
Medium & Large-Format Cameras
Meet Windows 8
Memory
Memory Card Accessories
Memory Card Adapters
Memory Card Cases
Memory Card Readers
Memory Cards
Memory Stick Cards
Messenger & Shoulder Bags
Metra Dynamic Coop
Mice
Micro SD Cards
Microcassette Recorders
Microdrive
Microphones
Microscope Accessories
Microscopes
Midland Dynamic Coop
Midland Two-Way & Emergency Radios
Mini-SAS Cables
MiniDV
MiniDiscs
Minidisc Players
Minis
Mirrorless Camera Lenses
Mirrorless Cameras
Mobile Broadband Devices
Modem Cables
Modem Router Combos
Modems
Monitor Accessories
Monitor Arms
Monitor Stands
Monitors
Mono Amplifiers
Monoculars
Monolights
Monopod Heads
Monopods
Mother's Day Gifts in Electronics Accessories
Motherboard - CPU Bundles
Motherboards
Motion Detectors
Motor Drives
Mounting Accessories
Mounting Brackets
Mounting Hardware
Mounts
Multichannel Amplifiers
Multifunction Devices
Musical Instruments
Must-Have Gadgets for Summer Travel
Network Adapters
Network Antennas
Network Attached Storage
Network Cameras
Network Cards
Network Media Players & Storage
Network Transceivers
Networking
Networking Products
Neutral Density Filters
New Arrivals - Electronics
New From Garmin Spring 2016
New Intel Powered ASUS Tablets
New LG Prepaid Phones
New Products in Camera, Photo & Video
New Year, New Tech Gear Electronics On the Go
New iPod Accessories
New in Electronics
Nexus 10
Nexus Accessory Starter Kit
Nexus Tablet Accessories
Nikon
Noise Filters
Nokia Lumia 635 DOTD
Note 8.0
Numeric Keypads
OLED TVs
Office Electronics
Office Electronics Accessories
Office Products
Olympus
On-Camera Video Lights
On-Dash Cameras
On-Ear Headphones
OnePlus
Open-Ear Headphones
Opera Glasses
Optical
Optical Drives
Optoma Projectors
Other
Other Accessories
Otter Products Holiday Electronics Store
OtterBox Brand Store
Outdoor Speakers
Outlet Deals
Over-Ear Headphones
Overhead Supplies
Overhead Video
PC & Camera Outlet
PC Accessories $5 Store
PC Components
PC Games
PC Gaming
PC Gaming & Accessories
PC Gaming Accessories
PC Part Finder
PC Products
PDA Accessories
PDUs
PS/2 Cables
Parallel Adapters
Parallel Cables
Parallel Port Cards
Parts & Accessories
Pentax
Personal Electronics
Personal Radios
Phone & Tablet Accessories
Phone Cards
Phono Preamps
Photo Adapters
Photo Enlarging Paper
Photo Studio
Pioneer Elite
Point & Shoot Digital Cameras
Point & Shoot Film Cameras
Polarizing Filters
Popular Electronics
Port Tubes
Portable & Handheld TVs
Portable Audio & Accessories Holiday Deals
Portable Audio & Video
Portable Audio Spring Outlet
Portable Bluetooth Speakers
Portable CD Players
Portable DVD Players
Portable DVD Players: For the Car
Portable Electronics for Mother's Day
Portable Line-In Speakers
Portable Photo Printers
Portable Speakers & Docks
Portfolios
Posing Props
Power & Ground Cable
Power Accessories
Power Adapters
Power Cables
Power Converters
Power Cords
Power Packs
Power Strips
Power Strips & Surge Protectors
Power Supplies & Chargers
Power-Cable Terminals
Power-Distribution Components
Power-Distribution Kits
Power-Over-Ethernet
Powerline Network Adapters
Preamplifiers
Premium Audio Promotion
Premium Electronics
Premium TV & Audio
Presentation Supplies
Presidents Day Deals Electronics On the Go
Print Servers
Printers
Printers & Scanners
Pro Series Ultrabooks
Processors
Professional Video Accessories
Professional Video Cameras
Projection Screens
Projector
Projector Accessories
Projector Bags & Cases
Protection Plans
Protective Tablet Accessories
Pyle
Pyle Electronics Father's Day Deals
Pyle Electronics Holiday Savings
QLED TVs
Quadcopter Camera Mounts
Quadcopters & Accessories
Qualifying Audible Devices
Quirky Back to College
RAID Controllers
RCA
RF Modulators
RV GPS
Racks & Cabinets
Radar Detectors
Radar Systems
Radio & Clock Stocking Stuffers
Radio Antennas
Radio Scanners
Radio Wiring Harnesses
Radios
Rain Covers
Rangefinder Cameras
Razer
Reading Lights
Receivers
Receivers & Amplifiers
Record Cleaners & Cleaning Supplies
Reflectors
Refractors
Remote Control Extenders
Remote Controls
Remote Triggers
Renewed Phones
Repair Kits
Repeaters
Replacement Bands
Replacement Screens
Rings
Rockford Fosgate Dynamic Coop
Router & Cable Modem Bundles on Sale
Routers
Running GPS Units
S-Video Cables
SATA Cables
SCSI Adapters
SCSI Cables
SCSI Port Cards
SD Cards
SLR Camera Lenses
SLR Cameras
Safelights
Samsung
Samsung Gift Ideas
Samsung Note 10.1
Samsung Note 8.0
Samsung Optical
Samsung Tab 2 7.0
Samsung Tablet Accessories
Samsung Tablet Accessory Starter Kit
Sandbags
Sandisk Dynamic Coop
Satellite Dish Mounts
Satellite Dishes
Satellite Equipment
Satellite Finders
Satellite Radio
Satellite Speakers
Satellite Television
Save on APC UPS and Surge Protectors
Scosche
Screen Filters
Screen Protector Foils
Screen Protectors
Screens
Security & Surveillance
Security & Surveillance Product Finder
Security Locks
Security Monitors & Displays
Select Favorites in Computer Accessories
Selector Switch Boxes
Sennheiser Mics & Instrument Sets
Sensors
Serial Adapters
Serial Cables
Serial Port Cards
Servers
Service Contracts
Service Plans
Shoe Mount Flashes
Shoe Mounts
Shoot and Share Video
Shooting Tables
Shooting Tents
Shop Dell Desktops
Shop eero WiFi
Shortwave Radios
Shower Radios
Shutter Release Cords
Silicon Grease
Simulated Cameras
Single Board Computers
Single-Use Cameras
Skins
Skins & Decals
SkullcandyHeadphones
Skylight & UV Filters
Slaves
Sleeves
Slide Projectors
Slide, Negative & Print Pages
Smart Clip Accessories
Smart Home Security & Lighting
Smart Light Switches
Smart Lighting
Smart Plugs
SmartMedia Cards
Smartwatches
Social Photography
Soft Boxes
Software Outlet
Sony
Sony PC
Sound Around Dynamic Coop
Sound Bars
Sound Storm Dynamic Coop
Speaker
Speaker Accessories
Speaker Boxes
Speaker Grills
Speaker Installation
Speaker Mounts
Speaker Parts & Components
Speaker Repair
Speaker Systems
Speaker Wire
Speaker Wire Connectors
Speaker Wiring Harnesses
Speakers
Specialty Film Cameras
Speck Tablet & MacBook Cases
Spikes
Splitters
Sports & Action Video Cameras
Sports & Handheld GPS
Sports & Vehicle GPS
Sports GPS
Spring Cleaning in Electronics Accessories
Stabilizers
Stands
Star Wars Day Tech Gadgets
SteelSeries
SteelSeriesBD
Step-Down Rings
Step-Up Rings
Stereo Jack Cables
Stereo Microscopes
Stereo Shelf Systems
Stereo System Components
Storage & Presentation Materials
Streaming Media Players
Strobe Lighting
Strobes & Flashes
Stylus Pens
Styluses
Subwoofer
Subwoofer Boxes & Enclosures
Subwoofer Kits
Subwoofers
Summer Colors for Tech Accessories
Summer Road Trip-Electronics On the Go
Summer is Coming in Tech Accessories
Surface-Mounted Speakers
Surge Protectors
Surround Processors
Surround Sound Systems
Surveillance Accessories
Surveillance Camera Cables
Surveillance Camera Kits
Surveillance Camera Lenses
Surveillance Cameras
Surveillance DVR Kits
Surveillance Housing & Mounting Brackets
Surveillance NVR Kits
Surveillance Systems

In [7]:
# Inspecting 'Books' category values to validate category filtering rules

books_main_category_query = f"""
SELECT
    main_category,
    COUNT(*) AS product_count
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_raw_dataset_id"]}.meta_books_raw`
GROUP BY main_category
ORDER BY product_count DESC, main_category
"""

books_category_values_query = f"""
SELECT DISTINCT
    category_element
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_raw_dataset_id"]}.meta_books_raw`,
UNNEST(JSON_VALUE_ARRAY(categories)) AS category_element
WHERE category_element IS NOT NULL
  AND TRIM(category_element) <> ''
ORDER BY category_element
"""

books_main_category_dataframe = run_query(books_main_category_query)
display(books_main_category_dataframe)

books_category_values_dataframe = run_query(books_category_values_query)
books_category_values_list = books_category_values_dataframe["category_element"].to_list()

for category_value in books_category_values_list:
    print(category_value)

                main_category  product_count
0                       Books        4078785
1                Buy a Kindle         260187
2          Audible Audiobooks         100479
3                                       7132
4         Musical Instruments            360
5                        None            358
6             Office Products            269
7                Toys & Games            224
8                 Amazon Home             76
9                    Software             72
10                 Automotive             61
11    Industrial & Scientific             54
12      Arts, Crafts & Sewing             32
13             AMAZON FASHION             21
14          Sports & Outdoors             20
15     Health & Personal Care             15
16   Tools & Home Improvement              8
17            All Electronics              7
18                 All Beauty              6
19  Cell Phones & Accessories              5
20             Camera & Photo              2
21                  Computers              2
22       Home Audio & Theater              2
23               Pet Supplies              2
24                       Baby              1
25               Unique Finds              1

#Booktok
16th Century
17th Century
1800s
18th Century
1900s
19th Century
2011 Best Books of the Year
2023 Calendars
20th Century
21st Century
3D Printing
7 Day Free Trial Textbooks
AERA 2015 Conference
AI & Machine Learning
AIDS
AIDS & HIV
ASINs for HQP
Abdominal
Abolition
Absurdist
Abuse
Academic Development
Academic Planners (18 Mo) - Limited Editions
Academic Planners (18 Mo) - Turntable
Academic Planners (18 Mo) - Weekly
Accounting
Acoustics
Acrobat 9
Acrobat X
Acrylics
Acting & Auditioning
Action & Adventure
Action & Adventure Fiction
Activities, Crafts & Games
Activity Books
Actors & Entertainers
Adaptations
Addiction & Recovery
Additional Texts
Address Books
Administration
Administration & Management
Administration & Medicine Economics
Administrative Law
Adobe
Adobe Photoshop
Adobe Resources
Adobe Store
Adolescent Psychology
Adoption
Adoption & Fostering
Adult
Adult & Continuing Education
Adult Children of Alcoholics
Adulthood & Aging
Advanced
Adventure
Advertising
Aerobics
Aerodynamics
Aeronautics & Astronautics
Aeronautics & Space
Aerospace
Aesthetics
Afghan & Iraq Wars
Afghan War
Africa
African
African American Studies
African Descent & Black
Afrikaans
Age 11
Age 5
Ages Baby-2
Agile
Aging
Aging Parents
Agnosticism
Agricultural & Food Sciences
Agricultural Sciences
Agriculture
Agriculture & Food Policy
Air & Space Science
Air Forces
Air Sports & Recreation
Alcoholism
Algebra
Algeria
Alien Invasion
Aliens
All Children's Boxed Sets
All Deals
All-American
Allergies
Allied Health Professions
Almanacs & Yearbooks
Alphabet
Alternate History
Alternative & Complementary Medicine
Alternative & Renewable
Alternative Family
Alternative Formats
Alternative Medicine
Alzheimer's Disease
Amateur Sleuths
Amazon Charts: Most Sold Fiction
Amazon Publishing
Amazon.com: Breakthrough
American
American Civil War
American Revolution
Americas
Amish
Amish & Mennonite
Analysis & Strategy
Analytic
Analytic Philosophy
Anarchism
Anatomy
Anatomy & Physiology
Ancient
Ancient & Classical
Ancient & Controversial Knowledge
Ancient & Medieval Literature
Ancient Civilizations
Ancient Greek & Roman
Ancient World
Ancient, Classical & Medieval
Android
Anesthesiology
Anesthesiology 2013
Angels & Spirit Guides
Angeology & Demonology
Anger Management
Anglican
Animal Behavior & Communication
Animal Husbandry
Animal Rights
Animals
Animals & Nature
Animated
Annuals
Anthologies
Anthologies & Short Stories
Anthropology
Antietam
Antiques & Collectibles
Antiques Care & Reference
Antitrust
Anxieties & Phobias
Anxiety Disorders
Apes & Monkeys
Apocalyptic & Post-Apocalyptic
Apologetics
Appetizers
Applied
Applied Psychology
Applique
Appomattox
Appreciation
Arab & Middle Eastern
Arabic
Archaeology
Archery
Architectural Engineering
Architecture
Arctic
Arctic & Antarctica
Argentina
Arithmetic
Armed Forces
Armored Vehicles
Arms Control
Aromatherapy
Art
Art & Architecture
Art Therapy & Relaxation
Art of Comics and Manga
Art, Music & Photography
Arthurian
Artists, Architects & Photographers
Arts
Arts & Entertainment
Arts & Humanities
Arts & Literature
Arts & Photography
Arts, Music & Photography
Asia
Asian
Asian & Asian American
Asian & Asian Descent
Asian American
Asian American & Asian
Asian American Studies
Assessment
Assistants & Aides
Assyria, Babylonia & Sumer
Astrology
Astronautics & Space Flight
Astronomy
Astronomy & Space
Astronomy & Space Science
Astrophysics & Space Science
Atheism
Atlases & Gazetteers
Atlases & Maps
Atmospheric Sciences
Atomic & Nuclear Physics
Attention Deficit & Attention Deficit Hyperactivity Disorders
Attention Deficit Disorders
Audible Books & Originals
Audible Latino
Audiobooks Test
Audiology & Speech Pathology
Auditing
Australia & New Zealand
Australia & Oceania
Australia & South Pacific
Australian & Oceanian
Australian & Oceanian Studies
Austria
Austria & Hungary
Authors
Authorship
Autism & Asperger's Syndrome
Autism Spectrum Disorder
Automotive
Aviation
Aviation & Nautical
Aztec
BDSM
Baby Animals
Baby Food
Baby's First Library
Babysitting, Day Care & Child Care
Back to School
Back to School 2019
Back to School for Teachers
Back-to-School Editors' Picks
Baha'i
Baking
Banjos
Bankruptcy
Banks & Banking
Banned Books
Banned Books Week Comics
Baptist
Bar Examination
Barbecuing & Grilling
Barcelona
Bargain Test
Bariatrics
Baseball
Baseball & Softball
Basic Concepts
Basic Sciences
Basketball
Baskets
Battletech
Beach Reads
Beadwork, Fashion & Jewelry
Bears
Beat Generation
Beatles
Beauty, Grooming & Style
Beauty, Grooming, & Style
Bedtime & Dreaming
Bedtime & Dreams
Beer
Beginner Readers
Beginner's Guides
Behavioral Disorders
Behavioral Sciences
Behaviorism
Beijing
Being a Teen
Belarus & Ukraine
Berlin
Best Books of 2013
Best Books of 2015
Best Books of 2016
Beverages & Wine
Bhagavad Gita
Bible
Bible Covers
Bible Study
Bible Study & Reference
Bibles
Bibles & Bible Study
Biblical Biography
Biblical History & Culture
Big Data
Big Data Guides
Billiards & Pool
Billionaires
Biochemistry
Bioengineering
Biographical
Biographies
Biographies & Memoirs
Biography
Biography & History
Biological & Chemical
Biological Sciences
Biology
Biomedical Engineering
Biotechnology
Bipolar
Birds
Birdwatching
Biscuits, Muffins & Scones
Black & African American
Black & African American Stories
Black & African Americans
Blank Books
Blogging & Blogs
Blowout Books
Blues
Board Books
Board Games
Boating
Boats & Ships
Body
Body Image & Eating Disorders
Bolivia
Bonds
Book Awards
Book Club Picks
Book Club Selections
Book Covers
Book Making & Binding
Book Notes
Book club picks: Nonfiction
Bookkeeping
Books
Books & Libraries
Books & Reading
Books ASINs
Books Deals
Books Home Page Test Bdwy Final
Books Markdowns
Books Outlet
Books Santa 2012
Books bestsellers
Books bestsellers in Nonfiction
Books by Alister McGrath
Books for History Buffs
Books in Bulk
Books on CD
Botany & Plants
Boxed Sets
Boxing
Boxing, Wrestling & MMA
Boys & Men
Brain
Branding & Logo Design
Branding, Innovation, & Visual Thinking Guides
Brass
Brazil
Bread
Bread Machines
Breast Cancer
Breeds
Bridge
Bring on Spring
British & Irish
British Literature
Broadway & Musicals
Buddhism
Budget
Budgeting & Money Management
Bugs & Spiders
Building Design & Technology
Buildings
Bulbs
Bullying
Bullying & Abuse
Bullying Prevention Month
Business
Business & Careers
Business & Finance
Business & Investing
Business & Money
Business & Professional
Business & Professional Growth
Business Aspects
Business Culture
Business Development & Entrepreneurship
Business Innovation
Business Intelligence Tools
Business Technology
Business Travel
Business Writing
Business of Art
Business, Law & Politics
Butterflies
Buttons
Buying & Selling Homes
Buying Guides
By Climate
By Publisher
By Region
By Technique
C
C & C++
C#
CLEP
CRM ILM
Cacti & Succulents
Cakes
Calculus
Calendars
California
Call of Cthulhu
Calligraphy
Calvinist
Cambodia
Campaigns & Battlefields
Camping
Camping & Outdoor Activities
Canada
Canadian
Cancer
Candlemaking
Canning & Preserving
Canoeing
Card Games
Cardiovascular
Care & Restoration
Career & Leadership
Career Development
Careers
Caribbean
Caribbean & Latin American
Caribbean & West Indies
Carpentry
Cars & Trucks
Cars, Trains & Things That Go
Cartooning
Cartoons
Cast Iron
Catalogs & Directories
Catholicism
Cats
Cats, Dogs & Animals
Cats, Lions & Tigers
Celebrations & Events
Celebrities & TV Shows
Celebrity & Popular Culture
Celebrity Picks 2015
Cell Biology
Cellos
Celtic
Cengage Courseware Store
Censorship
Central & South America
Central America
Central Asia
Ceramics
Ceremony, Vows & Toasts
Certification
Certification & Development
Certification Central
Chakras
Channeling
Chapter Books
Chapter Books & Readers
Charter Schools
Cheese & Dairy
Chemical
Chemical Engineering
Chemistry
Chess
Child
Child Abuse
Child Psychology
Children & Teens
Children's
Children's & Teens
Children's & Youth Sports
Children's Ages 9-12
Children's Audiobooks
Children's Book Awards
Children's Books
Children's Books: Picture Books
Children's Choice Book Awards
Children's Cookbooks
Children's General Study Aids
Children's Health
Children's Literature
Children's Studies
Children's audiobooks
Chile
China
China Books
Chinese
Chinese Languages
Choral
Christian
Christian Books & Bibles
Christian Denominations & Sects
Christian Eschatology
Christian Fiction
Christian Living
Christian Science
Christianity
Christmas
Christology
Chronic Fatigue Syndrome & Fibromyalgia
Church & Church Leadership
Church Institutions & Organizations
Churches & Church Leadership
Cinematography
Circus
Citi Free One-Day Shipping
Citizenship
City Life
City Planning & Urban Development
Civics & Citizenship
Civil & Environmental
Civil Engineering
Civil Law
Civil Procedure
Civil Rights
Civil Rights & Liberties
Civil Service
Civil War
Civil War Period
Civilization & Culture
Clarinets
Class
Classic Fiction
Classic Planners (12 Mo) - Daily
Classic Planners (12 Mo) - Desk Calendars
Classic Planners (12 Mo) - Monthly
Classic Planners (12 Mo) - Weekly
Classical
Classics
Classics & Allegories
Clean & Wholesome
Cleaning, Caretaking & Relocating
Client-Server Systems
Climate Change
Clinical Chemistry
Clinical Psychology
Cloud Computing
Coaching
Coal
Coastal
Codependency
Coffee & Tea
Coffee Table Books
Cognitive Behavioral Therapy
Cognitive Neuroscience & Neuropsychology
Cognitive Psychology
Collecting
Collections & Anthologies
Collections, Catalogs & Exhibitions
College & High School
College Entrance
College Guides
Colombia
Colon & Rectal
Colonial
Colonial & Revolutionary
Colonial & Revolutionary Periods
Colonial Period
Colonialism & Post-Colonialism
Coloring Books
Coloring Books for Grown-Ups
Combination Piano, Vocal, & Guitar
Comedy
Comets, Meteors & Asteroids
Comfort Food
Comic Strips
Comics & Graphic Novels
Comics & Manga
Coming of Age
Coming of Age Fiction
Commentaries
Commentary & Opinion
Commerce
Commercial
Commercial Policy
Commodities
Communication
Communication & Journalism
Communication & Media Studies
Communication & Social Skills
Communications
Communicative Disorders
Communism & Socialism
Community & Culture
CompTIA
Company Profiles
Comparative
Comparative Literature
Comparative Politics
Comparative Religion
Composers
Composers & Musicians
Composition
Composition & Creative Writing
Compulsive Disorders
Computer Science
Computer Vision & Pattern Recognition
Computers
Computers & Internet
Computers & Technology
Conducting
Confederacy
Conflict Management
Conflict Resolution & Mediation
Confucianism
Consciousness & Thought
Conservation
Conservatism & Liberalism
Consolidation & Merger
Constitutional Law
Constitutions
Construction
Consulting
Consumer Behavior
Consumer Guides
Container Gardening
Contemporary
Contemporary Christian
Contemporary Fiction
Conventional
Cookbooks, Food & Wine
Cooking
Cooking Education & Reference
Cooking Methods
Cooking by Ingredient
Cooking with Kids
Cooking, Food & Wine
Copyright
Corporate Finance
Corruption & Misconduct
Cosmetics
Cosmology
Costa Rica
Counseling
Counting
Country
Country & Ethnic
Country & Folk
Country Life
Courts
Cozy
Crafts
Crafts & Hobbies
Crafts for Children
Crafts, Hobbies & Home
Crafts, Home & Garden
Creationism
Creativity
Creativity & Genius
Crime
Crime & Criminal Biographies
Crime Fiction
Criminal & Forensic Psychology
Criminal Law
Criminal Procedure
Criminology
Crisis Management
Critical Care
Criticism
Criticism & Essays
Criticism & Interpretation
Crocheting
Crop Science
Cross-Country
Cross-Stitch
Crosswords
Crowdfunding
Cruises
Crystals
Cuba
Culinary
Cults
Cultural
Cultural Heritage
Cultural Policy
Cultural Studies
Cultural, Ethnic & Regional
Curricula
Curriculum & Lesson Plans
Customer Favorites
Customer Favorites of 2016
Customer Relations
Customs & Traditions
Customs, Traditions, Anthropology
Cybernetics
Cyberpunk
Cycling
Cyprus
DC
Daily Activities
Dalai Lama
Dance
Danish
Dark Fantasy
Dark Humor
Darkroom & Processing
Data Analytics
Data Mining
Data Modeling & Design
Data Processing
Data in the Enterprise
Databases & Big Data
Dating
Dating & Sex
Dead Sea Scrolls
Deals in Books
Dear Santa Children's Books
Death
Death & Dying
Death & Grief
Death, Grief & Loss
Decision-Making & Problem Solving
Decorating
Decorating & Design
Decorative Arts & Design
Dehydrators
Democracy
Demography
Denmark
Dental Assisting
Dental Hygiene
Dental Office Practice
Dentistry
Depression
Depression & Mental Health
Dermatology
Deserts
Design
Design & Architecture
Design & Construction
Design & Drawing
Design & Graphics
Design History & Criticism
Desserts
Detoxes & Cleanses
Development & Growth
Developmental & Intellectual Disabilities
Developmental Biology
Developmental Psychology
Devotionals
Diabetes
Diabetic & Sugar-Free
Diagnosis
Diaries & Journals
Dictionaries
Dictionaries & Terminology
Dictionaries & Thesauruses
Diet & Health
Diet & Nutrition
Diets & Nutrition
Diets & Weight Loss
Diets, Nutrition & Healthy Eating
Differential Geometry
Difficult Discussions
Difficult Situations
Digestive Organs
Digital Audio, Video & Photography
Digital Currencies
Digital Design
Digital Design Bookstore
Digital Photography
Digital Singles
Dinosaurs
Diplomacy
Direct
Direction & Production
Disabilities
Disabilities & Hyperactivity
Disability Fiction
Disaster & Recovery
Disaster Relief
Discipleship
Discover Promo 2012
Discover a New Series
Discoveries
Discrimination & Racism
Diseases
Diseases & Physical Ailments
Diseases & Physical Illness
Diseases, Illnesses & Injuries
Disney Store
Distribution & Warehouse Management
Divination
Divorce
Divorce & Separation
Do-It-Yourself
Doctor-Patient Relations
Dogs
Dogs & Wolves
Dollhouses
Dolls
Dolls, Toys & Figurines
Domestic
Domestic Relations
Dot to Dot
Drafting & Mechanical Drawing
Dragons & Mythical Creatures
Dragons, Unicorns & Mythical
Drama
Drama & Plays
Dramas & Plays
Dramatizations
Drawing
Dream Analysis
Dreams
Driver's Education
Drug Dependency
Drug Guides
Drugs & Alcohol Abuse
Drugs & Substance Abuse
Ducks & Other Waterfowl
Dummies Consumers
Dungeons & Dragons
Dutch
Dysfunctional Families
Dystopian
E-Commerce
ESP
Early Childhood
Early Childhood Development
Early Childhood Education
Early Learning
Early Readers
Earth Sciences
Earthquakes & Volcanoes
East Africa
East South Central
Easter & Lent
Easter 2014
Easter Cookbooks & Crafts
Eastern
Eating Disorders
Eating Disorders & Body Image
Ecology
Econometrics & Statistics
Economic Conditions
Economic History
Economic Policy
Economics
Ecosystems
Ecosystems & Habitats
Ecumenism
Editing
Editors' Holiday Gift Picks
Education
Education & Learning
Education & Reference
Education & Teaching
Education & Training
Education Theory
Education Theory & Policy
Educational Psychology
Educators
Egypt
Elections
Elections & Political Process
Electric
Electric Machinery & Motors
Electrical
Electrical & Electronics
Electrical Engineering
Electricity
Electricity & Electronics
Electromagnetism
Electronic Data Interchange (EDI)
Electronic Documents
Electronics
Elementary Education
Elephants
Email Administration
Embroidery
Embryology
Emergencies
Emergency
Emergency Medical Services
Emigrants & Immigrants
Emigration & Immigration
Emotions
Emotions & Feelings
Encryption
Encyclopedias & Subject Guides
Endangered Species
Endocrine System
Endocrinology & Metabolism
Energy & Mining
Energy Healing
Energy Policy
Energy Production & Extraction
Engineering
Engineering & Transportation
Engineering Calculations
Engines & Transmissions
England
English
English & Literature
English as a Second Language
English, Scottish & Welsh
Enterprise Applications
Entertaining & Holidays
Entertainment
Entertainment & Celebrities
Entertainment & Performing Arts
Entomology
Entrepreneurship
Environment
Environmental
Environmental & Natural Resources Law
Environmental Conservation & Protection
Environmental Economics
Environmental Engineering
Environmental Policy
Environmental Science
Environmentalism
Environmentalists & Naturalists
Epic
Epidemiology
Episcopalian
Epistemology
Epistolary
Equestrian
Equipment
Equipment & Supplies
Equipment, Techniques & Reference
Eritrea
Erotica
Eschatology
Espionage
Essays
Essays & Commentary
Essays & Correspondence
Estate Planning
Estates & Trusts
Ethics
Ethics & Morality
Ethics & Professional Responsibility
Ethnic
Ethnic & International
Ethnic Studies
Ethnomusicology
Etiquette
Etiquette Guides & Advice
Etymology
Europe
European
European & European Descent
Evangelism
Event Planning
Evidence
Evolution
Evolution & Genetics
Evolutionary Psychology
Excursion Guides
Executive Branch
Exegesis & Hermeneutics
Exercise & Fitness
Existential
Existentialism
Expand your sci-fi horizons
Expeditions & Discoveries
Experimental Methods
Experimental Psychology
Experiments, Instruments & Measurement
Expert Systems
Exploration
Exploration & Discoveries
Exploration & Discovery
Explore the World
Extended Families
Extraterrestrial Life
Extreme Sports
Eye Problems
Fairy Tale books for children
Fairy Tales
Fairy Tales & Folklore
Fairy Tales, Folk Tales & Myths
Fairy Tales, Folk Tales, Legends & Mythology
Fairy Tales, Folklore, Legends & Mythology
Faith
Fall Reading
Fall Reading 2015
Fall into Cooking
Family
Family Activities
Family Health
Family Law
Family Life
Family Life Fiction
Family Practice
Family Relationships
Family Saga
Family Travel
Fantasy
Fantasy & Magic
Fantasy & Supernatural
Fantasy Fiction
Fantasy Sports
Farm Animals
Farm Life
Fascism
Fashion
Fashion & Textile
Fashion Design
Fatherhood
Featured Children's Books
Featured Literature & Fiction
Featured Orthopedics Resources
Featured Reading Lists
Featured Sci-Fi & Fantasy
Featured Titles in Springer Engineering
Featured Titles in Springer Physics
Featured in Astronomy & Space Science
Featured in Bios & Memoirs
Featured in Literature & Fiction
Featured tech guides
Federal Legislation
Feminist
Feminist Theory
Feng Shui
Fertility
Fiction
Field Guides
Film & TV
Film & Video Art
Finance
Financial
Financial Aid
Financial Engineering
Financial Risk Management
Financial Services
Finding Your Strengths
Finland
Fire Science
Firearms
Firearms & Weapons
Fireworks CS5
Fish
Fish & Aquariums
Fish & Marine Life
Fish & Seafood
Fish & Sharks
Fisheries & Aquaculture
Fishing
Fitness
Fitness, Diet & Nutrition
Flash Professional CS5.5
Flower Arranging
Flower Arranging & Crafts
Flowers
Flowers & Landscapes
Flowers & Plants
Flutes
Folk & Traditional
Folklore
Folklore & Mythology
Font Size 16 Bold
Food & Nutrition
Food Animals
Food Counters
Food Science
Food, Lodging & Transportation
Foot & Ankle
Football
Football (American)
For the Aging
Foreign & International Law
Foreign Exchange
Foreign Language
Foreign Language Books
Foreign Language Dictionaries & Thesauruses
Foreign Language Learning
Foreign Language Study
Foreign Language Study & Reference
Forensic Medicine
Forensic Science
Forests & Forestry
Forms & Genres
Fortune Telling
Fossil Fuels
Fossils
Foxes & Wolves
Fractals
France
Franchises
Fredericksburg
Free Enterprise & Capitalism
Free Will & Determinism
Freemasonry
French
Friendship
Friendship books for children
Friendship, Social Skills & School Life
Frozen Desserts
Fruit
Fruits
Frustration-Free Packaging: Books - US
Fryers
Functional Analysis
Funding
Furniture
Furniture Design
Future Studies
Futures
GED
Gadget Guides
Gaia
Galactic Empire
Gambling
Game
Game Programming
Game Theory
Games
Games & Activities
Games & Strategy Guides
Gaming
Garden & Home
Garden Design
Gardening
Gardening & Landscape Design
Gaslamp
Gender Studies
Gender-Specific Topics
Genealogy
General
General & Reference
General Broadcasting
General Surgery
Genetic
Genetic Engineering
Genetics
Genocide & War Crimes
Genre Fiction
Genre Films
Genres
Genres & Styles
Geography
Geography & Cultures
Geology
Geometry
Geometry & Topology
Geophysics
Geopolitics
Georgia
Geriatrics
German
Germany
Gerontology
Gestalt
Get a free digital comic with purchase
Gettysburg
Ghosts
Ghosts & Hauntings
Gift Box Sets
Gift Ideas in Books
Gifted Students
Gifts for Kids & Teens
Girls & Women
Global
Globalization
Gluten Free
Goddesses
Golf
Good & Evil
Goodreads Choice Awards
Gospel
Gothic
Government
Government & Business
Graduate School

In [8]:
# Inspecting 'Movies and TV' category values to validate category filtering rules

movies_and_tv_main_category_query = f"""
SELECT
    main_category,
    COUNT(*) AS product_count
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_raw_dataset_id"]}.meta_movies_and_tv_raw`
GROUP BY main_category
ORDER BY product_count DESC, main_category
"""

movies_and_tv_category_values_query = f"""
SELECT DISTINCT
    category_element
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_raw_dataset_id"]}.meta_movies_and_tv_raw`,
UNNEST(JSON_VALUE_ARRAY(categories)) AS category_element
WHERE category_element IS NOT NULL
  AND TRIM(category_element) <> ''
ORDER BY category_element
"""

movies_and_tv_main_category_dataframe = run_query(movies_and_tv_main_category_query)
display(movies_and_tv_main_category_dataframe)

movies_and_tv_category_values_dataframe = run_query(movies_and_tv_category_values_query)
movies_and_tv_category_values_list = movies_and_tv_category_values_dataframe["category_element"].to_list()
for category_value in movies_and_tv_category_values_list:
    print(category_value)

                main_category  product_count
0                 Movies & TV         359953
1                 Prime Video         349118
2                        None          36338
3           Sports & Outdoors           1146
4                       Books            508
5              AMAZON FASHION            214
6               Entertainment            209
7               Digital Music            154
8                Toys & Games            117
9      Health & Personal Care             82
10                Amazon Home             74
11                Video Games             63
12            All Electronics             59
13            Office Products             30
14  Cell Phones & Accessories             27
15   Tools & Home Improvement             25
16                  Computers             16
17    Industrial & Scientific             15
18               Pet Supplies             12
19       Home Audio & Theater             11
20                 All Beauty              9
21                   Software              9
22      Arts, Crafts & Sewing              8
23        Musical Instruments              8
24                    Grocery              7
25             Camera & Photo              6
26           GPS & Navigation              2
27                 Automotive              1
28                       Baby              1
29          Collectible Coins              1
30               Unique Finds              1

10-12 Years
20/20
20th Century Fox Home Entertainment
3-6 Years
4-for-3 DVD
60 Minutes Store
7-11 Years
7-9 Years
A&E Home Video
A&E Original Movies
ABBA
ABC News
ABC News Classics
ABC News Specials
ABC TV Shows
AC/DC
Acción y aventura
Acorn Deals
Acting Troupes & Companies
Action
Action & Adventure
Adventure
Adventures
Aerosmith
Africa
African American Cinema
African American Heritage
Aguilera, Christina
Alice in Chains
Alien Invasion
Alien Saga
Alienated
Aliens
All
All A&E Titles
All BBC Titles
All Disney Titles
All FX Shows
All Fox Titles
All HBO Titles
All Lionsgate Titles
All MGM Titles
All MTV
All Made-for-TV Movies
All New Yorker Titles
All Sci Fi Channel Shows
All Showtime Titles
All Sony Pictures Classics
All Sony Pictures Titles
All Sundance Titles
All Terminator
All Titles
All Universal Studios Titles
Amazing Vacation Homes
Amazon Marketplace
Ambitious
American Film Institute Series
American Masters Collection
Anchor Bay Deals
Anchor Bay Horror Store
Animal Planet
Animals
Animated Cartoons
Animated Characters
Animated Movies
Animation
Anime
Anime & Manga
Anxious
Arabic
Argentina
Armstrong, Louis
Art & Artists
Art House & International
Arthouse
Arts & Entertainment
Arts, Entertainment, and Culture
Asian Cinema
Atmospheric
Australia & New Zealand
Award Winners in Movies & TV
BBC
Backstreet Boys
Ballet & Dance
Basie, Count
Batman Animated Movies
Beastie Boys
Beautiful
Bee Gees
Best of 2013
Bible
Biographies
Biography
Birth-2 Years
Biting
Blakey, Art
Blaxploitation
Bleak
Blu-ray
Bold
Bon Jovi
Borge, Victor
Bowie, David
Box Sets
Boxed Sets
Brazil
Breakthrough Cinema
British Cult Television
British Television
Broadway
Broadway Theatre Archive
Broadway's Lost Treasures
Brooks, Garth
Bruno Bozzetto
Bryan Kest
Buble, Michael
Buena Vista Social Club
By Age
By Animator
By Country
By Genre
By Instructor
By Original Language
CBS News
CBS News Network
Camp
Campy
Canada
Carey, Mariah
Carpenters
Cartoon Network
Cash, Johnny
Category III
Celtic Woman
Cerebral
Channels
Characters & Series
Charlie Rose Store
Charming
Cheerful
Chicago
Chile & Peru
China
Chinese
Christian Movies & TV
Christian Video
Christmas
Ciencia ficción y fantasía
Cine español
Cirque du Soleil
Clapton, Eric
Classic TV
Classical
Classics
Classics Kids Love
Clásicos
Coarse
Coldplay
Collections
Collections & Documentaries
Collector's Choice
Collins, Phil
Coltrane, John
Comedia
Comedy
Comedy Central Presents
Comic-Con Favorites
Compelling
Computer Animation
Confused
Contemplative
Cooking & Beverages
Cooper, Alice
Cops & Triads
Cream
Creedence Clearwater Revival
Crime & Conspiracy
Criterion Collection
Critic's Choice
Crosby, Stills & Nash
Crow, Sheryl
Cuba
Cult Classics
Cult Movies
Czech
Czech Republic & Slovakia
DC Comics Collection
DC Universe Animated Original Movies
DTS
DVD
Dance
Dance & Music
Daniel Craig
Danish
Dark
Davis, Miles
Decoding the Past
Deep Purple
Denise Austin
Denver, John
Deportes
Digging for the Truth
Digital Copy
Digital VHS
Dion, Celine
Disc on Demand
Discovery Channel
Disney Channel
Disney Channel Original Movies
Disney Channel Series
Disney Home Video
Documentary
Docurama
Dogfights
Dove Approved List
Dove-Approved Family Films
Downbeat
Dr. Dre
Drama
Dream Theater
DreamWorks
Dreamlike
Dune
Dutch
Dylan, Bob
Eagles
Easter
Easter Movies & TV Shows
Easygoing
Edifying
Editor's Picks
Educational
Eerie
Egypt
Electrifying
Ellington, Duke
Emerson, Lake & Palmer
Eminem
Emmy Central
Emmy Nominees
Emotional
Engineering an Empire
Enigmatic
Entertainment
Essential Art House
Estefan, Gloria
European Cinema
Eurythmics
Eve
Exciting
Exercise & Fitness
Exotic
Exploitation
Explore 50 Years of Great TV
Extended Editions
FX
FX Network
Faith & Spirituality
Faith and Spirituality
Family Features
Family Friendly
Fantastic
Fantasy
Father's Day
Feature Films
Featured Categories
Featured Deals & New Releases
Feel-good
Film History & Film Making
Film Movement
Finnish
First to Know
Fitness
Fitness & Yoga
Five Star Collection
Five Takes Pacific Rim
Fleetwood Mac
Flight Attendant School
Focus Features
Fogerty, John
For Seniors
For the Whole Family
Foreign Films
Foreign Spotlight
Fox Featured Deals
Fox News
Fox TV
France
French
French New Wave
Frightening
Full Moon Video
Fully Loaded DVDs
Fun
Futuristic
Gabriel, Peter
Gaiam
General
Genesis
Genre for Featured Categories
Gentle
George Harrison
German
Germany
Gerry Anderson
Gift Ideas in Movies & TV
Gillespie, Dizzy
Gilmour, David
Godsmack
Godzilla
Golden Globe Central
Golden Globe Nominees
Golden Globe Winners
Grateful Dead
Great Hotels
Greek
Gritty
Groban, Josh
HBO
HBO Deals
HDNet
Haggard, Merle
Hallmark Home Video
Halloween Movies & TV Shows
Hanna-Barbera
Harrowing
Harry Potter
Harry Potter and the Chamber of Secrets
Harry Potter and the Deathly Hallows
Harry Potter and the Goblet of Fire
Harry Potter and the Half-Blood Prince
Harry Potter and the Order of the Phoenix
Harry Potter and the Prisoner of Azkaban
Harry Potter and the Sorcerer's Stone
Haunted History
Haunting
Health
Heartwarming
Hendrix, Jimi
High-Definition DVDs
Hindi
Historical
Historical Context
History
History Channel
Holiday, Billie
Holidays & Seasonal
Hollywood Vault
Holocaust
Hong Kong
Hong Kong Action
Horror
Horror & Suspense
Hungarian
Hungary
Iceland
Il Divo
Imaginative
In Memoriam
Independently Distributed
India
Indiana Jones
Indie & Art House
Infantil y familiar
Infinifilm Edition
Inspirational
Inspiring
Intense
International
Introspective
Iran
Ireland
Iron Maiden
Italian
Italy
Jackass
Jackson, Janet
Jackson, Michael
James Bond
Jan Svankmajer
Jane Austen on DVD Store
Japan
Japanese
Jarrett, Keith
Jesus
Jewish Entertaining
Jewish Heritage
Joan of Arc
Joel, Billy
John Lennon
John Wayne Store
John, Elton
Johnson, Jack
Johnson, Robert
Jones, George
Jones, Norah
Journey
Joyous
Justice League Animated Movies
KISS
Kelly, R.
Kids
Kids & Family
King David
King, B.B.
King, Carole
Korea
LGBT
LGBTQ
Landmark Cult Classics
Lifetime Original Movies
Lilias Folan
Lions Gate Home Entertainment
Lionsgate DVDs Under $10
Lionsgate DVDs Under $15
Lionsgate DVDs Under $20
Lionsgate Home Entertainment
Lionsgate Indie Selects
Live Action
MGM Avant-Garde
MGM Contemporary Classics
MGM DVDs Under $15
MGM Family Entertainment
MGM Home Entertainment
MGM Midnite Movies
MGM Movie Time
MGM Musicals
MGM Screen Epics
MGM Soul Cinema
MGM Vintage Classics
MGM Western Legends
MOD CreateSpace Video
MTV
Made-for-TV Movies
Madonna
Major League Baseball
Malicious
Mamoru Oshii
Manilow, Barry
Marley, Bob
Martin, Ricky
Mary-Kate & Ashley
Matthews, Dave
Mayer, John
McLachlan, Sarah
Megadeth
Men in Black
Men's Basketball
Men's Ice Hockey
Men's Wrestling
Metallica
Metheny, Pat
Mexico
Middle East
Military & War
Military Channel
Military and War
Mingus, Charles
Mini-DVD
Miniseries
Miramax Home Entertainment
Miramax Home Video
Misterio y suspenso
Modern Adaptations
Molly Fox
Monk, Thelonious
Monster Movies
Monsters & Mutants
Monthly Deals
Monty Python Store
More to Explore
Morrissey & The Smiths
Moses
Mother Teresa
Mother's Day
Mother's Day Gift Ideas in Movies & TV
Motley Crue
Movie Blockbusters
Movies
Movies & TV
Movies & TV Halloween Store
Movies & TV Holiday Wishlist
Music
Music & Dance
Music & Musicals
Music & Performing Arts
Music Artists
Music Video & Concerts
Music Videos & Concerts
Music Videos and Concerts
Musicals
Musicals & Performing Arts
Musicals & Performing Arts Movies
Mysterious
Mystery
Mystery & Suspense
Mystery & Thrillers
Mystical
Música y conciertos
N Sync
NCAA on Demand
NOVA
Nail-Biting
Nature & Wildlife
Nelson, Willie
New Line Platinum Series
New Yorker Films
Niche Picks
Nightline
Noah
Norwegian
Nostalgic
Olympics
Ominous
Opera
Optimistic
Ordering
Osbourne, Ozzy
Oscar Central
Oscar Nominees
Oscar® Collection
Other Instructors
Other Topics
Outlandish
Outrageous
PBS
Paramount Home Entertainment
Parker, Charlie
Passionate
Passport to Europe
Past Emmy Winners
Past Golden Globe Winners
Past Oscar Winners
Patricia Walden
Paul McCartney
Peaceful
Performing Arts
Persian (Farsi)
Philosophical
Pierce Brosnan
Pink Floyd
Pirates of the Caribbean
Pixar
Planet of the Apes
Playful
Playing Shakespeare
Poland
Polish
Politics
Pope
Portuguese
Powerful
Pre & Post Natal
Pre-Orders
Presley, Elvis
Prime Video
Primetime
Primetime Emmy® Central
Prince
Princess Collection
Princess Diaries
Priscilla Patrick
Prison
Psychedelic
Queen
Queen Esther
Quirky
Ralph Bakshi
Reality TV
Reed, Lou
Relaxation
Religion
Religion & Spirituality
Rice, Damien
Rich, Buddy
Rieu, Andre
Ringo Starr
Riverdance
Robots & Androids
Rock, Chris
Rodney Yee
Roger Moore
Romance
Romantic
Roxy Music
Roy Orbison
Rush
Russia
Russian
Russian Masters
Sad
Samurai Films
Santana
Sassy
Scary
Sci Fi Channel
Sci-Fi & Fantasy
Sci-Fi Action
Sci-Fi Series & Sequels
Sci-fi & Fantasy
Science & Technology
Science Fiction
Science Fiction & Fantasy
Scooby Doo
Scooby Doo Animated Movies
Scooby Doo Live Action Movies
Sean Connery
Sensual
Sentimental
Serious
Shakespeare 101
Shakespeare for Kids
Shakespeare on DVD Store
Shakur, Tupac
Shootout
Showtime
Shrek
Silent Films
Slasher
Snoop Dogg
Sober
Sony Pictures Classics
Sony Pictures Home Entertainment
Sophisticated
Space Adventure
Spain
Spanish
Spanish Language
Spanish-Language
Spears, Britney
Special Editions
Special Interest
Special Interests
Sports
Spotlight Deals
Springsteen, Bruce
Stand Up
Star Trek
Star Wars
Stephen Lynch
Stewart, Rod
Sting
Stop-Motion & Clay Animation
Strange
Streisand, Barbra
Studio Specials
Study & Teaching Guides
Stunning
Subjects
Subversive Cinema
Sundance Channel Home Entertainment
Sundance Channel Store
Superbit Collection
Superman Animated Movies
Suspense
Suzanne Deason
Sweden
Swedish
Sweet
TLC
TV
TV & Miniseries
TV Game Shows
TV News Programming
TV Series
TV Talk Shows
Tai Chi
Taiwan
Talk Show and Variety
Talking Heads
Taylor, James
Television
Televisíon y documentales
Tenacious D
Tense
Terminator
Terrifying
The 1950s
The 1960s
The 1970s
The 1980s
The 1990s
The Beatles
The Big DVD & Blu-ray Blowout
The Big DVD Sale
The Blues Brothers
The Century of Warfare
The Comedies
The Comedy Central Store
The Doors
The Histories
The Judds
The Matrix
The Rolling Stones
The Shins
The Temptations
The Tragedies
The Twilight Zone
The Who
The Works
Theater
Thoughtful
Three Stooges
Thrilling
Timeless Holiday Favorites
Timothy Dalton & George Lazenby
Today's Deals
Today's Spotlight Deals
Too Short
Top Sellers
Touching
Travel
Travel Channel
Turkey
Turner, Tina
Twain, Shania
Tweens
Twilight Zone DVDs
Two-Disc Special Editions
U2
Ultimate Collector's Editions
Ultimate Editions
Understated
United Kingdom
Universal Media Discs
Universal Studios Featured Deals
Universal Studios Home Entertainment
Unscripted
Unsettling
UpClose
Upbeat
Van Halen
Vaughan, Stevie Ray
Vietnam
Visceral
Vista Series
WGBH Boston
WMV HD Store
Wai Lana
Wall-E
Walt Disney Legacy Collection
Walt Disney Studios Home Entertainment
Walt Disney Treasures
War & Military
Warner Archive
Warner Bros. 90th Anniversary Store
Warner Bros. Featured Deals
Warner DVD & Blu-ray Deals
Warner Home Video
Warner Sale
Warner Video Bargains
Waters, Muddy
Weird Al
Wellspring Home Video
Western
Westerns
Whimsical
Widescreen
Women's Basketball
Wondrous
World Class Cinema
World's Best
X-Men
Yes
Yoga
Yoga Journal
Yoga Studios
Yoga Zone
Young Adult Audience
Young, Neil
Zagreb School

In [9]:
# Building filtered product tables for the selected project categories
execute_sql_file(sql_file_path = "sql scripts/04_build_filtered_category_products.sql",
                 configuration = configuration
)

SQL script executed successfully : /Users/bhavikpatwa/Documents/PROJECTS/Amazon Reviews Intelligence/sql scripts/04_build_filtered_category_products.sql

In [10]:
# Summarizing filtered product coverage and key missing product fields by category

filtered_category_products_summary_query = f"""
SELECT
    category_name,
    COUNT(*) AS filtered_product_count,
    COUNTIF(TRIM(COALESCE(product_title, "")) = "") AS blank_product_title_count,
    COUNTIF(TRIM(COALESCE(main_category, "")) = "") AS blank_main_category_count,
    COUNTIF(TRIM(COALESCE(store, "")) = "") AS blank_store_count,
    COUNTIF(price_amount IS NULL) AS missing_price_count
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.filtered_category_products`
GROUP BY category_name
ORDER BY category_name
"""

filtered_category_products_summary_dataframe = run_query(filtered_category_products_summary_query)
display(filtered_category_products_summary_dataframe)

,category_name,filtered_product_count,blank_product_title_count,blank_main_category_count,blank_store_count,missing_price_count
0,Beauty_and_Personal_Care,1028108,54,102896,50424,647716
1,Books,4448181,0,7490,174576,847137
2,Electronics,1508480,91,69982,8164,1020508
3,Home_and_Kitchen,3735352,217,363310,83485,2456469
4,Movies_and_TV,747505,314002,36338,355040,483912

In [11]:
# Comparing original and filtered product counts to measure retained product coverage

filtered_vs_original_products_query = f"""
SELECT
    original.category_name,
    original.original_product_count,
    filtered.filtered_product_count,
    original.original_product_count - filtered.filtered_product_count AS excluded_product_count,
    SAFE_DIVIDE(
        filtered.filtered_product_count,
        original.original_product_count
    ) AS retained_product_ratio
FROM (
    SELECT
        category_name,
        COUNT(*) AS original_product_count
    FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.products`
    GROUP BY category_name
) AS original
LEFT JOIN (
    SELECT
        category_name,
        COUNT(*) AS filtered_product_count
    FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.filtered_category_products`
    GROUP BY category_name
) AS filtered
    ON original.category_name = filtered.category_name
ORDER BY original.category_name
"""

filtered_vs_original_products_dataframe = run_query(filtered_vs_original_products_query)
display(filtered_vs_original_products_dataframe)

,category_name,original_product_count,filtered_product_count,excluded_product_count,retained_product_ratio
0,Beauty_and_Personal_Care,1028914,1028108,806,0.999217
1,Books,4448181,4448181,0,1.000000
2,Electronics,1610012,1508480,101532,0.936937
3,Home_and_Kitchen,3735584,3735352,232,0.999938
4,Movies_and_TV,748224,747505,719,0.999039

In [12]:
# Checking how well reviews join to the filtered product universe

review_to_filtered_product_join_query = f"""
SELECT
    reviews.category_name,
    COUNT(*) AS review_count,
    COUNTIF(products.parent_asin IS NOT NULL) AS matched_review_count,
    COUNTIF(products.parent_asin IS NULL) AS unmatched_review_count,
    SAFE_DIVIDE(COUNTIF(products.parent_asin IS NOT NULL), COUNT(*)) AS matched_review_ratio
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.reviews` AS reviews
LEFT JOIN `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.filtered_category_products` AS products
    ON reviews.category_name = products.category_name
   AND reviews.parent_asin = products.parent_asin
GROUP BY reviews.category_name
ORDER BY reviews.category_name
"""

review_to_filtered_product_join_dataframe = run_query(review_to_filtered_product_join_query)
display(review_to_filtered_product_join_dataframe)

,category_name,review_count,matched_review_count,unmatched_review_count,matched_review_ratio
0,Beauty_and_Personal_Care,23911390,23907618,3772,0.999842
1,Books,29475453,29475453,0,1.000000
2,Electronics,43886944,42433444,1453500,0.966881
3,Home_and_Kitchen,67409944,67408754,1190,0.999982
4,Movies_and_TV,17328314,17324296,4018,0.999768

In [13]:
# Verifying filtered review coverage and review-to-product join quality by category

filtered_reviews_verification_query = f"""
WITH original_review_counts AS (
    SELECT
        category_name,
        COUNT(*) AS original_review_count,
        COUNT(DISTINCT parent_asin) AS original_distinct_parent_asin_count
    FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.reviews`
    GROUP BY category_name
),
filtered_review_counts AS (
    SELECT
        category_name,
        COUNT(*) AS filtered_review_count,
        COUNT(DISTINCT parent_asin) AS filtered_distinct_parent_asin_count
    FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.filtered_category_reviews`
    GROUP BY category_name
),
filtered_review_join_check AS (
    SELECT
        reviews.category_name,
        COUNT(*) AS filtered_review_join_count,
        COUNTIF(products.parent_asin IS NULL) AS unmatched_filtered_review_count
    FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.filtered_category_reviews` AS reviews
    LEFT JOIN `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.filtered_category_products` AS products
        ON reviews.category_name = products.category_name
       AND reviews.parent_asin = products.parent_asin
    GROUP BY reviews.category_name
)

SELECT
    original.category_name,
    original.original_review_count,
    filtered.filtered_review_count,
    original.original_review_count - filtered.filtered_review_count AS excluded_review_count,
    SAFE_DIVIDE(filtered.filtered_review_count, original.original_review_count) AS retained_review_ratio,
    original.original_distinct_parent_asin_count,
    filtered.filtered_distinct_parent_asin_count,
    join_check.unmatched_filtered_review_count
FROM original_review_counts AS original
INNER JOIN filtered_review_counts AS filtered
    ON original.category_name = filtered.category_name
INNER JOIN filtered_review_join_check AS join_check
    ON original.category_name = join_check.category_name
ORDER BY original.category_name
"""


filtered_reviews_verification_dataframe = run_query(filtered_reviews_verification_query)
display(filtered_reviews_verification_dataframe)

,category_name,original_review_count,filtered_review_count,excluded_review_count,retained_review_ratio,original_distinct_parent_asin_count,filtered_distinct_parent_asin_count,unmatched_filtered_review_count
0,Beauty_and_Personal_Care,23911390,23907618,3772,0.999842,1028731,1027925,0
1,Books,29475453,29475453,0,1.000000,4446065,4446065,0
2,Electronics,43886944,42433444,1453500,0.966881,1609860,1508336,0
3,Home_and_Kitchen,67409944,67408754,1190,0.999982,3734414,3734182,0
4,Movies_and_TV,17328314,17324296,4018,0.999768,747764,747046,0

In [14]:
# Creating core profiling tables for ratings, text quality, product quality and joins
execute_sql_file(sql_file_path = "sql scripts/05_profile_core_tables.sql",
                 configuration = configuration
)

SQL script executed successfully : /Users/bhavikpatwa/Documents/PROJECTS/Amazon Reviews Intelligence/sql scripts/05_profile_core_tables.sql

In [15]:
# Reviewing rating distribution across categories
rating_distribution_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.profile_rating_distribution`
ORDER BY category_name, rating
"""

rating_distribution_dataframe = run_query(rating_distribution_query)
rating_distribution_dataframe

               category_name  rating  review_count
0   Beauty_and_Personal_Care     1.0       2840682
1   Beauty_and_Personal_Care     2.0       1274932
2   Beauty_and_Personal_Care     3.0       1715661
3   Beauty_and_Personal_Care     4.0       2616075
4   Beauty_and_Personal_Care     5.0      15460268
5                      Books     0.0             4
6                      Books     1.0       1316085
7                      Books     2.0       1080897
8                      Books     3.0       2054057
9                      Books     4.0       4632932
10                     Books     5.0      20391478
11               Electronics     0.0             2
12               Electronics     1.0       5206041
13               Electronics     2.0       2192113
14               Electronics     3.0       2791618
15               Electronics     4.0       5385790
16               Electronics     5.0      26857880
17          Home_and_Kitchen     1.0       7160263
18          Home_and_Kitchen     2.0       3410745
19          Home_and_Kitchen     3.0       4600392
20          Home_and_Kitchen     4.0       7536253
21          Home_and_Kitchen     5.0      44701101
22             Movies_and_TV     1.0       1409973
23             Movies_and_TV     2.0        766608
24             Movies_and_TV     3.0       1259975
25             Movies_and_TV     4.0       2604259
26             Movies_and_TV     5.0      11283481

In [16]:
# Reviewing review text quality across categories
text_quality_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.profile_reviews_text_quality`
ORDER BY category_name
"""

text_quality_dataframe = run_query(text_quality_query)
text_quality_dataframe

,category_name,review_count,blank_review_text_count,very_short_review_count,short_review_count,long_review_count,no_alphabetic_character_count,url_present_count,average_review_text_length,max_review_text_length
0,Beauty_and_Personal_Care,23907618,36594,2601399,3916490,321304,68823,5667,177.618641,30454
1,Books,29475453,7636,2425868,3084509,3135017,27964,20919,423.101702,37878
2,Electronics,42433444,39789,4581217,6461375,1585518,82753,41097,242.865295,35208
3,Home_and_Kitchen,67408754,138834,6571794,11460055,971951,199541,21738,178.789289,30981
4,Movies_and_TV,17324296,1217,3131593,3020690,777819,34071,3623,236.719577,36887

In [17]:
# Reviewing product metadata and quality signals across categories
products_quality_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.profile_products_quality`
ORDER BY category_name
"""

products_quality_dataframe = run_query(products_quality_query)
products_quality_dataframe

,category_name,product_count,missing_parent_asin_count,null_product_title_count,blank_product_title_count,null_main_category_count,blank_main_category_count,null_store_count,blank_store_count,missing_price_count,non_positive_price_count,high_price_count,missing_average_rating_count,missing_rating_number_count,missing_categories_json_count,missing_features_json_count,missing_description_json_count,missing_details_json_count,average_price_amount,max_price_amount
0,Beauty_and_Personal_Care,1028108,0,0,54,102896,102896,50421,50424,647716,0,259,0,0,0,282680,464024,16114,29.184296,12999.99
1,Books,4448181,0,0,0,358,7490,174454,174576,847137,98255,2367,0,0,530961,520315,2607876,299687,25.230659,1000000.00
2,Electronics,1508480,0,0,91,69982,69982,8162,8164,1020508,3,7374,0,0,432443,401336,641433,18999,100.173353,30999.00
3,Home_and_Kitchen,3735352,0,0,217,363310,363310,83482,83485,2456469,1,4875,0,0,390737,911758,1631631,44858,54.239092,99999.00
4,Movies_and_TV,747505,0,313988,314002,36338,36338,355038,355040,483912,14,16,246,246,317809,710798,399986,10578,23.264866,2456.78

In [18]:
# Reviewing review-to-product join quality across categories
join_quality_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.profile_review_product_join_quality`
ORDER BY category_name
"""

join_quality_dataframe = run_query(join_quality_query)
join_quality_dataframe

,category_name,review_count,matched_product_count,unmatched_product_count,matched_product_ratio,unmatched_product_ratio
0,Beauty_and_Personal_Care,23907618,23907618,0,1.0,0.0
1,Books,29475453,29475453,0,1.0,0.0
2,Electronics,42433444,42433444,0,1.0,0.0
3,Home_and_Kitchen,67408754,67408754,0,1.0,0.0
4,Movies_and_TV,17324296,17324296,0,1.0,0.0

In [19]:
# Creating analysis-readiness profiling tables for reviews and products
execute_sql_file(sql_file_path = "sql scripts/06_profile_analysis_readiness.sql",
                 configuration = configuration
)

SQL script executed successfully : /Users/bhavikpatwa/Documents/PROJECTS/Amazon Reviews Intelligence/sql scripts/06_profile_analysis_readiness.sql

In [20]:
# Reviewing review value-quality signals such as ratings, votes and usable fields
reviews_value_quality_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.profile_reviews_value_quality`
ORDER BY category_name
"""

reviews_value_quality_dataframe = run_query(reviews_value_quality_query)
reviews_value_quality_dataframe

,category_name,review_count,invalid_rating_count,zero_rating_count,missing_helpful_vote_count,negative_helpful_vote_count,max_helpful_vote,suspicious_early_review_date_count,future_review_date_count
0,Beauty_and_Personal_Care,23907618,0,0,0,0,11931,0,0
1,Books,29475453,4,4,0,1,18130,0,0
2,Electronics,42433444,2,2,0,4,46841,0,0
3,Home_and_Kitchen,67408754,0,0,0,9,34619,0,0
4,Movies_and_TV,17324296,0,0,0,0,20604,0,0

In [21]:
# Reviewing duplicate-review signals across categories
reviews_duplicate_signals_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.profile_reviews_duplicate_signals`
ORDER BY category_name
"""

reviews_duplicate_signals_dataframe = run_query(reviews_duplicate_signals_query)
reviews_duplicate_signals_dataframe

,category_name,unique_review_groups,duplicated_review_groups,total_rows_in_grouping,duplicated_rows
0,Beauty_and_Personal_Care,23665121,207160,23907618,449657
1,Books,29142325,276765,29475453,609893
2,Electronics,41971019,391677,42433444,854102
3,Home_and_Kitchen,66736663,575149,67408754,1247240
4,Movies_and_TV,17154573,147106,17324296,316829

In [22]:
# Reviewing text-readiness coverage for downstream analysis
reviews_text_readiness_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.profile_reviews_text_readiness`
ORDER BY category_name
"""

reviews_text_readiness_dataframe = run_query(reviews_text_readiness_query)
reviews_text_readiness_dataframe

,category_name,review_count,non_blank_review_text_count,review_text_30_plus_count,review_text_50_plus_count,review_text_100_plus_count,alphabetic_word_pattern_count,symbol_only_or_empty_count
0,Beauty_and_Personal_Care,23907618,23871024,20071512,17472635,12576483,23790572,66765
1,Books,29475453,29467817,26064946,24046031,20439341,29388911,25361
2,Electronics,42433444,42393655,35750248,31535976,24109115,42240189,78072
3,Home_and_Kitchen,67408754,67269920,57204572,49589345,35325912,67103781,195303
4,Movies_and_TV,17324296,17323079,13155695,11250382,8408778,17219556,30159

In [23]:
# Reviewing product metadata readiness for content-based analysis
products_metadata_readiness_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.profile_products_metadata_readiness`
ORDER BY category_name
"""

products_metadata_readiness_dataframe = run_query(products_metadata_readiness_query)
products_metadata_readiness_dataframe

,category_name,product_count,usable_product_title_count,usable_main_category_count,usable_store_count,usable_price_count,usable_features_count,usable_description_count,usable_details_count
0,Beauty_and_Personal_Care,1028108,1028054,925212,977684,380392,745428,564084,1011994
1,Books,4448181,4448181,4440691,4273605,3502789,3927866,1840305,4148494
2,Electronics,1508480,1508389,1438498,1500316,487969,1107144,867047,1489481
3,Home_and_Kitchen,3735352,3735135,3372042,3651867,1278882,2823594,2103721,3690494
4,Movies_and_TV,747505,433503,711167,392465,263579,36707,347519,736927

In [24]:
# Reviewing price availability and price distribution readiness across categories
products_price_distribution_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.profile_products_price_distribution`
ORDER BY category_name
"""

products_price_distribution_dataframe = run_query(products_price_distribution_query)
products_price_distribution_dataframe

,category_name,product_count,missing_price_count,non_positive_price_count,price_p05,price_p25,price_p50,price_p75,price_p95,max_price_amount
0,Beauty_and_Personal_Care,1028108,647716,0,5.94,9.98,15.99,29.00,84.99,12999.99
1,Books,4448181,847137,98255,3.99,8.37,14.18,23.92,72.01,1000000.00
2,Electronics,1508480,1020508,3,6.99,11.99,22.99,64.79,419.95,30999.00
3,Home_and_Kitchen,3735352,2456469,1,6.99,12.99,20.74,40.14,185.90,99999.00
4,Movies_and_TV,747505,483912,14,5.00,9.99,15.05,24.99,63.00,2456.78

In [25]:
# Building cleaned analysis base tables for reviews, products and joined review-product records
execute_sql_file(sql_file_path = "sql scripts/07_build_analysis_base_tables.sql",
                 configuration = configuration
)

SQL script executed successfully : /Users/bhavikpatwa/Documents/PROJECTS/Amazon Reviews Intelligence/sql scripts/07_build_analysis_base_tables.sql

In [26]:
# Validating the review analysis base table by checking duplicate, text-ready and vote-quality signals

reviews_analysis_base_query = f"""
SELECT
    category_name,
    COUNT(*) AS review_count,
    COUNTIF(is_duplicate_candidate) AS duplicate_candidate_count,
    COUNTIF(is_text_analysis_ready) AS text_analysis_ready_count,
    COUNTIF(had_negative_helpful_vote) AS negative_helpful_vote_flag_count
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.reviews_analysis_base`
GROUP BY category_name
ORDER BY category_name
"""

reviews_analysis_base_dataframe = run_query(reviews_analysis_base_query)
reviews_analysis_base_dataframe

,category_name,review_count,duplicate_candidate_count,text_analysis_ready_count,negative_helpful_vote_flag_count
0,Beauty_and_Personal_Care,23907618,449657,20065779,0
1,Books,29475449,609893,26058171,1
2,Electronics,42433442,854102,35739187,4
3,Home_and_Kitchen,67408754,1247240,57185666,9
4,Movies_and_TV,17324296,316829,13149337,0

In [27]:
# Validating the product analysis base table by checking usable metadata and price fields

products_analysis_base_query = f"""
SELECT
    category_name,
    COUNT(*) AS product_count,
    COUNTIF(has_usable_product_title) AS usable_product_title_count,
    COUNTIF(has_usable_main_category) AS usable_main_category_count,
    COUNTIF(has_usable_store) AS usable_store_count,
    COUNTIF(has_usable_price) AS usable_price_count,
    COUNTIF(price_above_p95_flag) AS price_above_p95_count,
    COUNTIF(has_usable_features) AS usable_features_count,
    COUNTIF(has_usable_description) AS usable_description_count,
    COUNTIF(has_usable_details) AS usable_details_count
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.products_analysis_base`
GROUP BY category_name
ORDER BY category_name
"""

products_analysis_base_dataframe = run_query(products_analysis_base_query)
products_analysis_base_dataframe

,category_name,product_count,usable_product_title_count,usable_main_category_count,usable_store_count,usable_price_count,price_above_p95_count,usable_features_count,usable_description_count,usable_details_count
0,Beauty_and_Personal_Care,1028108,1028054,925212,977684,380392,18961,745428,564084,1011994
1,Books,4448181,4448181,4440691,4273605,3502789,176633,3927866,1840305,4148494
2,Electronics,1508480,1508389,1438498,1500316,487969,24455,1107144,867047,1489481
3,Home_and_Kitchen,3735352,3735135,3372042,3651867,1278882,64198,2823594,2103721,3690494
4,Movies_and_TV,747505,433503,711167,392465,263579,13213,36707,347519,736927

In [28]:
# Validating the joined review-product analysis base table for title, price and text readiness

review_product_analysis_base_query = f"""
SELECT
    category_name,
    COUNT(*) AS review_count,
    COUNTIF(has_usable_product_title) AS reviews_with_usable_product_title,
    COUNTIF(has_usable_price) AS reviews_with_usable_price,
    COUNTIF(is_text_analysis_ready) AS text_analysis_ready_review_count
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.review_product_analysis_base`
GROUP BY category_name
ORDER BY category_name
"""

review_product_analysis_base_dataframe = run_query(review_product_analysis_base_query)
review_product_analysis_base_dataframe

,category_name,review_count,reviews_with_usable_product_title,reviews_with_usable_price,text_analysis_ready_review_count
0,Beauty_and_Personal_Care,23907618,23906933,16743660,20065779
1,Books,29475449,29475449,23509134,26058171
2,Electronics,42433442,42432429,24659426,35739187
3,Home_and_Kitchen,67408754,67407287,45811976,57185666
4,Movies_and_TV,17324296,7903586,6535507,13149337

In [29]:
# Building analysis-scope tables for general, text, price, and content analysis
execute_sql_file(sql_file_path = "sql scripts/08_build_analysis_scope_tables.sql",
                 configuration = configuration
)

SQL script executed successfully : /Users/bhavikpatwa/Documents/PROJECTS/Amazon Reviews Intelligence/sql scripts/08_build_analysis_scope_tables.sql

In [30]:
# Reviewing category-level analysis scope coverage across all supported use cases
analysis_scope_summary_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.analysis_scope_category_summary`
ORDER BY category_name
"""

analysis_scope_summary_dataframe = run_query(analysis_scope_summary_query)
analysis_scope_summary_dataframe

,category_name,total_review_count,primary_duplicate_review_count,text_analysis_ready_review_count,price_analysis_ready_review_count,title_analysis_ready_review_count,store_analysis_ready_review_count,features_analysis_ready_review_count,description_analysis_ready_review_count,primary_duplicate_review_ratio,text_analysis_ready_ratio,price_analysis_ready_ratio,title_analysis_ready_ratio,store_analysis_ready_ratio,features_analysis_ready_ratio,description_analysis_ready_ratio
0,Beauty_and_Personal_Care,23907618,23665121,19863281,16573769,23664444,22314628,20617595,11806284,0.989857,0.830835,0.693242,0.989829,0.933369,0.862386,0.493829
1,Books,29475449,29142321,25760319,23239954,29142321,28740485,28039405,20134405,0.988698,0.873958,0.788451,0.988698,0.975065,0.951280,0.683091
2,Electronics,42433442,41971017,35351019,24393251,41970023,41923266,38382524,21129097,0.989102,0.833093,0.574859,0.989079,0.987977,0.904535,0.497935
3,Home_and_Kitchen,67408754,66736663,56620111,45359343,66735208,66361343,61311611,34877255,0.990030,0.839952,0.672900,0.990008,0.984462,0.909550,0.517399
4,Movies_and_TV,17324296,17154573,13020101,6471606,7825137,6648523,1181149,7331909,0.990203,0.751552,0.373557,0.451686,0.383769,0.068179,0.423215

In [31]:
# Comparing record volumes across general, text, price and content analysis scopes

analysis_scope_counts_query = f"""
SELECT
    "review_product_general_analysis_scope" AS table_name,
    category_name,
    COUNT(*) AS review_count
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.review_product_general_analysis_scope`
GROUP BY category_name

UNION ALL

SELECT
    "review_product_text_analysis_scope" AS table_name,
    category_name,
    COUNT(*) AS review_count
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.review_product_text_analysis_scope`
GROUP BY category_name

UNION ALL

SELECT
    "review_product_price_analysis_scope" AS table_name,
    category_name,
    COUNT(*) AS review_count
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.review_product_price_analysis_scope`
GROUP BY category_name

UNION ALL

SELECT
    "review_product_content_analysis_scope" AS table_name,
    category_name,
    COUNT(*) AS review_count
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.review_product_content_analysis_scope`
GROUP BY category_name

ORDER BY table_name, category_name
"""

analysis_scope_counts_dataframe = run_query(analysis_scope_counts_query)
analysis_scope_counts_dataframe

,table_name,category_name,review_count
0,review_product_content_analysis_scope,Beauty_and_Personal_Care,23636333
1,review_product_content_analysis_scope,Books,28774093
2,review_product_content_analysis_scope,Electronics,41858344
3,review_product_content_analysis_scope,Home_and_Kitchen,66674713
4,review_product_content_analysis_scope,Movies_and_TV,7762107
5,review_product_general_analysis_scope,Beauty_and_Personal_Care,23665121
6,review_product_general_analysis_scope,Books,29142321
7,review_product_general_analysis_scope,Electronics,41971017
8,review_product_general_analysis_scope,Home_and_Kitchen,66736663
9,review_product_general_analysis_scope,Movies_and_TV,17154573
10,review_product_price_analysis_scope,Beauty_and_Personal_Care,16573769
11,review_product_price_analysis_scope,Books,23239954
12,review_product_price_analysis_scope,Electronics,24393251
13,review_product_price_analysis_scope,Home_and_Kitchen,45359343
14,review_product_price_analysis_scope,Movies_and_TV,6471606
15,review_product_text_analysis_scope,Beauty_and_Personal_Care,19863281
16,review_product_text_analysis_scope,Books,25760319
17,review_product_text_analysis_scope,Electronics,35351019
18,review_product_text_analysis_scope,Home_and_Kitchen,56620111
19,review_product_text_analysis_scope,Movies_and_TV,13020101

In [32]:
# Building analysis quality and governance tables for exclusion tracking and readiness validation
execute_sql_file(sql_file_path = "sql scripts/09_build_analysis_quality_governance.sql",
                 configuration = configuration
)

SQL script executed successfully : /Users/bhavikpatwa/Documents/PROJECTS/Amazon Reviews Intelligence/sql scripts/09_build_analysis_quality_governance.sql

In [33]:
# Reviewing high-level reasons why records are excluded from downstream analysis
analysis_scope_exclusion_summary_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.analysis_scope_exclusion_summary`
ORDER BY category_name
"""

analysis_scope_exclusion_summary_dataframe = run_query(analysis_scope_exclusion_summary_query)
analysis_scope_exclusion_summary_dataframe

,category_name,total_review_count,excluded_duplicate_review_count,excluded_blank_text_review_count,excluded_text_analysis_review_count,excluded_price_analysis_review_count,excluded_title_analysis_review_count,excluded_store_analysis_review_count,excluded_content_analysis_review_count,included_general_analysis_review_count,included_text_analysis_review_count,included_price_analysis_review_count,included_content_analysis_review_count
0,Beauty_and_Personal_Care,23907618,242497,36594,3841839,7163958,685,1363897,28432,23665121,19863281,16573769,23636333
1,Books,29475449,333128,7636,3417278,5966315,0,406466,372152,29142321,25760319,23239954,28774093
2,Electronics,42433442,462425,39789,6694255,17774016,1013,48250,112945,41971017,35351019,24393251,41858344
3,Home_and_Kitchen,67408754,672091,138834,10223088,21596778,1467,379226,61125,66736663,56620111,45359343,66674713
4,Movies_and_TV,17324296,169723,1217,4174959,10788789,9420710,10608731,63941,17154573,13020101,6471606,7762107

In [34]:
# Reviewing detailed exclusion patterns by category and exclusion reason

analysis_scope_exclusion_details_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.analysis_scope_exclusion_details`
ORDER BY category_name, exclusion_reason
"""

analysis_scope_exclusion_details_dataframe = run_query(analysis_scope_exclusion_details_query)
analysis_scope_exclusion_details_dataframe

               category_name                 exclusion_reason  review_count
0   Beauty_and_Personal_Care                Blank review text         36594
1   Beauty_and_Personal_Care          Duplicate review record        242497
2   Beauty_and_Personal_Care  Missing usable content metadata         28432
3   Beauty_and_Personal_Care             Missing usable price       7163958
4   Beauty_and_Personal_Care     Missing usable product title           685
5   Beauty_and_Personal_Care             Missing usable store       1363897
6   Beauty_and_Personal_Care      Not ready for text analysis       3841839
7                      Books                Blank review text          7636
8                      Books          Duplicate review record        333128
9                      Books  Missing usable content metadata        372152
10                     Books             Missing usable price       5966315
11                     Books             Missing usable store        406466
12                     Books      Not ready for text analysis       3417278
13               Electronics                Blank review text         39789
14               Electronics          Duplicate review record        462425
15               Electronics  Missing usable content metadata        112945
16               Electronics             Missing usable price      17774016
17               Electronics     Missing usable product title          1013
18               Electronics             Missing usable store         48250
19               Electronics      Not ready for text analysis       6694255
20          Home_and_Kitchen                Blank review text        138834
21          Home_and_Kitchen          Duplicate review record        672091
22          Home_and_Kitchen  Missing usable content metadata         61125
23          Home_and_Kitchen             Missing usable price      21596778
24          Home_and_Kitchen     Missing usable product title          1467
25          Home_and_Kitchen             Missing usable store        379226
26          Home_and_Kitchen      Not ready for text analysis      10223088
27             Movies_and_TV                Blank review text          1217
28             Movies_and_TV          Duplicate review record        169723
29             Movies_and_TV  Missing usable content metadata         63941
30             Movies_and_TV             Missing usable price      10788789
31             Movies_and_TV     Missing usable product title       9420710
32             Movies_and_TV             Missing usable store      10608731
33             Movies_and_TV      Not ready for text analysis       4174959

In [35]:
# Reviewing category-level readiness for general, text, price and content analysis

analysis_scope_data_readiness_summary_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.analysis_scope_data_readiness_summary`
ORDER BY category_name
"""

analysis_scope_data_readiness_summary_dataframe = run_query(analysis_scope_data_readiness_summary_query)
analysis_scope_data_readiness_summary_dataframe

,category_name,total_review_count,general_analysis_readiness_ratio,text_analysis_readiness_ratio,price_analysis_readiness_ratio,content_analysis_readiness_ratio
0,Beauty_and_Personal_Care,23907618,0.989857,0.830835,0.693242,0.988653
1,Books,29475449,0.988698,0.873958,0.788451,0.976205
2,Electronics,42433442,0.989102,0.833093,0.574859,0.986447
3,Home_and_Kitchen,67408754,0.990030,0.839952,0.672900,0.989111
4,Movies_and_TV,17324296,0.990203,0.751552,0.373557,0.448047

In [36]:
# Building behavioral signal base tables for category, product and monthly analysis
execute_sql_file(sql_file_path = "sql scripts/10_build_behavioral_signal_base.sql",
                 configuration = configuration
)

SQL script executed successfully : /Users/bhavikpatwa/Documents/PROJECTS/Amazon Reviews Intelligence/sql scripts/10_build_behavioral_signal_base.sql

In [37]:
# Reviewing category readiness for business and analytical use cases
category_use_case_readiness_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.analysis_category_use_case_readiness`
ORDER BY category_name
"""

category_use_case_readiness_dataframe = run_query(category_use_case_readiness_query)
category_use_case_readiness_dataframe

,category_name,total_review_count,general_analysis_readiness_ratio,text_analysis_readiness_ratio,price_analysis_readiness_ratio,content_analysis_readiness_ratio,general_analysis_readiness_level,text_analysis_readiness_level,price_analysis_readiness_level,content_analysis_readiness_level
0,Beauty_and_Personal_Care,23907618,0.989857,0.830835,0.693242,0.988653,High,High,Moderate,High
1,Books,29475449,0.988698,0.873958,0.788451,0.976205,High,High,High,High
2,Electronics,42433442,0.989102,0.833093,0.574859,0.986447,High,High,Moderate,High
3,Home_and_Kitchen,67408754,0.990030,0.839952,0.672900,0.989111,High,High,Moderate,High
4,Movies_and_TV,17324296,0.990203,0.751552,0.373557,0.448047,High,Moderate,Low,Low

In [38]:
# Reviewing monthly eligibility coverage for trend analysis across categories
monthly_category_eligibility_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.analysis_monthly_category_eligibility`
ORDER BY category_name, review_month
"""

monthly_category_eligibility_dataframe = run_query(monthly_category_eligibility_query)
monthly_category_eligibility_dataframe

,category_name,review_month,review_count,average_rating,low_rating_ratio,high_rating_ratio,average_helpful_vote,helpful_vote_presence_ratio,long_review_ratio,verified_purchase_ratio,monthly_sample_size_band,is_trend_analysis_eligible,is_high_confidence_trend_period
0,Beauty_and_Personal_Care,2000-08-01,1,5.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,Very low,False,False
1,Beauty_and_Personal_Care,2000-11-01,3,4.333333,0.000000,1.000000,54.333333,1.000000,0.666667,0.000000,Very low,False,False
2,Beauty_and_Personal_Care,2000-12-01,3,4.333333,0.000000,0.666667,4.000000,1.000000,0.666667,0.666667,Very low,False,False
3,Beauty_and_Personal_Care,2001-01-01,2,4.500000,0.000000,1.000000,14.000000,1.000000,0.500000,0.000000,Very low,False,False
4,Beauty_and_Personal_Care,2001-02-01,1,5.000000,0.000000,1.000000,11.000000,1.000000,1.000000,0.000000,Very low,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,Movies_and_TV,2023-05-01,13148,4.110967,0.184743,0.759811,0.222467,0.123213,0.148844,0.950943,High,True,True
1496,Movies_and_TV,2023-06-01,8514,4.082922,0.196030,0.754757,0.251821,0.120155,0.133192,0.952549,Moderate,True,False
1497,Movies_and_TV,2023-07-01,7340,4.124251,0.182153,0.760899,0.183515,0.097548,0.128338,0.949046,Moderate,True,False
1498,Movies_and_TV,2023-08-01,6216,4.253861,0.152510,0.802124,0.092181,0.061615,0.120495,0.952542,Moderate,True,False
1499,Movies_and_TV,2023-09-01,473,4.361522,0.122622,0.818182,0.076110,0.031712,0.141649,0.949260,Low,False,False

In [39]:
# Summarizing month-level coverage and reliability across categories
category_month_coverage_summary_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.analysis_category_month_coverage_summary`
ORDER BY category_name
"""

category_month_coverage_summary_dataframe = run_query(category_month_coverage_summary_query)
category_month_coverage_summary_dataframe

,category_name,total_month_count,eligible_month_count,high_confidence_month_count,first_review_month,last_review_month
0,Beauty_and_Personal_Care,276,191,141,2000-08-01,2023-09-01
1,Books,326,312,283,1996-06-01,2023-09-01
2,Electronics,293,242,193,1998-12-01,2023-09-01
3,Home_and_Kitchen,292,221,164,1998-05-01,2023-09-01
4,Movies_and_TV,313,287,202,1997-08-01,2023-09-01

In [40]:
# Reviewing whether products meet minimum sample requirements for analysis
product_sample_eligibility_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.analysis_product_sample_eligibility`
ORDER BY category_name, review_count DESC
LIMIT 100
"""

product_sample_eligibility_dataframe = run_query(product_sample_eligibility_query)
product_sample_eligibility_dataframe

,category_name,parent_asin,product_title,store_name,price_amount,review_count,average_rating,low_rating_ratio,one_star_ratio,average_helpful_vote,helpful_vote_presence_ratio,average_review_text_length,long_review_ratio,verified_purchase_ratio,text_analysis_ready_review_count,text_analysis_ready_ratio,product_sample_size_band,is_product_analysis_eligible,is_high_confidence_product_analysis_eligible
0,Beauty_and_Personal_Care,B01LSUQSB0,REVLON One-Step Volumizer Original 1.0 Hair Dr...,REVLON,38.80,36823,4.342911,0.124949,0.085083,0.864052,0.091247,202.919154,0.273660,0.968308,32053,0.870461,Very high,True,True
1,Beauty_and_Personal_Care,B0BVGHXZJ1,essence | Lash Princess False Lash Effect Masc...,essence cosmetics,4.99,33835,4.001241,0.204551,0.126880,0.286863,0.058756,149.143579,0.167874,0.987232,29394,0.868745,Very high,True,True
2,Beauty_and_Personal_Care,B001MA0QY2,HSI Professional Glider Ceramic Flat Iron Hair...,HSI PROFESSIONAL,41.61,27299,4.303674,0.122495,0.074838,2.482399,0.190556,219.014286,0.293527,0.948057,24171,0.885417,Very high,True,True
3,Beauty_and_Personal_Care,B0BYBCFHTB,"Dr. Squatch All Natural Bar Soap for Men, 5 Ba...",Dr. Squatch,43.95,24136,3.746685,0.244987,0.140827,0.660549,0.087960,185.021752,0.222282,0.944854,21031,0.871354,Very high,True,True
4,Beauty_and_Personal_Care,B0BS71PXPX,TruSkin Vitamin C Serum for Face – Anti Aging ...,TruSkin Naturals,21.97,22377,4.218483,0.154623,0.106627,1.448720,0.185637,203.057827,0.266390,0.933548,19484,0.870715,Very high,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Beauty_and_Personal_Care,B003WR3QSG,Escali 100% Pure Badger Shaving Brush,Escali,NaN,6830,4.268521,0.107321,0.059883,0.272182,0.061640,216.057101,0.275403,0.946559,6088,0.891362,Very high,True,True
96,Beauty_and_Personal_Care,B0B79WK8GN,"Burts Bees Honey Lip Balm Tube, 4.25 GR",Burt's Bees,NaN,6828,4.589045,0.075718,0.054921,0.431166,0.108524,117.247803,0.119947,0.940832,5126,0.750732,Very high,True,True
97,Beauty_and_Personal_Care,B07GCB8BRT,Revlon Compact Hair Dryer | 1875W Lightweight ...,REVLON,13.99,6809,4.286679,0.134968,0.107064,0.928330,0.098546,107.061977,0.101043,0.949185,4991,0.733000,Very high,True,True
98,Beauty_and_Personal_Care,B07H9XB7G6,REVLON One-Step Volumizer Original 1.0 Hair Dr...,REVLON,42.00,6801,4.320835,0.132628,0.089105,0.381414,0.061609,203.353183,0.269225,0.971475,5951,0.875018,Very high,True,True
99,Beauty_and_Personal_Care,B0BJLPRXZ6,"NYX PROFESSIONAL MAKEUP Butter Gloss, Non-Stic...",NYX Professional Makeup,4.97,6780,4.384366,0.103392,0.071386,1.078024,0.176401,111.446313,0.096903,0.954425,5331,0.786283,Very high,True,True

In [41]:
# Building behavioral insight tables for pricing, trust, trends and product risk analysis
execute_sql_file(sql_file_path = "sql scripts/11_build_behavioral_insights.sql",
                 configuration = configuration
)

SQL script executed successfully : /Users/bhavikpatwa/Documents/PROJECTS/Amazon Reviews Intelligence/sql scripts/11_build_behavioral_insights.sql

In [42]:
# Reviewing customer behavior patterns across product price bands

price_band_summary_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.analysis_price_band_summary`
ORDER BY category_name, price_band
"""

price_band_summary_dataframe = run_query(price_band_summary_query)
price_band_summary_dataframe

,category_name,price_band,review_count,average_rating,low_rating_ratio,one_star_ratio,average_helpful_vote,helpful_vote_presence_ratio,average_review_text_length,long_review_ratio,verified_purchase_ratio
0,Beauty_and_Personal_Care,Budget,4769275,4.047975,0.187195,0.129607,0.964684,0.235896,153.799911,0.173164,0.924668
1,Beauty_and_Personal_Care,Lower mid,3517949,4.150343,0.163540,0.111579,1.125357,0.256429,172.880008,0.205769,0.923441
2,Beauty_and_Personal_Care,Premium,3319193,4.159684,0.163790,0.114966,1.417102,0.292428,190.441660,0.232220,0.911342
3,Beauty_and_Personal_Care,Upper mid,4140548,4.177641,0.158712,0.109588,1.237187,0.264056,178.717469,0.215357,0.919908
4,Beauty_and_Personal_Care,Very premium,826804,4.136390,0.172369,0.124920,2.039647,0.368051,208.851309,0.254545,0.903135
5,Books,Budget,6111774,4.394251,0.084497,0.046674,1.504779,0.337092,400.630395,0.375167,0.703046
6,Books,Lower mid,5608756,4.401054,0.083238,0.044984,1.568323,0.323157,401.755838,0.376932,0.708349
7,Books,Premium,4641276,4.462271,0.076345,0.042151,2.477175,0.443611,460.051130,0.412911,0.728064
8,Books,Upper mid,5719835,4.436506,0.079349,0.042727,2.117633,0.399694,483.365351,0.442066,0.671920
9,Books,Very premium,1158313,4.443497,0.083373,0.050179,2.394336,0.445696,424.543808,0.385109,0.754628
10,Electronics,Budget,6168914,4.179755,0.163057,0.120670,0.498304,0.138142,145.721421,0.159681,0.958937
11,Electronics,Lower mid,6022104,4.195324,0.154151,0.108120,0.668427,0.158955,182.778782,0.215916,0.949702
12,Electronics,Premium,4878463,4.067249,0.181203,0.127526,1.758605,0.288806,314.269848,0.359854,0.902885
13,Electronics,Upper mid,6103011,4.131705,0.166804,0.116317,1.006010,0.201600,235.297900,0.282972,0.932586
14,Electronics,Very premium,1220759,4.075540,0.180538,0.128902,3.312259,0.433942,420.320166,0.432724,0.875393
15,Home_and_Kitchen,Budget,11335026,4.224666,0.147337,0.100448,0.634009,0.181031,136.731353,0.143018,0.949849
16,Home_and_Kitchen,Lower mid,11360398,4.270446,0.136486,0.091297,0.754433,0.196515,151.490748,0.168579,0.942209
17,Home_and_Kitchen,Premium,8675479,4.153181,0.161628,0.109782,1.539355,0.283951,212.275831,0.263773,0.936998
18,Home_and_Kitchen,Upper mid,11721827,4.218608,0.147887,0.099211,0.999919,0.220987,172.059418,0.203362,0.936163
19,Home_and_Kitchen,Very premium,2266613,4.085332,0.176268,0.121082,2.611879,0.380895,298.169213,0.367818,0.928683
20,Movies_and_TV,Budget,1665727,4.347382,0.103464,0.065308,1.350778,0.291098,325.529402,0.277530,0.768572
21,Movies_and_TV,Lower mid,1570189,4.358412,0.102130,0.065890,1.457004,0.311034,317.120890,0.275116,0.798242
22,Movies_and_TV,Premium,1292533,4.428098,0.089897,0.059531,2.111070,0.364482,360.110434,0.311961,0.802551
23,Movies_and_TV,Upper mid,1619747,4.360685,0.102110,0.065555,1.557219,0.307810,301.688313,0.264422,0.820340
24,Movies_and_TV,Very premium,323410,4.420036,0.095006,0.064686,3.062679,0.434959,387.694360,0.349875,0.829109

In [43]:
# Reviewing how verified and non-verified reviews differ across rating segments

verified_rating_behavior_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.analysis_verified_rating_behavior`
ORDER BY category_name, verified_purchase, rating
"""

verified_rating_behavior_dataframe = run_query(verified_rating_behavior_query)
verified_rating_behavior_dataframe

,category_name,verified_purchase,rating,review_count,average_helpful_vote,helpful_vote_presence_ratio,average_review_text_length,long_review_ratio
0,Beauty_and_Personal_Care,False,1,219730,2.049861,0.411500,305.792686,0.416338
1,Beauty_and_Personal_Care,False,2,103432,1.169909,0.314487,392.216335,0.528047
2,Beauty_and_Personal_Care,False,3,160255,0.981417,0.256728,440.316820,0.572350
3,Beauty_and_Personal_Care,False,4,347389,0.948490,0.250014,469.410580,0.614262
4,Beauty_and_Personal_Care,False,5,1273836,1.059992,0.240869,333.086214,0.443345
5,Beauty_and_Personal_Care,True,1,2587737,1.609154,0.366316,167.542934,0.197275
6,Beauty_and_Personal_Care,True,2,1158531,0.955640,0.288284,195.823913,0.249184
7,Beauty_and_Personal_Care,True,3,1538945,0.932744,0.288681,191.302203,0.238230
8,Beauty_and_Personal_Care,True,4,2243413,1.178881,0.285777,188.672555,0.231931
9,Beauty_and_Personal_Care,True,5,14031853,1.103153,0.238267,146.268601,0.161081
10,Books,False,1,500742,7.555160,0.728573,702.574587,0.672993
11,Books,False,2,395602,4.584024,0.657125,978.891292,0.807534
12,Books,False,3,723575,3.242464,0.526811,1104.562626,0.816044
13,Books,False,4,1754227,2.104724,0.429053,1067.779335,0.790890
14,Books,False,5,5425992,2.309955,0.444070,710.741576,0.656911
15,Books,True,1,799042,4.388056,0.535021,299.447813,0.341535
16,Books,True,2,673305,3.210967,0.502312,373.530217,0.409048
17,Books,True,3,1309302,2.104427,0.395701,340.739858,0.353318
18,Books,True,4,2828995,1.230026,0.309433,308.490478,0.307559
19,Books,True,5,14731539,1.063809,0.285955,218.569416,0.230051
20,Electronics,False,1,535492,2.902391,0.457829,482.046152,0.576149
21,Electronics,False,2,222093,2.355099,0.402701,643.320145,0.688495
22,Electronics,False,3,248047,3.054715,0.375340,715.919898,0.677005
23,Electronics,False,4,494314,3.102785,0.346895,748.930172,0.659811
24,Electronics,False,5,1710087,2.112665,0.261362,459.288837,0.469256
25,Electronics,True,1,4605972,1.667752,0.342980,248.794156,0.310836
26,Electronics,True,2,1945290,1.091547,0.273992,322.698607,0.407118
27,Electronics,True,3,2513957,1.179317,0.257874,313.835655,0.381001
28,Electronics,True,4,4834076,1.106784,0.225601,291.051070,0.336742
29,Electronics,True,5,24861689,0.804839,0.165454,179.670580,0.197320
30,Home_and_Kitchen,False,1,551969,2.608663,0.423440,345.109521,0.457653
31,Home_and_Kitchen,False,2,241743,1.864178,0.346182,433.689075,0.552061
32,Home_and_Kitchen,False,3,307812,1.783689,0.296213,469.446194,0.564146
33,Home_and_Kitchen,False,4,628306,1.555172,0.268274,504.264892,0.603863
34,Home_and_Kitchen,False,5,2715958,1.193257,0.205854,332.142443,0.422145
35,Home_and_Kitchen,True,1,6523132,1.807085,0.371183,195.239695,0.243361
36,Home_and_Kitchen,True,2,3132523,1.071944,0.290523,225.667191,0.296979
37,Home_and_Kitchen,True,3,4247178,1.032567,0.281193,216.323699,0.276845
38,Home_and_Kitchen,True,4,6836674,1.083165,0.256750,206.881410,0.256722
39,Home_and_Kitchen,True,5,41551368,0.826059,0.192389,142.733557,0.150803
40,Movies_and_TV,False,1,414170,4.994365,0.634539,457.695550,0.478014
41,Movies_and_TV,False,2,206457,2.740479,0.533535,719.860746,0.621558
42,Movies_and_TV,False,3,291000,2.305794,0.447622,802.842787,0.611784
43,Movies_and_TV,False,4,572194,2.182234,0.387524,715.131697,0.535710
44,Movies_and_TV,False,5,2046783,2.051242,0.339571,428.287803,0.384448
45,Movies_and_TV,True,1,981116,2.024263,0.452265,189.397963,0.211769
46,Movies_and_TV,True,2,552949,1.127354,0.317438,232.572425,0.256235
47,Movies_and_TV,True,3,957230,0.842978,0.233837,218.238366,0.225028
48,Movies_and_TV,True,4,2007401,0.704581,0.194116,192.284194,0.187613
49,Movies_and_TV,True,5,9125273,0.642720,0.178278,140.104117,0.130343

In [44]:
# Reviewing products with the strongest dissatisfaction and operational risk signals

product_risk_ranking_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.analysis_product_risk_ranking`
WHERE category_risk_rank <= 25
ORDER BY category_name, category_risk_rank
"""

product_risk_ranking_dataframe = run_query(product_risk_ranking_query)
product_risk_ranking_dataframe

,category_name,parent_asin,product_title,store_name,price_amount,review_count,average_rating,low_rating_ratio,one_star_ratio,average_helpful_vote,helpful_vote_presence_ratio,average_review_text_length,long_review_ratio,verified_purchase_ratio,text_analysis_ready_review_count,text_analysis_ready_ratio,product_risk_score,category_risk_rank
0,Beauty_and_Personal_Care,B0B2837THB,"SoapCover, Gray Hair Coverage Soap, Hair Darke...",SOAP COVER,89.90,269,1.371747,0.892193,0.843866,6.081784,0.501859,131.107807,0.122677,0.788104,226,0.840149,0.683569,1
1,Beauty_and_Personal_Care,B0012SC3M2,Conair Pro Concentrator Nozzle,Conair,NaN,293,1.645051,0.822526,0.723549,1.300341,0.204778,179.040956,0.191126,0.901024,271,0.924915,0.592628,2
2,Beauty_and_Personal_Care,B09RFPYS6R,Dove Refillable Deodorant Starter Kit Deodoran...,Dove,8.98,512,1.830078,0.767578,0.597656,1.195313,0.269531,278.558594,0.427734,0.806641,489,0.955078,0.587871,3
3,Beauty_and_Personal_Care,B08M7M13QL,HATIKY Beard Pencil Filler for Men- Water Proo...,HATIKY,7.97,299,1.558528,0.849498,0.799331,0.384615,0.086957,94.688963,0.066890,0.983278,230,0.769231,0.583512,4
4,Beauty_and_Personal_Care,B01GE7CFI2,Sankuwen Professional Makeup Grooming Drawing ...,Sankuwen,NaN,428,1.668224,0.808411,0.724299,2.355140,0.182243,59.978972,0.025701,0.988318,266,0.621495,0.558949,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,Movies_and_TV,B08LB2W1FN,None,None,NaN,317,2.157729,0.687697,0.574132,2.283912,0.608833,292.933754,0.378549,0.763407,278,0.876972,0.588896,21
121,Movies_and_TV,B016DR2YZ2,None,None,NaN,315,1.558730,0.828571,0.695238,0.742857,0.234921,112.038095,0.123810,0.968254,212,0.673016,0.586095,22
122,Movies_and_TV,B01GU87FNA,None,None,NaN,2139,1.720430,0.803647,0.709210,0.980365,0.218326,184.238429,0.198223,0.929406,1733,0.810192,0.583988,23
123,Movies_and_TV,B004FHP7ES,None,None,NaN,358,2.262570,0.639665,0.569832,2.930168,0.648045,420.754190,0.435754,0.407821,319,0.891061,0.582542,24
124,Movies_and_TV,B0843QTGG9,None,None,NaN,253,2.126482,0.699605,0.667984,1.035573,0.691700,102.743083,0.086957,0.968379,186,0.735178,0.581462,25

In [45]:
# Reviewing monthly behavior trends across categories over time

monthly_behavior_trends_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.analysis_monthly_behavior_trends`
ORDER BY category_name, review_month
"""

monthly_behavior_trends_dataframe = run_query(monthly_behavior_trends_query)
monthly_behavior_trends_dataframe

,category_name,review_month,review_count,average_rating,low_rating_ratio,high_rating_ratio,average_helpful_vote,helpful_vote_presence_ratio,long_review_ratio,verified_purchase_ratio,monthly_sample_size_band,is_trend_analysis_eligible,is_high_confidence_trend_period,average_rating_3_month_moving_average,low_rating_ratio_3_month_moving_average,helpful_vote_presence_ratio_3_month_moving_average,long_review_ratio_3_month_moving_average
0,Beauty_and_Personal_Care,2007-01-01,1302,4.260369,0.103687,0.807988,4.697389,0.727343,0.493856,0.416283,Moderate,True,False,4.260369,0.103687,0.727343,0.493856
1,Beauty_and_Personal_Care,2007-12-01,1034,4.255319,0.108317,0.799807,6.302708,0.695358,0.572534,0.420696,Moderate,True,False,4.257844,0.106002,0.711350,0.533195
2,Beauty_and_Personal_Care,2008-01-01,1321,4.221045,0.128690,0.803936,5.355791,0.661620,0.576079,0.429220,Moderate,True,False,4.245577,0.113565,0.694773,0.547489
3,Beauty_and_Personal_Care,2008-02-01,1109,4.188458,0.131650,0.790803,5.189360,0.693417,0.587917,0.427412,Moderate,True,False,4.221607,0.122886,0.683465,0.578843
4,Beauty_and_Personal_Care,2008-03-01,1045,4.132057,0.150239,0.783732,11.235407,0.682297,0.597129,0.446890,Moderate,True,False,4.180520,0.136860,0.679111,0.587042
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1248,Movies_and_TV,2023-04-01,22463,4.067444,0.196189,0.747808,0.271335,0.132707,0.178160,0.944887,High,True,True,4.068553,0.195301,0.154084,0.198798
1249,Movies_and_TV,2023-05-01,13148,4.110967,0.184743,0.759811,0.222467,0.123213,0.148844,0.950943,High,True,True,4.089061,0.189865,0.131292,0.174818
1250,Movies_and_TV,2023-06-01,8514,4.082922,0.196030,0.754757,0.251821,0.120155,0.133192,0.952549,Moderate,True,False,4.087111,0.192321,0.125358,0.153399
1251,Movies_and_TV,2023-07-01,7340,4.124251,0.182153,0.760899,0.183515,0.097548,0.128338,0.949046,Moderate,True,False,4.106047,0.187642,0.113638,0.136791
1252,Movies_and_TV,2023-08-01,6216,4.253861,0.152510,0.802124,0.092181,0.061615,0.120495,0.952542,Moderate,True,False,4.153678,0.176897,0.093106,0.127342

In [46]:
# Reviewing category-level customer rating polarization patterns
category_polarization_summary_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.analysis_category_polarization_summary`
ORDER BY category_name
"""

category_polarization_summary_dataframe = run_query(category_polarization_summary_query)
category_polarization_summary_dataframe

,category_name,review_count,extreme_rating_ratio,five_star_ratio,one_star_ratio,low_rating_ratio,high_rating_ratio,average_helpful_vote
0,Beauty_and_Personal_Care,23665121,0.765395,0.646761,0.118633,0.171959,0.756239,1.151023
1,Books,29142321,0.736294,0.691693,0.044601,0.081280,0.848963,1.775547
2,Electronics,41971017,0.755599,0.633098,0.122500,0.174140,0.760052,1.098645
3,Home_and_Kitchen,66736663,0.769329,0.663313,0.106015,0.156576,0.775171,1.017700
4,Movies_and_TV,17154573,0.732594,0.651258,0.081336,0.125605,0.801632,1.133698

In [47]:
# Building business strategy tables for category prioritization and operational decision-making
execute_sql_file(sql_file_path = "sql scripts/12_build_business_strategy_tables.sql",
                 configuration = configuration
)

SQL script executed successfully : /Users/bhavikpatwa/Documents/PROJECTS/Amazon Reviews Intelligence/sql scripts/12_build_business_strategy_tables.sql

In [48]:
# Reviewing category-level business coverage and customer feedback summaries
category_coverage_summary_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.category_coverage_summary`
ORDER BY category_name
"""

category_feedback_summary_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.category_feedback_summary`
ORDER BY category_name
"""

category_coverage_summary_dataframe = run_query(category_coverage_summary_query)
category_feedback_summary_dataframe = run_query(category_feedback_summary_query)

display(category_coverage_summary_dataframe)
display(category_feedback_summary_dataframe)

,category_name,total_review_count,general_analysis_review_count,text_analysis_review_count,price_analysis_review_count,content_analysis_review_count,general_analysis_coverage_ratio,text_analysis_coverage_ratio,price_analysis_coverage_ratio,content_analysis_coverage_ratio,total_month_count,eligible_month_count,high_confidence_month_count,first_review_month,last_review_month,general_analysis_coverage_level,text_analysis_coverage_level,price_analysis_coverage_level,content_analysis_coverage_level
0,Beauty_and_Personal_Care,23907618,23665121,19863281,16573769,23636333,0.989857,0.830835,0.693242,0.988653,276,191,141,2000-08-01,2023-09-01,Strong,Strong,Usable,Strong
1,Books,29475449,29142321,25760319,23239954,28774093,0.988698,0.873958,0.788451,0.976205,326,312,283,1996-06-01,2023-09-01,Strong,Strong,Strong,Strong
2,Electronics,42433442,41971017,35351019,24393251,41858344,0.989102,0.833093,0.574859,0.986447,293,242,193,1998-12-01,2023-09-01,Strong,Strong,Usable,Strong
3,Home_and_Kitchen,67408754,66736663,56620111,45359343,66674713,0.990030,0.839952,0.672900,0.989111,292,221,164,1998-05-01,2023-09-01,Strong,Strong,Usable,Strong
4,Movies_and_TV,17324296,17154573,13020101,6471606,7762107,0.990203,0.751552,0.373557,0.448047,313,287,202,1997-08-01,2023-09-01,Strong,Usable,Limited,Limited

,category_name,analysis_review_count,average_rating,extreme_rating_ratio,five_star_ratio,one_star_ratio,low_rating_ratio,high_rating_ratio,average_helpful_vote,helpful_vote_presence_ratio,...,text_analysis_coverage_ratio,price_analysis_coverage_ratio,content_analysis_coverage_ratio,total_month_count,eligible_month_count,high_confidence_month_count,general_analysis_coverage_level,text_analysis_coverage_level,price_analysis_coverage_level,content_analysis_coverage_level
0,Beauty_and_Personal_Care,23665121,4.112409,0.765395,0.646761,0.118633,0.171959,0.756239,1.151023,0.264879,...,0.830835,0.693242,0.988653,276,191,141,Strong,Strong,Usable,Strong
1,Books,29142321,4.414774,0.736294,0.691693,0.044601,0.081280,0.848963,1.775547,0.361669,...,0.873958,0.788451,0.976205,326,312,283,Strong,Strong,Strong,Strong
2,Electronics,41971017,4.096510,0.755599,0.633098,0.122500,0.174140,0.760052,1.098645,0.214700,...,0.833093,0.574859,0.986447,293,242,193,Strong,Strong,Usable,Strong
3,Home_and_Kitchen,66736663,4.175893,0.769329,0.663313,0.106015,0.156576,0.775171,1.017700,0.230926,...,0.839952,0.672900,0.989111,292,221,164,Strong,Strong,Usable,Strong
4,Movies_and_TV,17154573,4.245949,0.732594,0.651258,0.081336,0.125605,0.801632,1.133698,0.249471,...,0.751552,0.373557,0.448047,313,287,202,Strong,Usable,Limited,Limited

In [49]:
# Reviewing category-level price behavior and dissatisfaction patterns

category_price_behavior_summary_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.category_price_behavior_summary`
ORDER BY category_name, price_band_order
"""

category_review_trust_summary_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.category_review_trust_summary`
ORDER BY category_name, verified_purchase, rating_group
"""

category_price_behavior_summary_dataframe = run_query(category_price_behavior_summary_query)
category_review_trust_summary_dataframe = run_query(category_review_trust_summary_query)

display(category_price_behavior_summary_dataframe)
display(category_review_trust_summary_dataframe)

,category_name,price_band,price_band_order,review_count,average_rating,low_rating_ratio,one_star_ratio,average_helpful_vote,helpful_vote_presence_ratio,average_review_text_length,long_review_ratio,verified_purchase_ratio,price_analysis_coverage_ratio,price_analysis_coverage_level,price_interpretation_strength
0,Beauty_and_Personal_Care,Budget,1,4769275,4.047975,0.187195,0.129607,0.964684,0.235896,153.799911,0.173164,0.924668,0.693242,Usable,Usable with caution
1,Beauty_and_Personal_Care,Lower mid,2,3517949,4.150343,0.163540,0.111579,1.125357,0.256429,172.880008,0.205769,0.923441,0.693242,Usable,Usable with caution
2,Beauty_and_Personal_Care,Upper mid,3,4140548,4.177641,0.158712,0.109588,1.237187,0.264056,178.717469,0.215357,0.919908,0.693242,Usable,Usable with caution
3,Beauty_and_Personal_Care,Premium,4,3319193,4.159684,0.163790,0.114966,1.417102,0.292428,190.441660,0.232220,0.911342,0.693242,Usable,Usable with caution
4,Beauty_and_Personal_Care,Very premium,5,826804,4.136390,0.172369,0.124920,2.039647,0.368051,208.851309,0.254545,0.903135,0.693242,Usable,Usable with caution
5,Books,Budget,1,6111774,4.394251,0.084497,0.046674,1.504779,0.337092,400.630395,0.375167,0.703046,0.788451,Strong,Strong
6,Books,Lower mid,2,5608756,4.401054,0.083238,0.044984,1.568323,0.323157,401.755838,0.376932,0.708349,0.788451,Strong,Strong
7,Books,Upper mid,3,5719835,4.436506,0.079349,0.042727,2.117633,0.399694,483.365351,0.442066,0.671920,0.788451,Strong,Strong
8,Books,Premium,4,4641276,4.462271,0.076345,0.042151,2.477175,0.443611,460.051130,0.412911,0.728064,0.788451,Strong,Strong
9,Books,Very premium,5,1158313,4.443497,0.083373,0.050179,2.394336,0.445696,424.543808,0.385109,0.754628,0.788451,Strong,Strong
10,Electronics,Budget,1,6168914,4.179755,0.163057,0.120670,0.498304,0.138142,145.721421,0.159681,0.958937,0.574859,Usable,Usable with caution
11,Electronics,Lower mid,2,6022104,4.195324,0.154151,0.108120,0.668427,0.158955,182.778782,0.215916,0.949702,0.574859,Usable,Usable with caution
12,Electronics,Upper mid,3,6103011,4.131705,0.166804,0.116317,1.006010,0.201600,235.297900,0.282972,0.932586,0.574859,Usable,Usable with caution
13,Electronics,Premium,4,4878463,4.067249,0.181203,0.127526,1.758605,0.288806,314.269848,0.359854,0.902885,0.574859,Usable,Usable with caution
14,Electronics,Very premium,5,1220759,4.075540,0.180538,0.128902,3.312259,0.433942,420.320166,0.432724,0.875393,0.574859,Usable,Usable with caution
15,Home_and_Kitchen,Budget,1,11335026,4.224666,0.147337,0.100448,0.634009,0.181031,136.731353,0.143018,0.949849,0.672900,Usable,Usable with caution
16,Home_and_Kitchen,Lower mid,2,11360398,4.270446,0.136486,0.091297,0.754433,0.196515,151.490748,0.168579,0.942209,0.672900,Usable,Usable with caution
17,Home_and_Kitchen,Upper mid,3,11721827,4.218608,0.147887,0.099211,0.999919,0.220987,172.059418,0.203362,0.936163,0.672900,Usable,Usable with caution
18,Home_and_Kitchen,Premium,4,8675479,4.153181,0.161628,0.109782,1.539355,0.283951,212.275831,0.263773,0.936998,0.672900,Usable,Usable with caution
19,Home_and_Kitchen,Very premium,5,2266613,4.085332,0.176268,0.121082,2.611879,0.380895,298.169213,0.367818,0.928683,0.672900,Usable,Usable with caution
20,Movies_and_TV,Budget,1,1665727,4.347382,0.103464,0.065308,1.350778,0.291098,325.529402,0.277530,0.768572,0.373557,Limited,Limited
21,Movies_and_TV,Lower mid,2,1570189,4.358412,0.102130,0.065890,1.457004,0.311034,317.120890,0.275116,0.798242,0.373557,Limited,Limited
22,Movies_and_TV,Upper mid,3,1619747,4.360685,0.102110,0.065555,1.557219,0.307810,301.688313,0.264422,0.820340,0.373557,Limited,Limited
23,Movies_and_TV,Premium,4,1292533,4.428098,0.089897,0.059531,2.111070,0.364482,360.110434,0.311961,0.802551,0.373557,Limited,Limited
24,Movies_and_TV,Very premium,5,323410,4.420036,0.095006,0.064686,3.062679,0.434959,387.694360,0.349875,0.829109,0.373557,Limited,Limited

,category_name,verified_purchase,rating_group,review_count,average_helpful_vote,helpful_vote_presence_ratio,average_review_text_length,long_review_ratio,segment_evidence_level
0,Beauty_and_Personal_Care,False,High rating,1621225,1.036100,0.242829,362.297202,0.479969,High
1,Beauty_and_Personal_Care,False,Low rating,323162,1.768222,0.380450,333.453646,0.452092,High
2,Beauty_and_Personal_Care,False,Mid rating,160255,0.981417,0.256728,440.316820,0.572350,High
3,Beauty_and_Personal_Care,True,High rating,16275266,1.113591,0.244815,152.113641,0.170847,High
4,Beauty_and_Personal_Care,True,Low rating,3746268,1.407056,0.342185,176.288809,0.213328,High
5,Beauty_and_Personal_Care,True,Mid rating,1538945,0.932744,0.288681,191.302203,0.238230,High
6,Books,False,High rating,7180219,2.259814,0.440401,797.970848,0.689644,High
7,Books,False,Low rating,896344,6.243847,0.697039,824.527142,0.732373,High
8,Books,False,Mid rating,723575,3.242464,0.526811,1104.562626,0.816044,High
9,Books,True,High rating,17560534,1.090586,0.289737,233.055663,0.242538,High
10,Books,True,Low rating,1472347,3.849773,0.520063,333.325732,0.372409,High
11,Books,True,Mid rating,1309302,2.104427,0.395701,340.739858,0.353318,High
12,Electronics,False,High rating,2204401,2.334689,0.280542,524.237894,0.511986,High
13,Electronics,False,Low rating,757585,2.741947,0.441668,529.325104,0.609084,High
14,Electronics,False,Mid rating,248047,3.054715,0.375340,715.919898,0.677005,High
15,Electronics,True,High rating,29695765,0.853992,0.175245,197.801844,0.220016,High
16,Electronics,True,Low rating,6551262,1.496657,0.322495,270.738873,0.339425,High
17,Electronics,True,Mid rating,2513957,1.179317,0.257874,313.835655,0.381001,High
18,Home_and_Kitchen,False,High rating,3344264,1.261252,0.217582,364.480071,0.456285,High
19,Home_and_Kitchen,False,Low rating,793712,2.381913,0.399910,372.088434,0.486407,High
20,Home_and_Kitchen,False,Mid rating,307812,1.783689,0.296213,469.446194,0.564146,High
21,Home_and_Kitchen,True,High rating,48388042,0.862385,0.201483,151.796911,0.165768,High
22,Home_and_Kitchen,True,Low rating,9655655,1.568588,0.345015,205.111094,0.260756,High
23,Home_and_Kitchen,True,Mid rating,4247178,1.032567,0.281193,216.323699,0.276845,High
24,Movies_and_TV,False,High rating,2618977,2.079861,0.350048,490.957447,0.417495,High
25,Movies_and_TV,False,Low rating,620627,4.244590,0.600939,544.907096,0.525765,High
26,Movies_and_TV,False,Mid rating,291000,2.305794,0.447622,802.842787,0.611784,High
27,Movies_and_TV,True,High rating,11132674,0.653874,0.181133,149.513028,0.140670,High
28,Movies_and_TV,True,Low rating,1534065,1.700975,0.403667,204.960065,0.227797,High
29,Movies_and_TV,True,Mid rating,957230,0.842978,0.233837,218.238366,0.225028,High

In [50]:
# Ranking products by dissatisfaction severity and business priority
product_issue_priority_query = f"""
WITH ranked_products AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY category_name, issue_priority_level
            ORDER BY review_count DESC, low_rating_ratio DESC, average_rating ASC
        ) AS category_priority_rank
    FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.product_issue_priority`
    WHERE issue_priority_level IN ("Highest priority", "Priority review")
)
SELECT *
FROM ranked_products
WHERE category_priority_rank <= 20
ORDER BY category_name, issue_priority_level, category_priority_rank
"""

product_content_gap_actionable_query = f"""
WITH ranked_products AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY category_name, metadata_improvement_priority
            ORDER BY review_count DESC, low_rating_ratio DESC, average_rating ASC
        ) AS category_priority_rank
    FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.product_content_gap_priority`
    WHERE metadata_improvement_priority IN ("Highest priority", "Priority review")
)
SELECT *
FROM ranked_products
WHERE category_priority_rank <= 20
ORDER BY category_name, metadata_improvement_priority, category_priority_rank
"""

product_content_gap_caution_query = f"""
WITH ranked_products AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY category_name, metadata_improvement_priority
            ORDER BY review_count DESC, low_rating_ratio DESC, average_rating ASC
        ) AS category_priority_rank
    FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.product_content_gap_priority`
    WHERE metadata_improvement_priority = "Use with caution"
)
SELECT *
FROM ranked_products
WHERE category_priority_rank <= 20
ORDER BY category_name, category_priority_rank
"""


product_issue_priority_dataframe = run_query(product_issue_priority_query)
product_content_gap_actionable_dataframe = run_query(product_content_gap_actionable_query)
product_content_gap_caution_dataframe = run_query(product_content_gap_caution_query)

display(product_issue_priority_dataframe)
display(product_content_gap_actionable_dataframe)
display(product_content_gap_caution_dataframe)

,category_name,parent_asin,product_title,product_display_name,store_name,store_display_name,price_amount,review_count,average_rating,low_rating_ratio,...,product_sample_size_band,is_product_analysis_eligible,is_high_confidence_product_analysis_eligible,issue_priority_level,evidence_confidence_level,product_identification_quality,business_use_caution,business_basis,comparison_scope,category_priority_rank
0,Beauty_and_Personal_Care,B09KM16YYV,L'Oreal Paris Feria Multi-Faceted Shimmering P...,L'Oreal Paris Feria Multi-Faceted Shimmering P...,L'Oreal Paris,L'Oreal Paris,21.98,8517,3.563226,0.316661,...,Very high,True,True,Highest priority,High,High,No major product identification limitation,High-volume product with unusually high dissat...,Compared only against products in the same cat...,1
1,Beauty_and_Personal_Care,B00X7VFSOM,CHI Professional 1-Inch Ceramic Tourmaline Hai...,CHI Professional 1-Inch Ceramic Tourmaline Hai...,CHI,CHI,54.72,4424,3.598779,0.305832,...,High,True,True,Highest priority,High,High,No major product identification limitation,High-volume product with unusually high dissat...,Compared only against products in the same cat...,2
2,Beauty_and_Personal_Care,B0BSRJ5HDH,CeraVe Eye Repair Cream | Under Eye Cream for ...,CeraVe Eye Repair Cream | Under Eye Cream for ...,CeraVe,CeraVe,14.44,3448,3.517401,0.307715,...,High,True,True,Highest priority,High,High,No major product identification limitation,High-volume product with unusually high dissat...,Compared only against products in the same cat...,3
3,Beauty_and_Personal_Care,B00M1E5F1W,Philips Norelco Replacement Head for Series 70...,Philips Norelco Replacement Head for Series 70...,PHILIPS,PHILIPS,NaN,2612,3.156585,0.402757,...,High,True,True,Highest priority,High,High,No major product identification limitation,High-volume product with unusually high dissat...,Compared only against products in the same cat...,4
4,Beauty_and_Personal_Care,B0C7PNWXJR,Schwarzkopf Got2b Metallics Permanent Hair Col...,Schwarzkopf Got2b Metallics Permanent Hair Col...,Got2B,Got2B,8.99,2290,2.868559,0.497380,...,High,True,True,Highest priority,High,High,No major product identification limitation,High-volume product with unusually high dissat...,Compared only against products in the same cat...,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,Movies_and_TV,B00MILGKPI,None,ASIN B00MILGKPI,None,Unknown store,NaN,4902,3.872705,0.154019,...,High,True,True,Priority review,Moderate,Low,"Category metadata support is limited, so produ...",Product underperforming against category peers...,Compared only against products in the same cat...,16
196,Movies_and_TV,B019YHGHX8,Daddy's Home,Daddy's Home,None,Unknown store,4.99,4875,3.846564,0.157538,...,High,True,True,Priority review,Moderate,Moderate,"Category metadata support is limited, so produ...",Product underperforming against category peers...,Compared only against products in the same cat...,17
197,Movies_and_TV,B00IIUATDM,None,ASIN B00IIUATDM,None,Unknown store,NaN,4806,3.461923,0.299417,...,High,True,True,Priority review,Moderate,Low,"Category metadata support is limited, so produ...",Product underperforming against category peers...,Compared only against products in the same cat...,18
198,Movies_and_TV,B01DTFEJVS,None,ASIN B01DTFEJVS,None,Unknown store,NaN,4665,3.401501,0.245016,...,High,True,True,Priority review,Moderate,Low,"Category metadata support is limited, so produ...",Product underperforming against category peers...,Compared only against products in the same cat...,19
199,Movies_and_TV,B00OYWSQFG,The Prince,The Prince,None,Unknown store,7.99,4312,3.150974,0.311920,...,High,True,True,Priority review,Moderate,Moderate,"Category metadata support is limited, so produ...",Product underperforming against category peers...,Compared only against products in the same cat...,20

,category_name,parent_asin,product_title,product_display_name,store_name,store_display_name,price_amount,review_count,average_rating,low_rating_ratio,...,has_rich_content_support,content_analysis_coverage_level,category_title_support_product_ratio,category_minimum_content_support_product_ratio,category_rich_content_support_product_ratio,metadata_gap_type,metadata_improvement_priority,evidence_confidence_level,business_basis,category_priority_rank
0,Beauty_and_Personal_Care,B083WKDWJL,Grande Cosmetics GrandeLASH-MD Lash Enhancing ...,Grande Cosmetics GrandeLASH-MD Lash Enhancing ...,None,Unknown store,68.00,6541,3.472863,0.352698,...,False,Strong,0.999947,0.992788,0.781901,Missing rich content support,Priority review,Moderate,"Meaningful customer feedback is present, dissa...",1
1,Beauty_and_Personal_Care,B08HWDNN4Q,Lume Deodorant Cream Stick - Underarms and Pri...,Lume Deodorant Cream Stick - Underarms and Pri...,Lume,Lume,NaN,1528,2.866492,0.483639,...,False,Strong,0.999947,0.992788,0.781901,Missing rich content support,Priority review,Moderate,"Meaningful customer feedback is present, dissa...",2
2,Beauty_and_Personal_Care,B09KQB5SHK,VRVOGUE Brazilian Deep Wave Bundles with Closu...,VRVOGUE Brazilian Deep Wave Bundles with Closu...,VRVogue,VRVogue,95.99,1481,3.376772,0.351789,...,False,Strong,0.999947,0.992788,0.781901,Missing rich content support,Priority review,Moderate,"Meaningful customer feedback is present, dissa...",3
3,Beauty_and_Personal_Care,B00JIM55MY,"St. Tropez Tan Applicator Mitt, Basic","St. Tropez Tan Applicator Mitt, Basic",None,Unknown store,NaN,1167,3.413882,0.343616,...,False,Strong,0.999947,0.992788,0.781901,Missing rich content support,Priority review,Moderate,"Meaningful customer feedback is present, dissa...",4
4,Beauty_and_Personal_Care,B0056FL4FY,Dragonpad Nail Art Drill KIT Electric FILE Buf...,Dragonpad Nail Art Drill KIT Electric FILE Buf...,DragonPad,DragonPad,NaN,1160,3.101724,0.406034,...,False,Strong,0.999947,0.992788,0.781901,Missing minimum content support,Priority review,Moderate,"Meaningful customer feedback is present, dissa...",5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Home_and_Kitchen,B08LKKGWQD,Laposso Milk Frother Rechargeable Handheld Ele...,Laposso Milk Frother Rechargeable Handheld Ele...,Laposso,Laposso,11.99,685,3.226277,0.400000,...,False,Strong,0.999942,0.995082,0.798371,Missing rich content support,Priority review,Moderate,"Meaningful customer feedback is present, dissa...",16
76,Home_and_Kitchen,B07P83K2LM,SHARP Digital Alarm with AccuSet - Automatic S...,SHARP Digital Alarm with AccuSet - Automatic S...,Sharp,Sharp,NaN,679,3.301915,0.393225,...,False,Strong,0.999942,0.995082,0.798371,Missing rich content support,Priority review,Moderate,"Meaningful customer feedback is present, dissa...",17
77,Home_and_Kitchen,B098B3XY1M,iLifeTech Hands Free Toothpaste Dispenser Auto...,iLifeTech Hands Free Toothpaste Dispenser Auto...,iLifeTech,iLifeTech,4.99,650,3.424615,0.316923,...,False,Strong,0.999942,0.995082,0.798371,Missing rich content support,Priority review,Moderate,"Meaningful customer feedback is present, dissa...",18
78,Home_and_Kitchen,B011SUKOHE,Meal Prep Haven MP-7D2C Stackable 2 Compartmen...,Meal Prep Haven MP-7D2C Stackable 2 Compartmen...,Meal Prep Haven,Meal Prep Haven,NaN,635,3.239370,0.374803,...,False,Strong,0.999942,0.995082,0.798371,Missing rich content support,Priority review,Moderate,"Meaningful customer feedback is present, dissa...",19
79,Home_and_Kitchen,B07GWCM246,"Dezin Electric Kettle, 2L Stainless Steel Cord...","Dezin Electric Kettle, 2L Stainless Steel Cord...",DEZIN,DEZIN,NaN,628,3.439490,0.345541,...,False,Strong,0.999942,0.995082,0.798371,Missing rich content support,Priority review,Moderate,"Meaningful customer feedback is present, dissa...",20

,category_name,parent_asin,product_title,product_display_name,store_name,store_display_name,price_amount,review_count,average_rating,low_rating_ratio,...,has_rich_content_support,content_analysis_coverage_level,category_title_support_product_ratio,category_minimum_content_support_product_ratio,category_rich_content_support_product_ratio,metadata_gap_type,metadata_improvement_priority,evidence_confidence_level,business_basis,category_priority_rank
0,Beauty_and_Personal_Care,B003ODETES,None,ASIN B003ODETES,ReNext,ReNext,NaN,245,4.048980,0.130612,...,False,Strong,0.999947,0.992788,0.781901,Missing product title,Use with caution,Moderate,"Product identifier is incomplete, so metadata ...",1
1,Beauty_and_Personal_Care,B07PNK4WWF,None,ASIN B07PNK4WWF,COLOUR ME,COLOUR ME,4.0,66,4.257576,0.136364,...,False,Strong,0.999947,0.992788,0.781901,Missing product title,Use with caution,Low,"Product identifier is incomplete, so metadata ...",2
2,Beauty_and_Personal_Care,B083BZ6DWW,None,ASIN B083BZ6DWW,Magnifeko,Magnifeko,NaN,59,3.932203,0.203390,...,False,Strong,0.999947,0.992788,0.781901,Missing product title,Use with caution,Low,"Product identifier is incomplete, so metadata ...",3
3,Beauty_and_Personal_Care,B07PMBRYNN,None,ASIN B07PMBRYNN,Learja,Learja,NaN,38,4.500000,0.078947,...,False,Strong,0.999947,0.992788,0.781901,Missing product title,Use with caution,Low,"Product identifier is incomplete, so metadata ...",4
4,Beauty_and_Personal_Care,B003O4H9HG,None,ASIN B003O4H9HG,essie,essie,NaN,35,4.514286,0.114286,...,False,Strong,0.999947,0.992788,0.781901,Missing product title,Use with caution,Low,"Product identifier is incomplete, so metadata ...",5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Movies_and_TV,B09F59CZ7R,None,ASIN B09F59CZ7R,None,Unknown store,NaN,20379,3.300260,0.406742,...,False,Limited,0.579933,0.566511,0.465257,Missing product title,Use with caution,Low,"Category-level metadata support is weak, so pr...",16
76,Movies_and_TV,B01347V50Y,None,ASIN B01347V50Y,None,Unknown store,NaN,19273,4.654387,0.028901,...,False,Limited,0.579933,0.566511,0.465257,Missing product title,Use with caution,Low,"Category-level metadata support is weak, so pr...",17
77,Movies_and_TV,B00PSLQYWE,None,ASIN B00PSLQYWE,None,Unknown store,NaN,18620,4.912567,0.007841,...,False,Limited,0.579933,0.566511,0.465257,Missing product title,Use with caution,Low,"Category-level metadata support is weak, so pr...",18
78,Movies_and_TV,B01J94B90W,The Grand Tour,The Grand Tour,None,Unknown store,NaN,18607,4.626538,0.040684,...,True,Limited,0.579933,0.566511,0.465257,No major metadata gap,Use with caution,Low,"Category-level metadata support is weak, so pr...",19
79,Movies_and_TV,B00I3MPZUW,None,ASIN B00I3MPZUW,None,Unknown store,NaN,17077,4.353868,0.099608,...,False,Limited,0.579933,0.566511,0.465257,Missing product title,Use with caution,Low,"Category-level metadata support is weak, so pr...",20

In [51]:
# Reviewing metadata readiness and content support quality across categories
category_metadata_readiness_summary_query = f"""
SELECT
    category_name,
    total_review_count,
    total_product_count,
    title_analysis_ready_review_ratio,
    store_analysis_ready_review_ratio,
    features_analysis_ready_review_ratio,
    description_analysis_ready_review_ratio,
    details_analysis_ready_review_ratio,
    minimum_content_support_review_ratio,
    rich_content_support_review_ratio,
    title_analysis_ready_product_ratio,
    store_analysis_ready_product_ratio,
    features_analysis_ready_product_ratio,
    description_analysis_ready_product_ratio,
    details_analysis_ready_product_ratio,
    minimum_content_support_product_ratio,
    rich_content_support_product_ratio,
    excluded_title_analysis_review_count,
    excluded_store_analysis_review_count,
    excluded_minimum_content_support_review_count,
    excluded_rich_content_support_review_count,
    excluded_title_analysis_product_count,
    excluded_store_analysis_product_count,
    excluded_minimum_content_support_product_count,
    excluded_rich_content_support_product_count,
    content_analysis_coverage_ratio,
    content_analysis_coverage_level
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.category_metadata_readiness_summary`
ORDER BY category_name
"""


category_feedback_trend_summary_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.category_feedback_trend_summary`
ORDER BY category_name, review_month
"""


category_metadata_readiness_summary_dataframe = run_query(category_metadata_readiness_summary_query)
category_feedback_trend_summary_dataframe = run_query(category_feedback_trend_summary_query)

display(category_metadata_readiness_summary_dataframe)
display(category_feedback_trend_summary_dataframe)

,category_name,total_review_count,total_product_count,title_analysis_ready_review_ratio,store_analysis_ready_review_ratio,features_analysis_ready_review_ratio,description_analysis_ready_review_ratio,details_analysis_ready_review_ratio,minimum_content_support_review_ratio,rich_content_support_review_ratio,...,excluded_title_analysis_review_count,excluded_store_analysis_review_count,excluded_minimum_content_support_review_count,excluded_rich_content_support_review_count,excluded_title_analysis_product_count,excluded_store_analysis_product_count,excluded_minimum_content_support_product_count,excluded_rich_content_support_product_count,content_analysis_coverage_ratio,content_analysis_coverage_level
0,Beauty_and_Personal_Care,23665121,1028108,0.999971,0.942933,0.871223,0.498890,0.995315,0.998784,0.889781,...,677,1350493,28788,2608352,54,50424,7415,224229,0.988653,Strong
1,Books,29142321,4448181,1.000000,0.986211,0.962154,0.690899,0.955150,0.987364,0.963198,...,0,401836,368228,1072495,0,174576,150325,511580,0.976205,Strong
2,Electronics,41971017,1508480,0.999976,0.998862,0.914501,0.503421,0.931735,0.997315,0.928614,...,994,47751,112673,2996153,91,8164,6363,331868,0.986447,Strong
3,Home_and_Kitchen,66736663,3735352,0.999978,0.994376,0.918710,0.522610,0.996279,0.999072,0.932861,...,1455,375320,61950,4480624,217,83485,18369,753157,0.989111,Strong
4,Movies_and_TV,17154573,747505,0.456155,0.387566,0.068853,0.427403,0.996151,0.452480,0.427657,...,9329436,10506050,9392466,9818304,314002,355040,324035,399723,0.448047,Limited

,category_name,review_month,review_count,average_rating,low_rating_ratio,high_rating_ratio,average_helpful_vote,helpful_vote_presence_ratio,long_review_ratio,verified_purchase_ratio,monthly_sample_size_band,is_trend_analysis_eligible,is_high_confidence_trend_period,average_rating_3_month_moving_average,low_rating_ratio_3_month_moving_average,helpful_vote_presence_ratio_3_month_moving_average,long_review_ratio_3_month_moving_average,trend_evidence_level
0,Beauty_and_Personal_Care,2000-08-01,1,5.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,Very low,False,False,NaN,NaN,NaN,NaN,Low
1,Beauty_and_Personal_Care,2000-11-01,3,4.333333,0.000000,1.000000,54.333333,1.000000,0.666667,0.000000,Very low,False,False,NaN,NaN,NaN,NaN,Low
2,Beauty_and_Personal_Care,2000-12-01,3,4.333333,0.000000,0.666667,4.000000,1.000000,0.666667,0.666667,Very low,False,False,NaN,NaN,NaN,NaN,Low
3,Beauty_and_Personal_Care,2001-01-01,2,4.500000,0.000000,1.000000,14.000000,1.000000,0.500000,0.000000,Very low,False,False,NaN,NaN,NaN,NaN,Low
4,Beauty_and_Personal_Care,2001-02-01,1,5.000000,0.000000,1.000000,11.000000,1.000000,1.000000,0.000000,Very low,False,False,NaN,NaN,NaN,NaN,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,Movies_and_TV,2023-05-01,13148,4.110967,0.184743,0.759811,0.222467,0.123213,0.148844,0.950943,High,True,True,4.089061,0.189865,0.131292,0.174818,High
1496,Movies_and_TV,2023-06-01,8514,4.082922,0.196030,0.754757,0.251821,0.120155,0.133192,0.952549,Moderate,True,False,4.087111,0.192321,0.125358,0.153399,Moderate
1497,Movies_and_TV,2023-07-01,7340,4.124251,0.182153,0.760899,0.183515,0.097548,0.128338,0.949046,Moderate,True,False,4.106047,0.187642,0.113638,0.136791,Moderate
1498,Movies_and_TV,2023-08-01,6216,4.253861,0.152510,0.802124,0.092181,0.061615,0.120495,0.952542,Moderate,True,False,4.153678,0.176897,0.093106,0.127342,Moderate
1499,Movies_and_TV,2023-09-01,473,4.361522,0.122622,0.818182,0.076110,0.031712,0.141649,0.949260,Low,False,False,NaN,NaN,NaN,NaN,Low

In [52]:
# Reviewing metadata improvement priorities and major content gaps by category

metadata_priority_validation_query = f"""
SELECT
    category_name,
    metadata_improvement_priority,
    metadata_gap_type,
    COUNT(*) AS product_count
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.product_content_gap_priority`
GROUP BY category_name, metadata_improvement_priority, metadata_gap_type
ORDER BY category_name, metadata_improvement_priority, metadata_gap_type
"""


trend_evidence_validation_query = f"""
SELECT
    category_name,
    trend_evidence_level,
    COUNT(*) AS month_count
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.category_feedback_trend_summary`
GROUP BY category_name, trend_evidence_level
ORDER BY category_name, trend_evidence_level
"""

metadata_priority_validation_dataframe = run_query(metadata_priority_validation_query)
trend_evidence_validation_dataframe = run_query(trend_evidence_validation_query)

display(metadata_priority_validation_dataframe)
display(trend_evidence_validation_dataframe)

,category_name,metadata_improvement_priority,metadata_gap_type,product_count
0,Beauty_and_Personal_Care,Monitor,Missing minimum content support,7356
1,Beauty_and_Personal_Care,Monitor,Missing rich content support,216340
2,Beauty_and_Personal_Care,Monitor,No major metadata gap,803737
3,Beauty_and_Personal_Care,Priority review,Missing minimum content support,4
4,Beauty_and_Personal_Care,Priority review,Missing rich content support,434
5,Beauty_and_Personal_Care,Use with caution,Missing product title,54
6,Books,Monitor,Missing minimum content support,150159
7,Books,Monitor,Missing rich content support,361056
8,Books,Monitor,No major metadata gap,3934756
9,Books,Priority review,Missing minimum content support,45
10,Books,Priority review,Missing rich content support,47
11,Electronics,Monitor,Missing minimum content support,6268
12,Electronics,Monitor,Missing rich content support,324961
13,Electronics,Monitor,No major metadata gap,1176499
14,Electronics,Priority review,Missing minimum content support,4
15,Electronics,Priority review,Missing rich content support,513
16,Electronics,Use with caution,Missing product title,91
17,Home_and_Kitchen,Monitor,Missing minimum content support,18138
18,Home_and_Kitchen,Monitor,Missing rich content support,733757
19,Home_and_Kitchen,Monitor,No major metadata gap,2981277
20,Home_and_Kitchen,Priority review,Missing minimum content support,8
21,Home_and_Kitchen,Priority review,Missing rich content support,785
22,Home_and_Kitchen,Use with caution,Missing product title,217
23,Movies_and_TV,Use with caution,Missing minimum content support,10022
24,Movies_and_TV,Use with caution,Missing product title,313873
25,Movies_and_TV,Use with caution,Missing rich content support,75584
26,Movies_and_TV,Use with caution,No major metadata gap,347567

               category_name trend_evidence_level  month_count
0   Beauty_and_Personal_Care                 High          141
1   Beauty_and_Personal_Care                  Low           85
2   Beauty_and_Personal_Care             Moderate           50
3                      Books                 High          283
4                      Books                  Low           14
5                      Books             Moderate           29
6                Electronics                 High          193
7                Electronics                  Low           51
8                Electronics             Moderate           49
9           Home_and_Kitchen                 High          164
10          Home_and_Kitchen                  Low           71
11          Home_and_Kitchen             Moderate           57
12             Movies_and_TV                 High          202
13             Movies_and_TV                  Low           26
14             Movies_and_TV             Moderate           85

In [53]:
# Building final reporting tables for dashboards and business review outputs
execute_sql_file(sql_file_path = "sql scripts/13_build_reporting_output_tables.sql",
                 configuration = configuration
)

SQL script executed successfully : /Users/bhavikpatwa/Documents/PROJECTS/Amazon Reviews Intelligence/sql scripts/13_build_reporting_output_tables.sql

In [54]:
# Reviewing the final category overview reporting table used for dashboards

reporting_category_overview_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.reporting_category_overview`
ORDER BY category_name
"""

reporting_category_price_behavior_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.reporting_category_price_behavior`
ORDER BY category_name, price_band_order
"""

reporting_category_review_trust_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.reporting_category_review_trust`
ORDER BY category_name, verified_purchase, rating_group
"""

reporting_category_overview_dataframe = run_query(reporting_category_overview_query)
reporting_category_price_behavior_dataframe = run_query(reporting_category_price_behavior_query)
reporting_category_review_trust_dataframe = run_query(reporting_category_review_trust_query)

display(reporting_category_overview_dataframe)
display(reporting_category_price_behavior_dataframe)
display(reporting_category_review_trust_dataframe)

,category_name,analysis_review_count,average_rating,low_rating_ratio,one_star_ratio,high_rating_ratio,extreme_rating_ratio,average_helpful_vote,helpful_vote_presence_ratio,average_review_text_length,...,text_analysis_coverage_ratio,price_analysis_coverage_ratio,content_analysis_coverage_ratio,total_month_count,eligible_month_count,high_confidence_month_count,general_analysis_coverage_level,text_analysis_coverage_level,price_analysis_coverage_level,content_analysis_coverage_level
0,Beauty_and_Personal_Care,23665121,4.112409,0.171959,0.118633,0.756239,0.765395,1.151023,0.264879,177.316079,...,0.830835,0.693242,0.988653,276,191,141,Strong,Strong,Usable,Strong
1,Books,29142321,4.414774,0.081280,0.044601,0.848963,0.736294,1.775547,0.361669,421.976812,...,0.873958,0.788451,0.976205,326,312,283,Strong,Strong,Strong,Strong
2,Electronics,41971017,4.096510,0.174140,0.122500,0.760052,0.755599,1.098645,0.214700,242.327909,...,0.833093,0.574859,0.986447,293,242,193,Strong,Strong,Usable,Strong
3,Home_and_Kitchen,66736663,4.175893,0.156576,0.106015,0.775171,0.769329,1.017700,0.230926,178.360017,...,0.839952,0.672900,0.989111,292,221,164,Strong,Strong,Usable,Strong
4,Movies_and_TV,17154573,4.245949,0.125605,0.081336,0.801632,0.732594,1.133698,0.249471,235.821885,...,0.751552,0.373557,0.448047,313,287,202,Strong,Usable,Limited,Limited

,category_name,price_band,price_band_order,review_count,average_rating,low_rating_ratio,one_star_ratio,average_helpful_vote,helpful_vote_presence_ratio,average_review_text_length,long_review_ratio,verified_purchase_ratio,price_analysis_coverage_ratio,price_analysis_coverage_level,price_interpretation_strength
0,Beauty_and_Personal_Care,Budget,1,4769275,4.047975,0.187195,0.129607,0.964684,0.235896,153.799911,0.173164,0.924668,0.693242,Usable,Usable with caution
1,Beauty_and_Personal_Care,Lower mid,2,3517949,4.150343,0.163540,0.111579,1.125357,0.256429,172.880008,0.205769,0.923441,0.693242,Usable,Usable with caution
2,Beauty_and_Personal_Care,Upper mid,3,4140548,4.177641,0.158712,0.109588,1.237187,0.264056,178.717469,0.215357,0.919908,0.693242,Usable,Usable with caution
3,Beauty_and_Personal_Care,Premium,4,3319193,4.159684,0.163790,0.114966,1.417102,0.292428,190.441660,0.232220,0.911342,0.693242,Usable,Usable with caution
4,Beauty_and_Personal_Care,Very premium,5,826804,4.136390,0.172369,0.124920,2.039647,0.368051,208.851309,0.254545,0.903135,0.693242,Usable,Usable with caution
5,Books,Budget,1,6111774,4.394251,0.084497,0.046674,1.504779,0.337092,400.630395,0.375167,0.703046,0.788451,Strong,Strong
6,Books,Lower mid,2,5608756,4.401054,0.083238,0.044984,1.568323,0.323157,401.755838,0.376932,0.708349,0.788451,Strong,Strong
7,Books,Upper mid,3,5719835,4.436506,0.079349,0.042727,2.117633,0.399694,483.365351,0.442066,0.671920,0.788451,Strong,Strong
8,Books,Premium,4,4641276,4.462271,0.076345,0.042151,2.477175,0.443611,460.051130,0.412911,0.728064,0.788451,Strong,Strong
9,Books,Very premium,5,1158313,4.443497,0.083373,0.050179,2.394336,0.445696,424.543808,0.385109,0.754628,0.788451,Strong,Strong
10,Electronics,Budget,1,6168914,4.179755,0.163057,0.120670,0.498304,0.138142,145.721421,0.159681,0.958937,0.574859,Usable,Usable with caution
11,Electronics,Lower mid,2,6022104,4.195324,0.154151,0.108120,0.668427,0.158955,182.778782,0.215916,0.949702,0.574859,Usable,Usable with caution
12,Electronics,Upper mid,3,6103011,4.131705,0.166804,0.116317,1.006010,0.201600,235.297900,0.282972,0.932586,0.574859,Usable,Usable with caution
13,Electronics,Premium,4,4878463,4.067249,0.181203,0.127526,1.758605,0.288806,314.269848,0.359854,0.902885,0.574859,Usable,Usable with caution
14,Electronics,Very premium,5,1220759,4.075540,0.180538,0.128902,3.312259,0.433942,420.320166,0.432724,0.875393,0.574859,Usable,Usable with caution
15,Home_and_Kitchen,Budget,1,11335026,4.224666,0.147337,0.100448,0.634009,0.181031,136.731353,0.143018,0.949849,0.672900,Usable,Usable with caution
16,Home_and_Kitchen,Lower mid,2,11360398,4.270446,0.136486,0.091297,0.754433,0.196515,151.490748,0.168579,0.942209,0.672900,Usable,Usable with caution
17,Home_and_Kitchen,Upper mid,3,11721827,4.218608,0.147887,0.099211,0.999919,0.220987,172.059418,0.203362,0.936163,0.672900,Usable,Usable with caution
18,Home_and_Kitchen,Premium,4,8675479,4.153181,0.161628,0.109782,1.539355,0.283951,212.275831,0.263773,0.936998,0.672900,Usable,Usable with caution
19,Home_and_Kitchen,Very premium,5,2266613,4.085332,0.176268,0.121082,2.611879,0.380895,298.169213,0.367818,0.928683,0.672900,Usable,Usable with caution

,category_name,verified_purchase,verified_purchase_label,rating_group,review_count,average_helpful_vote,helpful_vote_presence_ratio,average_review_text_length,long_review_ratio,segment_evidence_level
0,Beauty_and_Personal_Care,False,Non-verified purchase,High rating,1621225,1.036100,0.242829,362.297202,0.479969,High
1,Beauty_and_Personal_Care,False,Non-verified purchase,Low rating,323162,1.768222,0.380450,333.453646,0.452092,High
2,Beauty_and_Personal_Care,False,Non-verified purchase,Mid rating,160255,0.981417,0.256728,440.316820,0.572350,High
3,Beauty_and_Personal_Care,True,Verified purchase,High rating,16275266,1.113591,0.244815,152.113641,0.170847,High
4,Beauty_and_Personal_Care,True,Verified purchase,Low rating,3746268,1.407056,0.342185,176.288809,0.213328,High
5,Beauty_and_Personal_Care,True,Verified purchase,Mid rating,1538945,0.932744,0.288681,191.302203,0.238230,High
6,Books,False,Non-verified purchase,High rating,7180219,2.259814,0.440401,797.970848,0.689644,High
7,Books,False,Non-verified purchase,Low rating,896344,6.243847,0.697039,824.527142,0.732373,High
8,Books,False,Non-verified purchase,Mid rating,723575,3.242464,0.526811,1104.562626,0.816044,High
9,Books,True,Verified purchase,High rating,17560534,1.090586,0.289737,233.055663,0.242538,High
10,Books,True,Verified purchase,Low rating,1472347,3.849773,0.520063,333.325732,0.372409,High
11,Books,True,Verified purchase,Mid rating,1309302,2.104427,0.395701,340.739858,0.353318,High
12,Electronics,False,Non-verified purchase,High rating,2204401,2.334689,0.280542,524.237894,0.511986,High
13,Electronics,False,Non-verified purchase,Low rating,757585,2.741947,0.441668,529.325104,0.609084,High
14,Electronics,False,Non-verified purchase,Mid rating,248047,3.054715,0.375340,715.919898,0.677005,High
15,Electronics,True,Verified purchase,High rating,29695765,0.853992,0.175245,197.801844,0.220016,High
16,Electronics,True,Verified purchase,Low rating,6551262,1.496657,0.322495,270.738873,0.339425,High
17,Electronics,True,Verified purchase,Mid rating,2513957,1.179317,0.257874,313.835655,0.381001,High
18,Home_and_Kitchen,False,Non-verified purchase,High rating,3344264,1.261252,0.217582,364.480071,0.456285,High
19,Home_and_Kitchen,False,Non-verified purchase,Low rating,793712,2.381913,0.399910,372.088434,0.486407,High
20,Home_and_Kitchen,False,Non-verified purchase,Mid rating,307812,1.783689,0.296213,469.446194,0.564146,High
21,Home_and_Kitchen,True,Verified purchase,High rating,48388042,0.862385,0.201483,151.796911,0.165768,High
22,Home_and_Kitchen,True,Verified purchase,Low rating,9655655,1.568588,0.345015,205.111094,0.260756,High
23,Home_and_Kitchen,True,Verified purchase,Mid rating,4247178,1.032567,0.281193,216.323699,0.276845,High
24,Movies_and_TV,False,Non-verified purchase,High rating,2618977,2.079861,0.350048,490.957447,0.417495,High
25,Movies_and_TV,False,Non-verified purchase,Low rating,620627,4.244590,0.600939,544.907096,0.525765,High
26,Movies_and_TV,False,Non-verified purchase,Mid rating,291000,2.305794,0.447622,802.842787,0.611784,High
27,Movies_and_TV,True,Verified purchase,High rating,11132674,0.653874,0.181133,149.513028,0.140670,High
28,Movies_and_TV,True,Verified purchase,Low rating,1534065,1.700975,0.403667,204.960065,0.227797,High
29,Movies_and_TV,True,Verified purchase,Mid rating,957230,0.842978,0.233837,218.238366,0.225028,High

In [55]:
# Reviewing the final metadata and content readiness reporting table

reporting_category_metadata_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.reporting_category_metadata`
ORDER BY category_name
"""

reporting_category_trends_query = f"""
SELECT *
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.reporting_category_trends`
ORDER BY category_name, review_month
"""

reporting_category_metadata_dataframe = run_query(reporting_category_metadata_query)
reporting_category_trends_dataframe = run_query(reporting_category_trends_query)

display(reporting_category_metadata_dataframe)
display(reporting_category_trends_dataframe.head(20))

,category_name,total_review_count,total_product_count,title_analysis_ready_review_ratio,store_analysis_ready_review_ratio,features_analysis_ready_review_ratio,description_analysis_ready_review_ratio,details_analysis_ready_review_ratio,minimum_content_support_review_ratio,rich_content_support_review_ratio,...,excluded_title_analysis_review_count,excluded_store_analysis_review_count,excluded_minimum_content_support_review_count,excluded_rich_content_support_review_count,excluded_title_analysis_product_count,excluded_store_analysis_product_count,excluded_minimum_content_support_product_count,excluded_rich_content_support_product_count,content_analysis_coverage_ratio,content_analysis_coverage_level
0,Beauty_and_Personal_Care,23665121,1028108,0.999971,0.942933,0.871223,0.498890,0.995315,0.998784,0.889781,...,677,1350493,28788,2608352,54,50424,7415,224229,0.988653,Strong
1,Books,29142321,4448181,1.000000,0.986211,0.962154,0.690899,0.955150,0.987364,0.963198,...,0,401836,368228,1072495,0,174576,150325,511580,0.976205,Strong
2,Electronics,41971017,1508480,0.999976,0.998862,0.914501,0.503421,0.931735,0.997315,0.928614,...,994,47751,112673,2996153,91,8164,6363,331868,0.986447,Strong
3,Home_and_Kitchen,66736663,3735352,0.999978,0.994376,0.918710,0.522610,0.996279,0.999072,0.932861,...,1455,375320,61950,4480624,217,83485,18369,753157,0.989111,Strong
4,Movies_and_TV,17154573,747505,0.456155,0.387566,0.068853,0.427403,0.996151,0.452480,0.427657,...,9329436,10506050,9392466,9818304,314002,355040,324035,399723,0.448047,Limited

,category_name,review_month,review_count,average_rating,low_rating_ratio,high_rating_ratio,average_helpful_vote,helpful_vote_presence_ratio,long_review_ratio,verified_purchase_ratio,monthly_sample_size_band,is_trend_analysis_eligible,is_high_confidence_trend_period,average_rating_3_month_moving_average,low_rating_ratio_3_month_moving_average,helpful_vote_presence_ratio_3_month_moving_average,long_review_ratio_3_month_moving_average,trend_evidence_level
0,Beauty_and_Personal_Care,2007-01-01,1302,4.260369,0.103687,0.807988,4.697389,0.727343,0.493856,0.416283,Moderate,True,False,4.260369,0.103687,0.727343,0.493856,Moderate
1,Beauty_and_Personal_Care,2007-12-01,1034,4.255319,0.108317,0.799807,6.302708,0.695358,0.572534,0.420696,Moderate,True,False,4.257844,0.106002,0.711350,0.533195,Moderate
2,Beauty_and_Personal_Care,2008-01-01,1321,4.221045,0.128690,0.803936,5.355791,0.661620,0.576079,0.429220,Moderate,True,False,4.245577,0.113565,0.694773,0.547489,Moderate
3,Beauty_and_Personal_Care,2008-02-01,1109,4.188458,0.131650,0.790803,5.189360,0.693417,0.587917,0.427412,Moderate,True,False,4.221607,0.122886,0.683465,0.578843,Moderate
4,Beauty_and_Personal_Care,2008-03-01,1045,4.132057,0.150239,0.783732,11.235407,0.682297,0.597129,0.446890,Moderate,True,False,4.180520,0.136860,0.679111,0.587042,Moderate
5,Beauty_and_Personal_Care,2008-04-01,1155,4.202597,0.134199,0.794805,5.167100,0.703896,0.570563,0.406926,Moderate,True,False,4.174371,0.138696,0.693203,0.585203,Moderate
6,Beauty_and_Personal_Care,2008-05-01,1141,4.150745,0.141981,0.775635,4.345311,0.678352,0.611744,0.415425,Moderate,True,False,4.161800,0.142140,0.688182,0.593145,Moderate
7,Beauty_and_Personal_Care,2008-06-01,1059,4.102927,0.152975,0.757318,4.353163,0.678942,0.612842,0.452314,Moderate,True,False,4.152090,0.143051,0.687064,0.598383,Moderate
8,Beauty_and_Personal_Care,2008-07-01,1252,4.178115,0.121406,0.789137,4.841853,0.661342,0.590256,0.426518,Moderate,True,False,4.143929,0.138787,0.672879,0.604947,Moderate
9,Beauty_and_Personal_Care,2008-08-01,1150,4.194783,0.131304,0.794783,4.973043,0.651304,0.573043,0.413043,Moderate,True,False,4.158608,0.135228,0.663863,0.592047,Moderate
10,Beauty_and_Personal_Care,2008-09-01,1132,4.185512,0.131625,0.796820,5.004417,0.673145,0.573322,0.450530,Moderate,True,False,4.186137,0.128112,0.661930,0.578874,Moderate
11,Beauty_and_Personal_Care,2008-10-01,1118,4.165474,0.132379,0.780859,5.185152,0.671735,0.583184,0.430233,Moderate,True,False,4.181923,0.131770,0.665395,0.576516,Moderate
12,Beauty_and_Personal_Care,2008-11-01,1230,4.153659,0.143089,0.777236,5.804878,0.683740,0.568293,0.446341,Moderate,True,False,4.168215,0.135698,0.676207,0.574933,Moderate
13,Beauty_and_Personal_Care,2008-12-01,1508,4.153183,0.139920,0.777188,4.905836,0.688329,0.589523,0.441645,Moderate,True,False,4.157439,0.138463,0.681268,0.580333,Moderate
14,Beauty_and_Personal_Care,2009-01-01,2102,4.178877,0.147003,0.790200,4.529971,0.657469,0.570409,0.450523,Moderate,True,False,4.161906,0.143338,0.676513,0.576075,Moderate
15,Beauty_and_Personal_Care,2009-02-01,1664,4.121995,0.146034,0.776442,4.661058,0.680288,0.563101,0.493990,Moderate,True,False,4.151352,0.144319,0.675362,0.574344,Moderate
16,Beauty_and_Personal_Care,2009-03-01,1716,4.189977,0.132284,0.786713,4.772145,0.677739,0.565268,0.474359,Moderate,True,False,4.163616,0.141774,0.671832,0.566259,Moderate
17,Beauty_and_Personal_Care,2009-04-01,1731,4.177354,0.136337,0.781629,4.737146,0.677643,0.592721,0.485846,Moderate,True,False,4.163109,0.138218,0.678557,0.573697,Moderate
18,Beauty_and_Personal_Care,2009-05-01,1800,4.123889,0.153333,0.766111,5.801111,0.679444,0.590000,0.485000,Moderate,True,False,4.163740,0.140652,0.678275,0.582663,Moderate
19,Beauty_and_Personal_Care,2009-06-01,1774,4.151635,0.143179,0.777903,5.909808,0.702368,0.591883,0.487599,Moderate,True,False,4.150959,0.144283,0.686485,0.591535,Moderate

In [56]:
# Reviewing final product-level dissatisfaction and operational risk outputs

reporting_product_issue_actions_query = f"""
WITH ranked_products AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY category_name, issue_priority_level
            ORDER BY review_count DESC, low_rating_ratio DESC, average_rating ASC
        ) AS category_priority_rank
    FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.reporting_product_issue_actions`
)
SELECT *
FROM ranked_products
WHERE category_priority_rank <= 20
ORDER BY category_name, issue_priority_level, category_priority_rank
"""

reporting_product_content_actions_query = f"""
WITH ranked_products AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY category_name, metadata_improvement_priority
            ORDER BY review_count DESC, low_rating_ratio DESC, average_rating ASC
        ) AS category_priority_rank
    FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.reporting_product_content_actions`
)
SELECT *
FROM ranked_products
WHERE category_priority_rank <= 20
ORDER BY category_name, metadata_improvement_priority, category_priority_rank
"""

reporting_product_issue_actions_dataframe = run_query(reporting_product_issue_actions_query)
reporting_product_content_actions_dataframe = run_query(reporting_product_content_actions_query)

display(reporting_product_issue_actions_dataframe)
display(reporting_product_content_actions_dataframe)

,category_name,parent_asin,product_title,product_display_name,store_name,store_display_name,price_amount,review_count,average_rating,low_rating_ratio,...,text_analysis_ready_review_count,text_analysis_ready_ratio,product_sample_size_band,issue_priority_level,evidence_confidence_level,product_identification_quality,business_use_caution,business_basis,comparison_scope,category_priority_rank
0,Beauty_and_Personal_Care,B09KM16YYV,L'Oreal Paris Feria Multi-Faceted Shimmering P...,L'Oreal Paris Feria Multi-Faceted Shimmering P...,L'Oreal Paris,L'Oreal Paris,21.98,8517,3.563226,0.316661,...,7212,0.846777,Very high,Highest priority,High,High,No major product identification limitation,High-volume product with unusually high dissat...,Compared only against products in the same cat...,1
1,Beauty_and_Personal_Care,B00X7VFSOM,CHI Professional 1-Inch Ceramic Tourmaline Hai...,CHI Professional 1-Inch Ceramic Tourmaline Hai...,CHI,CHI,54.72,4424,3.598779,0.305832,...,4053,0.916139,High,Highest priority,High,High,No major product identification limitation,High-volume product with unusually high dissat...,Compared only against products in the same cat...,2
2,Beauty_and_Personal_Care,B0BSRJ5HDH,CeraVe Eye Repair Cream | Under Eye Cream for ...,CeraVe Eye Repair Cream | Under Eye Cream for ...,CeraVe,CeraVe,14.44,3448,3.517401,0.307715,...,2929,0.849478,High,Highest priority,High,High,No major product identification limitation,High-volume product with unusually high dissat...,Compared only against products in the same cat...,3
3,Beauty_and_Personal_Care,B00M1E5F1W,Philips Norelco Replacement Head for Series 70...,Philips Norelco Replacement Head for Series 70...,PHILIPS,PHILIPS,NaN,2612,3.156585,0.402757,...,2224,0.851455,High,Highest priority,High,High,No major product identification limitation,High-volume product with unusually high dissat...,Compared only against products in the same cat...,4
4,Beauty_and_Personal_Care,B0C7PNWXJR,Schwarzkopf Got2b Metallics Permanent Hair Col...,Schwarzkopf Got2b Metallics Permanent Hair Col...,Got2B,Got2B,8.99,2290,2.868559,0.497380,...,2010,0.877729,High,Highest priority,High,High,No major product identification limitation,High-volume product with unusually high dissat...,Compared only against products in the same cat...,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,Movies_and_TV,B00MILGKPI,None,ASIN B00MILGKPI,None,Unknown store,NaN,4902,3.872705,0.154019,...,2512,0.512444,High,Priority review,Moderate,Low,"Category metadata support is limited, so produ...",Product underperforming against category peers...,Compared only against products in the same cat...,16
196,Movies_and_TV,B019YHGHX8,Daddy's Home,Daddy's Home,None,Unknown store,4.99,4875,3.846564,0.157538,...,2474,0.507487,High,Priority review,Moderate,Moderate,"Category metadata support is limited, so produ...",Product underperforming against category peers...,Compared only against products in the same cat...,17
197,Movies_and_TV,B00IIUATDM,None,ASIN B00IIUATDM,None,Unknown store,NaN,4806,3.461923,0.299417,...,2917,0.606950,High,Priority review,Moderate,Low,"Category metadata support is limited, so produ...",Product underperforming against category peers...,Compared only against products in the same cat...,18
198,Movies_and_TV,B01DTFEJVS,None,ASIN B01DTFEJVS,None,Unknown store,NaN,4665,3.401501,0.245016,...,3407,0.730332,High,Priority review,Moderate,Low,"Category metadata support is limited, so produ...",Product underperforming against category peers...,Compared only against products in the same cat...,19
199,Movies_and_TV,B00OYWSQFG,The Prince,The Prince,None,Unknown store,7.99,4312,3.150974,0.311920,...,2388,0.553803,High,Priority review,Moderate,Moderate,"Category metadata support is limited, so produ...",Product underperforming against category peers...,Compared only against products in the same cat...,20

,category_name,parent_asin,product_title,product_display_name,store_name,store_display_name,price_amount,review_count,average_rating,low_rating_ratio,...,has_any_content_metadata,has_rich_content_metadata,has_minimum_content_support,has_rich_content_support,content_analysis_coverage_level,metadata_gap_type,metadata_improvement_priority,evidence_confidence_level,business_basis,category_priority_rank
0,Beauty_and_Personal_Care,B083WKDWJL,Grande Cosmetics GrandeLASH-MD Lash Enhancing ...,Grande Cosmetics GrandeLASH-MD Lash Enhancing ...,None,Unknown store,68.00,6541,3.472863,0.352698,...,True,False,True,False,Strong,Missing rich content support,Priority review,Moderate,"Meaningful customer feedback is present, dissa...",1
1,Beauty_and_Personal_Care,B08HWDNN4Q,Lume Deodorant Cream Stick - Underarms and Pri...,Lume Deodorant Cream Stick - Underarms and Pri...,Lume,Lume,NaN,1528,2.866492,0.483639,...,True,False,True,False,Strong,Missing rich content support,Priority review,Moderate,"Meaningful customer feedback is present, dissa...",2
2,Beauty_and_Personal_Care,B09KQB5SHK,VRVOGUE Brazilian Deep Wave Bundles with Closu...,VRVOGUE Brazilian Deep Wave Bundles with Closu...,VRVogue,VRVogue,95.99,1481,3.376772,0.351789,...,True,False,True,False,Strong,Missing rich content support,Priority review,Moderate,"Meaningful customer feedback is present, dissa...",3
3,Beauty_and_Personal_Care,B00JIM55MY,"St. Tropez Tan Applicator Mitt, Basic","St. Tropez Tan Applicator Mitt, Basic",None,Unknown store,NaN,1167,3.413882,0.343616,...,True,False,True,False,Strong,Missing rich content support,Priority review,Moderate,"Meaningful customer feedback is present, dissa...",4
4,Beauty_and_Personal_Care,B0056FL4FY,Dragonpad Nail Art Drill KIT Electric FILE Buf...,Dragonpad Nail Art Drill KIT Electric FILE Buf...,DragonPad,DragonPad,NaN,1160,3.101724,0.406034,...,False,False,False,False,Strong,Missing minimum content support,Priority review,Moderate,"Meaningful customer feedback is present, dissa...",5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Home_and_Kitchen,B08LKKGWQD,Laposso Milk Frother Rechargeable Handheld Ele...,Laposso Milk Frother Rechargeable Handheld Ele...,Laposso,Laposso,11.99,685,3.226277,0.400000,...,True,False,True,False,Strong,Missing rich content support,Priority review,Moderate,"Meaningful customer feedback is present, dissa...",16
76,Home_and_Kitchen,B07P83K2LM,SHARP Digital Alarm with AccuSet - Automatic S...,SHARP Digital Alarm with AccuSet - Automatic S...,Sharp,Sharp,NaN,679,3.301915,0.393225,...,True,False,True,False,Strong,Missing rich content support,Priority review,Moderate,"Meaningful customer feedback is present, dissa...",17
77,Home_and_Kitchen,B098B3XY1M,iLifeTech Hands Free Toothpaste Dispenser Auto...,iLifeTech Hands Free Toothpaste Dispenser Auto...,iLifeTech,iLifeTech,4.99,650,3.424615,0.316923,...,True,False,True,False,Strong,Missing rich content support,Priority review,Moderate,"Meaningful customer feedback is present, dissa...",18
78,Home_and_Kitchen,B011SUKOHE,Meal Prep Haven MP-7D2C Stackable 2 Compartmen...,Meal Prep Haven MP-7D2C Stackable 2 Compartmen...,Meal Prep Haven,Meal Prep Haven,NaN,635,3.239370,0.374803,...,True,False,True,False,Strong,Missing rich content support,Priority review,Moderate,"Meaningful customer feedback is present, dissa...",19
79,Home_and_Kitchen,B07GWCM246,"Dezin Electric Kettle, 2L Stainless Steel Cord...","Dezin Electric Kettle, 2L Stainless Steel Cord...",DEZIN,DEZIN,NaN,628,3.439490,0.345541,...,True,False,True,False,Strong,Missing rich content support,Priority review,Moderate,"Meaningful customer feedback is present, dissa...",20

In [57]:
# Building the Electronics text-analysis foundation for issue-theme modeling
execute_sql_file(sql_file_path = "sql scripts/14_build_electronics_text_foundation.sql",
                 configuration = configuration
)

SQL script executed successfully : /Users/bhavikpatwa/Documents/PROJECTS/Amazon Reviews Intelligence/sql scripts/14_build_electronics_text_foundation.sql

In [58]:
# Reviewing Electronics text-analysis modeling volume and dataset size

electronics_modeling_volume_query = f"""
SELECT
    'electronics_text_foundation' AS table_name,
    COUNT(*) AS row_count
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.electronics_text_foundation`

UNION ALL

SELECT
    'electronics_text_modeling_scope' AS table_name,
    COUNT(*) AS row_count
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.electronics_text_modeling_scope`

UNION ALL

SELECT
    'electronics_text_documents' AS table_name,
    COUNT(*) AS row_count
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.electronics_text_documents`

UNION ALL

SELECT
    'electronics_text_modeling_ready_documents' AS table_name,
    COUNT(*) AS row_count
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.electronics_text_modeling_ready`
"""

electronics_modeling_volume_dataframe = run_query(electronics_modeling_volume_query)
display(electronics_modeling_volume_dataframe)

                                  table_name  row_count
0                 electronics_text_documents      36622
1  electronics_text_modeling_ready_documents      36487
2                electronics_text_foundation   41971017
3            electronics_text_modeling_scope   12778563

In [59]:
# Reviewing Electronics sampling coverage across sentiment, price and priority segments

electronics_modeling_strata_query = f"""
SELECT
    verified_purchase,
    price_band,
    issue_priority_level,
    target_review_count_per_sentiment,
    stratum_evidence_level,
    is_selected_for_modeling
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.electronics_text_modeling_strata_summary`
ORDER BY verified_purchase, price_band, issue_priority_level
"""

electronics_modeling_strata_dataframe = run_query(electronics_modeling_strata_query)
display(electronics_modeling_strata_dataframe)

,verified_purchase,price_band,issue_priority_level,target_review_count_per_sentiment,stratum_evidence_level,is_selected_for_modeling
0,False,Budget,Highest priority,105,Limited,False
1,False,Budget,Monitor,5488,Comparison thin,False
2,False,Budget,Priority review,3220,Comparison thin,False
3,False,Lower mid,Highest priority,177,Limited,False
4,False,Lower mid,Monitor,9711,Comparison thin,False
5,False,Lower mid,Priority review,5035,Comparison thin,False
6,False,Premium,Highest priority,2117,Limited,False
7,False,Premium,Monitor,24232,Comparison thin,False
8,False,Premium,Priority review,27053,Comparison thin,False
9,False,Upper mid,Highest priority,639,Limited,False
10,False,Upper mid,Monitor,15112,Comparison thin,False
11,False,Upper mid,Priority review,15824,Comparison thin,False
12,False,Very premium,Highest priority,538,Limited,False
13,False,Very premium,Monitor,6299,Comparison thin,False
14,False,Very premium,Priority review,5148,Comparison thin,False
15,True,Budget,Highest priority,1025,Limited,False
16,True,Budget,Monitor,315909,Usable,True
17,True,Budget,Priority review,163580,Usable,True
18,True,Lower mid,Highest priority,1972,Limited,False
19,True,Lower mid,Monitor,342387,Usable,True
20,True,Lower mid,Priority review,138061,Usable,True
21,True,Premium,Highest priority,17787,Comparison thin,False
22,True,Premium,Monitor,272174,Usable,True
23,True,Premium,Priority review,169972,Usable,True
24,True,Upper mid,Highest priority,6480,Limited,False
25,True,Upper mid,Monitor,356710,Usable,True
26,True,Upper mid,Priority review,190800,Usable,True
27,True,Very premium,Highest priority,1940,Limited,False
28,True,Very premium,Monitor,50405,Usable,True
29,True,Very premium,Priority review,29030,Comparison thin,False