In [1]:
# Importing libraries for text analysis, visualization, embeddings, clustering and BigQuery access

from pathlib import Path
import sys

import pandas as pd
import numpy as np

import html
import re
import unicodedata
from collections import Counter
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, ENGLISH_STOP_WORDS
from sklearn.decomposition import NMF

from google.cloud import bigquery

import pickle

pd.set_option('display.max_rows', None)         # Show all rows
pd.set_option('display.max_columns', None)      # Show all columns

In [2]:
# Setting project paths and loading reusable helper functions

project_root = Path.cwd().resolve().parent if Path.cwd().name == "notebooks" else Path.cwd().resolve()
scripts_directory = project_root / "scripts"

if str(scripts_directory) not in sys.path:
    sys.path.append(str(scripts_directory))

from run_sql_scripts import load_project_configuration
from run_sql_scripts import configure_google_credentials

In [3]:
# Loading project configuration and creating BigQuery connections for Electronics NLP analysis

configuration = load_project_configuration()
configure_google_credentials(credentials_path_value = configuration["credentials_path"])

bigquery_client = bigquery.Client(project = configuration["gcp_project_id"])


def run_query(sql_text):
    return bigquery_client.query(sql_text).to_dataframe()

In [4]:
# Profiling Electronics review records for NLP readiness

modeling_ready_profile_query = f"""
SELECT
    analysis_pool_role,
    sentiment_cohort,
    verified_purchase,
    price_band,
    issue_priority_level,
    COUNT(*) AS document_count,
    SUM(sampled_review_count) AS total_sampled_reviews,
    AVG(sampled_review_count) AS average_sampled_reviews_per_document,
    MIN(sampled_review_count) AS min_sampled_reviews_per_document,
    MAX(sampled_review_count) AS max_sampled_reviews_per_document,
    AVG(aggregated_text_length) AS average_aggregated_text_length,
    MIN(aggregated_text_length) AS min_aggregated_text_length,
    MAX(aggregated_text_length) AS max_aggregated_text_length
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.electronics_text_modeling_ready`
GROUP BY
    analysis_pool_role,
    sentiment_cohort,
    verified_purchase,
    price_band,
    issue_priority_level
ORDER BY
    analysis_pool_role,
    sentiment_cohort,
    verified_purchase,
    price_band,
    issue_priority_level
"""

modeling_ready_profile_dataframe = run_query(modeling_ready_profile_query)
display(modeling_ready_profile_dataframe)

,analysis_pool_role,sentiment_cohort,verified_purchase,price_band,issue_priority_level,document_count,total_sampled_reviews,average_sampled_reviews_per_document,min_sampled_reviews_per_document,max_sampled_reviews_per_document,average_aggregated_text_length,min_aggregated_text_length,max_aggregated_text_length
0,Comparison baseline,Satisfaction,True,Budget,Monitor,3703,315963,85.326222,3,250,14844.635701,300,77129
1,Comparison baseline,Satisfaction,True,Budget,Priority review,1070,163689,152.980374,2,250,28525.889720,122,114791
2,Comparison baseline,Satisfaction,True,Lower mid,Monitor,3721,342517,92.049718,1,250,18707.086805,48,125902
3,Comparison baseline,Satisfaction,True,Lower mid,Priority review,949,138171,145.596417,1,250,32456.590095,83,125585
4,Comparison baseline,Satisfaction,True,Premium,Monitor,2903,272286,93.794695,1,250,27513.939029,55,189470
5,Comparison baseline,Satisfaction,True,Premium,Priority review,1185,169992,143.453165,3,250,44856.638819,428,167141
6,Comparison baseline,Satisfaction,True,Upper mid,Monitor,3668,356748,97.259542,1,250,23517.886314,310,124291
7,Comparison baseline,Satisfaction,True,Upper mid,Priority review,1282,190817,148.843214,1,250,39131.535881,88,139066
8,Comparison baseline,Satisfaction,True,Very premium,Monitor,712,50585,71.046348,1,250,25821.790730,184,132848
9,Topic modeling target,Dissatisfaction,True,Budget,Monitor,3168,315949,99.731376,1,250,21892.470013,33,102683
10,Topic modeling target,Dissatisfaction,True,Budget,Priority review,1088,163592,150.360294,1,250,30202.513787,60,96890
11,Topic modeling target,Dissatisfaction,True,Lower mid,Monitor,3224,342401,106.203784,1,250,26642.021402,163,118730
12,Topic modeling target,Dissatisfaction,True,Lower mid,Priority review,945,138147,146.187302,1,250,35311.462434,230,187706
13,Topic modeling target,Dissatisfaction,True,Premium,Monitor,2587,272410,105.299575,1,250,40545.158871,211,203015
14,Topic modeling target,Dissatisfaction,True,Premium,Priority review,1182,170041,143.858714,1,250,55882.846024,267,190282
15,Topic modeling target,Dissatisfaction,True,Upper mid,Monitor,3242,356723,110.031771,2,250,33870.147131,316,149768
16,Topic modeling target,Dissatisfaction,True,Upper mid,Priority review,1278,190846,149.331768,1,250,45341.797340,70,174069
17,Topic modeling target,Dissatisfaction,True,Very premium,Monitor,580,50411,86.915517,8,250,40084.872414,3858,170376

In [5]:
# Creating the Electronics NLP document dataset for downstream text and issue-theme analysis

electronics_nlp_documents_query = f"""
SELECT
    document_id,
    analysis_pool_role,
    sentiment_cohort,
    verified_purchase,
    price_band,
    issue_priority_level,
    product_evidence_segment,
    parent_asin,
    product_title_clean,
    product_display_name,
    store_clean,
    store_display_name,
    product_identification_quality,
    review_count,
    target_review_count_per_sentiment,
    target_review_count_for_product,
    per_document_review_cap,
    sampled_review_count,
    sampled_review_ratio,
    average_rating,
    average_helpful_vote,
    average_review_text_length,
    aggregated_text,
    aggregated_text_length,
    is_price_band_interpretation_eligible,
    is_price_sensitive_theme_comparison_eligible,
    is_issue_priority_comparison_eligible,
    is_product_interpretation_eligible
FROM `{configuration["gcp_project_id"]}.{configuration["bigquery_core_dataset_id"]}.electronics_text_modeling_ready`
ORDER BY
    analysis_pool_role,
    sentiment_cohort,
    verified_purchase,
    price_band,
    issue_priority_level,
    document_id
"""

electronics_nlp_documents_dataframe = run_query(electronics_nlp_documents_query)
print(f"Loaded rows : {len(electronics_nlp_documents_dataframe):,}")
electronics_nlp_documents_dataframe.head()

Loaded rows : 36,487

,document_id,analysis_pool_role,sentiment_cohort,verified_purchase,price_band,issue_priority_level,product_evidence_segment,parent_asin,product_title_clean,product_display_name,store_clean,store_display_name,product_identification_quality,review_count,target_review_count_per_sentiment,target_review_count_for_product,per_document_review_cap,sampled_review_count,sampled_review_ratio,average_rating,average_helpful_vote,average_review_text_length,aggregated_text,aggregated_text_length,is_price_band_interpretation_eligible,is_price_sensitive_theme_comparison_eligible,is_issue_priority_comparison_eligible,is_product_interpretation_eligible
0,Satisfaction|true|Budget|Monitor|106171327X|ch...,Comparison baseline,Satisfaction,True,Budget,Monitor,Evidence-backed product,106171327X,SanDisk SDSDQUA-064G-A11 Professional Ultra 64...,SanDisk SDSDQUA-064G-A11 Professional Ultra 64...,SanDisk,SanDisk,High,164,315909,27,250,27,0.164634,4.932927,0.548780,96.420732,great price my last card died after a year so ...,2870,True,True,True,True
1,Satisfaction|true|Budget|Monitor|B00000J1QR|ch...,Comparison baseline,Satisfaction,True,Budget,Monitor,Evidence-backed product,B00000J1QR,"Allsop CD and DVD FastWipes, lint-free wipes f...","Allsop CD and DVD FastWipes, lint-free wipes f...",Allsop,Allsop,High,169,315909,28,250,28,0.165680,4.715976,2.349112,166.295858,great for keeping dvds or cdcs clean br br yes...,4261,True,True,True,True
2,Satisfaction|true|Budget|Monitor|B00004Z5M1|ch...,Comparison baseline,Satisfaction,True,Budget,Monitor,Evidence-backed product,B00004Z5M1,Belkin - F3U133b10 (F3U133b10) Hi-Speed USB A/...,Belkin - F3U133b10 (F3U133b10) Hi-Speed USB A/...,Belkin,Belkin,High,850,315909,137,250,137,0.161176,4.889412,0.435294,163.344706,i really appreciate the good value of this pri...,25729,True,True,True,True
3,Satisfaction|true|Budget|Monitor|B00004ZCJF|ch...,Comparison baseline,Satisfaction,True,Budget,Monitor,Evidence-backed product,B00004ZCJF,Tiffen 49UVP 49mm UV Protection Camera Lens Fi...,Tiffen 49UVP 49mm UV Protection Camera Lens Fi...,Tiffen,Tiffen,High,194,315909,32,250,32,0.164948,4.829897,0.283505,164.737113,for the price i always buy tiffen lens filters...,5032,True,True,True,True
4,Satisfaction|true|Budget|Monitor|B00004ZCJJ|ch...,Comparison baseline,Satisfaction,True,Budget,Monitor,Evidence-backed product,B00004ZCJJ,Tiffen 62UVP 62mm UV Protection Filter,Tiffen 62UVP 62mm UV Protection Filter,Tiffen,Tiffen,High,225,315909,37,250,37,0.164444,4.826667,0.102222,151.924444,no tiene problema con la fotograf a review_bou...,6772,True,True,True,True

In [6]:
electronics_nlp_documents_dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36487 entries, 0 to 36486
Data columns (total 28 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   document_id                                   36487 non-null  object
 1   analysis_pool_role                            36487 non-null  object
 2   sentiment_cohort                              36487 non-null  object
 3   verified_purchase                             36487 non-null  boolean
 4   price_band                                    36487 non-null  object
 5   issue_priority_level                          36487 non-null  object
 6   product_evidence_segment                      36487 non-null  object
 7   parent_asin                                   36487 non-null  object
 8   product_title_clean                           36487 non-null  object
 9   product_display_name                          36487 non-null  object
 10  store_clean                                   36486 non-null  object
 11  store_display_name                            36487 non-null  object
 12  product_identification_quality                36487 non-null  object
 13  review_count                                  36487 non-null  Int64
 14  target_review_count_per_sentiment             36487 non-null  Int64
 15  target_review_count_for_product               36487 non-null  Int64
 16  per_document_review_cap                       36487 non-null  Int64
 17  sampled_review_count                          36487 non-null  Int64
 18  sampled_review_ratio                          36487 non-null  float64
 19  average_rating                                36487 non-null  float64
 20  average_helpful_vote                          36487 non-null  float64
 21  average_review_text_length                    36487 non-null  float64
 22  aggregated_text                               36487 non-null  object
 23  aggregated_text_length                        36487 non-null  Int64
 24  is_price_band_interpretation_eligible         36487 non-null  boolean
 25  is_price_sensitive_theme_comparison_eligible  36487 non-null  boolean
 26  is_issue_priority_comparison_eligible         36487 non-null  boolean
 27  is_product_interpretation_eligible            36487 non-null  boolean
dtypes: Int64(6), boolean(5), float64(4), object(13)
memory usage: 7.0+ MB

In [7]:
# Summarizing document quality, text readiness and review aggregation statistics
document_quality_summary_dataframe = pd.DataFrame({
    "metric": [
        "row_count",
        "unique_document_id_count",
        "duplicate_document_id_count",
        "null_aggregated_text_count",
        "blank_aggregated_text_count",
        "null_price_band_count",
        "null_issue_priority_level_count",
        "null_product_display_name_count",
        "null_store_display_name_count"
    ],
    "value": [
        len(electronics_nlp_documents_dataframe),
        electronics_nlp_documents_dataframe["document_id"].nunique(),
        len(electronics_nlp_documents_dataframe) - electronics_nlp_documents_dataframe["document_id"].nunique(),
        electronics_nlp_documents_dataframe["aggregated_text"].isna().sum(),
        electronics_nlp_documents_dataframe["aggregated_text"].fillna("").str.strip().eq("").sum(),
        electronics_nlp_documents_dataframe["price_band"].isna().sum(),
        electronics_nlp_documents_dataframe["issue_priority_level"].isna().sum(),
        electronics_nlp_documents_dataframe["product_display_name"].isna().sum(),
        electronics_nlp_documents_dataframe["store_display_name"].isna().sum()
    ]
})

display(document_quality_summary_dataframe)

                            metric  value
0                        row_count  36487
1         unique_document_id_count  36487
2      duplicate_document_id_count      0
3       null_aggregated_text_count      0
4      blank_aggregated_text_count      0
5            null_price_band_count      0
6  null_issue_priority_level_count      0
7  null_product_display_name_count      0
8    null_store_display_name_count      0

In [8]:
# Reviewing text-length distribution across Electronics NLP documents
text_length_distribution_dataframe = electronics_nlp_documents_dataframe[[
    "aggregated_text_length",
    "sampled_review_count",
    "average_rating",
    "average_helpful_vote",
    "average_review_text_length"
]].describe(percentiles = [0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]).T

display(text_length_distribution_dataframe)

,count,mean,std,min,1%,5%,25%,50%,75%,95%,99%,max
aggregated_text_length,36487.0,28973.935758,25206.134567,33.0,2661.44,4711.0,10264.0,19887.0,41545.5,79402.0,113102.12,203015.0
sampled_review_count,36487.0,109.663387,80.874216,1.0,15.0,26.0,43.0,78.0,170.0,250.0,250.0,250.0
average_rating,36487.0,3.161623,1.762326,1.020833,1.123364,1.188235,1.309278,4.703448,4.844503,4.918746,4.946734,5.0
average_helpful_vote,36487.0,1.450585,2.272433,0.0,0.095931,0.189189,0.464103,0.873555,1.655364,4.432372,9.103622,110.148936
average_review_text_length,36487.0,255.282469,116.476092,77.340426,107.455052,128.449066,176.137389,226.361111,301.652297,480.449834,669.619363,1458.325581

In [9]:
# Reviewing document distribution across satisfaction, price and priority segments

segment_distribution_dataframe = (
    electronics_nlp_documents_dataframe
    .groupby(
        ["analysis_pool_role", "sentiment_cohort", "verified_purchase", "price_band", "issue_priority_level"],
        dropna = False
    )
    .agg(
        document_count = ("document_id", "count"),
        total_sampled_reviews = ("sampled_review_count", "sum"),
        average_aggregated_text_length = ("aggregated_text_length", "mean")
    )
    .reset_index()
    .sort_values(
        by = ["analysis_pool_role", "sentiment_cohort", "verified_purchase", "price_band", "issue_priority_level"]
    )
)

display(segment_distribution_dataframe)

,analysis_pool_role,sentiment_cohort,verified_purchase,price_band,issue_priority_level,document_count,total_sampled_reviews,average_aggregated_text_length
0,Comparison baseline,Satisfaction,True,Budget,Monitor,3703,315963,14844.635701
1,Comparison baseline,Satisfaction,True,Budget,Priority review,1070,163689,28525.88972
2,Comparison baseline,Satisfaction,True,Lower mid,Monitor,3721,342517,18707.086805
3,Comparison baseline,Satisfaction,True,Lower mid,Priority review,949,138171,32456.590095
4,Comparison baseline,Satisfaction,True,Premium,Monitor,2903,272286,27513.939029
5,Comparison baseline,Satisfaction,True,Premium,Priority review,1185,169992,44856.638819
6,Comparison baseline,Satisfaction,True,Upper mid,Monitor,3668,356748,23517.886314
7,Comparison baseline,Satisfaction,True,Upper mid,Priority review,1282,190817,39131.535881
8,Comparison baseline,Satisfaction,True,Very premium,Monitor,712,50585,25821.79073
9,Topic modeling target,Dissatisfaction,True,Budget,Monitor,3168,315949,21892.470013
10,Topic modeling target,Dissatisfaction,True,Budget,Priority review,1088,163592,30202.513787
11,Topic modeling target,Dissatisfaction,True,Lower mid,Monitor,3224,342401,26642.021402
12,Topic modeling target,Dissatisfaction,True,Lower mid,Priority review,945,138147,35311.462434
13,Topic modeling target,Dissatisfaction,True,Premium,Monitor,2587,272410,40545.158871
14,Topic modeling target,Dissatisfaction,True,Premium,Priority review,1182,170041,55882.846024
15,Topic modeling target,Dissatisfaction,True,Upper mid,Monitor,3242,356723,33870.147131
16,Topic modeling target,Dissatisfaction,True,Upper mid,Priority review,1278,190846,45341.79734
17,Topic modeling target,Dissatisfaction,True,Very premium,Monitor,580,50411,40084.872414

In [10]:
# Cleaning and standardizing aggregated Electronics review text for NLP analysis
electronics_nlp_documents_dataframe["aggregated_text_clean"] = (
    electronics_nlp_documents_dataframe["aggregated_text"]
    .fillna("")
    .str.replace(r"\s+", " ", regex = True)
    .str.strip()
)

electronics_nlp_documents_dataframe["is_usable_text_document"] = (
    electronics_nlp_documents_dataframe["aggregated_text_clean"].ne("")
    & electronics_nlp_documents_dataframe["aggregated_text_length"].fillna(0).ge(100)
    & electronics_nlp_documents_dataframe["sampled_review_count"].fillna(0).ge(25)
)

post_load_quality_summary_dataframe = pd.DataFrame({
    "metric": [
        "usable_text_document_count",
        "excluded_text_document_count",
        "usable_topic_modeling_target_count",
        "usable_comparison_baseline_count"
    ],
    "value": [
        electronics_nlp_documents_dataframe["is_usable_text_document"].sum(),
        (~electronics_nlp_documents_dataframe["is_usable_text_document"]).sum(),
        (
            electronics_nlp_documents_dataframe["is_usable_text_document"]
            & electronics_nlp_documents_dataframe["analysis_pool_role"].eq("Topic modeling target")
        ).sum(),
        (
            electronics_nlp_documents_dataframe["is_usable_text_document"]
            & electronics_nlp_documents_dataframe["analysis_pool_role"].eq("Comparison baseline")
        ).sum()
    ]
})

display(post_load_quality_summary_dataframe)

                               metric  value
0          usable_text_document_count  35213
1        excluded_text_document_count   1274
2  usable_topic_modeling_target_count  16853
3    usable_comparison_baseline_count  18360

In [11]:
# Previewing cleaned Electronics review documents prepared for NLP analysis

usable_documents_preview_dataframe = electronics_nlp_documents_dataframe.loc[
    electronics_nlp_documents_dataframe["is_usable_text_document"],
    [
        "document_id",
        "analysis_pool_role",
        "sentiment_cohort",
        "price_band",
        "issue_priority_level",
        "product_display_name",
        "sampled_review_count",
        "aggregated_text_length",
        "aggregated_text_clean"
    ]
].head(10)

display(usable_documents_preview_dataframe)

,document_id,analysis_pool_role,sentiment_cohort,price_band,issue_priority_level,product_display_name,sampled_review_count,aggregated_text_length,aggregated_text_clean
0,Satisfaction|true|Budget|Monitor|106171327X|ch...,Comparison baseline,Satisfaction,Budget,Monitor,SanDisk SDSDQUA-064G-A11 Professional Ultra 64...,27,2870,great price my last card died after a year so ...
1,Satisfaction|true|Budget|Monitor|B00000J1QR|ch...,Comparison baseline,Satisfaction,Budget,Monitor,"Allsop CD and DVD FastWipes, lint-free wipes f...",28,4261,great for keeping dvds or cdcs clean br br yes...
2,Satisfaction|true|Budget|Monitor|B00004Z5M1|ch...,Comparison baseline,Satisfaction,Budget,Monitor,Belkin - F3U133b10 (F3U133b10) Hi-Speed USB A/...,137,25729,i really appreciate the good value of this pri...
3,Satisfaction|true|Budget|Monitor|B00004ZCJF|ch...,Comparison baseline,Satisfaction,Budget,Monitor,Tiffen 49UVP 49mm UV Protection Camera Lens Fi...,32,5032,for the price i always buy tiffen lens filters...
4,Satisfaction|true|Budget|Monitor|B00004ZCJJ|ch...,Comparison baseline,Satisfaction,Budget,Monitor,Tiffen 62UVP 62mm UV Protection Filter,37,6772,no tiene problema con la fotograf a review_bou...
5,Satisfaction|true|Budget|Monitor|B00005MDZD|ch...,Comparison baseline,Satisfaction,Budget,Monitor,Gam3Gear Component AV Audio Video Cable for PS...,62,18761,this cable fixed my black and white problem wi...
6,Satisfaction|true|Budget|Monitor|B00005T3DX|ch...,Comparison baseline,Satisfaction,Budget,Monitor,"Duracell CR2 3V Lithium Battery, 1 Count Pack,...",27,3576,the batteries fit the security connections i n...
7,Satisfaction|true|Budget|Monitor|B00005T3EY|ch...,Comparison baseline,Satisfaction,Budget,Monitor,RCA Matching Transformer -VH54R,32,6265,old school transformer needed it for a vintage...
8,Satisfaction|true|Budget|Monitor|B00005T3GH|ch...,Comparison baseline,Satisfaction,Budget,Monitor,RCA AH216 Stereo Headphone Adapter Plug,29,5622,the package came in rca brand packaging seems ...
9,Satisfaction|true|Budget|Monitor|B0000668YX|ch...,Comparison baseline,Satisfaction,Budget,Monitor,Belkin Single Outlet MasterCube Wall-Mount Sur...,27,7864,our phones got fried in a nearby lightning str...

In [12]:
# Filtering usable Electronics NLP documents with sufficient text quality
usable_electronics_nlp_documents_dataframe = (
    electronics_nlp_documents_dataframe.loc[
        electronics_nlp_documents_dataframe["is_usable_text_document"]
    ].copy()
)

print(f"Usable documents retained for NLP preparation : {len(usable_electronics_nlp_documents_dataframe):,}")

Usable documents retained for NLP preparation : 35,213

In [13]:
# Reviewing text-cleaning artifacts and remaining formatting patterns
text_artifact_summary_dataframe = pd.DataFrame({
    "metric": [
        "document_count",
        "documents_with_html_break_tokens",
        "documents_with_encoded_html_entities",
        "documents_with_non_ascii_characters",
        "documents_with_repeated_whitespace",
        "documents_with_digit_sequences",
        "documents_with_very_long_text_over_100000_chars"
    ],
    "value": [
        len(usable_electronics_nlp_documents_dataframe),
        usable_electronics_nlp_documents_dataframe["aggregated_text_clean"].str.contains(r"\bbr\b", regex = True, na = False).sum(),
        usable_electronics_nlp_documents_dataframe["aggregated_text_clean"].str.contains(r"&[a-zA-Z]+;", regex = True, na = False).sum(),
        usable_electronics_nlp_documents_dataframe["aggregated_text_clean"].str.contains(r"[^\x00-\x7F]", regex = True, na = False).sum(),
        usable_electronics_nlp_documents_dataframe["aggregated_text_clean"].str.contains(r"\s{2,}", regex = True, na = False).sum(),
        usable_electronics_nlp_documents_dataframe["aggregated_text_clean"].str.contains(r"\d{2,}", regex = True, na = False).sum(),
        usable_electronics_nlp_documents_dataframe["aggregated_text_length"].gt(100000).sum()
    ]
})

display(text_artifact_summary_dataframe)

                                            metric  value
0                                   document_count  35213
1                 documents_with_html_break_tokens  34671
2             documents_with_encoded_html_entities      0
3              documents_with_non_ascii_characters      0
4               documents_with_repeated_whitespace      0
5                   documents_with_digit_sequences  34847
6  documents_with_very_long_text_over_100000_chars    695

In [14]:
# Defining grouping dimensions for Electronics NLP segmentation analysis
group_columns = [
    "analysis_pool_role",
    "price_band",
    "issue_priority_level"
]

diagnostic_sample_size_per_segment = 400
random_number_generator = np.random.default_rng(42)

diagnostic_sample_dataframe = (
    usable_electronics_nlp_documents_dataframe
    .assign(_random_order = random_number_generator.random(len(usable_electronics_nlp_documents_dataframe)))
    .sort_values(group_columns + ["_random_order"])
    .groupby(group_columns, dropna = False, group_keys = False)
    .head(diagnostic_sample_size_per_segment)
    .drop(columns = ["_random_order"])
    .reset_index(drop = True)
)

print(f"Diagnostic sample size : {len(diagnostic_sample_dataframe):,}")

diagnostic_segment_summary_dataframe = (
    diagnostic_sample_dataframe
    .groupby(group_columns, dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        total_sampled_reviews = ("sampled_review_count", "sum"),
        average_aggregated_text_length = ("aggregated_text_length", "mean")
    )
    .reset_index()
    .sort_values(group_columns)
)

display(diagnostic_segment_summary_dataframe)

Diagnostic sample size : 7,200

,analysis_pool_role,price_band,issue_priority_level,document_count,total_sampled_reviews,average_aggregated_text_length
0,Comparison baseline,Budget,Monitor,400,36957,16056.8025
1,Comparison baseline,Budget,Priority review,400,62964,29284.56
2,Comparison baseline,Lower mid,Monitor,400,37060,19070.8875
3,Comparison baseline,Lower mid,Priority review,400,58542,32358.74
4,Comparison baseline,Premium,Monitor,400,39900,29048.9675
5,Comparison baseline,Premium,Priority review,400,58513,45702.2425
6,Comparison baseline,Upper mid,Monitor,400,42222,25456.2075
7,Comparison baseline,Upper mid,Priority review,400,59644,39842.3675
8,Comparison baseline,Very premium,Monitor,400,28451,25841.9075
9,Topic modeling target,Budget,Monitor,400,42753,23364.41
10,Topic modeling target,Budget,Priority review,400,62285,31220.82
11,Topic modeling target,Lower mid,Monitor,400,43484,27127.4725
12,Topic modeling target,Lower mid,Priority review,400,59550,35963.04
13,Topic modeling target,Premium,Monitor,400,43380,41997.41
14,Topic modeling target,Premium,Priority review,400,60077,57314.315
15,Topic modeling target,Upper mid,Monitor,400,46592,35693.97
16,Topic modeling target,Upper mid,Priority review,400,58142,43275.3775
17,Topic modeling target,Very premium,Monitor,400,35463,41060.1425

In [15]:
# Defining review boundary markers, text-cleaning tokens and protected technical terms

review_boundary_token = "review_boundary"

short_technical_tokens = {
    "tv", "pc", "vr", "hd", "sd", "ac", "dc",
    "usb", "ssd", "wifi", "hdmi", "ps5", "ps4",
    "oled", "qled", "lcd", "led", "dslr", "gps"
}

domain_stopwords = {
    "product", "products", "item", "items", "review", "reviews",
    "videoid",
    "month", "months", "day", "days",
    "did", "does", "got", "just", "thing", "things",
    "make", "makes", "made", "using", "used", "use",
    "new", "little", "nice", "way", "know", "want",
    "look", "looks", "looking"
}

month_stopwords = {
    "january", "february", "march", "april", "june", "july",
    "august", "september", "october", "november", "december",
    "jan", "feb", "mar", "apr", "jun", "jul", "aug", "sep", "sept",
    "oct", "nov", "dec"
}

low_value_noise_tokens = {
    "br", "quot", "nbsp", "amp"
}

artifact_stopwords = {
    "deadline", "pos", "wast", "waist", "straw", "avail",
    "honor", "smh", "wtf"
}

generic_sentiment_tokens = {
    "good", "great", "better", "best", "perfect", "recommend",
    "recommended", "happy", "easy", "love", "loved", "liked",
    "fine", "pretty", "absolutely"
}

generic_context_tokens = {
    "like", "time", "people", "say", "actually", "think", "lot",
    "small", "big", "old", "right", "long", "set", "stars",
    "able", "getting", "having", "times", "going", "needed",
    "different", "second", "far", "takes", "taking", "bit", "fact",
    "need", "device", "money", "away",
    "week", "weeks", "year", "years", "hour", "hours",
    "doing", "tell", "gets"
}

residual_generic_tokens = {
    "really", "sure", "wanted", "ones", "person", "stuff",
    "seen", "similar", "previous", "real", "extra", "deal", "type",
    "home", "house", "large", "high", "low", "perfectly"
}

evaluative_outcome_tokens = {
    "waste_money", "not_worth", "disappointed", "disappointing",
    "terrible", "horrible", "awful", "useless", "worthless",
    "junk", "garbage", "trash", "worst"
}

delivery_or_fulfillment_tokens = {
    "late_delivery", "on_time_delivery", "shipping", "ship", "shipped",
    "arrived", "arrive", "arrival", "arrived_damaged", "wrong_item",
    "package", "packaging", "box", "seller", "sellers", "amazon",
    "customer_service", "tech_support"
}

remedy_or_transaction_tokens = {
    "return", "returns", "returned", "returning",
    "refund", "refunds", "refunded",
    "return_window", "return_policy",
    "warranty", "warranties",
    "buyer", "buyers", "beware",
    "false_advertising", "false_advertisement",
    "exchange", "restocking",
    "pay_shipping"
}


base_stopwords = set(ENGLISH_STOP_WORDS)

combined_stopwords = (
    base_stopwords
    .union(domain_stopwords)
    .union(month_stopwords)
    .union(low_value_noise_tokens)
    .union(artifact_stopwords)
    .union(generic_sentiment_tokens)
    .union(generic_context_tokens)
    .union(residual_generic_tokens)
)

protected_phrase_tokens = {
    "does_not_work", "did_not_work", "not_working", "stopped_working",
    "will_not_turn_on", "not_turn_on",
    "battery_life", "battery_died",
    "sound_quality", "picture_quality", "build_quality",
    "customer_service", "tech_support",
    "not_charge", "not_charging",
    "not_connect", "not_connecting", "keeps_disconnecting",
    "not_pair", "not_pairing",
    "not_compatible", "not_fit",
    "late_delivery", "on_time_delivery",
    "return_policy", "return_window",
    "dead_on_arrival", "noise_cancelling",
    "smart_tv", "usb_c", "usb_a", "sd_card", "micro_sd",
    "bluetooth", "wifi", "hard_drive", "poor_quality",
    "no_signal", "no_sound", "no_power",
    review_boundary_token
}

token_normalization_map = {
    "works": "work",
    "worked": "work",
    "working": "work",
    "charges": "charge",
    "charged": "charge",
    "charging": "charge",
    "connects": "connect",
    "connected": "connect",
    "connecting": "connect",
    "disconnects": "disconnect",
    "disconnected": "disconnect",
    "disconnecting": "disconnect",
    "installs": "install",
    "installed": "install",
    "installing": "install",
    "pairs": "pair",
    "paired": "pair",
    "pairing": "pair",
    "returns": "return",
    "returned": "return",
    "returning": "return",
    "replaced": "replace",
    "replacing": "replace",
    "tries": "try",
    "tried": "try",
    "trying": "try",
    "batteries": "battery",
    "cables": "cable",
    "devices": "device",
    "headphones": "headphone",
    "speakers": "speaker",
    "routers": "router",
    "monitors": "monitor",
    "cameras": "camera",
    "wast": "wasted",
    "avail": "available",
    "dissappointed": "disappointed",
    "dissapointed": "disappointed"
}

contraction_replacements = {
    r"\bwon(?:['’]t|\s+t)\b": "will not",
    r"\bcan(?:['’]t|\s+t)\b": "can not",
    r"\bdon(?:['’]t|\s+t)\b": "do not",
    r"\bdoesn(?:['’]t|\s+t)\b": "does not",
    r"\bdidn(?:['’]t|\s+t)\b": "did not",
    r"\bisn(?:['’]t|\s+t)\b": "is not",
    r"\baren(?:['’]t|\s+t)\b": "are not",
    r"\bwasn(?:['’]t|\s+t)\b": "was not",
    r"\bweren(?:['’]t|\s+t)\b": "were not",
    r"\bshouldn(?:['’]t|\s+t)\b": "should not",
    r"\bcouldn(?:['’]t|\s+t)\b": "could not",
    r"\bwouldn(?:['’]t|\s+t)\b": "would not",
    r"\bhasn(?:['’]t|\s+t)\b": "has not",
    r"\bhaven(?:['’]t|\s+t)\b": "have not",
    r"\bhadn(?:['’]t|\s+t)\b": "had not",
    r"\bit(?:['’]s|\s+s)\b": "it is",
    r"\bthat(?:['’]s|\s+s)\b": "that is",
    r"\bthere(?:['’]s|\s+s)\b": "there is",
    r"\bi(?:['’]m|\s+m)\b": "i am",
    r"\bi(?:['’]ve|\s+ve)\b": "i have",
    r"\bwe(?:['’]ve|\s+ve)\b": "we have",
    r"\bthey(?:['’]ve|\s+ve)\b": "they have",
    r"\byou(?:['’]ve|\s+ve)\b": "you have",
    r"\bi(?:['’]ll|\s+ll)\b": "i will",
    r"\bwe(?:['’]ll|\s+ll)\b": "we will",
    r"\bthey(?:['’]ll|\s+ll)\b": "they will",
    r"\byou(?:['’]ll|\s+ll)\b": "you will",
    r"\bthey(?:['’]re|\s+re)\b": "they are",
    r"\bwe(?:['’]re|\s+re)\b": "we are",
    r"\byou(?:['’]re|\s+re)\b": "you are"
}

spelling_normalizations = {
    r"\bstoped\b": "stopped",
    r"\bdisapointed\b": "disappointed",
    r"\bdissapointed\b": "disappointed",
    r"\bdissappointed\b": "disappointed",
    r"\bperfet\b": "perfect",
    r"\bmala\s+calidad\b": "poor_quality"
}

phrase_replacements = {
    r"\bsound\s+quality\b": "sound_quality",
    r"\bpicture\s+quality\b": "picture_quality",
    r"\bbuild\s+quality\b": "build_quality",
    r"\bbattery\s+life\b": "battery_life",
    r"\bcustomer\s+service\b": "customer_service",
    r"\bcustomer\s+support\b": "customer_service",
    r"\btech\s+support\b": "tech_support",
    r"\bhard\s+drive\b": "hard_drive",
    r"\bsolid\s+state\s+drive\b": "ssd",
    r"\bscreen\s+protector\b": "screen_protector",
    r"\bplug\s+and\s+play\b": "plug_and_play",
    r"\bset\s+up\b": "setup",
    r"\bwi\s*fi\b": "wifi",
    r"\bblu[\s\-]*ray\b": "bluray",
    r"\bblu[\s\-]*tooth\b": "bluetooth",
    r"\busb[\s\-]*c\b": "usb_c",
    r"\busb[\s\-]*a\b": "usb_a",
    r"\bmicro[\s\-]*sd(?:\s+card)?\b": "micro_sd",
    r"\bsd[\s\-]*card\b": "sd_card",
    r"\bnoise\s+cancell(?:ing|ation)\b": "noise_cancelling",
    r"\bsmart\s+tv\b": "smart_tv",
    r"\b4k\b": "four_k",
    r"\b1080p\b": "full_hd",
    r"\b2\s*4\s*ghz\b": "two_four_ghz",
    r"\b5\s*ghz\b": "five_ghz",
    r"\bdoes\s+not\s+work\b": "does_not_work",
    r"\bdid\s+not\s+work\b": "did_not_work",
    r"\bnot\s+working\b": "not_working",
    r"\bstopped\s+working\b": "stopped_working",
    r"\bwill\s+not\s+turn\s+on\b": "will_not_turn_on",
    r"\bnot\s+turn(?:ing)?\s+on\b": "not_turn_on",
    r"\bdead\s+on\s+arrival\b": "dead_on_arrival",
    r"\bbattery\s+died\b": "battery_died",
    r"\bwill\s+not\s+charge\b": "not_charge",
    r"\bdoes\s+not\s+charge\b": "not_charge",
    r"\bnot\s+charging\b": "not_charging",
    r"\bdoes\s+not\s+connect\b": "not_connect",
    r"\bnot\s+connecting\b": "not_connecting",
    r"\bkeeps\s+disconnecting\b": "keeps_disconnecting",
    r"\bdoes\s+not\s+pair\b": "not_pair",
    r"\bnot\s+pairing\b": "not_pairing",
    r"\bnot\s+compatible\b": "not_compatible",
    r"\bdoes\s+not\s+fit\b": "not_fit",
    r"\blate\s+delivery\b": "late_delivery",
    r"\barrived\s+late\b": "late_delivery",
    r"\bon\s+time\b": "on_time_delivery",
    r"\breturn\s+window\b": "return_window",
    r"\breturn\s+policy\b": "return_policy",
    r"\bpoor\s+quality\b": "poor_quality",
    r"\bno\s+signal\b": "no_signal",
    r"\bno\s+sound\b": "no_sound",
    r"\bno\s+power\b": "no_power",
    r"\bfalse\s+advertising\b": "false_advertising",
    r"\bnot\s+as\s+described\b": "not_as_described",
    r"\bnot\s+worth\b": "not_worth",
    r"\bwaste\s+of\s+money\b": "waste_money",
    r"\bcustomer\s+care\b": "customer_service",
    r"\btech\s+help\b": "tech_support",
    r"\barrived\s+damaged\b": "arrived_damaged",
    r"\bwrong\s+item\b": "wrong_item",
    r"\bdefective\s+unit\b": "defective_unit",
    r"\bstop(?:ped)?\s+charging\b": "not_charging",
    r"\bstop(?:ped)?\s+connecting\b": "not_connecting"
}

repeated_token_pattern = re.compile(r"\b(\w+)(?:\s+\1){3,}\b")

def collapse_repeated_tokens(text_value, max_consecutive_repeats = 2):
    if not text_value:
        return ""

    input_tokens = text_value.split()
    output_tokens = []
    previous_token = None
    repeat_count = 0

    for token in input_tokens:
        if token == previous_token:
            repeat_count += 1
        else:
            previous_token = token
            repeat_count = 1

        if repeat_count <= max_consecutive_repeats:
            output_tokens.append(token)

    return " ".join(output_tokens)

def clip_text_balanced_by_review_boundaries(
    text_value,
    boundary_token = review_boundary_token,
    max_reviews = 120,
    min_reviews_to_clip = 140
):
    if not text_value:
        return "", False

    review_parts = [
        part.strip()
        for part in str(text_value).split(boundary_token)
        if part.strip()
    ]

    review_count = len(review_parts)

    if review_count <= min_reviews_to_clip:
        return f" {boundary_token} ".join(review_parts), False

    first_block_size = max_reviews // 3
    middle_block_size = max_reviews // 3
    last_block_size = max_reviews - first_block_size - middle_block_size

    middle_start_index = max((review_count // 2) - (middle_block_size // 2), 0)
    middle_end_index = middle_start_index + middle_block_size

    clipped_reviews = (
        review_parts[ : first_block_size]
        + review_parts[middle_start_index:middle_end_index]
        + review_parts[-last_block_size:]
    )

    return f" {boundary_token} ".join(clipped_reviews), True


def clean_electronics_review_text(text_value):
    if pd.isna(text_value):
        return ""

    cleaned_text = str(text_value)
    cleaned_text = html.unescape(cleaned_text)
    cleaned_text = unicodedata.normalize("NFKC", cleaned_text)
    cleaned_text = cleaned_text.lower()

    cleaned_text = re.sub(rf"\b{review_boundary_token}\b", f" {review_boundary_token} ", cleaned_text)
    cleaned_text = cleaned_text.replace("\n", " ").replace("\r", " ").replace("\t", " ")
    cleaned_text = re.sub(r"https?://\S+|www\.\S+", " ", cleaned_text)

    for pattern, replacement in contraction_replacements.items():
        cleaned_text = re.sub(pattern, replacement, cleaned_text)

    for pattern, replacement in spelling_normalizations.items():
        cleaned_text = re.sub(pattern, replacement, cleaned_text)

    cleaned_text = re.sub(r"\bbr\b", " ", cleaned_text)
    cleaned_text = re.sub(r"\bvideoid\b", " ", cleaned_text)

    # Normalizing separators before phrase preservation so patterns like 
    # "return-window" and "blu-tooth" can still be captured.
    cleaned_text = re.sub(r"[-/]+", " ", cleaned_text)

    for pattern, replacement in phrase_replacements.items():
        cleaned_text = re.sub(pattern, replacement, cleaned_text)

    cleaned_text = re.sub(r"[~`]+", " ", cleaned_text)
    cleaned_text = re.sub(r"[^a-z0-9_\s]", " ", cleaned_text)
    cleaned_text = re.sub(r"\b[a-f0-9]{12,}\b", " ", cleaned_text)
    cleaned_text = re.sub(r"\b(?=\w*[a-z])(?=\w*\d)[a-z0-9_]{8,}\b", " ", cleaned_text)
    cleaned_text = re.sub(r"\b(?:amp|quot|nbsp)\b", " ", cleaned_text)
    cleaned_text = re.sub(r"\b\d{1,2}(?:st|nd|rd|th)\b", " ", cleaned_text)
    cleaned_text = re.sub(r"\b(?:year|month|day|week)s?\s+old\b", " ", cleaned_text)
    cleaned_text = re.sub(r"(?<![a-z_])\d+(?![a-z_])", " ", cleaned_text)
    cleaned_text = re.sub(r"\b[a-z]\b", " ", cleaned_text)
    cleaned_text = re.sub(r"\s+", " ", cleaned_text).strip()
    cleaned_text = collapse_repeated_tokens(cleaned_text, max_consecutive_repeats = 2)

    return cleaned_text

def build_modeling_text(text_value):
    if not text_value:
        return ""

    output_tokens = []

    for token in str(text_value).split():
        if token == review_boundary_token:
            output_tokens.append(review_boundary_token)
            continue

        token = token_normalization_map.get(token, token)

        if token.isdigit():
            continue

        if token in combined_stopwords:
            continue

        if token in protected_phrase_tokens:
            output_tokens.append(token)
            continue

        if len(token) >= 3 or token in short_technical_tokens:
            output_tokens.append(token)

    return " ".join(output_tokens)

diagnostic_sample_dataframe["modeling_text_clean"] = (
    diagnostic_sample_dataframe["aggregated_text_clean"]
    .fillna("")
    .apply(clean_electronics_review_text)
)

diagnostic_sample_dataframe["clean_word_count_preclip"] = (
    diagnostic_sample_dataframe["modeling_text_clean"].str.split().str.len()
)

clip_results = diagnostic_sample_dataframe["modeling_text_clean"].apply(
    lambda value: clip_text_balanced_by_review_boundaries(
        value,
        boundary_token = review_boundary_token,
        max_reviews = 120,
        min_reviews_to_clip = 140
    )
)

diagnostic_sample_dataframe["modeling_text_clipped"] = clip_results.apply(lambda value: value[0])
diagnostic_sample_dataframe["clipping_applied"] = clip_results.apply(lambda value: value[1])

diagnostic_sample_dataframe["modeling_text_for_vectorizer"] = (
    diagnostic_sample_dataframe["modeling_text_clipped"]
    .apply(build_modeling_text)
)

diagnostic_sample_dataframe["diagnostic_tokens"] = (
    diagnostic_sample_dataframe["modeling_text_for_vectorizer"]
    .apply(lambda value: [token for token in value.split() if token != review_boundary_token])
)

diagnostic_sample_dataframe["raw_word_count"] = (
    diagnostic_sample_dataframe["aggregated_text_clean"].str.split().str.len()
)

diagnostic_sample_dataframe["clean_word_count_postclip"] = (
    diagnostic_sample_dataframe["modeling_text_clipped"].str.split().str.len()
)

diagnostic_sample_dataframe["diagnostic_token_count"] = (
    diagnostic_sample_dataframe["diagnostic_tokens"].str.len()
)

diagnostic_sample_dataframe["unique_token_count"] = (
    diagnostic_sample_dataframe["diagnostic_tokens"].apply(lambda values: len(set(values)))
)

diagnostic_sample_dataframe["unique_token_ratio"] = (
    diagnostic_sample_dataframe["unique_token_count"] /
    diagnostic_sample_dataframe["diagnostic_token_count"].replace(0, np.nan)
)

diagnostic_sample_dataframe["cleaning_retention_ratio_preclip"] = (
    diagnostic_sample_dataframe["clean_word_count_preclip"] /
    diagnostic_sample_dataframe["raw_word_count"].replace(0, np.nan)
)

diagnostic_sample_dataframe["has_repeated_token_sequences"] = (
    diagnostic_sample_dataframe["modeling_text_clipped"]
    .apply(lambda value: bool(repeated_token_pattern.search(value)))
)

In [16]:
# Summarizing diagnostic quality checks for Electronics NLP documents

diagnostic_quality_summary_dataframe = pd.DataFrame({
    "metric": [
        "diagnostic_document_count",
        "blank_modeling_text_count",
        "documents_under_100_words_after_cleaning",
        "documents_under_50_diagnostic_tokens",
        "documents_with_repeated_token_sequences",
        "documents_with_cleaning_retention_ratio_below_0_40",
        "documents_with_unique_token_ratio_below_0_20",
        "documents_with_clipping_applied",
        "documents_with_br_after_cleaning",
        "documents_with_non_ascii_after_cleaning",
        "documents_with_no_signal_token",
        "documents_with_no_sound_token",
        "documents_with_no_power_token"
    ],
    "value": [
        len(diagnostic_sample_dataframe),
        diagnostic_sample_dataframe["modeling_text_clipped"].fillna("").str.strip().eq("").sum(),
        diagnostic_sample_dataframe["clean_word_count_postclip"].lt(100).sum(),
        diagnostic_sample_dataframe["diagnostic_token_count"].lt(50).sum(),
        diagnostic_sample_dataframe["has_repeated_token_sequences"].sum(),
        diagnostic_sample_dataframe["cleaning_retention_ratio_preclip"].lt(0.40).sum(),
        diagnostic_sample_dataframe["unique_token_ratio"].lt(0.20).sum(),
        diagnostic_sample_dataframe["clipping_applied"].sum(),
        diagnostic_sample_dataframe["modeling_text_clipped"].str.contains(r"\bbr\b", regex = True, na = False).sum(),
        diagnostic_sample_dataframe["modeling_text_clipped"].str.contains(r"[^\x00-\x7F]", regex = True, na = False).sum(),
        diagnostic_sample_dataframe["modeling_text_clipped"].str.contains(r"\bno_signal\b", regex = True, na = False).sum(),
        diagnostic_sample_dataframe["modeling_text_clipped"].str.contains(r"\bno_sound\b", regex = True, na = False).sum(),
        diagnostic_sample_dataframe["modeling_text_clipped"].str.contains(r"\bno_power\b", regex = True, na = False).sum()
    ]
})

phrase_validation_tokens = [
    "does_not_work",
    "did_not_work",
    "stopped_working",
    "battery_life",
    "customer_service",
    "return_window",
    "late_delivery",
    "false_advertising",
    "not_charging",
    "not_connecting",
    "not_compatible",
    "poor_quality",
    "no_signal",
    "no_sound",
    "no_power"
]

phrase_validation_rows = []

for token_value in phrase_validation_tokens:
    phrase_validation_rows.append({
        "token": token_value,
        "document_count": diagnostic_sample_dataframe["modeling_text_for_vectorizer"]
            .str.contains(rf"\b{re.escape(token_value)}\b", regex = True, na = False)
            .sum()
    })

phrase_validation_dataframe = pd.DataFrame(phrase_validation_rows).sort_values(
    by = "document_count",
    ascending = False
)


all_diagnostic_tokens = [
    token
    for token_list in diagnostic_sample_dataframe["diagnostic_tokens"]
    for token in token_list
]

overall_top_tokens_dataframe = pd.DataFrame(
    Counter(all_diagnostic_tokens).most_common(100),
    columns = ["token", "frequency"]
)

vectorizer = CountVectorizer(
    lowercase = False,
    stop_words = None,
    token_pattern = r"(?u)\b[a-z_][a-z0-9_]{2,}\b",
    ngram_range = (1, 2),
    min_df = 10
)

document_term_matrix = vectorizer.fit_transform(
    diagnostic_sample_dataframe["modeling_text_for_vectorizer"]
)

terms = np.array(vectorizer.get_feature_names_out())
valid_feature_mask = np.array([review_boundary_token not in term for term in terms])

document_term_matrix = document_term_matrix[ : , valid_feature_mask]
terms = terms[valid_feature_mask]

dissatisfaction_mask = diagnostic_sample_dataframe["analysis_pool_role"].eq("Topic modeling target").to_numpy()
satisfaction_mask = diagnostic_sample_dataframe["analysis_pool_role"].eq("Comparison baseline").to_numpy()

dissatisfaction_document_frequency = np.asarray(
    (document_term_matrix[dissatisfaction_mask] > 0).sum(axis = 0)
).ravel()

satisfaction_document_frequency = np.asarray(
    (document_term_matrix[satisfaction_mask] > 0).sum(axis = 0)
).ravel()

dissatisfaction_document_count = dissatisfaction_mask.sum()
satisfaction_document_count = satisfaction_mask.sum()

token_lift_dataframe = pd.DataFrame({
    "token_or_phrase": terms,
    "dissatisfaction_document_frequency": dissatisfaction_document_frequency,
    "dissatisfaction_document_frequency_ratio": dissatisfaction_document_frequency / dissatisfaction_document_count,
    "satisfaction_document_frequency": satisfaction_document_frequency,
    "satisfaction_document_frequency_ratio": satisfaction_document_frequency / satisfaction_document_count
})

token_lift_dataframe["dissatisfaction_vs_satisfaction_ratio"] = (
    (token_lift_dataframe["dissatisfaction_document_frequency_ratio"] + 1e-6) /
    (token_lift_dataframe["satisfaction_document_frequency_ratio"] + 1e-6)
)

token_lift_dataframe["absolute_ratio_gap"] = (
    token_lift_dataframe["dissatisfaction_document_frequency_ratio"] -
    token_lift_dataframe["satisfaction_document_frequency_ratio"]
)

differential_topic_terms_dataframe = (
    token_lift_dataframe
    .query("dissatisfaction_document_frequency >= 25 and satisfaction_document_frequency >= 5")
    .sort_values(
        by = ["dissatisfaction_vs_satisfaction_ratio", "absolute_ratio_gap"],
        ascending = [False, False]
    )
    .reset_index(drop = True)
)

generic_top_terms_dataframe = (
    token_lift_dataframe
    .sort_values(
        by = ["dissatisfaction_document_frequency_ratio", "satisfaction_document_frequency_ratio"],
        ascending = [False, False]
    )
    .reset_index(drop = True)
)

display(diagnostic_quality_summary_dataframe)
display(phrase_validation_dataframe)
display(overall_top_tokens_dataframe.head(80))
display(differential_topic_terms_dataframe.head(120))
display(generic_top_terms_dataframe.head(120))

                                               metric  value
0                           diagnostic_document_count   7200
1                           blank_modeling_text_count      0
2            documents_under_100_words_after_cleaning      0
3                documents_under_50_diagnostic_tokens      0
4             documents_with_repeated_token_sequences      0
5   documents_with_cleaning_retention_ratio_below_...      0
6        documents_with_unique_token_ratio_below_0_20      0
7                     documents_with_clipping_applied   2474
8                    documents_with_br_after_cleaning      0
9             documents_with_non_ascii_after_cleaning      0
10                     documents_with_no_signal_token    434
11                      documents_with_no_sound_token    906
12                      documents_with_no_power_token    594

                token  document_count
1        did_not_work            4057
0       does_not_work            4010
2     stopped_working            3543
4    customer_service            3536
5       return_window            2060
3        battery_life            1917
11       poor_quality            1770
10     not_compatible            1223
8        not_charging             918
13           no_sound             906
14           no_power             594
9      not_connecting             482
12          no_signal             434
7   false_advertising             429
6       late_delivery              40

              token  frequency
0              work     232130
1               try      68661
2            bought      66587
3            camera      63889
4            charge      60858
5             sound      56073
6            return      55402
7               buy      53005
8             cable      52279
9             phone      51165
10          quality      48437
11            price      48406
12          connect      47026
13             case      45752
14          battery      42754
15               tv      38779
16           screen      35420
17          install      34316
18           amazon      33449
19        headphone      33298
20          speaker      32218
21            setup      31634
22         computer      30547
23           laptop      30358
24         keyboard      29667
25        purchased      29314
26              usb      28487
27          monitor      28484
28            mouse      28218
29          problem      27908
30            power      27900
31              fit      26421
32         purchase      24998
33             pair      24848
34             unit      24182
35           router      23821
36            issue      23707
37              ear      23320
38              box      23107
39             came      23086
40           issues      22765
41            light      22601
42              bad      21958
43          replace      21705
44            drive      21252
45           remote      20853
46     disappointed      20771
47             wifi      20520
48            watch      20413
49             cord      20230
50            music      20222
51        bluetooth      20167
52  stopped_working      20033
53              app      19816
54       connection      19735
55            video      19648
56             ipad      19529
57    sound_quality      19279
58            cheap      18759
59    does_not_work      18394
60      replacement      18109
61             plug      17865
62           volume      17484
63             hard      17419
64             turn      17291
65             fast      17007
66           update      16750
67         received      16641
68          support      16306
69     did_not_work      16278
70          thought      16149
71             went      16091
72            audio      16070
73            brand      15915
74          charger      15714
75           longer      15689
76         wireless      15440
77          ordered      15343
78            broke      15343
79          plugged      15044

,token_or_phrase,dissatisfaction_document_frequency,dissatisfaction_document_frequency_ratio,satisfaction_document_frequency,satisfaction_document_frequency_ratio,dissatisfaction_vs_satisfaction_ratio,absolute_ratio_gap
0,total waste_money,568,0.157778,7,0.001944,81.101662,0.155833
1,missed return_window,363,0.100833,5,0.001389,72.548485,0.099444
2,wish return,553,0.153611,9,0.002500,61.420276,0.151111
3,complete waste_money,555,0.154167,10,0.002778,55.480387,0.151389
4,super disappointed,328,0.091111,6,0.001667,54.634486,0.089444
5,disappointed return,371,0.103056,7,0.001944,52.973271,0.101111
6,complete waste,260,0.072222,5,0.001389,51.963306,0.070833
7,terrible quality,305,0.084722,6,0.001667,50.803451,0.083056
8,definitely not_worth,301,0.083611,6,0.001667,50.137184,0.081944
9,huge disappointment,236,0.065556,5,0.001389,47.166760,0.064167
10,outside return_window,417,0.115833,9,0.002500,46.315207,0.113333
11,window return,360,0.100000,8,0.002222,44.980209,0.097778
12,stopped_working return,300,0.083333,7,0.001944,42.835627,0.081389
13,work waste,337,0.093611,8,0.002222,42.106502,0.091389
14,late return,838,0.232778,20,0.005556,41.892639,0.227222
15,returnable,245,0.068056,6,0.001667,40.809448,0.066389
16,simply does_not_work,224,0.062222,6,0.001667,37.311546,0.060556
17,waste_money buy,255,0.070833,7,0.001944,36.410360,0.068889
18,not_worth buying,214,0.059444,6,0.001667,35.645879,0.057778
19,pay return,245,0.068056,7,0.001944,34.982523,0.066111
20,try contacting,210,0.058333,6,0.001667,34.979612,0.056667
21,return refund,1237,0.343611,36,0.010000,34.357775,0.333611
22,poor customer_service,203,0.056389,6,0.001667,33.813645,0.054722
23,extremely disappointed,642,0.178333,19,0.005278,33.783262,0.173056
24,buyer beware,1077,0.299167,32,0.008889,33.652577,0.290278
25,try troubleshooting,202,0.056111,6,0.001667,33.647078,0.054444
26,return period,639,0.177500,19,0.005278,33.625397,0.172222
27,junk buy,268,0.074444,8,0.002222,33.485382,0.072222
28,totally useless,260,0.072222,8,0.002222,32.485831,0.070000
29,complete garbage,259,0.071944,8,0.002222,32.360888,0.069722
30,rendering useless,160,0.044444,5,0.001389,31.977696,0.043056
31,stopped_working try,383,0.106389,12,0.003333,31.907394,0.103056
32,total waste,286,0.079444,9,0.002500,31.765472,0.076944
33,likely return,158,0.043889,5,0.001389,31.577984,0.042500
34,stopped_working disappointed,189,0.052500,6,0.001667,31.481711,0.050833
35,accept return,156,0.043333,5,0.001389,31.178272,0.041944
36,work disappointing,155,0.043056,5,0.001389,30.978416,0.041667
37,stopped_working altogether,216,0.060000,7,0.001944,30.841796,0.058056
38,buy waste_money,153,0.042500,5,0.001389,30.578703,0.041111
39,dont waste,367,0.101944,12,0.003333,30.574461,0.098611
40,absolute garbage,366,0.101667,12,0.003333,30.491153,0.098333
41,refund buy,151,0.041944,5,0.001389,30.178991,0.040556
42,return buying,209,0.058056,7,0.001944,29.842310,0.056111
43,return_window closed,893,0.248056,30,0.008333,29.763215,0.239722
44,waste buy,238,0.066111,8,0.002222,29.737068,0.063889
45,completely unusable,208,0.057778,7,0.001944,29.699526,0.055833
46,completely stopped_working,473,0.131389,16,0.004444,29.556075,0.126944
47,not_worth return,236,0.065556,8,0.002222,29.487181,0.063333
48,piece junk,1261,0.350278,43,0.011944,29.323210,0.338333
49,did_not_work box,321,0.089167,11,0.003056,29.172598,0.086111
50,stopped_working buy,230,0.063889,8,0.002222,28.737518,0.061667
51,return return,309,0.085833,11,0.003056,28.082046,0.082778
52,buy risk,140,0.038889,5,0.001389,27.980574,0.037500
53,stopped_working completely,390,0.108333,14,0.003889,27.850239,0.104444
54,let return,194,0.053889,7,0.001944,27.700554,0.051944
55,maybe defective,192,0.053333,7,0.001944,27.414987,0.051389
56,false advertisement,137,0.038056,5,0.001389,27.381006,0.036667
57,piece garbage,464,0.128889,17,0.004722,27.288551,0.124167
58,gave return,136,0.037778,5,0.001389,27.181150,0.036389
59,waste_money,2710,0.752778,100,0.027778,27.099060,0.725000
60,paper weight,324,0.090000,12,0.003333,26.992202,0.086667
61,terrible customer_service,162,0.045000,6,0.001667,26.984409,0.043333
62,help return,135,0.037500,5,0.001389,26.981293,0.036111
63,past return,509,0.141389,19,0.005278,26.784588,0.136111
64,paperweight,453,0.125833,17,0.004722,26.641629,0.121111
65,stopped_working purchase,212,0.058889,8,0.002222,26.488530,0.056667
66,amazon refund,316,0.087778,12,0.003333,26.325736,0.084444
67,junk work,184,0.051111,7,0.001944,26.272717,0.049167
68,threw trash,184,0.051111,7,0.001944,26.272717,0.049167
69,amazon return_window,182,0.050556,7,0.001944,25.987149,0.048611
70,buyers beware,155,0.043056,6,0.001667,25.818442,0.041389
71,false_advertising,413,0.114722,16,0.004444,25.806918,0.110278
72,return pay,129,0.035833,5,0.001389,25.782157,0.034444
73,lasted stopped_working,206,0.057222,8,0.002222,25.738868,0.055000
74,not_worth price,463,0.128611,18,0.005000,25.717279,0.123611
75,wont turn,128,0.035556,5,0.001389,25.582301,0.034167
76,recourse,127,0.035278,5,0.001389,25.382445,0.033889
77,pay guess,152,0.042222,6,0.001667,25.318742,0.040556
78,return date,656,0.182222,26,0.007222,25.227415,0.175000
79,ashamed,176,0.048889,7,0.001944,25.130447,0.046944
80,return_window,1981,0.550278,79,0.021944,25.074852,0.528333
81,return soon,150,0.041667,6,0.001667,24.985609,0.040000
82,try trouble,125,0.034722,5,0.001389,24.982732,0.033333
83,quality terrible,174,0.048333,7,0.001944,24.844880,0.046389
84,insult,149,0.041389,6,0.001667,24.819042,0.039722
85,inoperable,124,0.034444,5,0.001389,24.782876,0.033056
86,extremely disappointing,122,0.033889,5,0.001389,24.383164,0.032500
87,wish read,169,0.046944,7,0.001944,24.130961,0.045000
88,completely useless,555,0.154167,23,0.006389,24.126815,0.147778
89,work stopped,407,0.113056,17,0.004722,23.936319,0.108333
90,sorry bought,118,0.032778,5,0.001389,23.583740,0.031389
91,horrendous,211,0.058611,9,0.002500,23.435470,0.056111
92,seller response,117,0.032500,5,0.001389,23.383884,0.031111
93,absolute trash,140,0.038889,6,0.001667,23.319941,0.037222
94,connect return,140,0.038889,6,0.001667,23.319941,0.037222
95,eligible,256,0.071111,11,0.003056,23.265440,0.068056
96,guess pay,531,0.147500,23,0.006389,23.083500,0.141111
97,work suddenly,252,0.070000,11,0.003056,22.901923,0.066944
98,try contact,480,0.133333,21,0.005833,22.853397,0.127500
99,sound_quality terrible,226,0.062778,10,0.002778,22.592227,0.060000
100,piece crap,788,0.218889,35,0.009722,22.512073,0.209167
101,connection constantly,112,0.031111,5,0.001389,22.384603,0.029722
102,completely died,223,0.061944,10,0.002778,22.292335,0.059167
103,plan return,111,0.030833,5,0.001389,22.184747,0.029444
104,exact issue,133,0.036944,6,0.001667,22.153974,0.035278
105,told return,133,0.036944,6,0.001667,22.153974,0.035278
106,multiple attempts,154,0.042778,7,0.001944,21.989206,0.040833
107,ups store,132,0.036667,6,0.001667,21.987408,0.035000
108,did_not_work connect,110,0.030556,5,0.001389,21.984891,0.029167
109,extremely slow,219,0.060833,10,0.002778,21.892479,0.058056
110,bad quality,503,0.139722,23,0.006389,21.866299,0.133333
111,return buy,481,0.133611,22,0.006111,21.860223,0.127500
112,charge disappointed,153,0.042500,7,0.001944,21.846422,0.040556
113,bother return,131,0.036389,6,0.001667,21.820841,0.034722
114,does_not_work connect,131,0.036389,6,0.001667,21.820841,0.034722
115,not_as_described,131,0.036389,6,0.001667,21.820841,0.034722
116,save hassle,131,0.036389,6,0.001667,21.820841,0.034722
117,probably return,218,0.060556,10,0.002778,21.792515,0.057778
118,will_not_turn_on,562,0.156111,26,0.007222,21.612531,0.148889
119,started making,216,0.060000,10,0.002778,21.592587,0.057222

,token_or_phrase,dissatisfaction_document_frequency,dissatisfaction_document_frequency_ratio,satisfaction_document_frequency,satisfaction_document_frequency_ratio,dissatisfaction_vs_satisfaction_ratio,absolute_ratio_gap
0,return,3588,0.996667,1893,0.525833,1.895402,0.470833
1,work,3585,0.995833,3588,0.996667,0.999164,-0.000833
2,bought,3570,0.991667,3525,0.979167,1.012766,0.012500
3,try,3562,0.989444,3072,0.853333,1.159505,0.136111
4,buy,3552,0.986667,3433,0.953611,1.034664,0.033056
5,disappointed,3418,0.949444,1473,0.409167,2.320431,0.540278
6,purchased,3387,0.940833,3156,0.876667,1.073194,0.064167
7,amazon,3339,0.927500,2526,0.701667,1.321852,0.225833
8,bad,3320,0.922222,2230,0.619444,1.488788,0.302778
9,quality,3295,0.915278,3365,0.934722,0.979198,-0.019444
10,came,3223,0.895278,2980,0.827778,1.081544,0.067500
11,purchase,3211,0.891944,3225,0.895833,0.995659,-0.003889
12,thought,3204,0.890000,2388,0.663333,1.341708,0.226667
13,received,3181,0.883611,2214,0.615000,1.436765,0.268611
14,waste,3145,0.873611,384,0.106667,8.190037,0.766944
15,problem,3139,0.871944,2900,0.805556,1.082414,0.066389
16,does_not_work,3126,0.868333,884,0.245556,3.536189,0.622778
17,went,3085,0.856944,2150,0.597222,1.434883,0.259722
18,price,3041,0.844722,3508,0.974444,0.866876,-0.129722
19,cheap,3032,0.842222,2225,0.618056,1.362696,0.224167
20,did_not_work,3027,0.840833,1030,0.286111,2.938828,0.554722
21,ordered,3023,0.839722,2503,0.695278,1.207750,0.144444
22,replace,3020,0.838889,2517,0.699167,1.199841,0.139722
23,brand,3000,0.833333,2053,0.570278,1.461275,0.263056
24,completely,2998,0.832778,1474,0.409444,2.033919,0.423333
25,maybe,2979,0.827500,1745,0.484722,1.707162,0.342778
26,started,2967,0.824167,1565,0.434722,1.895845,0.389444
27,buying,2964,0.823333,2313,0.642500,1.281452,0.180833
28,box,2947,0.818611,2358,0.655000,1.249788,0.163611
29,said,2941,0.816944,2238,0.621667,1.314119,0.195278
30,issue,2934,0.815000,2557,0.710278,1.147438,0.104722
31,longer,2934,0.815000,2212,0.614444,1.326401,0.200556
32,come,2898,0.805000,2508,0.696667,1.155502,0.108333
33,unfortunately,2898,0.805000,1016,0.282222,2.852356,0.522778
34,couple,2884,0.801111,2367,0.657500,1.218420,0.143611
35,replacement,2874,0.798333,1831,0.508611,1.569633,0.289722
36,useless,2872,0.797778,491,0.136389,5.849252,0.661389
37,refund,2871,0.797500,334,0.092778,8.595727,0.704722
38,hard,2864,0.795556,2531,0.703056,1.131568,0.092500
39,connect,2854,0.792778,2452,0.681111,1.163948,0.111667
40,not_worth,2804,0.778889,229,0.063611,12.244365,0.715278
41,sent,2793,0.775833,1269,0.352500,2.200942,0.423333
42,piece,2785,0.773611,1514,0.420556,1.839496,0.353056
43,terrible,2778,0.771667,578,0.160556,4.806205,0.611111
44,took,2752,0.764444,2511,0.697500,1.095978,0.066944
45,stopped_working,2746,0.762778,797,0.221389,3.445409,0.541389
46,reason,2717,0.754722,1868,0.518889,1.454496,0.235833
47,stay,2716,0.754444,1301,0.361389,2.087622,0.393056
48,waste_money,2710,0.752778,100,0.027778,27.099060,0.725000
49,junk,2704,0.751111,308,0.085556,8.779130,0.665556
50,order,2698,0.749444,2159,0.599722,1.249652,0.149722
51,guess,2690,0.747222,1148,0.318889,2.343201,0.428333
52,pay,2683,0.745278,1440,0.400000,1.863192,0.345278
53,broke,2654,0.737222,1154,0.320556,2.299823,0.416667
54,end,2647,0.735278,2079,0.577500,1.273208,0.157778
55,minutes,2643,0.734167,1749,0.485833,1.511148,0.248333
56,send,2637,0.732500,984,0.273333,2.679872,0.459167
57,half,2631,0.730833,1408,0.391111,1.868606,0.339722
58,issues,2628,0.730000,2823,0.784167,0.930925,-0.054167
59,says,2626,0.729444,1538,0.427222,1.707411,0.302222
60,company,2624,0.728889,1560,0.433333,1.682050,0.295556
61,ago,2623,0.728611,1848,0.513333,1.419371,0.215278
62,poor,2612,0.725556,719,0.199722,3.632810,0.525833
63,update,2589,0.719167,2071,0.575278,1.250120,0.143889
64,later,2563,0.711944,1385,0.384722,1.850539,0.327222
65,horrible,2559,0.710833,418,0.116111,6.121965,0.594722
66,garbage,2550,0.708333,238,0.066111,10.714139,0.642222
67,point,2547,0.707500,1986,0.551667,1.282477,0.155833
68,instead,2542,0.706111,1960,0.544444,1.296938,0.161667
69,wrong,2540,0.705556,1770,0.491667,1.435027,0.213889
70,properly,2527,0.701944,1152,0.320000,2.193573,0.381944
71,defective,2521,0.700278,472,0.131111,5.341069,0.569167
72,broken,2510,0.697222,884,0.245556,2.839359,0.451667
73,light,2509,0.696944,2364,0.656667,1.061337,0.040278
74,wish,2508,0.696667,2569,0.713611,0.976255,-0.016944
75,gave,2504,0.695556,1842,0.511667,1.359391,0.183889
76,power,2486,0.690556,2174,0.603889,1.143514,0.086667
77,phone,2485,0.690278,2202,0.611667,1.128519,0.078611
78,read,2481,0.689167,2041,0.566944,1.215580,0.122222
79,case,2476,0.687778,2410,0.669444,1.027386,0.018333
80,save,2462,0.683889,1168,0.324444,2.107873,0.359444
81,probably,2447,0.679722,2084,0.578889,1.174184,0.100833
82,hold,2446,0.679444,1905,0.529167,1.283989,0.150278
83,short,2446,0.679444,1695,0.470833,1.443067,0.208611
84,turn,2440,0.677778,1914,0.531667,1.274817,0.146111
85,help,2438,0.677222,1831,0.508611,1.331512,0.168611
86,left,2436,0.676667,1629,0.452500,1.495395,0.224167
87,definitely,2431,0.675278,3016,0.837778,0.806035,-0.162500
88,star,2412,0.670000,1564,0.434444,1.542198,0.235556
89,unless,2403,0.667500,1128,0.313333,2.130316,0.354167
90,finally,2394,0.665000,1816,0.504444,1.318281,0.160556
91,lasted,2379,0.660833,1012,0.281111,2.350786,0.379722
92,kept,2377,0.660278,1202,0.333889,1.977535,0.326389
93,disappointing,2359,0.655278,291,0.080833,8.106441,0.574444
94,multiple,2358,0.655000,1599,0.444167,1.474671,0.210833
95,extremely,2357,0.654722,1934,0.537222,1.218717,0.117500
96,expected,2352,0.653333,2904,0.806667,0.809918,-0.153333
97,today,2341,0.650278,1221,0.339167,1.917278,0.311111
98,comes,2337,0.649167,2542,0.706111,0.919355,-0.056944
99,connection,2327,0.646389,1744,0.484444,1.334288,0.161944
100,plug,2319,0.644167,1980,0.550000,1.171212,0.094167
101,start,2319,0.644167,1533,0.425833,1.512719,0.218333
102,super,2310,0.641667,2897,0.804722,0.797377,-0.163056
103,let,2301,0.639167,1749,0.485833,1.315608,0.153333
104,support,2283,0.634167,1331,0.369722,1.715250,0.264444
105,place,2277,0.632500,2049,0.569167,1.111274,0.063333
106,cable,2275,0.631944,2117,0.588056,1.074634,0.043889
107,stop,2273,0.631389,1073,0.298056,2.118356,0.333333
108,plugged,2271,0.630833,1528,0.424444,1.486255,0.206389
109,goes,2270,0.630556,1622,0.450556,1.399506,0.180000
110,past,2266,0.629444,1437,0.399167,1.576895,0.230278
111,feel,2259,0.627500,2396,0.665556,0.942821,-0.038056
112,spend,2259,0.627500,1235,0.343056,1.829147,0.284444
113,unit,2253,0.625833,1799,0.499722,1.252362,0.126111
114,constantly,2252,0.625556,961,0.266944,2.343387,0.358611
115,seller,2242,0.622778,1297,0.360278,1.728602,0.262500
116,problems,2241,0.622500,2517,0.699167,0.890346,-0.076667
117,charge,2240,0.622222,1825,0.506944,1.227397,0.115278
118,worst,2224,0.617778,267,0.074167,8.329489,0.543611
119,arrived,2222,0.617222,2166,0.601667,1.025854,0.015556

In [17]:
# Creating a balanced Electronics NLP sample for exploratory diagnostics and validation

sample_modeling_dataframe = diagnostic_sample_dataframe.loc[
    diagnostic_sample_dataframe["modeling_text_for_vectorizer"].fillna("").str.strip().ne("")
].copy()

sample_modeling_dataframe["is_dissatisfaction"] = (
    sample_modeling_dataframe["analysis_pool_role"] == "Topic modeling target"
)

print(f"Sample documents for pilot modeling : {len(sample_modeling_dataframe):,}")
print(f"Dissatisfaction documents : {sample_modeling_dataframe['is_dissatisfaction'].sum():,}")
print(f"Comparison baseline documents : {(~sample_modeling_dataframe['is_dissatisfaction']).sum():,}")

Sample documents for pilot modeling : 7,200
Dissatisfaction documents : 3,600
Comparison baseline documents : 3,600

In [18]:
# Creating dissatisfaction-focused Electronics review samples for issue-theme exploration

dissatisfaction_sample_dataframe = sample_modeling_dataframe.loc[
    sample_modeling_dataframe["is_dissatisfaction"]
].copy()

tfidf_vectorizer = TfidfVectorizer(
    lowercase = False,
    stop_words = None,
    token_pattern = r"(?u)\b[a-z_][a-z0-9_]{2,}\b",
    ngram_range = (1, 2),
    min_df = 15,
    max_df = 0.35,
    max_features = 20000,
    sublinear_tf = True
)

dissatisfaction_tfidf_matrix = tfidf_vectorizer.fit_transform(
    dissatisfaction_sample_dataframe["modeling_text_for_vectorizer"]
)

topic_count = 12

nmf_model = NMF(
    n_components = topic_count,
    init = "nndsvda",
    random_state = 42,
    max_iter = 400
)

dissatisfaction_topic_matrix = nmf_model.fit_transform(dissatisfaction_tfidf_matrix)
topic_term_matrix = nmf_model.components_
feature_names = np.array(tfidf_vectorizer.get_feature_names_out())

top_term_count = 15
topic_rows = []

for topic_index, topic_weights in enumerate(topic_term_matrix):
    top_term_indices = topic_weights.argsort()[ : : -1][ : top_term_count]
    topic_rows.append({
        "topic_id": topic_index,
        "top_terms": ", ".join(feature_names[top_term_indices])
    })

sample_topic_terms_dataframe = pd.DataFrame(topic_rows)
display(sample_topic_terms_dataframe)

    topic_id                                          top_terms
0          0  router, wifi, network, netgear, modem, interne...
1          1  ear, headphone, earbuds, ears, buds, earbud, s...
2          2  review_boundary case, screen_protector, ipad, ...
3          3  chargers, charge phone, review_boundary cable,...
4          4  drive, drives, files, hard_drive, disk, window...
5          5  sound_quality, radio, music, bass, bluetooth, ...
6          6  camera, review_boundary camera, camera work, c...
7          7  mouse, keyboard, review_boundary mouse, keys, ...
8          8  hdmi, monitor, hdmi cable, display, four_k, hd...
9          9  fitbit, watch, review_boundary watch, heart ra...
10        10  screws, mount, screw, tighten, bracket, mounti...
11        11  antenna, channels, stations, reception, channe...

In [19]:
# Resetting dissatisfaction sample indexing for downstream processing consistency

dissatisfaction_sample_dataframe = dissatisfaction_sample_dataframe.reset_index(drop = True)

document_topic_assignment = dissatisfaction_topic_matrix.argmax(axis = 1)
document_topic_strength = dissatisfaction_topic_matrix.max(axis = 1)

dissatisfaction_sample_dataframe["topic_id"] = document_topic_assignment
dissatisfaction_sample_dataframe["topic_strength"] = document_topic_strength

representative_topic_documents_dataframe = (
    dissatisfaction_sample_dataframe[
        [
            "topic_id",
            "topic_strength",
            "price_band",
            "issue_priority_level",
            "product_display_name",
            "sampled_review_count",
            "modeling_text_for_vectorizer"
        ]
    ]
    .sort_values(["topic_id", "topic_strength"], ascending = [True, False])
    .groupby("topic_id", group_keys = False)
    .head(5)
    .reset_index(drop = True)
)

display(representative_topic_documents_dataframe)

,topic_id,topic_strength,price_band,issue_priority_level,product_display_name,sampled_review_count,modeling_text_for_vectorizer
0,0,0.147679,Very premium,Monitor,NETGEAR Nighthawk X6 Smart Wi-Fi Router (R8000...,250,pile scrap simplest activities router pass dns...
1,0,0.147193,Very premium,Monitor,NETGEAR Nighthawk X6 Smart Wi-Fi Router (R8000...,250,router cheapo linksys bought powerful router v...
2,0,0.144883,Premium,Monitor,NETGEAR Nighthawk Smart WiFi Router (R7000P) -...,250,drops signal constantly bad outside close yard...
3,0,0.143458,Very premium,Monitor,NETGEAR Orbi Whole Home Tri-band Mesh WiFi 6 S...,250,update2 replacement work satellite stopped_wor...
4,0,0.141907,Very premium,Monitor,NETGEAR Orbi Whole Home Tri-band Mesh WiFi 6 S...,250,bought linksys usb port clearly stated work ce...
5,1,0.202116,Upper mid,Monitor,TOZO NC2 Hybrid Active Noise Cancelling Wirele...,250,work ago earbuds cut watching listening music ...
6,1,0.201013,Upper mid,Monitor,TOZO NC2 Hybrid Active Noise Cancelling Wirele...,140,expecting charge case average size compared no...
7,1,0.199576,Premium,Priority review,Sony WF-SP800N Truly Wireless Sports In-Ear No...,121,sound_quality earpiece left earpiece try earpi...
8,1,0.196052,Lower mid,Monitor,TOZO T10 Bluetooth 5.3 Wireless Earbuds with W...,250,ear synced piece work try resetting saved box ...
9,1,0.194319,Lower mid,Monitor,TOZO T10 Bluetooth 5.3 Wireless Earbuds with W...,250,sound_quality okay lifespan short left earbud ...
10,2,0.224704,Lower mid,Priority review,MOSISO Compatible with MacBook Air 13 inch Cas...,250,bought edges case started cracking rarely lapt...
11,2,0.221318,Upper mid,Priority review,MOSISO Compatible with MacBook Pro 15 inch Cas...,123,clip not_fit properly section review_boundary ...
12,2,0.220285,Lower mid,Priority review,MOSISO Compatible with MacBook Pro 13 inch Cas...,250,stay computer review_boundary ugly scratched b...
13,2,0.213344,Lower mid,Priority review,IBENZER Compatible with New MacBook Air 13 inc...,250,today applied screen_protector case notice com...
14,2,0.211918,Lower mid,Priority review,MOSISO Compatible with MacBook Air 13 inch Cas...,250,received deep scratches case packaging ripped ...
15,3,0.226256,Budget,Priority review,APFEN [3-Pack] 6FT/2M iPhone Gaming Charger Ca...,250,awful stopped_working response seller review_b...
16,3,0.226039,Budget,Priority review,"iPhone Charger, Lightning Cable, 5Pack 3FT Pho...",250,awful single cord bent unable plugged usb bric...
17,3,0.225858,Lower mid,Priority review,FEEL2NICE iPhone Charger Cable [MFi Certified]...,250,chargers review_boundary feel cheap mistake re...
18,3,0.225615,Budget,Monitor,JSAUX USB-C to USB A Cable 3.1A Fast Charging ...,250,cord randomly stopped_working super disappoint...
19,3,0.225340,Budget,Priority review,Atill iPhone Charger 9FT iPhone Charger Cable ...,124,stop work couple review_boundary total garbage...
20,4,0.214639,Upper mid,Monitor,Western Digital 500GB WD Blue SA510 SATA Inter...,250,purchased 1tb nand ssd gaming rig performance ...
21,4,0.214458,Very premium,Monitor,Seagate Backup Plus Portable 5TB External Hard...,250,quit work review_boundary work review_boundary...
22,4,0.213820,Very premium,Monitor,Seagate Backup Plus Portable 5TB External Hard...,250,seagate seagate crashed died expired seagate b...
23,4,0.212482,Upper mid,Monitor,"WD 2TB Elements Portable HDD, External Hard Dr...",250,work figured issues cable seat properly comput...
24,4,0.212016,Very premium,Monitor,Seagate Backup Plus Portable 5TB External Hard...,250,bought couple hard drives seagate unfortunatel...
25,5,0.186559,Upper mid,Monitor,"TEWELL Computer Speaker, HD 24W Audio Vintage ...",109,stylish echo dot sounds nope shocked flat rela...
26,5,0.182936,Premium,Monitor,Edifier R1700BT Bluetooth Bookshelf Speakers -...,122,speaker sound price point issues buy bluetooth...
27,5,0.174080,Premium,Priority review,Acoustic Audio AA5171 5.1 Surround Sound Bluet...,184,business playing moderate volume heard crackle...
28,5,0.171515,Premium,Priority review,Pyle Bluetooth Boombox Street Blaster Stereo S...,180,quit connect customer_service worthless lots e...
29,5,0.165785,Premium,Monitor,Cyber Acoustics CA-3908 2.1 Stereo Speaker Sys...,87,admit speaker sound awesome quite improvement ...
30,6,0.217548,Premium,Priority review,Blink Whole Home Bundle | Video Doorbell Syste...,250,hopes letdown harsh poor optics class security...
31,6,0.213230,Premium,Priority review,Blink Whole Home Bundle | Video Doorbell Syste...,250,ticked amazon requires monthly plan observe mo...
32,6,0.210610,Premium,Priority review,Blink Whole Home Bundle | Video Doorbell Syste...,250,video clear bright daytime camera night guess ...
33,6,0.208040,Premium,Priority review,Blink Mini – Compact indoor plug-in smart secu...,250,camera work 2hrs not_working review_boundary p...
34,6,0.207873,Premium,Priority review,Blink Whole Home Bundle | Video Doorbell Syste...,250,app does_not_work matter support steps review_...
35,7,0.241851,Premium,Monitor,Logitech MK710 Wireless Keyboard and Mouse Com...,250,ergonomic design poor hand wrist supports keyb...
36,7,0.235880,Upper mid,Priority review,"Wireless Keyboard and Mouse,J JOYACCESS 2.4G E...",250,exchange twice key keyboard does_not_work frus...
37,7,0.234283,Lower mid,Priority review,Eagletec K104 Wireless Keyboard and Mouse Comb...,250,bought wireless keyboard work spent couple dol...
38,7,0.233871,Upper mid,Monitor,iClever GK03 Wireless Keyboard and Mouse Combo...,204,battery keyboard mouse layout compact bad keyb...
39,7,0.232397,Lower mid,Priority review,"Wireless Keyboard Mouse Combo, cimetech Compac...",236,cheap bad review_boundary mouse stopped_workin...
40,8,0.175674,Upper mid,Monitor,Amazon Basics 5-Pack DisplayPort to HDMI Displ...,151,frayed spot plugs phone particularly rough mov...
41,8,0.174915,Very premium,Monitor,Dell Ultra HD 4K Monitor P2415Q 24-Inch Screen...,175,remotely standards dell higher end monitor cos...
42,8,0.174618,Very premium,Monitor,"PHILIPS 322E1C 32"" Super-Curved Frameless Moni...",95,decent four_k curved monitor text editing swit...
43,8,0.173960,Budget,Priority review,HDMI Splitter Adapter Cable - HDMI Splitter 1 ...,236,did_not_work audio complete garbage enemy revi...
44,8,0.173141,Lower mid,Priority review,"StarTech.com DVI I to DVI D and VGA Splitter, ...",153,split signal signal weak issues screens cuttin...
45,9,0.293959,Premium,Priority review,Amazfit GTS 2 Mini Smart Watch for Women Girls...,250,watch obviously poorly died turn starting ago ...
46,9,0.293455,Premium,Priority review,"Amazfit GTS 3 Smart Watch for Android iPhone, ...",124,understand amazfit logic work features mistake...
47,9,0.290738,Premium,Monitor,"SAMSUNG Galaxy Watch Active (40MM, GPS, Blueto...",240,galaxy active watch not_charging watch not_cha...
48,9,0.290559,Upper mid,Monitor,"Pautios Smart Watch, Swimming Waterproof Fitne...",114,went nutritionists recommendation smart watch ...
49,9,0.287991,Upper mid,Priority review,Fitpolo Smart Watch for Android and iOS Phones...,107,pedometer stopped_working return review_bounda...
50,10,0.267992,Lower mid,Monitor,Mount-It! TV Wall Mount Monitor Bracket with F...,126,expected return review_boundary sturdy came mi...
51,10,0.260883,Upper mid,Monitor,"Ergear Dual Monitor Stand for 13 to 32 inch, H...",178,hold monitor monitor weight limits review_boun...
52,10,0.259129,Upper mid,Priority review,suptek Black Projector Ceiling Mount Bracket F...,92,horrible spend dollars work review_boundary pi...
53,10,0.257620,Upper mid,Priority review,"MOUNTUP Single Monitor Desk Mount, Adjustable ...",250,mounting ridicules review_boundary gas spring ...
54,10,0.254064,Lower mid,Monitor,VideoSecu TV Wall Mount Monitor Bracket with F...,230,work assemble various bits store purchase corr...
55,11,0.339399,Lower mid,Priority review,Portable HDTV Antenna - Includes Magnetic Base...,250,hooked smart roku tv does_not_work review_boun...
56,11,0.336360,Upper mid,Monitor,1byone Amplified HD Digital TV Antenna - Suppo...,250,plugged turned received channels poor_quality ...
57,11,0.335531,Lower mid,Priority review,"Vansky TV Antenna Indoor, Digital Amplified In...",250,work phoenix received exact channels super whi...
58,11,0.334123,Lower mid,Priority review,"Vansky TV Antenna Indoor, Digital Amplified In...",250,unit delivering signal broadcast review_bounda...
59,11,0.332841,Lower mid,Monitor,1byone Amplified HD Digital TV Antenna - Suppo...,91,work channels review_boundary meet expectation...

In [20]:
# Creating the full Electronics NLP corpus for full-scale NLP modeling

full_corpus_dataframe = usable_electronics_nlp_documents_dataframe.copy()

full_corpus_dataframe["modeling_text_clean"] = (
    full_corpus_dataframe["aggregated_text_clean"]
    .fillna("")
    .apply(clean_electronics_review_text)
)

full_corpus_dataframe["clean_word_count_preclip"] = (
    full_corpus_dataframe["modeling_text_clean"].str.split().str.len()
)

full_clip_results = full_corpus_dataframe["modeling_text_clean"].apply(
    lambda value: clip_text_balanced_by_review_boundaries(
        value,
        boundary_token = review_boundary_token,
        max_reviews = 120,
        min_reviews_to_clip = 140
    )
)

full_corpus_dataframe["modeling_text_clipped"] = full_clip_results.apply(lambda value: value[0])
full_corpus_dataframe["clipping_applied"] = full_clip_results.apply(lambda value: value[1])

full_corpus_dataframe["modeling_text_for_vectorizer"] = (
    full_corpus_dataframe["modeling_text_clipped"]
    .apply(build_modeling_text)
    .str.replace(rf"\b{review_boundary_token}\b", " ", regex = True)
    .str.replace(r"\s+", " ", regex = True)
    .str.strip()
)

full_corpus_dataframe["modeling_tokens"] = (
    full_corpus_dataframe["modeling_text_for_vectorizer"]
    .apply(lambda value: value.split() if value else [])
)

full_corpus_dataframe["raw_word_count"] = (
    full_corpus_dataframe["aggregated_text_clean"].str.split().str.len()
)

full_corpus_dataframe["clean_word_count_postclip"] = (
    full_corpus_dataframe["modeling_text_clipped"].str.split().str.len()
)

full_corpus_dataframe["modeling_token_count"] = (
    full_corpus_dataframe["modeling_tokens"].str.len()
)

full_corpus_dataframe["unique_token_count"] = (
    full_corpus_dataframe["modeling_tokens"].apply(lambda values: len(set(values)))
)

full_corpus_dataframe["unique_token_ratio"] = (
    full_corpus_dataframe["unique_token_count"] /
    full_corpus_dataframe["modeling_token_count"].replace(0, np.nan)
)

full_corpus_dataframe["cleaning_retention_ratio_preclip"] = (
    full_corpus_dataframe["clean_word_count_preclip"] /
    full_corpus_dataframe["raw_word_count"].replace(0, np.nan)
)

full_corpus_dataframe["has_repeated_token_sequences"] = (
    full_corpus_dataframe["modeling_text_clipped"]
    .apply(lambda value: bool(repeated_token_pattern.search(value)))
)

print(f"Full corpus documents prepared : {len(full_corpus_dataframe):,}")

Full corpus documents prepared : 35,213

In [21]:
# Reviewing full-corpus text quality before modeling
full_corpus_quality_summary_dataframe = pd.DataFrame({
    "metric": [
        "full_document_count",
        "blank_modeling_text_count",
        "documents_under_100_words_after_cleaning",
        "documents_under_50_modeling_tokens",
        "documents_with_repeated_token_sequences",
        "documents_with_cleaning_retention_ratio_below_0_40",
        "documents_with_unique_token_ratio_below_0_20",
        "documents_with_clipping_applied",
        "documents_with_review_boundary_after_vectorizer_text"
    ],
    "value": [
        len(full_corpus_dataframe),
        full_corpus_dataframe["modeling_text_for_vectorizer"].fillna("").str.strip().eq("").sum(),
        full_corpus_dataframe["clean_word_count_postclip"].lt(100).sum(),
        full_corpus_dataframe["modeling_token_count"].lt(50).sum(),
        full_corpus_dataframe["has_repeated_token_sequences"].sum(),
        full_corpus_dataframe["cleaning_retention_ratio_preclip"].lt(0.40).sum(),
        full_corpus_dataframe["unique_token_ratio"].lt(0.20).sum(),
        full_corpus_dataframe["clipping_applied"].sum(),
        full_corpus_dataframe["modeling_text_for_vectorizer"].str.contains(
            rf"\b{review_boundary_token}\b",
            regex = True,
            na = False
        ).sum()
    ]
})

display(full_corpus_quality_summary_dataframe)

                                              metric  value
0                                full_document_count  35213
1                          blank_modeling_text_count      0
2           documents_under_100_words_after_cleaning      0
3                 documents_under_50_modeling_tokens      0
4            documents_with_repeated_token_sequences      0
5  documents_with_cleaning_retention_ratio_below_...      0
6       documents_with_unique_token_ratio_below_0_20      0
7                    documents_with_clipping_applied  10820
8  documents_with_review_boundary_after_vectorize...      0

In [22]:
# Creating the final modeling corpus with usable text records

full_corpus_modeling_dataframe = full_corpus_dataframe.loc[
    full_corpus_dataframe["modeling_text_for_vectorizer"].fillna("").str.strip().ne("")
].copy()

full_corpus_modeling_dataframe["is_dissatisfaction"] = (
    full_corpus_modeling_dataframe["analysis_pool_role"] == "Topic modeling target"
)

print(f"Full modeling documents : {len(full_corpus_modeling_dataframe):,}")
print("Dissatisfaction documents : "
      f"{full_corpus_modeling_dataframe['is_dissatisfaction'].sum():,}"
)
print("Comparison baseline documents : "
      f"{(~full_corpus_modeling_dataframe['is_dissatisfaction']).sum():,}"
)

Full modeling documents : 35,213
Dissatisfaction documents : 16,853
Comparison baseline documents : 18,360

In [23]:
# Building the dissatisfaction-only corpus for topic modeling

full_dissatisfaction_dataframe = full_corpus_modeling_dataframe.loc[
    full_corpus_modeling_dataframe["is_dissatisfaction"]
].copy()

full_tfidf_vectorizer = TfidfVectorizer(
    lowercase = False,
    stop_words = None,
    token_pattern = r"(?u)\b[a-z_][a-z0-9_]{2,}\b",
    ngram_range = (1, 2),
    min_df = 25,
    max_df = 0.35,
    max_features = 30000,
    sublinear_tf = True
)

full_dissatisfaction_tfidf_matrix = full_tfidf_vectorizer.fit_transform(
    full_dissatisfaction_dataframe["modeling_text_for_vectorizer"]
)

print(full_dissatisfaction_tfidf_matrix.shape)

(16853, 30000)

In [24]:
# Comparing different topic counts to choose a stable topic model

candidate_topic_counts = [10, 12, 15, 18]

topic_model_diagnostics = []

for topic_count in candidate_topic_counts:
    candidate_nmf_model = NMF(
        n_components = topic_count,
        init = "nndsvda",
        random_state = 42,
        max_iter = 400
    )

    candidate_document_topic_matrix = candidate_nmf_model.fit_transform(full_dissatisfaction_tfidf_matrix)

    topic_model_diagnostics.append({
        "topic_count": topic_count,
        "reconstruction_error": candidate_nmf_model.reconstruction_err_,
        "mean_max_topic_strength": candidate_document_topic_matrix.max(axis = 1).mean(),
        "median_max_topic_strength": np.median(candidate_document_topic_matrix.max(axis = 1))
    })

topic_model_diagnostics_dataframe = pd.DataFrame(topic_model_diagnostics)
display(topic_model_diagnostics_dataframe)

,topic_count,reconstruction_error,mean_max_topic_strength,median_max_topic_strength
0,10,122.206903,0.073579,0.066558
1,12,121.683329,0.075101,0.070779
2,15,121.035939,0.078982,0.075012
3,18,120.479698,0.081087,0.075200

In [25]:
# Training candidate topic models and collecting representative topic examples

candidate_topic_counts = [10, 12, 15, 18]

candidate_topic_models = {}
candidate_topic_review_rows = []

for topic_count in candidate_topic_counts:
    candidate_nmf_model = NMF(
        n_components = topic_count,
        init = "nndsvda",
        random_state = 42,
        max_iter = 400
    )

    candidate_document_topic_matrix = candidate_nmf_model.fit_transform(full_dissatisfaction_tfidf_matrix)
    candidate_topic_term_matrix = candidate_nmf_model.components_

    candidate_topic_models[topic_count] = {
        "nmf_model": candidate_nmf_model,
        "document_topic_matrix": candidate_document_topic_matrix,
        "topic_term_matrix": candidate_topic_term_matrix
    }

    dominant_topic_assignment = candidate_document_topic_matrix.argmax(axis = 1)
    dominant_topic_strength = candidate_document_topic_matrix.max(axis = 1)

    topic_size_dataframe = (
        pd.DataFrame({
            "topic_id": dominant_topic_assignment,
            "topic_strength": dominant_topic_strength
        })
        .groupby("topic_id", dropna = False)
        .agg(
            document_count = ("topic_id", "count"),
            average_topic_strength = ("topic_strength", "mean"),
            median_topic_strength = ("topic_strength", "median")
        )
        .reset_index()
    )

    topic_entropy_proxy = (
        topic_size_dataframe["document_count"] / topic_size_dataframe["document_count"].sum()
    )

    candidate_topic_review_rows.append({
        "topic_count": topic_count,
        "reconstruction_error": candidate_nmf_model.reconstruction_err_,
        "mean_max_topic_strength": dominant_topic_strength.mean(),
        "median_max_topic_strength": np.median(dominant_topic_strength),
        "smallest_topic_document_count": topic_size_dataframe["document_count"].min(),
        "largest_topic_document_count": topic_size_dataframe["document_count"].max(),
        "topic_size_ratio_max_to_min": (
            topic_size_dataframe["document_count"].max() /
            topic_size_dataframe["document_count"].min()
        )
    })

candidate_topic_review_dataframe = pd.DataFrame(candidate_topic_review_rows)
display(candidate_topic_review_dataframe.sort_values("topic_count"))

,topic_count,reconstruction_error,mean_max_topic_strength,median_max_topic_strength,smallest_topic_document_count,largest_topic_document_count,topic_size_ratio_max_to_min
0,10,122.206903,0.073579,0.066558,494,3125,6.325911
1,12,121.683329,0.075101,0.070779,510,2275,4.460784
2,15,121.035939,0.078982,0.075012,474,1937,4.086498
3,18,120.479698,0.081087,0.075200,421,1945,4.619952

In [26]:
# Selecting the final broad topic model for Electronics dissatisfaction analysis

selected_topic_count = 15

selected_nmf_model = candidate_topic_models[selected_topic_count]["nmf_model"]
selected_document_topic_matrix = candidate_topic_models[selected_topic_count]["document_topic_matrix"]
selected_topic_term_matrix = candidate_topic_models[selected_topic_count]["topic_term_matrix"]
selected_feature_names = np.array(full_tfidf_vectorizer.get_feature_names_out())

print(f"Selected topic count for detailed review : {selected_topic_count}")

Selected topic count for detailed review : 15

In [27]:
# Assigning selected topics to dissatisfied Electronics documents

full_dissatisfaction_topic_review_dataframe = full_dissatisfaction_dataframe.reset_index(drop = True).copy()

full_dissatisfaction_topic_review_dataframe["topic_id"] = selected_document_topic_matrix.argmax(axis = 1)
full_dissatisfaction_topic_review_dataframe["topic_strength"] = selected_document_topic_matrix.max(axis = 1)

print(f"Assigned topics to {len(full_dissatisfaction_topic_review_dataframe):,} dissatisfaction documents")

Assigned topics to 16,853 dissatisfaction documents

In [28]:
# Extracting top keywords for each selected topic

topic_top_term_rows = []

for topic_index, topic_weights in enumerate(selected_topic_term_matrix):
    top_term_indices = topic_weights.argsort()[ : : -1][ : 15]
    topic_top_term_rows.append({
        "topic_id": topic_index,
        "top_terms": ", ".join(selected_feature_names[top_term_indices])
    })

topic_top_terms_dataframe = pd.DataFrame(topic_top_term_rows)

topic_size_summary_dataframe = (
    full_dissatisfaction_topic_review_dataframe
    .groupby("topic_id", dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        total_sampled_reviews = ("sampled_review_count", "sum"),
        average_topic_strength = ("topic_strength", "mean"),
        median_topic_strength = ("topic_strength", "median"),
        average_rating = ("average_rating", "mean"),
        average_helpful_vote = ("average_helpful_vote", "mean")
    )
    .reset_index()
    .sort_values("document_count", ascending = False)
)

full_topic_summary_dataframe = topic_size_summary_dataframe.merge(
    topic_top_terms_dataframe,
    on = "topic_id",
    how = "left"
)

display(full_topic_summary_dataframe)

,topic_id,document_count,total_sampled_reviews,average_topic_strength,median_topic_strength,average_rating,average_helpful_vote,top_terms
0,1,1937,285262,0.087805,0.089475,1.358950,1.290585,"ear, headphone, earbuds, ears, buds, earbud, s..."
1,2,1649,151277,0.075462,0.074127,1.377515,1.053450,"ipad, not_fit, protect, color, cases, fits, co..."
2,4,1545,183129,0.075803,0.074010,1.231458,2.416205,"drive, drives, files, disk, data, hard_drive, ..."
3,8,1508,185948,0.061545,0.061543,1.324395,1.637885,"speaker, sound_quality, music, bluetooth, bass..."
4,7,1339,156051,0.077219,0.075124,1.303286,3.327786,"camera, camera work, motion, recording, view, ..."
5,6,1246,105915,0.069002,0.062515,1.359285,1.684490,"screws, mount, screw, mounting, bracket, tight..."
6,3,1231,162709,0.086244,0.089526,1.256194,1.215423,"charge phone, cords, chargers, charger, not_ch..."
7,9,1109,116610,0.075755,0.080711,1.261656,1.617113,"hdmi, monitor, hdmi cable, display, adapter, p..."
8,12,1060,109780,0.071391,0.054123,1.256757,2.432281,"charger, charge battery, hold charge, battery ..."
9,5,945,124495,0.089500,0.094093,1.340732,1.209011,"mouse, keyboard, keys, logitech, mouse work, k..."
10,11,915,116085,0.077447,0.080516,1.276203,2.052309,"remote, remote work, remotes, buttons, remote ..."
11,0,830,126020,0.061121,0.066148,1.267146,2.398637,"router, wifi, network, internet, modem, netgea..."
12,13,558,66470,0.100459,0.080365,1.314494,2.045112,"antenna, stations, reception, channels, miles,..."
13,10,507,51465,0.115678,0.137356,1.300156,1.057393,"bubbles, screen_protector, protectors, screen ..."
14,14,474,52127,0.106606,0.122029,1.326081,2.023808,"fitbit, band, wrist, watch, bands, heart rate,..."

In [29]:
# Selecting representative documents for each topic

full_representative_topic_documents_dataframe = (
    full_dissatisfaction_topic_review_dataframe[
        [
            "topic_id",
            "topic_strength",
            "price_band",
            "issue_priority_level",
            "product_display_name",
            "sampled_review_count",
            "modeling_text_for_vectorizer"
        ]
    ]
    .sort_values(["topic_id", "topic_strength"], ascending = [True, False])
    .groupby("topic_id", group_keys = False)
    .head(5)
    .reset_index(drop = True)
)

display(full_representative_topic_documents_dataframe)

,topic_id,topic_strength,price_band,issue_priority_level,product_display_name,sampled_review_count,modeling_text_for_vectorizer
0,0,0.087883,Very premium,Monitor,NETGEAR Nighthawk X6 Smart Wi-Fi Router (R8000...,250,pile scrap simplest activities router pass dns...
1,0,0.087399,Premium,Priority review,NETGEAR R7500 Nighthawk X4 AC2350 Dual Band Wi...,108,constantly reset terrible router buy open sent...
2,0,0.087073,Premium,Monitor,NETGEAR Nighthawk X4S Smart WiFi Router (R7800...,250,piece crap mouth owning started continued conn...
3,0,0.086200,Premium,Priority review,NETGEAR Nighthawk 4-Stream AX4 Wi-fi 6 Router ...,250,purchased ago disappointed start constantly di...
4,0,0.085783,Premium,Monitor,NETGEAR Nighthawk X4S Smart WiFi Router (R7800...,250,wireless stopped broadcasting try factory rese...
5,1,0.137643,Upper mid,Monitor,TOZO NC2 Hybrid Active Noise Cancelling Wirele...,250,completely dead_on_arrival no_power whatsoever...
6,1,0.136635,Upper mid,Monitor,TOZO NC2 Hybrid Active Noise Cancelling Wirele...,250,work ago earbuds cut watching listening music ...
7,1,0.135819,Premium,Priority review,Sony WF-SP800N Truly Wireless Sports In-Ear No...,121,sound_quality earpiece left earpiece try earpi...
8,1,0.135364,Lower mid,Monitor,MEE audio M6 X1 Wired In-Ear Sports Headphones...,250,sounds tin iphone hear kind awkward secure ear...
9,1,0.134971,Upper mid,Monitor,TOZO NC2 Hybrid Active Noise Cancelling Wirele...,140,expecting charge case average size compared no...
10,2,0.138012,Budget,Monitor,MoKo Case Fit 2018/2017 iPad 9.7 6th/5th Gener...,250,case title misleading not_fit ipad release cou...
11,2,0.137992,Lower mid,Monitor,JETech Case for iPad Air 1st Edition (NOT for ...,250,hole camera lens line feel case crazy flaw tip...
12,2,0.137101,Budget,Monitor,"Fintie Case for iPad Air (3rd Gen) 10.5"" 2019 ...",141,generation ipad fit frustrating cool case leav...
13,2,0.137045,Budget,Monitor,ProCase Smart Case for iPad Air 2 (2014 Releas...,230,cheap feeling stand received yesterday complet...
14,2,0.136839,Budget,Monitor,MoKo Case Fit iPad Air 2 - Slim Lightweight Sm...,168,lightweight cheap hold everyday return durable...
15,3,0.150794,Budget,Monitor,JSAUX USB-C to USB A Cable 3.1A Fast Charging ...,250,cord randomly stopped_working super disappoint...
16,3,0.147780,Lower mid,Priority review,[Apple MFi Certified] USB C to Lightning Cable...,250,bought thinking maybe round wrong messed bad b...
17,3,0.147763,Budget,Monitor,[Apple MFi Certified] iPhone Fast Charger 3Pac...,152,bend cable stops work brand iphone cable scams...
18,3,0.146822,Lower mid,Priority review,FEEL2NICE iPhone Charger Cable [MFi Certified]...,123,bought cord length feature mean no_power trans...
19,3,0.146398,Budget,Monitor,"AkoaDa USB C Cable, 3-Pack (10ft+6.6ft+3.3ft) ...",250,inconsistent quality durability issues adverti...
20,4,0.140911,Premium,Monitor,SanDisk 2TB Extreme Portable SSD - Up to 1050M...,185,failed connect mac organizational work video h...
21,4,0.138420,Upper mid,Monitor,SanDisk SSD PLUS 1TB Internal SSD - SATA III 6...,250,hate rating ssd defective computer recognize p...
22,4,0.137802,Premium,Monitor,(OLD MODEL) Seagate Expansion 3TB Desktop Exte...,250,bought drives backup business files personal f...
23,4,0.136277,Premium,Priority review,SanDisk 1TB Extreme PRO Portable SSD - Up to 2...,201,according sandisk trusted store data reason ex...
24,4,0.135907,Budget,Monitor,"PNY 128GB Turbo Attache 3 USB 3.0 Flash Drive,...",250,stay likely deffective taken star seriousley r...
25,5,0.154259,Lower mid,Priority review,"Wireless Keyboard and Mouse Combo, UHURU 2.4G ...",243,quality terrible bang keys mouse okay trouble ...
26,5,0.153140,Premium,Monitor,Logitech MK710 Wireless Keyboard and Mouse Com...,250,ergonomic design poor hand wrist supports keyb...
27,5,0.150639,Upper mid,Monitor,Logitech MK320 Wireless Desktop Keyboard and M...,250,purchased pc connect projector wireless keyboa...
28,5,0.149836,Upper mid,Priority review,Logitech MK570 Wireless Wave Keyboard and Mous...,193,keyboard random letter keys stopped_working so...
29,5,0.149413,Upper mid,Monitor,Microsoft Desktop 3000 Wireless Keyboard and M...,86,ordered stations office comprised pro desktops...
30,6,0.158134,Lower mid,Monitor,WALI TV Wall Mount Articulating LCD Monitor Fu...,250,pay cheap tv mount fit tv screws hole light tv...
31,6,0.158126,Budget,Monitor,VideoSecu ML411B Adjustable Tilt Swivel Rotati...,122,walk terrible mount mounts office lcd screens ...
32,6,0.155452,Lower mid,Monitor,VideoSecu ML12 TV Wall Mount Articulating Arm ...,134,tiest screws pre drilled holes proper screws s...
33,6,0.154911,Upper mid,Monitor,VIVO Extra Tall Single Monitor Desk Mount Stan...,183,monitor mount pain work mount save space monit...
34,6,0.150473,Upper mid,Monitor,USX MOUNT Full Motion TV Wall Mount for Most 4...,173,wall base wide wall studs position luck meanin...
35,7,0.149931,Premium,Priority review,Blink Whole Home Bundle | Video Doorbell Syste...,250,hopes letdown harsh poor optics class security...
36,7,0.149578,Premium,Monitor,Dzees 4MP Solar Security Camera Outdoor Wirele...,135,frustrated camera recording motion clips live ...
37,7,0.149495,Premium,Priority review,Blink Mini – Compact indoor plug-in smart secu...,250,mara gusta mucho hay que ponerle plan para pod...
38,7,0.149472,Upper mid,Priority review,"YI 2pc Security Home Camera, 1080p 2.4G WiFi S...",250,camera work try access camera remotely iphone ...
39,7,0.149407,Premium,Priority review,Blink Whole Home Bundle | Video Doorbell Syste...,250,town apparently power outage sync module conne...
40,8,0.118061,Upper mid,Monitor,"TEWELL Computer Speaker, HD 24W Audio Vintage ...",109,stylish echo dot sounds nope shocked flat rela...
41,8,0.107582,Premium,Monitor,Edifier R1280Ts Powered Bookshelf Speakers - 2...,250,sound expecting kind sad speaker audio technic...
42,8,0.106321,Upper mid,Monitor,Logitech X-140 2.0 Speakers,71,bought speaker excellent sound speaker loud be...
43,8,0.105576,Premium,Monitor,Logitech Z333 2.1 Speakers – Easy-access Volum...,135,sub did_not_work volume sound distorted turned...
44,8,0.105529,Premium,Monitor,Edifier R1700BT Bluetooth Bookshelf Speakers -...,122,speaker sound price point issues buy bluetooth...
45,9,0.143149,Upper mid,Monitor,Amazon Basics 5-Pack DisplayPort to HDMI Displ...,151,frayed spot plugs phone particularly rough mov...
46,9,0.138953,Budget,Priority review,AVACON DisplayPort to HDMI 6 Feet Gold-Plated ...,246,did_not_work connect did_not_work uses cable p...
47,9,0.137250,Budget,Monitor,"BENFEI DisplayPort to HDMI, 4K@30Hz Gold-Plate...",104,despite slew buzzwords headline converter conv...
48,9,0.137001,Lower mid,Monitor,"Warrky DisplayPort to HDMI Adapter 2-Pack (4K,...",100,suddenly lose monitor blue screened convert fi...
49,9,0.136772,Lower mid,Monitor,Warrky 4K DisplayPort to HDMI Cable Adapter 15...,188,purchased hdmi end cable loose picture_quality...
50,10,0.200069,Budget,Priority review,Supershieldz (3 Pack) Anti Glare (Matte) Scree...,133,flimsy material bubbles install ipad worse ipa...
51,10,0.199801,Budget,Priority review,Supershieldz (3 Pack) Anti-Glare (Matte) Scree...,196,anti glare adhere bubbles matter try smooth un...
52,10,0.197280,Budget,Priority review,(3 Pack) Supershieldz Anti Glare and Anti Fing...,95,mentioned hard bubbles fit screen putting lett...
53,10,0.195698,Budget,Priority review,Supershieldz (3 Pack) Designed for Fire HD 10 ...,250,failed attempts inferior cut crooked line edge...
54,10,0.194742,Budget,Priority review,Supershieldz (3 Pack) Anti Glare and Anti Fing...,182,glare ipad thought honestly eyes matte finish ...
55,11,0.152637,Budget,Priority review,Philips Universal Remote Control Replacement f...,124,work philips tv work went bought expecting ins...
56,11,0.148479,Budget,Monitor,GE 6-Device Backlit Universal Remote Control f...,250,asked roku remote numbers change channels voic...
57,11,0.147882,Budget,Monitor,GE 6-Device Backlit Universal Remote Control f...,250,buy worthless took code work went code cleared...
58,11,0.147222,Budget,Priority review,Philips Universal Remote Control Replacement f...,250,work receiver try auto method manual method re...
59,11,0.146224,Budget,Priority review,"Backlit Universal Remote Control by GE, Works ...",179,remote did_not_work bose tv sound combo identi...
60,12,0.196464,Upper mid,Priority review,"4 Pack CR123A Lithium Batteries,QUICKHELP 3.7V...",135,battery fried flashlight longer turns cycles l...
61,12,0.189663,Upper mid,Monitor,EBL 2800mAh Ni-MH AA Rechargeable Batteries (8...,250,broke charger quit work charger work battery n...
62,12,0.185928,Lower mid,Priority review,Energizer Rechargeable AA and AAA Battery Char...,250,placed order packs battery intended flashlight...
63,12,0.182777,Upper mid,Monitor,EBL 2800mAh Ni-MH AA Rechargeable Batteries (8...,250,charger work lights green battery charge purch...
64,12,0.182283,Lower mid,Priority review,Energizer Rechargeable AA and AAA Battery Char...,250,battery xbox controller fully charge stop work...
65,13,0.228663,Upper mid,Priority review,1byone Outdoor TV Antenna 360° Omni-Directiona...,185,weak signal tune channels tv fades rabbit ears...
66,13,0.228394,Upper mid,Monitor,1byone Amplified HD Digital TV Antenna - Suppo...,250,purchased antennas 1byone mile amplified mohu ...
67,13,0.225999,Upper mid,Monitor,Antennas Direct ClearStream Eclipse Amplified ...,250,hopes cut cable cord unfortunately gave channe...
68,13,0.225679,Upper mid,Priority review,"Mohu Leaf 50 Amplified Indoor TV Antenna, 60-M...",106,piece junk antenna dies service yesterday tv a...
69,13,0.224799,Upper mid,Priority review,RCA ANT1650F Flat Digital Amplified Indoor TV ...,250,bought refused pay tv higher hang work play re...
70,14,0.177937,Upper mid,Monitor,"Smart Watch for Men Women, 2022 Fitness Tracke...",110,disappointed smart phone watch fully function ...
71,14,0.171402,Upper mid,Monitor,"EURANS Smart Watch 44mm, Fitness Tracker with ...",146,work charge keeps loosing alerts sleep trackin...
72,14,0.170666,Upper mid,Priority review,Amazfit Bip U Pro Smart Watch with Alexa Built...,250,return instruction booklet tiny gray print whi...
73,14,0.169836,Premium,Priority review,Amazfit GTS Fitness Smartwatch with Heart Rate...,117,digital face rest subpar watch multitask funct...
74,14,0.168832,Very premium,Monitor,"Amazfit T-Rex Ultra Smart Watch for Men, 20-Da...",171,amazfit fan gtr rex pro issues watch tough tru...

In [30]:
# Reviewing topic distribution

topic_segment_distribution_dataframe = (
    full_dissatisfaction_topic_review_dataframe
    .groupby(["topic_id", "price_band", "issue_priority_level"], dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        total_sampled_reviews = ("sampled_review_count", "sum"),
        average_topic_strength = ("topic_strength", "mean")
    )
    .reset_index()
    .sort_values(["topic_id", "price_band", "issue_priority_level"])
)

display(topic_segment_distribution_dataframe)

,topic_id,price_band,issue_priority_level,document_count,total_sampled_reviews,average_topic_strength
0,0,Budget,Monitor,33,4398,0.039279
1,0,Budget,Priority review,17,3800,0.063073
2,0,Lower mid,Monitor,94,12647,0.041572
3,0,Lower mid,Priority review,44,6897,0.063079
4,0,Premium,Monitor,208,31662,0.066698
5,0,Premium,Priority review,108,16848,0.069171
6,0,Upper mid,Monitor,163,24033,0.059010
7,0,Upper mid,Priority review,131,20960,0.063930
8,0,Very premium,Monitor,32,4775,0.073187
9,1,Budget,Monitor,194,22368,0.075236
10,1,Budget,Priority review,162,25603,0.077965
11,1,Lower mid,Monitor,402,64214,0.090254
12,1,Lower mid,Priority review,158,23102,0.089739
13,1,Premium,Monitor,200,25030,0.081602
14,1,Premium,Priority review,204,38108,0.096797
15,1,Upper mid,Monitor,356,47481,0.091388
16,1,Upper mid,Priority review,218,35038,0.094502
17,1,Very premium,Monitor,43,4318,0.074135
18,2,Budget,Monitor,401,35790,0.071406
19,2,Budget,Priority review,49,5570,0.067526
20,2,Lower mid,Monitor,664,56168,0.081618
21,2,Lower mid,Priority review,106,16669,0.087447
22,2,Premium,Monitor,40,2667,0.059007
23,2,Premium,Priority review,15,1945,0.066793
24,2,Upper mid,Monitor,325,25691,0.067878
25,2,Upper mid,Priority review,47,6672,0.074463
26,2,Very premium,Monitor,2,105,0.054121
27,3,Budget,Monitor,573,73269,0.086990
28,3,Budget,Priority review,258,41837,0.102829
29,3,Lower mid,Monitor,235,26377,0.072447
30,3,Lower mid,Priority review,84,14085,0.099554
31,3,Premium,Monitor,7,669,0.042541
32,3,Premium,Priority review,4,446,0.049416
33,3,Upper mid,Monitor,60,4469,0.052937
34,3,Upper mid,Priority review,8,1455,0.086340
35,3,Very premium,Monitor,2,102,0.020668
36,4,Budget,Monitor,288,36513,0.073942
37,4,Budget,Priority review,45,6787,0.068519
38,4,Lower mid,Monitor,272,30535,0.071123
39,4,Lower mid,Priority review,55,7551,0.075487
40,4,Premium,Monitor,322,35118,0.082754
41,4,Premium,Priority review,89,11221,0.077581
42,4,Upper mid,Monitor,324,36256,0.079677
43,4,Upper mid,Priority review,60,9451,0.067828
44,4,Very premium,Monitor,90,9697,0.064484
45,5,Budget,Monitor,132,15516,0.076066
46,5,Budget,Priority review,78,13942,0.088151
47,5,Lower mid,Monitor,160,20752,0.088304
48,5,Lower mid,Priority review,90,14924,0.101073
49,5,Premium,Monitor,109,11500,0.086719
50,5,Premium,Priority review,41,4298,0.065363
51,5,Upper mid,Monitor,203,25478,0.096002
52,5,Upper mid,Priority review,107,15353,0.107164
53,5,Very premium,Monitor,25,2732,0.053958
54,6,Budget,Monitor,209,13828,0.052410
55,6,Budget,Priority review,47,6066,0.057357
56,6,Lower mid,Monitor,312,26924,0.070071
57,6,Lower mid,Priority review,50,6604,0.055456
58,6,Premium,Monitor,188,13450,0.066568
59,6,Premium,Priority review,16,2514,0.077123
60,6,Upper mid,Monitor,378,31516,0.080772
61,6,Upper mid,Priority review,34,4246,0.078833
62,6,Very premium,Monitor,12,767,0.060947
63,7,Budget,Monitor,56,3820,0.038890
64,7,Budget,Priority review,10,1035,0.047211
65,7,Lower mid,Monitor,84,7463,0.051591
66,7,Lower mid,Priority review,51,8866,0.071106
67,7,Premium,Monitor,397,36513,0.074568
68,7,Premium,Priority review,216,33698,0.099780
69,7,Upper mid,Monitor,283,33500,0.074323
70,7,Upper mid,Priority review,144,24390,0.091719
71,7,Very premium,Monitor,98,6766,0.075401
72,8,Budget,Monitor,127,12443,0.043867
73,8,Budget,Priority review,43,6526,0.055807
74,8,Lower mid,Monitor,226,32260,0.067165
75,8,Lower mid,Priority review,55,7278,0.061187
76,8,Premium,Monitor,340,34393,0.064615
77,8,Premium,Priority review,116,15591,0.062837
78,8,Upper mid,Monitor,354,45806,0.063968
79,8,Upper mid,Priority review,173,26271,0.057006
80,8,Very premium,Monitor,74,5380,0.061221
81,9,Budget,Monitor,288,27543,0.075227
82,9,Budget,Priority review,97,16334,0.077303
83,9,Lower mid,Monitor,180,17483,0.075981
84,9,Lower mid,Priority review,35,4343,0.075055
85,9,Premium,Monitor,197,18375,0.073758
86,9,Premium,Priority review,63,7863,0.070526
87,9,Upper mid,Monitor,129,12831,0.080938
88,9,Upper mid,Priority review,49,6765,0.090809
89,9,Very premium,Monitor,71,5073,0.065933
90,10,Budget,Monitor,288,27261,0.130623
91,10,Budget,Priority review,87,12821,0.111133
92,10,Lower mid,Monitor,81,6964,0.097021
93,10,Lower mid,Priority review,15,1608,0.095278
94,10,Premium,Monitor,9,762,0.037287
95,10,Upper mid,Monitor,23,1505,0.067947
96,10,Upper mid,Priority review,1,250,0.074639
97,10,Very premium,Monitor,3,294,0.033286
98,11,Budget,Monitor,170,15540,0.092564
99,11,Budget,Priority review,77,11745,0.102091
100,11,Lower mid,Monitor,59,6637,0.073207
101,11,Lower mid,Priority review,40,5447,0.081673
102,11,Premium,Monitor,191,25343,0.061494
103,11,Premium,Priority review,94,11256,0.072554
104,11,Upper mid,Monitor,170,26227,0.079813
105,11,Upper mid,Priority review,58,8091,0.073381
106,11,Very premium,Monitor,56,5799,0.058766
107,12,Budget,Monitor,169,12591,0.071491
108,12,Budget,Priority review,25,3221,0.063238
109,12,Lower mid,Monitor,255,20708,0.080337
110,12,Lower mid,Priority review,61,8638,0.095591
111,12,Premium,Monitor,150,19699,0.050073
112,12,Premium,Priority review,65,8721,0.054811
113,12,Upper mid,Monitor,212,20170,0.083502
114,12,Upper mid,Priority review,98,14014,0.060224
115,12,Very premium,Monitor,25,2018,0.040659
116,13,Budget,Monitor,48,3918,0.071395
117,13,Budget,Priority review,30,4183,0.142441
118,13,Lower mid,Monitor,67,7435,0.101904
119,13,Lower mid,Priority review,55,8835,0.136037
120,13,Premium,Monitor,97,9899,0.080861
121,13,Premium,Priority review,39,5158,0.092537
122,13,Upper mid,Monitor,141,15967,0.099753
123,13,Upper mid,Priority review,68,10367,0.114098
124,13,Very premium,Monitor,13,708,0.059247
125,14,Budget,Monitor,112,9661,0.108036
126,14,Budget,Priority review,30,3783,0.115226
127,14,Lower mid,Monitor,51,4375,0.090357
128,14,Lower mid,Priority review,20,3012,0.114981
129,14,Premium,Monitor,60,6086,0.082063
130,14,Premium,Priority review,77,11973,0.120178
131,14,Upper mid,Monitor,55,4602,0.104722
132,14,Upper mid,Priority review,52,7137,0.123010
133,14,Very premium,Monitor,17,1498,0.101943

In [31]:
# Measuring how text clipping affects document preparation

clipping_impact_summary_dataframe = pd.DataFrame({
    "metric": [
        "full_document_count",
        "documents_with_clipping_applied",
        "clipping_applied_ratio",
        "average_raw_word_count",
        "average_clean_word_count_preclip",
        "average_clean_word_count_postclip",
        "average_modeling_token_count",
        "average_sampled_review_count"
    ],
    "value": [
        len(full_corpus_dataframe),
        full_corpus_dataframe["clipping_applied"].sum(),
        full_corpus_dataframe["clipping_applied"].mean(),
        full_corpus_dataframe["raw_word_count"].mean(),
        full_corpus_dataframe["clean_word_count_preclip"].mean(),
        full_corpus_dataframe["clean_word_count_postclip"].mean(),
        full_corpus_dataframe["modeling_token_count"].mean(),
        full_corpus_dataframe["sampled_review_count"].mean()
    ]
})

clipped_vs_unclipped_summary_dataframe = (
    full_corpus_dataframe
    .groupby("clipping_applied", dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        total_sampled_reviews = ("sampled_review_count", "sum"),
        average_raw_word_count = ("raw_word_count", "mean"),
        average_clean_word_count_preclip = ("clean_word_count_preclip", "mean"),
        average_clean_word_count_postclip = ("clean_word_count_postclip", "mean"),
        average_modeling_token_count = ("modeling_token_count", "mean"),
        average_aggregated_text_length = ("aggregated_text_length", "mean")
    )
    .reset_index()
)

display(clipping_impact_summary_dataframe)
display(clipped_vs_unclipped_summary_dataframe)

                              metric         value
0                full_document_count  35213.000000
1    documents_with_clipping_applied  10820.000000
2             clipping_applied_ratio      0.307273
3             average_raw_word_count   5626.417090
4   average_clean_word_count_preclip   5110.421180
5  average_clean_word_count_postclip   3686.933576
6       average_modeling_token_count   1300.040326
7       average_sampled_review_count    112.978133

,clipping_applied,document_count,total_sampled_reviews,average_raw_word_count,average_clean_word_count_preclip,average_clean_word_count_postclip,average_modeling_token_count,average_aggregated_text_length
0,False,24393,1563824,3236.758209,2940.436191,2940.436150,1043.963678,17165.49301
1,True,10820,2414475,11013.750647,10002.513956,5369.864418,1877.348799,58481.566451

In [32]:
# Applying the topic model to comparison documents for cohort analysis

full_comparison_dataframe = full_corpus_modeling_dataframe.loc[
    ~full_corpus_modeling_dataframe["is_dissatisfaction"]
].copy()

full_comparison_tfidf_matrix = full_tfidf_vectorizer.transform(
    full_comparison_dataframe["modeling_text_for_vectorizer"]
)

full_comparison_topic_matrix = selected_nmf_model.transform(full_comparison_tfidf_matrix)

full_comparison_dataframe = full_comparison_dataframe.reset_index(drop = True)
full_comparison_dataframe["topic_id"] = full_comparison_topic_matrix.argmax(axis = 1)
full_comparison_dataframe["topic_strength"] = full_comparison_topic_matrix.max(axis = 1)

full_topic_assignment_dataframe = pd.concat(
    [
        full_dissatisfaction_topic_review_dataframe.assign(cohort_role = "Dissatisfaction"),
        full_comparison_dataframe.assign(cohort_role = "Satisfaction")
    ],
    ignore_index = True
)

print(f"Combined topic assignment rows : {len(full_topic_assignment_dataframe):,}")
print(full_topic_assignment_dataframe["cohort_role"].value_counts(dropna = False))

Combined topic assignment rows : 35,213
cohort_role
Satisfaction       18360
Dissatisfaction    16853
Name: count, dtype: int64

In [33]:
# Preparing topic labels and top-term mappings for interpretation

topic_top_terms_map = {}

for topic_index, topic_weights in enumerate(selected_topic_term_matrix):
    top_term_indices = topic_weights.argsort()[ : : -1][ : 15]
    topic_top_terms_map[topic_index] = selected_feature_names[top_term_indices].tolist()

topic_overlap_rows = []

for left_topic_id in sorted(topic_top_terms_map.keys()):
    left_terms = set(topic_top_terms_map[left_topic_id])

    overlap_scores = []
    for right_topic_id in sorted(topic_top_terms_map.keys()):
        if left_topic_id == right_topic_id:
            continue

        right_terms = set(topic_top_terms_map[right_topic_id])
        overlap_score = len(left_terms.intersection(right_terms)) / len(left_terms.union(right_terms))
        overlap_scores.append(overlap_score)

    topic_overlap_rows.append({
        "topic_id": left_topic_id,
        "max_top_term_jaccard_overlap": max(overlap_scores) if overlap_scores else 0.0,
        "mean_top_term_jaccard_overlap": float(np.mean(overlap_scores)) if overlap_scores else 0.0
    })

topic_overlap_summary_dataframe = pd.DataFrame(topic_overlap_rows)

cohort_topic_summary_dataframe = (
    full_topic_assignment_dataframe
    .groupby(["cohort_role", "topic_id"], dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        sampled_reviews = ("sampled_review_count", "sum"),
        average_topic_strength = ("topic_strength", "mean")
    )
    .reset_index()
)

cohort_totals_dataframe = (
    full_topic_assignment_dataframe
    .groupby("cohort_role", dropna = False)
    .agg(
        total_documents = ("document_id", "count"),
        total_sampled_reviews_cohort = ("sampled_review_count", "sum")
    )
    .reset_index()
)

cohort_topic_summary_dataframe = cohort_topic_summary_dataframe.merge(
    cohort_totals_dataframe,
    on = "cohort_role",
    how = "left"
)

cohort_topic_summary_dataframe["document_share"] = (
    cohort_topic_summary_dataframe["document_count"] /
    cohort_topic_summary_dataframe["total_documents"]
)

cohort_topic_summary_dataframe["sampled_review_share"] = (
    cohort_topic_summary_dataframe["sampled_reviews"] /
    cohort_topic_summary_dataframe["total_sampled_reviews_cohort"]
)

topic_comparison_pivot_dataframe = (
    cohort_topic_summary_dataframe[
        [
            "cohort_role",
            "topic_id",
            "document_count",
            "sampled_reviews",
            "document_share",
            "sampled_review_share",
            "average_topic_strength"
        ]
    ]
    .pivot(index = "topic_id", columns = "cohort_role")
)

topic_comparison_pivot_dataframe.columns = [
    f"{metric_name}_{cohort_name.lower()}"
    for metric_name, cohort_name in topic_comparison_pivot_dataframe.columns
]

topic_comparison_pivot_dataframe = topic_comparison_pivot_dataframe.reset_index()

topic_comparison_pivot_dataframe["document_share_lift_dissatisfaction_vs_satisfaction"] = (
    (topic_comparison_pivot_dataframe["document_share_dissatisfaction"] + 1e-6) /
    (topic_comparison_pivot_dataframe["document_share_satisfaction"] + 1e-6)
)

topic_comparison_pivot_dataframe["sampled_review_share_lift_dissatisfaction_vs_satisfaction"] = (
    (topic_comparison_pivot_dataframe["sampled_review_share_dissatisfaction"] + 1e-6) /
    (topic_comparison_pivot_dataframe["sampled_review_share_satisfaction"] + 1e-6)
)

topic_comparison_pivot_dataframe["document_share_gap"] = (
    topic_comparison_pivot_dataframe["document_share_dissatisfaction"] -
    topic_comparison_pivot_dataframe["document_share_satisfaction"]
)

topic_comparison_pivot_dataframe["top_terms"] = topic_comparison_pivot_dataframe["topic_id"].map(
    lambda topic_id: ", ".join(topic_top_terms_map[topic_id])
)

topic_comparison_summary_dataframe = (
    topic_comparison_pivot_dataframe
    .merge(topic_overlap_summary_dataframe, on = "topic_id", how = "left")
    .sort_values(
        by = ["document_share_lift_dissatisfaction_vs_satisfaction", "document_share_gap"],
        ascending = [False, False]
    )
    .reset_index(drop = True)
)

display(topic_comparison_summary_dataframe)

,topic_id,document_count_dissatisfaction,document_count_satisfaction,sampled_reviews_dissatisfaction,sampled_reviews_satisfaction,document_share_dissatisfaction,document_share_satisfaction,sampled_review_share_dissatisfaction,sampled_review_share_satisfaction,average_topic_strength_dissatisfaction,average_topic_strength_satisfaction,document_share_lift_dissatisfaction_vs_satisfaction,sampled_review_share_lift_dissatisfaction_vs_satisfaction,document_share_gap,top_terms,max_top_term_jaccard_overlap,mean_top_term_jaccard_overlap
0,12,1060,740,109780,60861,0.062897,0.040305,0.055073,0.030661,0.071391,0.064315,1.560507,1.796167,0.022592,"charger, charge battery, hold charge, battery ...",0.111111,0.007937
1,3,1231,1171,162709,130872,0.073043,0.063780,0.081626,0.065932,0.086244,0.068559,1.145238,1.238034,0.009263,"charge phone, cords, chargers, charger, not_ch...",0.111111,0.012863
2,5,945,933,124495,110320,0.056073,0.050817,0.062455,0.055578,0.089500,0.077449,1.103430,1.123739,0.005256,"mouse, keyboard, keys, logitech, mouse work, k...",0.000000,0.000000
3,0,830,822,126020,113852,0.049249,0.044771,0.06322,0.057357,0.061121,0.053412,1.100021,1.102217,0.004478,"router, wifi, network, internet, modem, netgea...",0.034483,0.004926
4,1,1937,1926,285262,253887,0.114935,0.104902,0.143107,0.127906,0.087805,0.088255,1.095641,1.11885,0.010033,"ear, headphone, earbuds, ears, buds, earbud, s...",0.071429,0.005102
5,11,915,923,116085,103688,0.054293,0.050272,0.058236,0.052237,0.077447,0.070782,1.079976,1.114848,0.004021,"remote, remote work, remotes, buttons, remote ...",0.000000,0.000000
6,10,507,515,51465,49783,0.030084,0.028050,0.025818,0.02508,0.115678,0.096046,1.072495,1.029436,0.002034,"bubbles, screen_protector, protectors, screen ...",0.000000,0.000000
7,4,1545,1571,183129,171371,0.091675,0.085566,0.09187,0.086335,0.075803,0.063656,1.071390,1.064114,0.006109,"drive, drives, files, disk, data, hard_drive, ...",0.000000,0.000000
8,9,1109,1163,116610,116659,0.065804,0.063344,0.0585,0.058772,0.075755,0.068694,1.038836,0.995374,0.002460,"hdmi, monitor, hdmi cable, display, adapter, p...",0.034483,0.007389
9,13,558,593,66470,67822,0.033110,0.032298,0.033346,0.034168,0.100459,0.096746,1.025120,0.975943,0.000811,"antenna, stations, reception, channels, miles,...",0.034483,0.007389
10,14,474,545,52127,56722,0.028126,0.029684,0.026151,0.028576,0.106606,0.100322,0.947498,0.915127,-0.001559,"fitbit, band, wrist, watch, bands, heart rate,...",0.000000,0.000000
11,8,1508,1767,185948,208146,0.089480,0.096242,0.093284,0.104862,0.061545,0.060918,0.929738,0.889596,-0.006762,"speaker, sound_quality, music, bluetooth, bass...",0.071429,0.007565
12,7,1339,1759,156051,182050,0.079452,0.095806,0.078286,0.091715,0.077219,0.068607,0.829299,0.853583,-0.016354,"camera, camera work, motion, recording, view, ...",0.000000,0.000000
13,6,1246,1664,105915,142767,0.073933,0.090632,0.053134,0.071925,0.069002,0.059402,0.815758,0.738755,-0.016698,"screws, mount, screw, mounting, bracket, tight...",0.000000,0.000000
14,2,1649,2268,151277,216156,0.097846,0.123529,0.075891,0.108897,0.075462,0.065271,0.792089,0.696909,-0.025683,"ipad, not_fit, protect, color, cases, fits, co...",0.034483,0.002463

In [34]:
# Comparing topic exposure across cohorts, price bands, and priority groups

topic_segment_comparison_dataframe = (
    full_topic_assignment_dataframe
    .groupby(
        ["cohort_role", "topic_id", "price_band", "issue_priority_level"],
        dropna = False
    )
    .agg(
        document_count = ("document_id", "count"),
        total_sampled_reviews = ("sampled_review_count", "sum"),
        average_topic_strength = ("topic_strength", "mean")
    )
    .reset_index()
)

display(topic_segment_comparison_dataframe.sort_values(
    ["topic_id", "cohort_role", "price_band", "issue_priority_level"]
))

full_representative_documents_both_cohorts_dataframe = (
    full_topic_assignment_dataframe[
        [
            "cohort_role",
            "topic_id",
            "topic_strength",
            "price_band",
            "issue_priority_level",
            "product_display_name",
            "sampled_review_count",
            "modeling_text_for_vectorizer"
        ]
    ]
    .sort_values(
        ["cohort_role", "topic_id", "topic_strength"],
        ascending = [True, True, False]
    )
    .groupby(["cohort_role", "topic_id"], group_keys = False)
    .head(3)
    .reset_index(drop = True)
)

display(full_representative_documents_both_cohorts_dataframe)

,cohort_role,topic_id,price_band,issue_priority_level,document_count,total_sampled_reviews,average_topic_strength
0,Dissatisfaction,0,Budget,Monitor,33,4398,0.039279
1,Dissatisfaction,0,Budget,Priority review,17,3800,0.063073
2,Dissatisfaction,0,Lower mid,Monitor,94,12647,0.041572
3,Dissatisfaction,0,Lower mid,Priority review,44,6897,0.063079
4,Dissatisfaction,0,Premium,Monitor,208,31662,0.066698
5,Dissatisfaction,0,Premium,Priority review,108,16848,0.069171
6,Dissatisfaction,0,Upper mid,Monitor,163,24033,0.059010
7,Dissatisfaction,0,Upper mid,Priority review,131,20960,0.063930
8,Dissatisfaction,0,Very premium,Monitor,32,4775,0.073187
134,Satisfaction,0,Budget,Monitor,78,9898,0.032675
135,Satisfaction,0,Budget,Priority review,21,4831,0.054530
136,Satisfaction,0,Lower mid,Monitor,87,8530,0.037925
137,Satisfaction,0,Lower mid,Priority review,52,9354,0.059626
138,Satisfaction,0,Premium,Monitor,170,21919,0.058897
139,Satisfaction,0,Premium,Priority review,111,17245,0.063381
140,Satisfaction,0,Upper mid,Monitor,142,15990,0.050258
141,Satisfaction,0,Upper mid,Priority review,135,23164,0.059562
142,Satisfaction,0,Very premium,Monitor,26,2921,0.060993
9,Dissatisfaction,1,Budget,Monitor,194,22368,0.075236
10,Dissatisfaction,1,Budget,Priority review,162,25603,0.077965
11,Dissatisfaction,1,Lower mid,Monitor,402,64214,0.090254
12,Dissatisfaction,1,Lower mid,Priority review,158,23102,0.089739
13,Dissatisfaction,1,Premium,Monitor,200,25030,0.081602
14,Dissatisfaction,1,Premium,Priority review,204,38108,0.096797
15,Dissatisfaction,1,Upper mid,Monitor,356,47481,0.091388
16,Dissatisfaction,1,Upper mid,Priority review,218,35038,0.094502
17,Dissatisfaction,1,Very premium,Monitor,43,4318,0.074135
143,Satisfaction,1,Budget,Monitor,214,21397,0.072637
144,Satisfaction,1,Budget,Priority review,155,21466,0.081335
145,Satisfaction,1,Lower mid,Monitor,363,48740,0.088598
146,Satisfaction,1,Lower mid,Priority review,170,25381,0.092530
147,Satisfaction,1,Premium,Monitor,207,22907,0.083656
148,Satisfaction,1,Premium,Priority review,198,33676,0.099708
149,Satisfaction,1,Upper mid,Monitor,347,40916,0.091278
150,Satisfaction,1,Upper mid,Priority review,226,35296,0.096404
151,Satisfaction,1,Very premium,Monitor,46,4108,0.074276
18,Dissatisfaction,2,Budget,Monitor,401,35790,0.071406
19,Dissatisfaction,2,Budget,Priority review,49,5570,0.067526
20,Dissatisfaction,2,Lower mid,Monitor,664,56168,0.081618
21,Dissatisfaction,2,Lower mid,Priority review,106,16669,0.087447
22,Dissatisfaction,2,Premium,Monitor,40,2667,0.059007
23,Dissatisfaction,2,Premium,Priority review,15,1945,0.066793
24,Dissatisfaction,2,Upper mid,Monitor,325,25691,0.067878
25,Dissatisfaction,2,Upper mid,Priority review,47,6672,0.074463
26,Dissatisfaction,2,Very premium,Monitor,2,105,0.054121
152,Satisfaction,2,Budget,Monitor,528,46144,0.064305
153,Satisfaction,2,Budget,Priority review,48,6792,0.067729
154,Satisfaction,2,Lower mid,Monitor,898,78906,0.070499
155,Satisfaction,2,Lower mid,Priority review,106,16537,0.074122
156,Satisfaction,2,Premium,Monitor,85,8597,0.047771
157,Satisfaction,2,Premium,Priority review,28,3723,0.048623
158,Satisfaction,2,Upper mid,Monitor,495,45497,0.059916
159,Satisfaction,2,Upper mid,Priority review,65,8862,0.064244
160,Satisfaction,2,Very premium,Monitor,15,1098,0.027249
27,Dissatisfaction,3,Budget,Monitor,573,73269,0.086990
28,Dissatisfaction,3,Budget,Priority review,258,41837,0.102829
29,Dissatisfaction,3,Lower mid,Monitor,235,26377,0.072447
30,Dissatisfaction,3,Lower mid,Priority review,84,14085,0.099554
31,Dissatisfaction,3,Premium,Monitor,7,669,0.042541
32,Dissatisfaction,3,Premium,Priority review,4,446,0.049416
33,Dissatisfaction,3,Upper mid,Monitor,60,4469,0.052937
34,Dissatisfaction,3,Upper mid,Priority review,8,1455,0.086340
35,Dissatisfaction,3,Very premium,Monitor,2,102,0.020668
161,Satisfaction,3,Budget,Monitor,522,53554,0.067728
162,Satisfaction,3,Budget,Priority review,222,34542,0.089795
163,Satisfaction,3,Lower mid,Monitor,248,23138,0.056224
164,Satisfaction,3,Lower mid,Priority review,73,11103,0.086010
165,Satisfaction,3,Premium,Monitor,13,1127,0.036655
166,Satisfaction,3,Premium,Priority review,3,312,0.044114
167,Satisfaction,3,Upper mid,Monitor,74,5242,0.044181
168,Satisfaction,3,Upper mid,Priority review,11,1607,0.070102
169,Satisfaction,3,Very premium,Monitor,5,247,0.024523
36,Dissatisfaction,4,Budget,Monitor,288,36513,0.073942
37,Dissatisfaction,4,Budget,Priority review,45,6787,0.068519
38,Dissatisfaction,4,Lower mid,Monitor,272,30535,0.071123
39,Dissatisfaction,4,Lower mid,Priority review,55,7551,0.075487
40,Dissatisfaction,4,Premium,Monitor,322,35118,0.082754
41,Dissatisfaction,4,Premium,Priority review,89,11221,0.077581
42,Dissatisfaction,4,Upper mid,Monitor,324,36256,0.079677
43,Dissatisfaction,4,Upper mid,Priority review,60,9451,0.067828
44,Dissatisfaction,4,Very premium,Monitor,90,9697,0.064484
170,Satisfaction,4,Budget,Monitor,310,34128,0.057883
171,Satisfaction,4,Budget,Priority review,43,6501,0.058860
172,Satisfaction,4,Lower mid,Monitor,268,26478,0.060207
173,Satisfaction,4,Lower mid,Priority review,51,6118,0.068146
174,Satisfaction,4,Premium,Monitor,356,35108,0.067700
175,Satisfaction,4,Premium,Priority review,92,11725,0.072113
176,Satisfaction,4,Upper mid,Monitor,309,34224,0.066084
177,Satisfaction,4,Upper mid,Priority review,57,8573,0.065737
178,Satisfaction,4,Very premium,Monitor,85,8516,0.058995
45,Dissatisfaction,5,Budget,Monitor,132,15516,0.076066
46,Dissatisfaction,5,Budget,Priority review,78,13942,0.088151
47,Dissatisfaction,5,Lower mid,Monitor,160,20752,0.088304
48,Dissatisfaction,5,Lower mid,Priority review,90,14924,0.101073
49,Dissatisfaction,5,Premium,Monitor,109,11500,0.086719
50,Dissatisfaction,5,Premium,Priority review,41,4298,0.065363
51,Dissatisfaction,5,Upper mid,Monitor,203,25478,0.096002
52,Dissatisfaction,5,Upper mid,Priority review,107,15353,0.107164
53,Dissatisfaction,5,Very premium,Monitor,25,2732,0.053958
179,Satisfaction,5,Budget,Monitor,133,13165,0.062524
180,Satisfaction,5,Budget,Priority review,89,16333,0.077390
181,Satisfaction,5,Lower mid,Monitor,148,15258,0.075654
182,Satisfaction,5,Lower mid,Priority review,85,13875,0.090827
183,Satisfaction,5,Premium,Monitor,119,10649,0.074020
184,Satisfaction,5,Premium,Priority review,47,5333,0.060837
185,Satisfaction,5,Upper mid,Monitor,176,17824,0.083405
186,Satisfaction,5,Upper mid,Priority review,106,15713,0.097953
187,Satisfaction,5,Very premium,Monitor,30,2170,0.046970
54,Dissatisfaction,6,Budget,Monitor,209,13828,0.052410
55,Dissatisfaction,6,Budget,Priority review,47,6066,0.057357
56,Dissatisfaction,6,Lower mid,Monitor,312,26924,0.070071
57,Dissatisfaction,6,Lower mid,Priority review,50,6604,0.055456
58,Dissatisfaction,6,Premium,Monitor,188,13450,0.066568
59,Dissatisfaction,6,Premium,Priority review,16,2514,0.077123
60,Dissatisfaction,6,Upper mid,Monitor,378,31516,0.080772
61,Dissatisfaction,6,Upper mid,Priority review,34,4246,0.078833
62,Dissatisfaction,6,Very premium,Monitor,12,767,0.060947
188,Satisfaction,6,Budget,Monitor,271,17469,0.044832
189,Satisfaction,6,Budget,Priority review,38,5227,0.050011
190,Satisfaction,6,Lower mid,Monitor,433,37937,0.057438
191,Satisfaction,6,Lower mid,Priority review,53,6973,0.047557
192,Satisfaction,6,Premium,Monitor,250,18869,0.062152
193,Satisfaction,6,Premium,Priority review,22,3020,0.057863
194,Satisfaction,6,Upper mid,Monitor,536,45870,0.069025
195,Satisfaction,6,Upper mid,Priority review,43,5990,0.059502
196,Satisfaction,6,Very premium,Monitor,18,1412,0.057610
63,Dissatisfaction,7,Budget,Monitor,56,3820,0.038890
64,Dissatisfaction,7,Budget,Priority review,10,1035,0.047211
65,Dissatisfaction,7,Lower mid,Monitor,84,7463,0.051591
66,Dissatisfaction,7,Lower mid,Priority review,51,8866,0.071106
67,Dissatisfaction,7,Premium,Monitor,397,36513,0.074568
68,Dissatisfaction,7,Premium,Priority review,216,33698,0.099780
69,Dissatisfaction,7,Upper mid,Monitor,283,33500,0.074323
70,Dissatisfaction,7,Upper mid,Priority review,144,24390,0.091719
71,Dissatisfaction,7,Very premium,Monitor,98,6766,0.075401
197,Satisfaction,7,Budget,Monitor,137,10506,0.037988
198,Satisfaction,7,Budget,Priority review,21,2924,0.050310
199,Satisfaction,7,Lower mid,Monitor,116,9340,0.047018
200,Satisfaction,7,Lower mid,Priority review,63,10724,0.071767
201,Satisfaction,7,Premium,Monitor,531,46073,0.068046
202,Satisfaction,7,Premium,Priority review,228,35191,0.091701
203,Satisfaction,7,Upper mid,Monitor,321,31771,0.066049
204,Satisfaction,7,Upper mid,Priority review,149,24342,0.087671
205,Satisfaction,7,Very premium,Monitor,193,11179,0.068076
72,Dissatisfaction,8,Budget,Monitor,127,12443,0.043867
73,Dissatisfaction,8,Budget,Priority review,43,6526,0.055807
74,Dissatisfaction,8,Lower mid,Monitor,226,32260,0.067165
75,Dissatisfaction,8,Lower mid,Priority review,55,7278,0.061187
76,Dissatisfaction,8,Premium,Monitor,340,34393,0.064615
77,Dissatisfaction,8,Premium,Priority review,116,15591,0.062837
78,Dissatisfaction,8,Upper mid,Monitor,354,45806,0.063968
79,Dissatisfaction,8,Upper mid,Priority review,173,26271,0.057006
80,Dissatisfaction,8,Very premium,Monitor,74,5380,0.061221
206,Satisfaction,8,Budget,Monitor,155,14007,0.041272
207,Satisfaction,8,Budget,Priority review,58,8630,0.055011
208,Satisfaction,8,Lower mid,Monitor,241,30827,0.063700
209,Satisfaction,8,Lower mid,Priority review,64,8448,0.060436
210,Satisfaction,8,Premium,Monitor,435,43273,0.065613
211,Satisfaction,8,Premium,Priority review,128,18358,0.064075
212,Satisfaction,8,Upper mid,Monitor,408,49327,0.061942
213,Satisfaction,8,Upper mid,Priority review,185,28055,0.058981
214,Satisfaction,8,Very premium,Monitor,93,7221,0.063531
81,Dissatisfaction,9,Budget,Monitor,288,27543,0.075227
82,Dissatisfaction,9,Budget,Priority review,97,16334,0.077303
83,Dissatisfaction,9,Lower mid,Monitor,180,17483,0.075981
84,Dissatisfaction,9,Lower mid,Priority review,35,4343,0.075055
85,Dissatisfaction,9,Premium,Monitor,197,18375,0.073758
86,Dissatisfaction,9,Premium,Priority review,63,7863,0.070526
87,Dissatisfaction,9,Upper mid,Monitor,129,12831,0.080938
88,Dissatisfaction,9,Upper mid,Priority review,49,6765,0.090809
89,Dissatisfaction,9,Very premium,Monitor,71,5073,0.065933
215,Satisfaction,9,Budget,Monitor,324,31144,0.067260
216,Satisfaction,9,Budget,Priority review,91,15798,0.073876
217,Satisfaction,9,Lower mid,Monitor,193,17124,0.064613
218,Satisfaction,9,Lower mid,Priority review,38,4944,0.075672
219,Satisfaction,9,Premium,Monitor,201,17193,0.067980
220,Satisfaction,9,Premium,Priority review,60,8023,0.071785
221,Satisfaction,9,Upper mid,Monitor,127,10523,0.069918
222,Satisfaction,9,Upper mid,Priority review,50,6957,0.085965
223,Satisfaction,9,Very premium,Monitor,79,4953,0.061791
90,Dissatisfaction,10,Budget,Monitor,288,27261,0.130623
91,Dissatisfaction,10,Budget,Priority review,87,12821,0.111133
92,Dissatisfaction,10,Lower mid,Monitor,81,6964,0.097021
93,Dissatisfaction,10,Lower mid,Priority review,15,1608,0.095278
94,Dissatisfaction,10,Premium,Monitor,9,762,0.037287
95,Dissatisfaction,10,Upper mid,Monitor,23,1505,0.067947
96,Dissatisfaction,10,Upper mid,Priority review,1,250,0.074639
97,Dissatisfaction,10,Very premium,Monitor,3,294,0.033286
224,Satisfaction,10,Budget,Monitor,277,22812,0.111299
225,Satisfaction,10,Budget,Priority review,85,13291,0.096437
226,Satisfaction,10,Lower mid,Monitor,78,7322,0.083921
227,Satisfaction,10,Lower mid,Priority review,15,1538,0.089886
228,Satisfaction,10,Premium,Monitor,15,1106,0.031094
229,Satisfaction,10,Premium,Priority review,3,293,0.032933
230,Satisfaction,10,Upper mid,Monitor,33,2595,0.051484
231,Satisfaction,10,Upper mid,Priority review,7,734,0.032002
232,Satisfaction,10,Very premium,Monitor,2,92,0.027097
98,Dissatisfaction,11,Budget,Monitor,170,15540,0.092564
99,Dissatisfaction,11,Budget,Priority review,77,11745,0.102091
100,Dissatisfaction,11,Lower mid,Monitor,59,6637,0.073207
101,Dissatisfaction,11,Lower mid,Priority review,40,5447,0.081673
102,Dissatisfaction,11,Premium,Monitor,191,25343,0.061494
103,Dissatisfaction,11,Premium,Priority review,94,11256,0.072554
104,Dissatisfaction,11,Upper mid,Monitor,170,26227,0.079813
105,Dissatisfaction,11,Upper mid,Priority review,58,8091,0.073381
106,Dissatisfaction,11,Very premium,Monitor,56,5799,0.058766
233,Satisfaction,11,Budget,Monitor,190,12703,0.077909
234,Satisfaction,11,Budget,Priority review,82,13669,0.093785
235,Satisfaction,11,Lower mid,Monitor,79,10064,0.054777
236,Satisfaction,11,Lower mid,Priority review,33,3966,0.082823
237,Satisfaction,11,Premium,Monitor,182,20887,0.057741
238,Satisfaction,11,Premium,Priority review,83,9445,0.074152
239,Satisfaction,11,Upper mid,Monitor,158,21546,0.073711
240,Satisfaction,11,Upper mid,Priority review,56,7180,0.071042
241,Satisfaction,11,Very premium,Monitor,60,4228,0.058167
107,Dissatisfaction,12,Budget,Monitor,169,12591,0.071491
108,Dissatisfaction,12,Budget,Priority review,25,3221,0.063238
109,Dissatisfaction,12,Lower mid,Monitor,255,20708,0.080337
110,Dissatisfaction,12,Lower mid,Priority review,61,8638,0.095591
111,Dissatisfaction,12,Premium,Monitor,150,19699,0.050073
112,Dissatisfaction,12,Premium,Priority review,65,8721,0.054811
113,Dissatisfaction,12,Upper mid,Monitor,212,20170,0.083502
114,Dissatisfaction,12,Upper mid,Priority review,98,14014,0.060224
115,Dissatisfaction,12,Very premium,Monitor,25,2018,0.040659
242,Satisfaction,12,Budget,Monitor,172,10798,0.055500
243,Satisfaction,12,Budget,Priority review,24,3299,0.059464
244,Satisfaction,12,Lower mid,Monitor,212,12907,0.071248
245,Satisfaction,12,Lower mid,Priority review,45,6690,0.084983
246,Satisfaction,12,Premium,Monitor,60,6752,0.038078
247,Satisfaction,12,Premium,Priority review,25,3745,0.049678
248,Satisfaction,12,Upper mid,Monitor,156,11305,0.074783
249,Satisfaction,12,Upper mid,Priority review,42,5191,0.056663
250,Satisfaction,12,Very premium,Monitor,4,174,0.029626
116,Dissatisfaction,13,Budget,Monitor,48,3918,0.071395
117,Dissatisfaction,13,Budget,Priority review,30,4183,0.142441
118,Dissatisfaction,13,Lower mid,Monitor,67,7435,0.101904
119,Dissatisfaction,13,Lower mid,Priority review,55,8835,0.136037
120,Dissatisfaction,13,Premium,Monitor,97,9899,0.080861
121,Dissatisfaction,13,Premium,Priority review,39,5158,0.092537
122,Dissatisfaction,13,Upper mid,Monitor,141,15967,0.099753
123,Dissatisfaction,13,Upper mid,Priority review,68,10367,0.114098
124,Dissatisfaction,13,Very premium,Monitor,13,708,0.059247
251,Satisfaction,13,Budget,Monitor,63,4353,0.070008
252,Satisfaction,13,Budget,Priority review,32,5772,0.147239
253,Satisfaction,13,Lower mid,Monitor,72,6850,0.081318
254,Satisfaction,13,Lower mid,Priority review,57,8922,0.130369
255,Satisfaction,13,Premium,Monitor,99,9481,0.078332
256,Satisfaction,13,Premium,Priority review,42,5949,0.094673
257,Satisfaction,13,Upper mid,Monitor,154,16064,0.095782
258,Satisfaction,13,Upper mid,Priority review,58,9663,0.130874
259,Satisfaction,13,Very premium,Monitor,16,768,0.055640
125,Dissatisfaction,14,Budget,Monitor,112,9661,0.108036
126,Dissatisfaction,14,Budget,Priority review,30,3783,0.115226
127,Dissatisfaction,14,Lower mid,Monitor,51,4375,0.090357
128,Dissatisfaction,14,Lower mid,Priority review,20,3012,0.114981
129,Dissatisfaction,14,Premium,Monitor,60,6086,0.082063
130,Dissatisfaction,14,Premium,Priority review,77,11973,0.120178
131,Dissatisfaction,14,Upper mid,Monitor,55,4602,0.104722
132,Dissatisfaction,14,Upper mid,Priority review,52,7137,0.123010
133,Dissatisfaction,14,Very premium,Monitor,17,1498,0.101943
260,Satisfaction,14,Budget,Monitor,140,9956,0.099642
261,Satisfaction,14,Budget,Priority review,28,4140,0.115349
262,Satisfaction,14,Lower mid,Monitor,64,4731,0.080166
263,Satisfaction,14,Lower mid,Priority review,21,3281,0.106171
264,Satisfaction,14,Premium,Monitor,66,6238,0.075404
265,Satisfaction,14,Premium,Priority review,87,13580,0.118133
266,Satisfaction,14,Upper mid,Monitor,62,4738,0.096980
267,Satisfaction,14,Upper mid,Priority review,61,9059,0.115762
268,Satisfaction,14,Very premium,Monitor,16,999,0.112927

,cohort_role,topic_id,topic_strength,price_band,issue_priority_level,product_display_name,sampled_review_count,modeling_text_for_vectorizer
0,Dissatisfaction,0,0.087883,Very premium,Monitor,NETGEAR Nighthawk X6 Smart Wi-Fi Router (R8000...,250,pile scrap simplest activities router pass dns...
1,Dissatisfaction,0,0.087399,Premium,Priority review,NETGEAR R7500 Nighthawk X4 AC2350 Dual Band Wi...,108,constantly reset terrible router buy open sent...
2,Dissatisfaction,0,0.087073,Premium,Monitor,NETGEAR Nighthawk X4S Smart WiFi Router (R7800...,250,piece crap mouth owning started continued conn...
3,Dissatisfaction,1,0.137643,Upper mid,Monitor,TOZO NC2 Hybrid Active Noise Cancelling Wirele...,250,completely dead_on_arrival no_power whatsoever...
4,Dissatisfaction,1,0.136635,Upper mid,Monitor,TOZO NC2 Hybrid Active Noise Cancelling Wirele...,250,work ago earbuds cut watching listening music ...
5,Dissatisfaction,1,0.135819,Premium,Priority review,Sony WF-SP800N Truly Wireless Sports In-Ear No...,121,sound_quality earpiece left earpiece try earpi...
6,Dissatisfaction,2,0.138012,Budget,Monitor,MoKo Case Fit 2018/2017 iPad 9.7 6th/5th Gener...,250,case title misleading not_fit ipad release cou...
7,Dissatisfaction,2,0.137992,Lower mid,Monitor,JETech Case for iPad Air 1st Edition (NOT for ...,250,hole camera lens line feel case crazy flaw tip...
8,Dissatisfaction,2,0.137101,Budget,Monitor,"Fintie Case for iPad Air (3rd Gen) 10.5"" 2019 ...",141,generation ipad fit frustrating cool case leav...
9,Dissatisfaction,3,0.150794,Budget,Monitor,JSAUX USB-C to USB A Cable 3.1A Fast Charging ...,250,cord randomly stopped_working super disappoint...
10,Dissatisfaction,3,0.147780,Lower mid,Priority review,[Apple MFi Certified] USB C to Lightning Cable...,250,bought thinking maybe round wrong messed bad b...
11,Dissatisfaction,3,0.147763,Budget,Monitor,[Apple MFi Certified] iPhone Fast Charger 3Pac...,152,bend cable stops work brand iphone cable scams...
12,Dissatisfaction,4,0.140911,Premium,Monitor,SanDisk 2TB Extreme Portable SSD - Up to 1050M...,185,failed connect mac organizational work video h...
13,Dissatisfaction,4,0.138420,Upper mid,Monitor,SanDisk SSD PLUS 1TB Internal SSD - SATA III 6...,250,hate rating ssd defective computer recognize p...
14,Dissatisfaction,4,0.137802,Premium,Monitor,(OLD MODEL) Seagate Expansion 3TB Desktop Exte...,250,bought drives backup business files personal f...
15,Dissatisfaction,5,0.154259,Lower mid,Priority review,"Wireless Keyboard and Mouse Combo, UHURU 2.4G ...",243,quality terrible bang keys mouse okay trouble ...
16,Dissatisfaction,5,0.153140,Premium,Monitor,Logitech MK710 Wireless Keyboard and Mouse Com...,250,ergonomic design poor hand wrist supports keyb...
17,Dissatisfaction,5,0.150639,Upper mid,Monitor,Logitech MK320 Wireless Desktop Keyboard and M...,250,purchased pc connect projector wireless keyboa...
18,Dissatisfaction,6,0.158134,Lower mid,Monitor,WALI TV Wall Mount Articulating LCD Monitor Fu...,250,pay cheap tv mount fit tv screws hole light tv...
19,Dissatisfaction,6,0.158126,Budget,Monitor,VideoSecu ML411B Adjustable Tilt Swivel Rotati...,122,walk terrible mount mounts office lcd screens ...
20,Dissatisfaction,6,0.155452,Lower mid,Monitor,VideoSecu ML12 TV Wall Mount Articulating Arm ...,134,tiest screws pre drilled holes proper screws s...
21,Dissatisfaction,7,0.149931,Premium,Priority review,Blink Whole Home Bundle | Video Doorbell Syste...,250,hopes letdown harsh poor optics class security...
22,Dissatisfaction,7,0.149578,Premium,Monitor,Dzees 4MP Solar Security Camera Outdoor Wirele...,135,frustrated camera recording motion clips live ...
23,Dissatisfaction,7,0.149495,Premium,Priority review,Blink Mini – Compact indoor plug-in smart secu...,250,mara gusta mucho hay que ponerle plan para pod...
24,Dissatisfaction,8,0.118061,Upper mid,Monitor,"TEWELL Computer Speaker, HD 24W Audio Vintage ...",109,stylish echo dot sounds nope shocked flat rela...
25,Dissatisfaction,8,0.107582,Premium,Monitor,Edifier R1280Ts Powered Bookshelf Speakers - 2...,250,sound expecting kind sad speaker audio technic...
26,Dissatisfaction,8,0.106321,Upper mid,Monitor,Logitech X-140 2.0 Speakers,71,bought speaker excellent sound speaker loud be...
27,Dissatisfaction,9,0.143149,Upper mid,Monitor,Amazon Basics 5-Pack DisplayPort to HDMI Displ...,151,frayed spot plugs phone particularly rough mov...
28,Dissatisfaction,9,0.138953,Budget,Priority review,AVACON DisplayPort to HDMI 6 Feet Gold-Plated ...,246,did_not_work connect did_not_work uses cable p...
29,Dissatisfaction,9,0.137250,Budget,Monitor,"BENFEI DisplayPort to HDMI, 4K@30Hz Gold-Plate...",104,despite slew buzzwords headline converter conv...
30,Dissatisfaction,10,0.200069,Budget,Priority review,Supershieldz (3 Pack) Anti Glare (Matte) Scree...,133,flimsy material bubbles install ipad worse ipa...
31,Dissatisfaction,10,0.199801,Budget,Priority review,Supershieldz (3 Pack) Anti-Glare (Matte) Scree...,196,anti glare adhere bubbles matter try smooth un...
32,Dissatisfaction,10,0.197280,Budget,Priority review,(3 Pack) Supershieldz Anti Glare and Anti Fing...,95,mentioned hard bubbles fit screen putting lett...
33,Dissatisfaction,11,0.152637,Budget,Priority review,Philips Universal Remote Control Replacement f...,124,work philips tv work went bought expecting ins...
34,Dissatisfaction,11,0.148479,Budget,Monitor,GE 6-Device Backlit Universal Remote Control f...,250,asked roku remote numbers change channels voic...
35,Dissatisfaction,11,0.147882,Budget,Monitor,GE 6-Device Backlit Universal Remote Control f...,250,buy worthless took code work went code cleared...
36,Dissatisfaction,12,0.196464,Upper mid,Priority review,"4 Pack CR123A Lithium Batteries,QUICKHELP 3.7V...",135,battery fried flashlight longer turns cycles l...
37,Dissatisfaction,12,0.189663,Upper mid,Monitor,EBL 2800mAh Ni-MH AA Rechargeable Batteries (8...,250,broke charger quit work charger work battery n...
38,Dissatisfaction,12,0.185928,Lower mid,Priority review,Energizer Rechargeable AA and AAA Battery Char...,250,placed order packs battery intended flashlight...
39,Dissatisfaction,13,0.228663,Upper mid,Priority review,1byone Outdoor TV Antenna 360° Omni-Directiona...,185,weak signal tune channels tv fades rabbit ears...
40,Dissatisfaction,13,0.228394,Upper mid,Monitor,1byone Amplified HD Digital TV Antenna - Suppo...,250,purchased antennas 1byone mile amplified mohu ...
41,Dissatisfaction,13,0.225999,Upper mid,Monitor,Antennas Direct ClearStream Eclipse Amplified ...,250,hopes cut cable cord unfortunately gave channe...
42,Dissatisfaction,14,0.177937,Upper mid,Monitor,"Smart Watch for Men Women, 2022 Fitness Tracke...",110,disappointed smart phone watch fully function ...
43,Dissatisfaction,14,0.171402,Upper mid,Monitor,"EURANS Smart Watch 44mm, Fitness Tracker with ...",146,work charge keeps loosing alerts sleep trackin...
44,Dissatisfaction,14,0.170666,Upper mid,Priority review,Amazfit Bip U Pro Smart Watch with Alexa Built...,250,return instruction booklet tiny gray print whi...
45,Satisfaction,0,0.079629,Upper mid,Priority review,NETGEAR Wireless Router – AC1750 Dual Band Gig...,141,allows access wireless capabilities form modem...
46,Satisfaction,0,0.079410,Premium,Monitor,TP-Link AC1900 Smart Wireless Router - Beamfor...,226,setup fast speeds reliable router available wh...
47,Satisfaction,0,0.078201,Upper mid,Priority review,TP-Link AC2300 Wifi Router,139,route setting features work expected ive route...
48,Satisfaction,1,0.137090,Upper mid,Monitor,"comiso Wireless Earbuds Bluetooth Headphones, ...",182,sound setup fit comfortable package battery_li...
49,Satisfaction,1,0.135626,Premium,Priority review,"ACREO The Next Generation Open Ear Headphones,...",122,sound enjoy singing music open ear buds hear l...
50,Satisfaction,1,0.133838,Premium,Priority review,"Jabra Elite 65t Earbuds – Alexa Built-in, True...",250,researched truly wireless headphone believe de...
51,Satisfaction,2,0.121520,Premium,Monitor,"ZUGU Case for iPad Pro 11 inch (1st, 2nd, 3rd ...",133,worth puppy try chew fail don case terms textu...
52,Satisfaction,2,0.117402,Lower mid,Monitor,JETech Case for iPad Pro 10.5-Inch and iPad Ai...,173,cover strong durable fits ipad air highly jete...
53,Satisfaction,2,0.116909,Lower mid,Monitor,Ztotop Case for iPad Air 3rd Generation 2019/i...,204,pleased ipad case durable heavy elastic straps...
54,Satisfaction,3,0.127556,Budget,Monitor,[Apple MFi Certified] iPhone Fast Charger 3Pac...,144,fits usb_c socket cord length allows connect f...
55,Satisfaction,3,0.127476,Budget,Priority review,"iPhone Charger, JAHMAI Nylon Braided Lightning...",250,arrived quickly customer appears issues cord p...
56,Satisfaction,3,0.123604,Budget,Priority review,"iPhone Fast Charger Cable,Apple Super Quick Li...",140,cords fast charge charge phone minutes length ...
57,Satisfaction,4,0.122512,Premium,Priority review,(Old Model) Seagate Backup Plus 2TB Desktop Ex...,75,drive expected buy achieved promised simple se...
58,Satisfaction,4,0.121711,Upper mid,Monitor,Unitek USB 3.0 to IDE and SATA Converter Exter...,107,simple work personal data recovery transfer pr...
59,Satisfaction,4,0.119311,Premium,Priority review,"WD 8TB My Book Desktop External Hard Drive, US...",250,satisfied western digital hd design fast belie...
60,Satisfaction,5,0.134496,Premium,Monitor,Logitech MK710 Wireless Keyboard and Mouse Com...,244,constant living room work battery wore letter ...
61,Satisfaction,5,0.133097,Upper mid,Priority review,Logitech MK545 Advanced Wireless Keyboard and ...,250,keyboard work mouse problems keyboard exactly ...
62,Satisfaction,5,0.130354,Lower mid,Priority review,Eagletec K104 Wireless Keyboard and Mouse Comb...,189,touch keyboard feels expensive mouse work upda...
63,Satisfaction,6,0.139356,Upper mid,Monitor,"VideoSecu Tilt Swivel TV Wall Mount 32""- 70"" L...",213,mount solid heavy purchases past including pri...
64,Satisfaction,6,0.138549,Upper mid,Monitor,VideoSecu MW380B5 Full Motion Articulating TV ...,250,price expensive analogues stores mount plenty ...
65,Satisfaction,6,0.137517,Lower mid,Monitor,VideoSecu TV Wall Mount Tilt Swivel Low Profil...,78,value install work hisense tv comes hardware m...
66,Satisfaction,7,0.148808,Lower mid,Priority review,"YI Home Security Camera, 1080p 2.4G WiFi IP In...",250,camera quality excellent compare price moves p...
67,Satisfaction,7,0.147635,Upper mid,Priority review,"WYZE Cam v3 with Color Night Vision, Wired 108...",250,muy buena super cil instalar puedo verla desde...
68,Satisfaction,7,0.146255,Premium,Monitor,"Dzees Security Cameras Wireless Outdoor,2K Sol...",101,super order night visions smart service motion...
69,Satisfaction,8,0.101422,Premium,Monitor,Creative Labs 51MF1610AA002 GigaWorks T20 Seri...,177,speaker remember kids computer speaker studio ...
70,Satisfaction,8,0.101187,Premium,Monitor,Edifier R1280Ts Powered Bookshelf Speakers - 2...,250,speaker amazing ipod classic sound produced bo...
71,Satisfaction,8,0.101110,Premium,Monitor,Logitech Speaker System Z323 with Subwoofer,180,speaker price spent decent shopping convinced ...
72,Satisfaction,9,0.128824,Lower mid,Monitor,Selore&S-Global USB C to Dual HDMI Adapter 4K ...,129,simple connect issue configuring screen modes ...
73,Satisfaction,9,0.128163,Lower mid,Monitor,"Warrky DisplayPort to HDMI Adapter 2-Pack (4K,...",133,feels quality did_not_work particular screen s...
74,Satisfaction,9,0.127093,Budget,Monitor,"Amazon Basics HDMI to DVI Adapter Cable, Bi-Di...",250,work wish ordered longer cord exactly hooked m...
75,Satisfaction,10,0.172256,Budget,Monitor,SPARIN 2 Pack Screen Protector Compatible with...,165,price work kids ipads tempered glass exactly k...
76,Satisfaction,10,0.169990,Lower mid,Monitor,OMOTON Screen Protector Compatible with Surfac...,250,simple install try future buy omoton brand eas...
77,Satisfaction,10,0.167758,Budget,Priority review,Supershieldz (3 Pack) Designed for iPad Pro 12...,97,remove tooo bubbles muuuch arrived earlier exp...
78,Satisfaction,11,0.151584,Budget,Monitor,GE 6-Device Backlit Universal Remote Control f...,250,bought streaming roku pink super setup work re...
79,Satisfaction,11,0.148480,Budget,Priority review,Philips Universal Remote Control Replacement f...,250,remote hoped guessing tv issue remote issue in...
80,Satisfaction,11,0.145393,Budget,Monitor,GE 6-Device Backlit Universal Remote Control f...,243,program clear step step instructions follow te...
81,Satisfaction,12,0.159005,Upper mid,Monitor,EBL 2800mAh Ni-MH AA Rechargeable Batteries (8...,250,battery remote controls video game controllers...
82,Satisfaction,12,0.154954,Upper mid,Monitor,EBL 12 Bay LCD Universal Battery Charger for R...,117,battery charger work christmas battery charger...
83,Satisfaction,12,0.151654,Lower mid,Monitor,BONAI Smart Battery Charger for AA AAA C D 9V ...,123,work ordered rechargable battery charge batter...
84,Satisfaction,13,0.208704,Upper mid,Monitor,Antennas Direct ClearStream 1MAX HDTV Antenna ...,60,beautiful clear pic channels antennas bought w...
85,Satisfaction,13,0.208332,Premium,Monitor,Channel Master ULTRAtenna Outdoor TV Antenna M...,152,antenna mounted motor stationary location plyw...
86,Satisfaction,13,0.207433,Upper mid,Priority review,RCA ANT121Z Durable Passive Indoor Antenna Black,158,install picture_quality reservations picked ch...
87,Satisfaction,14,0.173288,Premium,Priority review,Amazfit GTS 2 Mini Smart Watch for Women Girls...,141,smart watch features wife battery_life likes r...
88,Satisfaction,14,0.173173,Upper mid,Monitor,TOZO S2 40mm Mini Smart Watch Alexa Built-in F...,130,owned smartwatch ability watch limited general...
89,Satisfaction,14,0.172319,Premium,Priority review,"Fitbit Versa Smart Watch, Gray/Silver Aluminiu...",171,stopped_working answers emails watch heart rat...

In [35]:
# Calculating topic assignment confidence for each document

def compute_assignment_margin(topic_matrix):
    sorted_strengths = np.sort(topic_matrix, axis = 1)
    max_strength = sorted_strengths[ : , -1]
    second_strength = sorted_strengths[ : , -2]
    return max_strength - second_strength


full_dissatisfaction_topic_review_dataframe["topic_margin"] = compute_assignment_margin(
    selected_document_topic_matrix
)

full_comparison_dataframe["topic_margin"] = compute_assignment_margin(
    full_comparison_topic_matrix
)

assignment_confidence_summary_dataframe = (
    pd.concat(
        [
            full_dissatisfaction_topic_review_dataframe.assign(cohort_role = "Dissatisfaction"),
            full_comparison_dataframe.assign(cohort_role = "Satisfaction")
        ],
        ignore_index = True
    )
    .groupby(["cohort_role", "topic_id"], dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        average_topic_strength = ("topic_strength", "mean"),
        median_topic_strength = ("topic_strength", "median"),
        average_topic_margin = ("topic_margin", "mean"),
        median_topic_margin = ("topic_margin", "median"),
        low_margin_document_count = ("topic_margin", lambda values: (values < 0.015).sum())
    )
    .reset_index()
    .sort_values(["cohort_role", "topic_id"])
)

display(assignment_confidence_summary_dataframe)

,cohort_role,topic_id,document_count,average_topic_strength,median_topic_strength,average_topic_margin,median_topic_margin,low_margin_document_count
0,Dissatisfaction,0,830,0.061121,0.066148,0.048389,0.055147,126
1,Dissatisfaction,1,1937,0.087805,0.089475,0.065651,0.067718,160
2,Dissatisfaction,2,1649,0.075462,0.074127,0.055432,0.055434,218
3,Dissatisfaction,3,1231,0.086244,0.089526,0.067411,0.072081,330
4,Dissatisfaction,4,1545,0.075803,0.074010,0.055108,0.044309,313
5,Dissatisfaction,5,945,0.089500,0.094093,0.068815,0.076124,158
6,Dissatisfaction,6,1246,0.069002,0.062515,0.047992,0.036532,300
7,Dissatisfaction,7,1339,0.077219,0.075124,0.053167,0.047307,297
8,Dissatisfaction,8,1508,0.061545,0.061543,0.033555,0.030727,386
9,Dissatisfaction,9,1109,0.075755,0.080711,0.050545,0.053225,258
10,Dissatisfaction,10,507,0.115678,0.137356,0.101886,0.128618,90
11,Dissatisfaction,11,915,0.077447,0.080516,0.055333,0.058762,224
12,Dissatisfaction,12,1060,0.071391,0.054123,0.048695,0.023479,391
13,Dissatisfaction,13,558,0.100459,0.080365,0.073351,0.044054,137
14,Dissatisfaction,14,474,0.106606,0.122029,0.085495,0.102129,84
15,Satisfaction,0,822,0.053412,0.057871,0.038726,0.042711,158
16,Satisfaction,1,1926,0.088255,0.092106,0.071396,0.075994,155
17,Satisfaction,2,2268,0.065271,0.065944,0.045905,0.044300,433
18,Satisfaction,3,1171,0.068559,0.069954,0.051563,0.055117,336
19,Satisfaction,4,1571,0.063656,0.060381,0.043855,0.034646,383
20,Satisfaction,5,933,0.077449,0.083086,0.058231,0.065471,191
21,Satisfaction,6,1664,0.059402,0.051380,0.038379,0.026082,557
22,Satisfaction,7,1759,0.068607,0.062825,0.048240,0.040443,445
23,Satisfaction,8,1767,0.060918,0.061700,0.038588,0.038815,388
24,Satisfaction,9,1163,0.068694,0.070386,0.044873,0.043076,305
25,Satisfaction,10,515,0.096046,0.111570,0.081861,0.102535,121
26,Satisfaction,11,923,0.070782,0.073483,0.051291,0.054138,253
27,Satisfaction,12,740,0.064315,0.055074,0.045600,0.029827,276
28,Satisfaction,13,593,0.096746,0.081252,0.070904,0.048248,123
29,Satisfaction,14,545,0.100322,0.116570,0.085002,0.104275,128

In [36]:
# Checking whether text clipping is biasing topic assignments

topic_clipping_bias_dataframe = (
    full_topic_assignment_dataframe
    .groupby(["cohort_role", "topic_id", "clipping_applied"], dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        sampled_reviews = ("sampled_review_count", "sum")
    )
    .reset_index()
)

topic_clipping_totals_dataframe = (
    topic_clipping_bias_dataframe
    .groupby(["cohort_role", "topic_id"], dropna = False)
    .agg(
        total_document_count = ("document_count", "sum"),
        total_sampled_reviews = ("sampled_reviews", "sum")
    )
    .reset_index()
)

topic_clipping_bias_dataframe = topic_clipping_bias_dataframe.merge(
    topic_clipping_totals_dataframe,
    on = ["cohort_role", "topic_id"],
    how = "left"
)

topic_clipping_bias_dataframe["document_share_within_topic"] = (
    topic_clipping_bias_dataframe["document_count"] /
    topic_clipping_bias_dataframe["total_document_count"]
)

display(
    topic_clipping_bias_dataframe.sort_values(
        ["cohort_role", "topic_id", "clipping_applied"]
    )
)

,cohort_role,topic_id,clipping_applied,document_count,sampled_reviews,total_document_count,total_sampled_reviews,document_share_within_topic
0,Dissatisfaction,0,False,413,29761,830,126020,0.497590
1,Dissatisfaction,0,True,417,96259,830,126020,0.502410
2,Dissatisfaction,1,False,1007,72968,1937,285262,0.519876
3,Dissatisfaction,1,True,930,212294,1937,285262,0.480124
4,Dissatisfaction,2,False,1319,79567,1649,151277,0.799879
5,Dissatisfaction,2,True,330,71710,1649,151277,0.200121
6,Dissatisfaction,3,False,740,53337,1231,162709,0.601137
7,Dissatisfaction,3,True,491,109372,1231,162709,0.398863
8,Dissatisfaction,4,False,1038,69331,1545,183129,0.671845
9,Dissatisfaction,4,True,507,113798,1545,183129,0.328155
10,Dissatisfaction,5,False,580,41119,945,124495,0.613757
11,Dissatisfaction,5,True,365,83376,945,124495,0.386243
12,Dissatisfaction,6,False,1036,60574,1246,105915,0.831461
13,Dissatisfaction,6,True,210,45341,1246,105915,0.168539
14,Dissatisfaction,7,False,898,57575,1339,156051,0.670650
15,Dissatisfaction,7,True,441,98476,1339,156051,0.329350
16,Dissatisfaction,8,False,982,66923,1508,185948,0.651194
17,Dissatisfaction,8,True,526,119025,1508,185948,0.348806
18,Dissatisfaction,9,False,834,55963,1109,116610,0.752029
19,Dissatisfaction,9,True,275,60647,1109,116610,0.247971
20,Dissatisfaction,10,False,379,24483,507,51465,0.747535
21,Dissatisfaction,10,True,128,26982,507,51465,0.252465
22,Dissatisfaction,11,False,579,40074,915,116085,0.632787
23,Dissatisfaction,11,True,336,76011,915,116085,0.367213
24,Dissatisfaction,12,False,792,51799,1060,109780,0.747170
25,Dissatisfaction,12,True,268,57981,1060,109780,0.252830
26,Dissatisfaction,13,False,381,27145,558,66470,0.682796
27,Dissatisfaction,13,True,177,39325,558,66470,0.317204
28,Dissatisfaction,14,False,341,23682,474,52127,0.719409
29,Dissatisfaction,14,True,133,28445,474,52127,0.280591
30,Satisfaction,0,False,459,31658,822,113852,0.558394
31,Satisfaction,0,True,363,82194,822,113852,0.441606
32,Satisfaction,1,False,1157,79855,1926,253887,0.600727
33,Satisfaction,1,True,769,174032,1926,253887,0.399273
34,Satisfaction,2,False,1750,103140,2268,216156,0.771605
35,Satisfaction,2,True,518,113016,2268,216156,0.228395
36,Satisfaction,3,False,813,52298,1171,130872,0.694278
37,Satisfaction,3,True,358,78574,1171,130872,0.305722
38,Satisfaction,4,False,1099,68154,1571,171371,0.699554
39,Satisfaction,4,True,472,103217,1571,171371,0.300446
40,Satisfaction,5,False,621,40127,933,110320,0.665595
41,Satisfaction,5,True,312,70193,933,110320,0.334405
42,Satisfaction,6,False,1372,79101,1664,142767,0.824519
43,Satisfaction,6,True,292,63666,1664,142767,0.175481
44,Satisfaction,7,False,1282,77006,1759,182050,0.728823
45,Satisfaction,7,True,477,105044,1759,182050,0.271177
46,Satisfaction,8,False,1188,76196,1767,208146,0.672326
47,Satisfaction,8,True,579,131950,1767,208146,0.327674
48,Satisfaction,9,False,883,54857,1163,116659,0.759243
49,Satisfaction,9,True,280,61802,1163,116659,0.240757
50,Satisfaction,10,False,397,23748,515,49783,0.770874
51,Satisfaction,10,True,118,26035,515,49783,0.229126
52,Satisfaction,11,False,627,38100,923,103688,0.679307
53,Satisfaction,11,True,296,65588,923,103688,0.320693
54,Satisfaction,12,False,623,35145,740,60861,0.841892
55,Satisfaction,12,True,117,25716,740,60861,0.158108
56,Satisfaction,13,False,404,25643,593,67822,0.681282
57,Satisfaction,13,True,189,42179,593,67822,0.318718
58,Satisfaction,14,False,399,24495,545,56722,0.732110
59,Satisfaction,14,True,146,32227,545,56722,0.267890

In [37]:
# Checking topic segment reliability for reporting use

topic_segment_reporting_eligibility_dataframe = (
    full_topic_assignment_dataframe
    .groupby(["cohort_role", "topic_id", "price_band", "issue_priority_level"], dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        sampled_reviews = ("sampled_review_count", "sum")
    )
    .reset_index()
    .pivot(
        index = ["topic_id", "price_band", "issue_priority_level"],
        columns = "cohort_role",
        values = ["document_count", "sampled_reviews"]
    )
)

topic_segment_reporting_eligibility_dataframe.columns = [
    f"{metric_name}_{cohort_name.lower()}"
    for metric_name, cohort_name in topic_segment_reporting_eligibility_dataframe.columns
]

topic_segment_reporting_eligibility_dataframe = (
    topic_segment_reporting_eligibility_dataframe
    .reset_index()
    .fillna(0)
)

topic_segment_reporting_eligibility_dataframe["is_segment_reporting_eligible"] = (
    (topic_segment_reporting_eligibility_dataframe["document_count_dissatisfaction"] >= 25)
    & (topic_segment_reporting_eligibility_dataframe["document_count_satisfaction"] >= 25)
    & (topic_segment_reporting_eligibility_dataframe["sampled_reviews_dissatisfaction"] >= 3000)
    & (topic_segment_reporting_eligibility_dataframe["sampled_reviews_satisfaction"] >= 3000)
)

display(
    topic_segment_reporting_eligibility_dataframe.sort_values(
        ["topic_id", "price_band", "issue_priority_level"]
    )
)

/var/folders/f1/ws24m5bs3cx9_1d_nclvhd1w0000gn/T/ipykernel_51314/1094106930.py:26: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .fillna(0)

,topic_id,price_band,issue_priority_level,document_count_dissatisfaction,document_count_satisfaction,sampled_reviews_dissatisfaction,sampled_reviews_satisfaction,is_segment_reporting_eligible
0,0,Budget,Monitor,33,78,4398,9898,True
1,0,Budget,Priority review,17,21,3800,4831,False
2,0,Lower mid,Monitor,94,87,12647,8530,True
3,0,Lower mid,Priority review,44,52,6897,9354,True
4,0,Premium,Monitor,208,170,31662,21919,True
5,0,Premium,Priority review,108,111,16848,17245,True
6,0,Upper mid,Monitor,163,142,24033,15990,True
7,0,Upper mid,Priority review,131,135,20960,23164,True
8,0,Very premium,Monitor,32,26,4775,2921,False
9,1,Budget,Monitor,194,214,22368,21397,True
10,1,Budget,Priority review,162,155,25603,21466,True
11,1,Lower mid,Monitor,402,363,64214,48740,True
12,1,Lower mid,Priority review,158,170,23102,25381,True
13,1,Premium,Monitor,200,207,25030,22907,True
14,1,Premium,Priority review,204,198,38108,33676,True
15,1,Upper mid,Monitor,356,347,47481,40916,True
16,1,Upper mid,Priority review,218,226,35038,35296,True
17,1,Very premium,Monitor,43,46,4318,4108,True
18,2,Budget,Monitor,401,528,35790,46144,True
19,2,Budget,Priority review,49,48,5570,6792,True
20,2,Lower mid,Monitor,664,898,56168,78906,True
21,2,Lower mid,Priority review,106,106,16669,16537,True
22,2,Premium,Monitor,40,85,2667,8597,False
23,2,Premium,Priority review,15,28,1945,3723,False
24,2,Upper mid,Monitor,325,495,25691,45497,True
25,2,Upper mid,Priority review,47,65,6672,8862,True
26,2,Very premium,Monitor,2,15,105,1098,False
27,3,Budget,Monitor,573,522,73269,53554,True
28,3,Budget,Priority review,258,222,41837,34542,True
29,3,Lower mid,Monitor,235,248,26377,23138,True
30,3,Lower mid,Priority review,84,73,14085,11103,True
31,3,Premium,Monitor,7,13,669,1127,False
32,3,Premium,Priority review,4,3,446,312,False
33,3,Upper mid,Monitor,60,74,4469,5242,True
34,3,Upper mid,Priority review,8,11,1455,1607,False
35,3,Very premium,Monitor,2,5,102,247,False
36,4,Budget,Monitor,288,310,36513,34128,True
37,4,Budget,Priority review,45,43,6787,6501,True
38,4,Lower mid,Monitor,272,268,30535,26478,True
39,4,Lower mid,Priority review,55,51,7551,6118,True
40,4,Premium,Monitor,322,356,35118,35108,True
41,4,Premium,Priority review,89,92,11221,11725,True
42,4,Upper mid,Monitor,324,309,36256,34224,True
43,4,Upper mid,Priority review,60,57,9451,8573,True
44,4,Very premium,Monitor,90,85,9697,8516,True
45,5,Budget,Monitor,132,133,15516,13165,True
46,5,Budget,Priority review,78,89,13942,16333,True
47,5,Lower mid,Monitor,160,148,20752,15258,True
48,5,Lower mid,Priority review,90,85,14924,13875,True
49,5,Premium,Monitor,109,119,11500,10649,True
50,5,Premium,Priority review,41,47,4298,5333,True
51,5,Upper mid,Monitor,203,176,25478,17824,True
52,5,Upper mid,Priority review,107,106,15353,15713,True
53,5,Very premium,Monitor,25,30,2732,2170,False
54,6,Budget,Monitor,209,271,13828,17469,True
55,6,Budget,Priority review,47,38,6066,5227,True
56,6,Lower mid,Monitor,312,433,26924,37937,True
57,6,Lower mid,Priority review,50,53,6604,6973,True
58,6,Premium,Monitor,188,250,13450,18869,True
59,6,Premium,Priority review,16,22,2514,3020,False
60,6,Upper mid,Monitor,378,536,31516,45870,True
61,6,Upper mid,Priority review,34,43,4246,5990,True
62,6,Very premium,Monitor,12,18,767,1412,False
63,7,Budget,Monitor,56,137,3820,10506,True
64,7,Budget,Priority review,10,21,1035,2924,False
65,7,Lower mid,Monitor,84,116,7463,9340,True
66,7,Lower mid,Priority review,51,63,8866,10724,True
67,7,Premium,Monitor,397,531,36513,46073,True
68,7,Premium,Priority review,216,228,33698,35191,True
69,7,Upper mid,Monitor,283,321,33500,31771,True
70,7,Upper mid,Priority review,144,149,24390,24342,True
71,7,Very premium,Monitor,98,193,6766,11179,True
72,8,Budget,Monitor,127,155,12443,14007,True
73,8,Budget,Priority review,43,58,6526,8630,True
74,8,Lower mid,Monitor,226,241,32260,30827,True
75,8,Lower mid,Priority review,55,64,7278,8448,True
76,8,Premium,Monitor,340,435,34393,43273,True
77,8,Premium,Priority review,116,128,15591,18358,True
78,8,Upper mid,Monitor,354,408,45806,49327,True
79,8,Upper mid,Priority review,173,185,26271,28055,True
80,8,Very premium,Monitor,74,93,5380,7221,True
81,9,Budget,Monitor,288,324,27543,31144,True
82,9,Budget,Priority review,97,91,16334,15798,True
83,9,Lower mid,Monitor,180,193,17483,17124,True
84,9,Lower mid,Priority review,35,38,4343,4944,True
85,9,Premium,Monitor,197,201,18375,17193,True
86,9,Premium,Priority review,63,60,7863,8023,True
87,9,Upper mid,Monitor,129,127,12831,10523,True
88,9,Upper mid,Priority review,49,50,6765,6957,True
89,9,Very premium,Monitor,71,79,5073,4953,True
90,10,Budget,Monitor,288,277,27261,22812,True
91,10,Budget,Priority review,87,85,12821,13291,True
92,10,Lower mid,Monitor,81,78,6964,7322,True
93,10,Lower mid,Priority review,15,15,1608,1538,False
94,10,Premium,Monitor,9,15,762,1106,False
95,10,Premium,Priority review,0,3,0,293,False
96,10,Upper mid,Monitor,23,33,1505,2595,False
97,10,Upper mid,Priority review,1,7,250,734,False
98,10,Very premium,Monitor,3,2,294,92,False
99,11,Budget,Monitor,170,190,15540,12703,True
100,11,Budget,Priority review,77,82,11745,13669,True
101,11,Lower mid,Monitor,59,79,6637,10064,True
102,11,Lower mid,Priority review,40,33,5447,3966,True
103,11,Premium,Monitor,191,182,25343,20887,True
104,11,Premium,Priority review,94,83,11256,9445,True
105,11,Upper mid,Monitor,170,158,26227,21546,True
106,11,Upper mid,Priority review,58,56,8091,7180,True
107,11,Very premium,Monitor,56,60,5799,4228,True
108,12,Budget,Monitor,169,172,12591,10798,True
109,12,Budget,Priority review,25,24,3221,3299,False
110,12,Lower mid,Monitor,255,212,20708,12907,True
111,12,Lower mid,Priority review,61,45,8638,6690,True
112,12,Premium,Monitor,150,60,19699,6752,True
113,12,Premium,Priority review,65,25,8721,3745,True
114,12,Upper mid,Monitor,212,156,20170,11305,True
115,12,Upper mid,Priority review,98,42,14014,5191,True
116,12,Very premium,Monitor,25,4,2018,174,False
117,13,Budget,Monitor,48,63,3918,4353,True
118,13,Budget,Priority review,30,32,4183,5772,True
119,13,Lower mid,Monitor,67,72,7435,6850,True
120,13,Lower mid,Priority review,55,57,8835,8922,True
121,13,Premium,Monitor,97,99,9899,9481,True
122,13,Premium,Priority review,39,42,5158,5949,True
123,13,Upper mid,Monitor,141,154,15967,16064,True
124,13,Upper mid,Priority review,68,58,10367,9663,True
125,13,Very premium,Monitor,13,16,708,768,False
126,14,Budget,Monitor,112,140,9661,9956,True
127,14,Budget,Priority review,30,28,3783,4140,True
128,14,Lower mid,Monitor,51,64,4375,4731,True
129,14,Lower mid,Priority review,20,21,3012,3281,False
130,14,Premium,Monitor,60,66,6086,6238,True
131,14,Premium,Priority review,77,87,11973,13580,True
132,14,Upper mid,Monitor,55,62,4602,4738,True
133,14,Upper mid,Priority review,52,61,7137,9059,True
134,14,Very premium,Monitor,17,16,1498,999,False

In [38]:
# Measuring overall topic weight share across dissatisfied documents

dissatisfaction_topic_weight_share = (
    selected_document_topic_matrix.sum(axis = 0) /
    selected_document_topic_matrix.sum()
)

satisfaction_topic_weight_share = (
    full_comparison_topic_matrix.sum(axis = 0) /
    full_comparison_topic_matrix.sum()
)

soft_topic_comparison_dataframe = pd.DataFrame({
    "topic_id": np.arange(selected_topic_count),
    "topic_weight_share_dissatisfaction": dissatisfaction_topic_weight_share,
    "topic_weight_share_satisfaction": satisfaction_topic_weight_share
})

soft_topic_comparison_dataframe["topic_weight_share_lift_dissatisfaction_vs_satisfaction"] = (
    (soft_topic_comparison_dataframe["topic_weight_share_dissatisfaction"] + 1e-6) /
    (soft_topic_comparison_dataframe["topic_weight_share_satisfaction"] + 1e-6)
)

soft_topic_comparison_dataframe["topic_weight_share_gap"] = (
    soft_topic_comparison_dataframe["topic_weight_share_dissatisfaction"] -
    soft_topic_comparison_dataframe["topic_weight_share_satisfaction"]
)

display(
    soft_topic_comparison_dataframe.sort_values(
        by = "topic_weight_share_lift_dissatisfaction_vs_satisfaction",
        ascending = False
    )
)

,topic_id,topic_weight_share_dissatisfaction,topic_weight_share_satisfaction,topic_weight_share_lift_dissatisfaction_vs_satisfaction,topic_weight_share_gap
12,12,0.082268,0.050882,1.616824,0.031386
3,3,0.076694,0.059047,1.298866,0.017647
0,0,0.043807,0.034378,1.274283,0.009430
4,4,0.079433,0.069354,1.145317,0.010078
10,10,0.048469,0.044053,1.100252,0.004416
11,11,0.060327,0.055149,1.093902,0.005179
5,5,0.059885,0.055270,1.083497,0.004615
9,9,0.069385,0.068057,1.019514,0.001328
1,1,0.089549,0.093391,0.958862,-0.003842
8,8,0.071682,0.080550,0.889906,-0.008868
13,13,0.046565,0.052410,0.888472,-0.005845
7,7,0.074035,0.086589,0.855017,-0.012554
14,14,0.044610,0.054867,0.813049,-0.010258
6,6,0.069892,0.088758,0.787445,-0.018866
2,2,0.083400,0.107245,0.777654,-0.023846

In [39]:
# Building topic-level driver metrics for business interpretation

topic_driver_core_dataframe = (
    full_topic_summary_dataframe[
        [
            "topic_id",
            "document_count",
            "total_sampled_reviews",
            "average_topic_strength",
            "average_rating",
            "average_helpful_vote",
            "top_terms"
        ]
    ]
    .merge(
        topic_comparison_summary_dataframe[
            [
                "topic_id",
                "document_count_dissatisfaction",
                "document_count_satisfaction",
                "sampled_reviews_dissatisfaction",
                "sampled_reviews_satisfaction",
                "document_share_dissatisfaction",
                "document_share_satisfaction",
                "document_share_lift_dissatisfaction_vs_satisfaction",
                "sampled_review_share_lift_dissatisfaction_vs_satisfaction",
                "document_share_gap",
                "max_top_term_jaccard_overlap"
            ]
        ],
        on = "topic_id",
        how = "left"
    )
    .merge(
        assignment_confidence_summary_dataframe.loc[
            assignment_confidence_summary_dataframe["cohort_role"] == "Dissatisfaction",
            [
                "topic_id",
                "average_topic_margin",
                "median_topic_margin",
                "low_margin_document_count"
            ]
        ],
        on = "topic_id",
        how = "left"
    )
    .merge(
        soft_topic_comparison_dataframe[
            [
                "topic_id",
                "topic_weight_share_dissatisfaction",
                "topic_weight_share_satisfaction",
                "topic_weight_share_lift_dissatisfaction_vs_satisfaction",
                "topic_weight_share_gap"
            ]
        ],
        on = "topic_id",
        how = "left"
    )
)

topic_driver_core_dataframe["low_margin_document_ratio"] = (
    topic_driver_core_dataframe["low_margin_document_count"] /
    topic_driver_core_dataframe["document_count"].replace(0, np.nan)
)

display(
    topic_driver_core_dataframe.sort_values(
        by = [
            "document_share_lift_dissatisfaction_vs_satisfaction",
            "topic_weight_share_lift_dissatisfaction_vs_satisfaction",
            "document_count"
        ],
        ascending = [False, False, False]
    )
)

,topic_id,document_count,total_sampled_reviews,average_topic_strength,average_rating,average_helpful_vote,top_terms,document_count_dissatisfaction,document_count_satisfaction,sampled_reviews_dissatisfaction,sampled_reviews_satisfaction,document_share_dissatisfaction,document_share_satisfaction,document_share_lift_dissatisfaction_vs_satisfaction,sampled_review_share_lift_dissatisfaction_vs_satisfaction,document_share_gap,max_top_term_jaccard_overlap,average_topic_margin,median_topic_margin,low_margin_document_count,topic_weight_share_dissatisfaction,topic_weight_share_satisfaction,topic_weight_share_lift_dissatisfaction_vs_satisfaction,topic_weight_share_gap,low_margin_document_ratio
8,12,1060,109780,0.071391,1.256757,2.432281,"charger, charge battery, hold charge, battery ...",1060,740,109780,60861,0.062897,0.040305,1.560507,1.796167,0.022592,0.111111,0.048695,0.023479,391,0.082268,0.050882,1.616824,0.031386,0.368868
6,3,1231,162709,0.086244,1.256194,1.215423,"charge phone, cords, chargers, charger, not_ch...",1231,1171,162709,130872,0.073043,0.063780,1.145238,1.238034,0.009263,0.111111,0.067411,0.072081,330,0.076694,0.059047,1.298866,0.017647,0.268075
9,5,945,124495,0.089500,1.340732,1.209011,"mouse, keyboard, keys, logitech, mouse work, k...",945,933,124495,110320,0.056073,0.050817,1.103430,1.123739,0.005256,0.000000,0.068815,0.076124,158,0.059885,0.055270,1.083497,0.004615,0.167196
11,0,830,126020,0.061121,1.267146,2.398637,"router, wifi, network, internet, modem, netgea...",830,822,126020,113852,0.049249,0.044771,1.100021,1.102217,0.004478,0.034483,0.048389,0.055147,126,0.043807,0.034378,1.274283,0.009430,0.151807
0,1,1937,285262,0.087805,1.358950,1.290585,"ear, headphone, earbuds, ears, buds, earbud, s...",1937,1926,285262,253887,0.114935,0.104902,1.095641,1.11885,0.010033,0.071429,0.065651,0.067718,160,0.089549,0.093391,0.958862,-0.003842,0.082602
10,11,915,116085,0.077447,1.276203,2.052309,"remote, remote work, remotes, buttons, remote ...",915,923,116085,103688,0.054293,0.050272,1.079976,1.114848,0.004021,0.000000,0.055333,0.058762,224,0.060327,0.055149,1.093902,0.005179,0.244809
13,10,507,51465,0.115678,1.300156,1.057393,"bubbles, screen_protector, protectors, screen ...",507,515,51465,49783,0.030084,0.028050,1.072495,1.029436,0.002034,0.000000,0.101886,0.128618,90,0.048469,0.044053,1.100252,0.004416,0.177515
2,4,1545,183129,0.075803,1.231458,2.416205,"drive, drives, files, disk, data, hard_drive, ...",1545,1571,183129,171371,0.091675,0.085566,1.071390,1.064114,0.006109,0.000000,0.055108,0.044309,313,0.079433,0.069354,1.145317,0.010078,0.202589
7,9,1109,116610,0.075755,1.261656,1.617113,"hdmi, monitor, hdmi cable, display, adapter, p...",1109,1163,116610,116659,0.065804,0.063344,1.038836,0.995374,0.002460,0.034483,0.050545,0.053225,258,0.069385,0.068057,1.019514,0.001328,0.232642
12,13,558,66470,0.100459,1.314494,2.045112,"antenna, stations, reception, channels, miles,...",558,593,66470,67822,0.033110,0.032298,1.025120,0.975943,0.000811,0.034483,0.073351,0.044054,137,0.046565,0.052410,0.888472,-0.005845,0.245520
14,14,474,52127,0.106606,1.326081,2.023808,"fitbit, band, wrist, watch, bands, heart rate,...",474,545,52127,56722,0.028126,0.029684,0.947498,0.915127,-0.001559,0.000000,0.085495,0.102129,84,0.044610,0.054867,0.813049,-0.010258,0.177215
3,8,1508,185948,0.061545,1.324395,1.637885,"speaker, sound_quality, music, bluetooth, bass...",1508,1767,185948,208146,0.089480,0.096242,0.929738,0.889596,-0.006762,0.071429,0.033555,0.030727,386,0.071682,0.080550,0.889906,-0.008868,0.255968
4,7,1339,156051,0.077219,1.303286,3.327786,"camera, camera work, motion, recording, view, ...",1339,1759,156051,182050,0.079452,0.095806,0.829299,0.853583,-0.016354,0.000000,0.053167,0.047307,297,0.074035,0.086589,0.855017,-0.012554,0.221807
5,6,1246,105915,0.069002,1.359285,1.684490,"screws, mount, screw, mounting, bracket, tight...",1246,1664,105915,142767,0.073933,0.090632,0.815758,0.738755,-0.016698,0.000000,0.047992,0.036532,300,0.069892,0.088758,0.787445,-0.018866,0.240770
1,2,1649,151277,0.075462,1.377515,1.053450,"ipad, not_fit, protect, color, cases, fits, co...",1649,2268,151277,216156,0.097846,0.123529,0.792089,0.696909,-0.025683,0.034483,0.055432,0.055434,218,0.083400,0.107245,0.777654,-0.023846,0.132201

In [40]:
# Reviewing dissatisfied topic distribution across price and priority segments
dissatisfaction_topic_segment_distribution_dataframe = (
    full_dissatisfaction_topic_review_dataframe
    .groupby(["topic_id", "price_band", "issue_priority_level"], dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        sampled_reviews = ("sampled_review_count", "sum")
    )
    .reset_index()
)

dissatisfaction_topic_segment_distribution_dataframe["segment_document_share_within_topic"] = (
    dissatisfaction_topic_segment_distribution_dataframe["document_count"] /
    dissatisfaction_topic_segment_distribution_dataframe.groupby("topic_id")["document_count"].transform("sum")
)

topic_breadth_summary_dataframe = (
    dissatisfaction_topic_segment_distribution_dataframe
    .groupby("topic_id", dropna = False)
    .agg(
        covered_segment_count = ("segment_document_share_within_topic", "count"),
        segment_count_above_05_share = (
            "segment_document_share_within_topic",
            lambda values: (values >= 0.05).sum()
        ),
        segment_count_above_10_share = (
            "segment_document_share_within_topic",
            lambda values: (values >= 0.10).sum()
        ),
        max_segment_share = ("segment_document_share_within_topic", "max"),
        concentration_hhi = (
            "segment_document_share_within_topic",
            lambda values: np.square(values).sum()
        )
    )
    .reset_index()
)

display(
    topic_breadth_summary_dataframe.sort_values(
        by = ["concentration_hhi", "max_segment_share"],
        ascending = [False, False]
    )
)

,topic_id,covered_segment_count,segment_count_above_05_share,segment_count_above_10_share,max_segment_share,concentration_hhi
10,10,8,3,3,0.568047,0.380935
3,3,9,4,3,0.465475,0.304157
2,2,9,4,3,0.402668,0.266621
6,6,9,4,4,0.303371,0.209671
7,7,9,6,4,0.296490,0.182711
4,4,9,6,4,0.209709,0.163492
0,0,9,6,5,0.250602,0.162334
12,12,9,7,4,0.240566,0.160048
8,8,9,6,4,0.234748,0.159123
9,9,9,7,4,0.259693,0.156795
13,13,9,8,4,0.252688,0.148771
11,11,9,8,4,0.208743,0.144080
14,14,9,7,6,0.236287,0.142392
5,5,9,7,5,0.214815,0.138913
1,1,9,8,6,0.207537,0.135442

In [41]:
# Comparing topic exposure by price band across customer cohorts

topic_price_band_comparison_dataframe = (
    full_topic_assignment_dataframe
    .groupby(["cohort_role", "topic_id", "price_band"], dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        sampled_reviews = ("sampled_review_count", "sum")
    )
    .reset_index()
)

topic_price_band_totals_dataframe = (
    topic_price_band_comparison_dataframe
    .groupby(["cohort_role", "topic_id"], dropna = False)
    .agg(
        total_documents = ("document_count", "sum"),
        total_sampled_reviews = ("sampled_reviews", "sum")
    )
    .reset_index()
)

topic_price_band_comparison_dataframe = topic_price_band_comparison_dataframe.merge(
    topic_price_band_totals_dataframe,
    on = ["cohort_role", "topic_id"],
    how = "left"
)

topic_price_band_comparison_dataframe["document_share_within_topic"] = (
    topic_price_band_comparison_dataframe["document_count"] /
    topic_price_band_comparison_dataframe["total_documents"].replace(0, np.nan)
)

topic_price_band_comparison_dataframe = (
    topic_price_band_comparison_dataframe
    .pivot_table(
        index = ["topic_id", "price_band"],
        columns = "cohort_role",
        values = ["document_count", "sampled_reviews", "document_share_within_topic"],
        fill_value = 0
    )
)

topic_price_band_comparison_dataframe.columns = [
    f"{metric_name}_{cohort_name.lower()}"
    for metric_name, cohort_name in topic_price_band_comparison_dataframe.columns
]

topic_price_band_comparison_dataframe = (
    topic_price_band_comparison_dataframe
    .reset_index()
    .infer_objects(copy = False)
)

topic_price_band_comparison_dataframe["price_band_document_share_lift_dissatisfaction_vs_satisfaction"] = (
    (topic_price_band_comparison_dataframe["document_share_within_topic_dissatisfaction"] + 1e-6) /
    (topic_price_band_comparison_dataframe["document_share_within_topic_satisfaction"] + 1e-6)
)

display(
    topic_price_band_comparison_dataframe.sort_values(
        by = ["topic_id", "price_band"]
    )
)

,topic_id,price_band,document_count_dissatisfaction,document_count_satisfaction,document_share_within_topic_dissatisfaction,document_share_within_topic_satisfaction,sampled_reviews_dissatisfaction,sampled_reviews_satisfaction,price_band_document_share_lift_dissatisfaction_vs_satisfaction
0,0,Budget,50.0,99.0,0.060241,0.120438,8198.0,14729.0,0.500187
1,0,Lower mid,138.0,139.0,0.166265,0.169100,19544.0,17884.0,0.983237
2,0,Premium,316.0,281.0,0.380723,0.341849,48510.0,39164.0,1.113716
3,0,Upper mid,294.0,277.0,0.354217,0.336983,44993.0,39154.0,1.051142
4,0,Very premium,32.0,26.0,0.038554,0.031630,4775.0,2921.0,1.218899
5,1,Budget,356.0,369.0,0.183789,0.191589,47971.0,42863.0,0.959291
6,1,Lower mid,560.0,533.0,0.289107,0.276739,87316.0,74121.0,1.044690
7,1,Premium,404.0,405.0,0.208570,0.210280,63138.0,56583.0,0.991866
8,1,Upper mid,574.0,573.0,0.296335,0.297508,82519.0,76212.0,0.996056
9,1,Very premium,43.0,46.0,0.022199,0.023884,4318.0,4108.0,0.929477
10,2,Budget,450.0,576.0,0.272893,0.253968,41360.0,52936.0,1.074515
11,2,Lower mid,770.0,1004.0,0.466950,0.442681,72837.0,95443.0,1.054822
12,2,Premium,55.0,113.0,0.033354,0.049824,4612.0,12320.0,0.669439
13,2,Upper mid,372.0,560.0,0.225591,0.246914,32363.0,54359.0,0.913645
14,2,Very premium,2.0,15.0,0.001213,0.006614,105.0,1098.0,0.183507
15,3,Budget,831.0,744.0,0.675061,0.635354,115106.0,88096.0,1.062495
16,3,Lower mid,319.0,321.0,0.259139,0.274125,40462.0,34241.0,0.945332
17,3,Premium,11.0,16.0,0.008936,0.013664,1115.0,1439.0,0.654016
18,3,Upper mid,68.0,85.0,0.055240,0.072588,5924.0,6849.0,0.761011
19,3,Very premium,2.0,5.0,0.001625,0.004270,102.0,247.0,0.380649
20,4,Budget,333.0,353.0,0.215534,0.224698,43300.0,40629.0,0.959218
21,4,Lower mid,327.0,319.0,0.211650,0.203055,38086.0,32596.0,1.042329
22,4,Premium,411.0,448.0,0.266019,0.285169,46339.0,46833.0,0.932850
23,4,Upper mid,384.0,366.0,0.248544,0.232973,45707.0,42797.0,1.066836
24,4,Very premium,90.0,85.0,0.058252,0.054106,9697.0,8516.0,1.076641
25,5,Budget,210.0,222.0,0.222222,0.237942,29458.0,29498.0,0.933934
26,5,Lower mid,250.0,233.0,0.264550,0.249732,35676.0,29133.0,1.059336
27,5,Premium,150.0,166.0,0.158730,0.177921,15798.0,15982.0,0.892141
28,5,Upper mid,310.0,282.0,0.328042,0.302251,40831.0,33537.0,1.085331
29,5,Very premium,25.0,30.0,0.026455,0.032154,2732.0,2170.0,0.822757
30,6,Budget,256.0,309.0,0.205457,0.185697,19894.0,22696.0,1.106411
31,6,Lower mid,362.0,486.0,0.290530,0.292067,33528.0,44910.0,0.994735
32,6,Premium,204.0,272.0,0.163724,0.163462,15964.0,21889.0,1.001605
33,6,Upper mid,412.0,579.0,0.330658,0.347957,35762.0,51860.0,0.950285
34,6,Very premium,12.0,18.0,0.009631,0.010817,767.0,1412.0,0.890326
35,7,Budget,66.0,158.0,0.049291,0.089824,4855.0,13430.0,0.548752
36,7,Lower mid,135.0,179.0,0.100822,0.101762,16329.0,20064.0,0.990754
37,7,Premium,613.0,759.0,0.457804,0.431495,70211.0,81264.0,1.060972
38,7,Upper mid,427.0,470.0,0.318895,0.267197,57890.0,56113.0,1.193480
39,7,Very premium,98.0,193.0,0.073189,0.109721,6766.0,11179.0,0.667046
40,8,Budget,170.0,213.0,0.112732,0.120543,18969.0,22637.0,0.935201
41,8,Lower mid,281.0,305.0,0.186340,0.172609,39538.0,39275.0,1.079547
42,8,Premium,456.0,563.0,0.302387,0.318619,49984.0,61631.0,0.949056
43,8,Upper mid,527.0,593.0,0.349469,0.335597,72077.0,77382.0,1.041336
44,8,Very premium,74.0,93.0,0.049072,0.052632,5380.0,7221.0,0.932362
45,9,Budget,385.0,415.0,0.347160,0.356836,43877.0,46942.0,0.972883
46,9,Lower mid,215.0,231.0,0.193868,0.198624,21826.0,22068.0,0.976056
47,9,Premium,260.0,261.0,0.234445,0.224420,26238.0,25216.0,1.044674
48,9,Upper mid,178.0,177.0,0.160505,0.152193,19596.0,17480.0,1.054617
49,9,Very premium,71.0,79.0,0.064022,0.067928,5073.0,4953.0,0.942497
50,10,Budget,375.0,362.0,0.739645,0.702913,40082.0,36103.0,1.052257
51,10,Lower mid,96.0,93.0,0.189349,0.180583,8572.0,8860.0,1.048546
52,10,Premium,9.0,18.0,0.017751,0.034951,762.0,1399.0,0.507904
53,10,Upper mid,24.0,40.0,0.047337,0.077670,1755.0,3329.0,0.609472
54,10,Very premium,3.0,2.0,0.005917,0.003883,294.0,92.0,1.523534
55,11,Budget,247.0,272.0,0.269945,0.294691,27285.0,26372.0,0.916028
56,11,Lower mid,99.0,112.0,0.108197,0.121343,12084.0,14030.0,0.891658
57,11,Premium,285.0,265.0,0.311475,0.287107,36599.0,30332.0,1.084874
58,11,Upper mid,228.0,214.0,0.249180,0.231853,34318.0,28726.0,1.074735
59,11,Very premium,56.0,60.0,0.061202,0.065005,5799.0,4228.0,0.941495
60,12,Budget,194.0,196.0,0.183019,0.264865,15812.0,14097.0,0.690991
61,12,Lower mid,316.0,257.0,0.298113,0.347297,29346.0,19597.0,0.858381
62,12,Premium,215.0,85.0,0.202830,0.114865,28420.0,10497.0,1.765809
63,12,Upper mid,310.0,198.0,0.292453,0.267568,34184.0,16496.0,1.093005
64,12,Very premium,25.0,4.0,0.023585,0.005405,2018.0,174.0,4.362585
65,13,Budget,78.0,95.0,0.139785,0.160202,8101.0,10125.0,0.872553
66,13,Lower mid,122.0,129.0,0.218638,0.217538,16270.0,15772.0,1.005057
67,13,Premium,136.0,141.0,0.243728,0.237774,15057.0,15430.0,1.025039
68,13,Upper mid,209.0,212.0,0.374552,0.357504,26334.0,25727.0,1.047685
69,13,Very premium,13.0,16.0,0.023297,0.026981,708.0,768.0,0.863468
70,14,Budget,142.0,168.0,0.299578,0.308257,13444.0,14096.0,0.971846
71,14,Lower mid,71.0,85.0,0.149789,0.155963,7387.0,8012.0,0.960412
72,14,Premium,137.0,153.0,0.289030,0.280734,18059.0,19818.0,1.029550
73,14,Upper mid,107.0,123.0,0.225738,0.225688,11739.0,13797.0,1.000223
74,14,Very premium,17.0,16.0,0.035865,0.029358,1498.0,999.0,1.221643

In [42]:
# Comparing topic exposure by product priority level across customer cohorts

topic_priority_comparison_dataframe = (
    full_topic_assignment_dataframe
    .groupby(["cohort_role", "topic_id", "issue_priority_level"], dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        sampled_reviews = ("sampled_review_count", "sum")
    )
    .reset_index()
)

topic_priority_totals_dataframe = (
    topic_priority_comparison_dataframe
    .groupby(["cohort_role", "topic_id"], dropna = False)
    .agg(
        total_documents = ("document_count", "sum")
    )
    .reset_index()
)

topic_priority_comparison_dataframe = topic_priority_comparison_dataframe.merge(
    topic_priority_totals_dataframe,
    on = ["cohort_role", "topic_id"],
    how = "left"
)

topic_priority_comparison_dataframe["document_share_within_topic"] = (
    topic_priority_comparison_dataframe["document_count"] /
    topic_priority_comparison_dataframe["total_documents"].replace(0, np.nan)
)

topic_priority_comparison_dataframe = (
    topic_priority_comparison_dataframe
    .pivot_table(
        index = ["topic_id", "issue_priority_level"],
        columns = "cohort_role",
        values = ["document_count", "sampled_reviews", "document_share_within_topic"],
        fill_value = 0
    )
)

topic_priority_comparison_dataframe.columns = [
    f"{metric_name}_{cohort_name.lower()}"
    for metric_name, cohort_name in topic_priority_comparison_dataframe.columns
]

topic_priority_comparison_dataframe = (
    topic_priority_comparison_dataframe
    .reset_index()
    .infer_objects(copy = False)
)

display(
    topic_priority_comparison_dataframe.sort_values(
        by = ["topic_id", "issue_priority_level"]
    )
)

,topic_id,issue_priority_level,document_count_dissatisfaction,document_count_satisfaction,document_share_within_topic_dissatisfaction,document_share_within_topic_satisfaction,sampled_reviews_dissatisfaction,sampled_reviews_satisfaction
0,0,Monitor,530.0,503.0,0.638554,0.611922,77515.0,59258.0
1,0,Priority review,300.0,319.0,0.361446,0.388078,48505.0,54594.0
2,1,Monitor,1195.0,1177.0,0.616933,0.611111,163411.0,138068.0
3,1,Priority review,742.0,749.0,0.383067,0.388889,121851.0,115819.0
4,2,Monitor,1432.0,2021.0,0.868405,0.891093,120421.0,180242.0
5,2,Priority review,217.0,247.0,0.131595,0.108907,30856.0,35914.0
6,3,Monitor,877.0,862.0,0.712429,0.736123,104886.0,83308.0
7,3,Priority review,354.0,309.0,0.287571,0.263877,57823.0,47564.0
8,4,Monitor,1296.0,1328.0,0.838835,0.845321,148119.0,138454.0
9,4,Priority review,249.0,243.0,0.161165,0.154679,35010.0,32917.0
10,5,Monitor,629.0,606.0,0.665608,0.649518,75978.0,59066.0
11,5,Priority review,316.0,327.0,0.334392,0.350482,48517.0,51254.0
12,6,Monitor,1099.0,1508.0,0.882022,0.906250,86485.0,121557.0
13,6,Priority review,147.0,156.0,0.117978,0.093750,19430.0,21210.0
14,7,Monitor,918.0,1298.0,0.685586,0.737919,88062.0,108869.0
15,7,Priority review,421.0,461.0,0.314414,0.262081,67989.0,73181.0
16,8,Monitor,1121.0,1332.0,0.743369,0.753820,130282.0,144655.0
17,8,Priority review,387.0,435.0,0.256631,0.246180,55666.0,63491.0
18,9,Monitor,865.0,924.0,0.779982,0.794497,81305.0,80937.0
19,9,Priority review,244.0,239.0,0.220018,0.205503,35305.0,35722.0
20,10,Monitor,404.0,405.0,0.796844,0.786408,36786.0,33927.0
21,10,Priority review,103.0,110.0,0.203156,0.213592,14679.0,15856.0
22,11,Monitor,646.0,669.0,0.706011,0.724810,79546.0,69428.0
23,11,Priority review,269.0,254.0,0.293989,0.275190,36539.0,34260.0
24,12,Monitor,811.0,604.0,0.765094,0.816216,75186.0,41936.0
25,12,Priority review,249.0,136.0,0.234906,0.183784,34594.0,18925.0
26,13,Monitor,366.0,404.0,0.655914,0.681282,37927.0,37516.0
27,13,Priority review,192.0,189.0,0.344086,0.318718,28543.0,30306.0
28,14,Monitor,295.0,348.0,0.622363,0.638532,26222.0,26662.0
29,14,Priority review,179.0,197.0,0.377637,0.361468,25905.0,30060.0

In [43]:
# Extracting frequent phrases from the full Electronics corpus

full_phrase_vectorizer = CountVectorizer(
    lowercase = False,
    stop_words = None,
    token_pattern = r"(?u)\b[a-z_][a-z0-9_]{2,}\b",
    ngram_range = (2, 3),
    min_df = 20,
    max_df = 0.20,
    max_features = 40000
)

full_phrase_matrix = full_phrase_vectorizer.fit_transform(
    full_topic_assignment_dataframe["modeling_text_for_vectorizer"]
)

full_phrase_names = np.array(full_phrase_vectorizer.get_feature_names_out())

topic_phrase_comparison_rows = []

for topic_id in sorted(full_topic_assignment_dataframe["topic_id"].unique()):
    topic_mask = full_topic_assignment_dataframe["topic_id"].eq(topic_id).to_numpy()
    dissatisfaction_mask = topic_mask & full_topic_assignment_dataframe["cohort_role"].eq("Dissatisfaction").to_numpy()
    satisfaction_mask = topic_mask & full_topic_assignment_dataframe["cohort_role"].eq("Satisfaction").to_numpy()

    dissatisfaction_document_count = dissatisfaction_mask.sum()
    satisfaction_document_count = satisfaction_mask.sum()

    if dissatisfaction_document_count == 0 or satisfaction_document_count == 0:
        continue

    dissatisfaction_document_frequency = np.asarray(
        (full_phrase_matrix[dissatisfaction_mask] > 0).sum(axis = 0)
    ).ravel()

    satisfaction_document_frequency = np.asarray(
        (full_phrase_matrix[satisfaction_mask] > 0).sum(axis = 0)
    ).ravel()

    topic_phrase_dataframe = pd.DataFrame({
        "topic_id": topic_id,
        "phrase_token": full_phrase_names,
        "dissatisfaction_document_frequency": dissatisfaction_document_frequency,
        "satisfaction_document_frequency": satisfaction_document_frequency
    })

    topic_phrase_dataframe["combined_document_frequency"] = (
        topic_phrase_dataframe["dissatisfaction_document_frequency"] +
        topic_phrase_dataframe["satisfaction_document_frequency"]
    )

    topic_phrase_dataframe["dissatisfaction_document_ratio"] = (
        topic_phrase_dataframe["dissatisfaction_document_frequency"] /
        dissatisfaction_document_count
    )

    topic_phrase_dataframe["satisfaction_document_ratio"] = (
        topic_phrase_dataframe["satisfaction_document_frequency"] /
        satisfaction_document_count
    )

    topic_phrase_dataframe["phrase_ratio_lift"] = (
        (topic_phrase_dataframe["dissatisfaction_document_ratio"] + 1e-6) /
        (topic_phrase_dataframe["satisfaction_document_ratio"] + 1e-6)
    )

    topic_phrase_dataframe["phrase_ratio_gap"] = (
        topic_phrase_dataframe["dissatisfaction_document_ratio"] -
        topic_phrase_dataframe["satisfaction_document_ratio"]
    )

    topic_phrase_comparison_rows.append(topic_phrase_dataframe)

topic_phrase_comparison_dataframe = pd.concat(
    topic_phrase_comparison_rows,
    ignore_index = True
)

accepted_topic_phrase_comparison_dataframe = (
    topic_phrase_comparison_dataframe
    .query(
        "dissatisfaction_document_frequency >= 20 "
        "and combined_document_frequency >= 30 "
        "and phrase_ratio_gap >= 0.015"
    )
    .sort_values(
        by = ["topic_id", "phrase_ratio_lift", "phrase_ratio_gap", "dissatisfaction_document_frequency"],
        ascending = [True, False, False, False]
    )
    .reset_index(drop = True)
)

accepted_topic_phrase_summary_dataframe = (
    accepted_topic_phrase_comparison_dataframe
    .groupby("topic_id", dropna = False)
    .agg(
        accepted_phrase_count = ("phrase_token", "count"),
        top_accepted_phrases = ("phrase_token", lambda values: ", ".join(values.head(12)))
    )
    .reset_index()
)

display(accepted_topic_phrase_comparison_dataframe.head(120))
display(accepted_topic_phrase_summary_dataframe.sort_values("topic_id"))

,topic_id,phrase_token,dissatisfaction_document_frequency,satisfaction_document_frequency,combined_document_frequency,dissatisfaction_document_ratio,satisfaction_document_ratio,phrase_ratio_lift,phrase_ratio_gap
0,0,outside return_window,117,0,117,0.140964,0.0,140964.855422,0.140964
1,0,past return_window,107,0,107,0.128916,0.0,128916.662651,0.128916
2,0,complete waste,102,0,102,0.122892,0.0,122892.566265,0.122892
3,0,amazon return_window,98,0,98,0.118072,0.0,118073.289157,0.118072
4,0,stopped_working completely,98,0,98,0.118072,0.0,118073.289157,0.118072
5,0,piece trash,80,0,80,0.096386,0.0,96386.542169,0.096386
6,0,return waste,77,0,77,0.092771,0.0,92772.084337,0.092771
7,0,unable return,77,0,77,0.092771,0.0,92772.084337,0.092771
8,0,constantly loses,76,0,76,0.091566,0.0,91567.265060,0.091566
9,0,tech_support useless,76,0,76,0.091566,0.0,91567.265060,0.091566
10,0,return stuck,73,0,73,0.087952,0.0,87952.807229,0.087952
11,0,waste bought,72,0,72,0.086747,0.0,86747.987952,0.086747
12,0,garbage buy,71,0,71,0.085542,0.0,85543.168675,0.085542
13,0,restocking fee,68,0,68,0.081928,0.0,81928.710843,0.081928
14,0,connect internet try,67,0,67,0.080723,0.0,80723.891566,0.080723
15,0,waste_money work,66,0,66,0.079518,0.0,79519.072289,0.079518
16,0,return past,65,0,65,0.078313,0.0,78314.253012,0.078313
17,0,did_not_work advertised,63,0,63,0.075904,0.0,75904.614458,0.075904
18,0,waste_money bought,60,0,60,0.072289,0.0,72290.156627,0.072289
19,0,return window,59,0,59,0.071084,0.0,71085.337349,0.071084
20,0,return junk,58,0,58,0.069880,0.0,69880.518072,0.069880
21,0,definitely not_worth,57,0,57,0.068675,0.0,68675.698795,0.068675
22,0,return exchange,57,0,57,0.068675,0.0,68675.698795,0.068675
23,0,waste return,57,0,57,0.068675,0.0,68675.698795,0.068675
24,0,junk bought,56,0,56,0.067470,0.0,67470.879518,0.067470
25,0,piece junk work,56,0,56,0.067470,0.0,67470.879518,0.067470
26,0,rma number,56,0,56,0.067470,0.0,67470.879518,0.067470
27,0,worst experience,56,0,56,0.067470,0.0,67470.879518,0.067470
28,0,does_not_work buy,55,0,55,0.066265,0.0,66266.060241,0.066265
29,0,return soon,54,0,54,0.065060,0.0,65061.240964,0.065060
30,0,total garbage,54,0,54,0.065060,0.0,65061.240964,0.065060
31,0,worst purchase,53,0,53,0.063855,0.0,63856.421687,0.063855
32,0,refund buy,51,0,51,0.061446,0.0,61446.783133,0.061446
33,0,worst bought,51,0,51,0.061446,0.0,61446.783133,0.061446
34,0,allow return,50,0,50,0.060241,0.0,60241.963855,0.060241
35,0,completely unreliable,49,0,49,0.059036,0.0,59037.144578,0.059036
36,0,return warranty,49,0,49,0.059036,0.0,59037.144578,0.059036
37,0,not_worth effort,48,0,48,0.057831,0.0,57832.325301,0.057831
38,0,pay return shipping,48,0,48,0.057831,0.0,57832.325301,0.057831
39,0,return_window amazon,48,0,48,0.057831,0.0,57832.325301,0.057831
40,0,support window,48,0,48,0.057831,0.0,57832.325301,0.057831
41,0,total junk,48,0,48,0.057831,0.0,57832.325301,0.057831
42,0,unable help,48,0,48,0.057831,0.0,57832.325301,0.057831
43,0,warranty return,48,0,48,0.057831,0.0,57832.325301,0.057831
44,0,finally agreed,47,0,47,0.056627,0.0,56627.506024,0.056627
45,0,stopped_working warranty,46,0,46,0.055422,0.0,55422.686747,0.055422
46,0,agreed replace,45,0,45,0.054217,0.0,54217.867470,0.054217
47,0,customer_service joke,45,0,45,0.054217,0.0,54217.867470,0.054217
48,0,junk return,45,0,45,0.054217,0.0,54217.867470,0.054217
49,0,piece junk buy,45,0,45,0.054217,0.0,54217.867470,0.054217
50,0,return_window stuck,45,0,45,0.054217,0.0,54217.867470,0.054217
51,0,warranty service,45,0,45,0.054217,0.0,54217.867470,0.054217
52,0,buy junk,44,0,44,0.053012,0.0,53013.048193,0.053012
53,0,support horrible,44,0,44,0.053012,0.0,53013.048193,0.053012
54,0,trash buy,44,0,44,0.053012,0.0,53013.048193,0.053012
55,0,buy piece junk,43,0,43,0.051807,0.0,51808.228916,0.051807
56,0,buy stopped_working,43,0,43,0.051807,0.0,51808.228916,0.051807
57,0,customer_service useless,43,0,43,0.051807,0.0,51808.228916,0.051807
58,0,garbage bought,43,0,43,0.051807,0.0,51808.228916,0.051807
59,0,garbage waste,43,0,43,0.051807,0.0,51808.228916,0.051807
60,0,went troubleshooting,43,0,43,0.051807,0.0,51808.228916,0.051807
61,0,customer_service non,42,0,42,0.050602,0.0,50603.409639,0.050602
62,0,return spent,42,0,42,0.050602,0.0,50603.409639,0.050602
63,0,return terrible,42,0,42,0.050602,0.0,50603.409639,0.050602
64,0,zero star,42,0,42,0.050602,0.0,50603.409639,0.050602
65,0,junk waste,41,0,41,0.049398,0.0,49398.590361,0.049398
66,0,return maybe,41,0,41,0.049398,0.0,49398.590361,0.049398
67,0,return piece junk,41,0,41,0.049398,0.0,49398.590361,0.049398
68,0,work not_working,41,0,41,0.049398,0.0,49398.590361,0.049398
69,0,buyers beware,40,0,40,0.048193,0.0,48193.771084,0.048193
70,0,completely unusable,40,0,40,0.048193,0.0,48193.771084,0.048193
71,0,totally unacceptable,40,0,40,0.048193,0.0,48193.771084,0.048193
72,0,buy garbage,39,0,39,0.046988,0.0,46988.951807,0.046988
73,0,constantly loses connection,39,0,39,0.046988,0.0,46988.951807,0.046988
74,0,work disappointing,39,0,39,0.046988,0.0,46988.951807,0.046988
75,0,buy risk,38,0,38,0.045783,0.0,45784.132530,0.045783
76,0,collecting dust,38,0,38,0.045783,0.0,45784.132530,0.045783
77,0,customer_service non existent,38,0,38,0.045783,0.0,45784.132530,0.045783
78,0,not_worth buy,38,0,38,0.045783,0.0,45784.132530,0.045783
79,0,terrible terrible,38,0,38,0.045783,0.0,45784.132530,0.045783
80,0,told help,38,0,38,0.045783,0.0,45784.132530,0.045783
81,0,unfortunately return_window,38,0,38,0.045783,0.0,45784.132530,0.045783
82,0,waste does_not_work,38,0,38,0.045783,0.0,45784.132530,0.045783
83,0,work couple started,38,0,38,0.045783,0.0,45784.132530,0.045783
84,0,connect does_not_work,37,0,37,0.044578,0.0,44579.313253,0.044578
85,0,constantly goes,37,0,37,0.044578,0.0,44579.313253,0.044578
86,0,passed return,37,0,37,0.044578,0.0,44579.313253,0.044578
87,0,pure junk,37,0,37,0.044578,0.0,44579.313253,0.044578
88,0,return help,37,0,37,0.044578,0.0,44579.313253,0.044578
89,0,return late,37,0,37,0.044578,0.0,44579.313253,0.044578
90,0,return period expired,37,0,37,0.044578,0.0,44579.313253,0.044578
91,0,work junk,37,0,37,0.044578,0.0,44579.313253,0.044578
92,0,zero help,37,0,37,0.044578,0.0,44579.313253,0.044578
93,0,customer_service worst,36,0,36,0.043373,0.0,43374.493976,0.043373
94,0,stuck piece,36,0,36,0.043373,0.0,43374.493976,0.043373
95,0,threw trash,36,0,36,0.043373,0.0,43374.493976,0.043373
96,0,total piece,36,0,36,0.043373,0.0,43374.493976,0.043373
97,0,warranty purchase,36,0,36,0.043373,0.0,43374.493976,0.043373
98,0,work return_window,36,0,36,0.043373,0.0,43374.493976,0.043373
99,0,absolute trash,35,0,35,0.042169,0.0,42169.674699,0.042169
100,0,died today,35,0,35,0.042169,0.0,42169.674699,0.042169
101,0,lasted stopped_working,35,0,35,0.042169,0.0,42169.674699,0.042169
102,0,stopped_working power,35,0,35,0.042169,0.0,42169.674699,0.042169
103,0,charge restocking,34,0,34,0.040964,0.0,40964.855422,0.040964
104,0,door stop,34,0,34,0.040964,0.0,40964.855422,0.040964
105,0,junk connect,34,0,34,0.040964,0.0,40964.855422,0.040964
106,0,maybe dud,34,0,34,0.040964,0.0,40964.855422,0.040964
107,0,needless return,34,0,34,0.040964,0.0,40964.855422,0.040964
108,0,receive replacement,34,0,34,0.040964,0.0,40964.855422,0.040964
109,0,return garbage,34,0,34,0.040964,0.0,40964.855422,0.040964
110,0,return return_window,34,0,34,0.040964,0.0,40964.855422,0.040964
111,0,return tomorrow,34,0,34,0.040964,0.0,40964.855422,0.040964
112,0,return unfortunately,34,0,34,0.040964,0.0,40964.855422,0.040964
113,0,said warranty,34,0,34,0.040964,0.0,40964.855422,0.040964
114,0,stopped_working entirely,34,0,34,0.040964,0.0,40964.855422,0.040964
115,0,stuck expensive,34,0,34,0.040964,0.0,40964.855422,0.040964
116,0,totally disappointed,34,0,34,0.040964,0.0,40964.855422,0.040964
117,0,charge restocking fee,33,0,33,0.039759,0.0,39760.036145,0.039759
118,0,chat phone,33,0,33,0.039759,0.0,39760.036145,0.039759
119,0,return horrible,33,0,33,0.039759,0.0,39760.036145,0.039759

,topic_id,accepted_phrase_count,top_accepted_phrases
0,0,3284,"outside return_window, past return_window, com..."
1,1,3711,"work waste_money, return waste, return not_wor..."
2,2,1781,"total waste_money, waste_money case, case poor..."
3,3,2605,"stopped_working waste_money, return try, retur..."
4,4,3223,"outside return_window, try multiple computers,..."
5,5,2316,"stopped_working disappointed, disappointed ret..."
6,6,1175,"complete waste_money, super disappointed, retu..."
7,7,3272,"customer_service horrible, does_not_work adver..."
8,8,2953,"return immediately, waste work, return waste, ..."
9,9,2453,"does_not_work advertised, waste bought, return..."
10,10,569,"complete waste_money, buyer beware, total wast..."
11,11,2216,"late return, total waste_money, dont buy, miss..."
12,12,1933,"total waste_money, complete waste_money, wish ..."
13,13,775,"window return, dont waste, work waste, does_no..."
14,14,730,"total waste_money, return immediately, complet..."

In [44]:
# Grouping frequent phrases into interpretable business signal families

phrase_family_definitions = {
    "transaction_or_remedy": {
        "return", "return_window", "return_policy", "refund", "restocking",
        "warranty", "buyer", "buyers", "beware", "false_advertising",
        "false_advertisement", "exchange"
    },
    "delivery_or_marketplace": {
        "late_delivery", "on_time_delivery", "shipping", "ship", "shipped",
        "arrived", "arrive", "arrival", "arrived_damaged", "wrong_item",
        "package", "packaging", "box", "seller", "amazon",
        "customer_service", "tech_support"
    },
    "product_failure_or_breakdown": {
        "does_not_work", "did_not_work", "stopped_working", "dead_on_arrival",
        "not_charge", "not_charging", "not_connect", "not_connecting",
        "not_pair", "not_pairing", "not_turn_on", "will_not_turn_on",
        "no_power", "no_sound", "no_signal", "battery_died",
        "defective_unit", "defective", "broken", "broke"
    },
    "compatibility_or_fit": {
        "not_compatible", "not_fit", "compatible", "adapter", "hdmi",
        "screen_protector", "usb_c", "usb_a", "micro_sd", "sd_card", "case"
    },
    "setup_or_connectivity": {
        "connect", "disconnect", "keeps_disconnecting", "wifi", "bluetooth",
        "pair", "setup", "router", "network", "internet", "modem",
        "signal", "reception", "channels"
    },
    "quality_or_durability": {
        "poor_quality", "quality", "cheap", "junk", "garbage", "trash",
        "cracked", "cracking", "bubbles", "flimsy", "strap", "zipper",
        "screws", "mount", "mounting"
    },
    "audio_or_visual_performance": {
        "sound_quality", "picture_quality", "audio", "speaker", "speakers",
        "earbuds", "headphone", "headphones", "bass", "display", "monitor",
        "camera", "recording", "motion"
    }
}


def phrase_contains_family_signal(phrase_value, family_terms):
    phrase_tokens = set(str(phrase_value).split())
    return len(phrase_tokens.intersection(family_terms)) > 0


topic_phrase_family_rows = []

for topic_id in sorted(accepted_topic_phrase_comparison_dataframe["topic_id"].unique()):
    topic_phrase_subset_dataframe = accepted_topic_phrase_comparison_dataframe.loc[
        accepted_topic_phrase_comparison_dataframe["topic_id"] == topic_id
    ].copy()

    topic_result = {
        "topic_id": topic_id,
        "accepted_phrase_count": len(topic_phrase_subset_dataframe)
    }

    total_gap_score = topic_phrase_subset_dataframe["phrase_ratio_gap"].sum()

    for family_name, family_terms in phrase_family_definitions.items():
        family_mask = topic_phrase_subset_dataframe["phrase_token"].apply(
            lambda value: phrase_contains_family_signal(value, family_terms)
        )

        family_phrase_count = family_mask.sum()
        family_gap_score = topic_phrase_subset_dataframe.loc[
            family_mask,
            "phrase_ratio_gap"
        ].sum()

        topic_result[f"{family_name}_phrase_count"] = family_phrase_count
        topic_result[f"{family_name}_gap_score"] = family_gap_score
        topic_result[f"{family_name}_gap_share"] = (
            family_gap_score / total_gap_score if total_gap_score > 0 else 0.0
        )

    family_share_columns = [
        column_name
        for column_name in topic_result.keys()
        if column_name.endswith("_gap_share")
    ]

    strongest_family_column = max(
        family_share_columns,
        key = lambda column_name: topic_result[column_name]
    )

    strongest_family_share = topic_result[strongest_family_column]

    if strongest_family_share >= 0.40:
        dominant_driver_family = strongest_family_column.replace("_gap_share", "")
    else:
        dominant_driver_family = "Mixed"

    topic_result["dominant_driver_family"] = dominant_driver_family
    topic_result["dominant_driver_family_share"] = strongest_family_share
    topic_result["total_phrase_gap_score"] = total_gap_score

    topic_phrase_family_rows.append(topic_result)

topic_phrase_family_summary_dataframe = pd.DataFrame(topic_phrase_family_rows)

display(topic_phrase_family_summary_dataframe.sort_values("topic_id"))

,topic_id,accepted_phrase_count,transaction_or_remedy_phrase_count,transaction_or_remedy_gap_score,transaction_or_remedy_gap_share,delivery_or_marketplace_phrase_count,delivery_or_marketplace_gap_score,delivery_or_marketplace_gap_share,product_failure_or_breakdown_phrase_count,product_failure_or_breakdown_gap_score,product_failure_or_breakdown_gap_share,compatibility_or_fit_phrase_count,compatibility_or_fit_gap_score,compatibility_or_fit_gap_share,setup_or_connectivity_phrase_count,setup_or_connectivity_gap_score,setup_or_connectivity_gap_share,quality_or_durability_phrase_count,quality_or_durability_gap_score,quality_or_durability_gap_share,audio_or_visual_performance_phrase_count,audio_or_visual_performance_gap_score,audio_or_visual_performance_gap_share,dominant_driver_family,dominant_driver_family_share,total_phrase_gap_score
0,0,3284,273,22.223759,0.117320,192,12.578014,0.066400,109,7.618676,0.040219,17,0.531296,0.002805,667,40.039396,0.211370,46,3.407610,0.017989,0,0.000000,0.000000,Mixed,0.211370,189.428253
1,1,3711,399,17.097389,0.120397,138,4.590974,0.032329,433,17.797937,0.125330,36,0.978679,0.006892,273,11.568286,0.081462,178,6.339378,0.044641,275,12.689355,0.089356,Mixed,0.125330,142.008387
2,2,1781,208,8.742860,0.126230,55,1.639866,0.023676,147,5.757577,0.083128,368,18.349154,0.264926,3,0.075318,0.001087,141,7.392076,0.106727,12,0.315889,0.004561,Mixed,0.264926,69.261557
3,3,2605,170,9.451748,0.075105,84,2.971944,0.023615,404,25.624154,0.203612,37,1.096855,0.008716,64,2.875793,0.022851,110,4.938919,0.039245,8,0.166494,0.001323,Mixed,0.203612,125.847917
4,4,3223,349,16.675277,0.133299,223,8.042196,0.064288,241,9.338921,0.074654,39,1.112768,0.008895,76,2.714723,0.021701,87,3.643642,0.029127,20,0.471372,0.003768,Mixed,0.133299,125.096777
5,5,2316,198,14.032182,0.116304,103,4.381949,0.036319,201,14.315412,0.118652,11,0.254744,0.002111,91,4.061798,0.033666,77,4.616656,0.038265,0,0.000000,0.000000,Mixed,0.118652,120.650460
6,6,1175,144,6.655610,0.150053,84,3.087447,0.069608,108,4.194723,0.094572,11,0.247664,0.005584,7,0.149336,0.003367,159,7.095841,0.159978,34,0.814897,0.018372,Mixed,0.159978,44.354976
7,7,3272,307,15.351038,0.116674,224,8.703249,0.066148,149,6.795586,0.051649,15,0.362043,0.002752,235,9.531743,0.072445,91,4.716155,0.035845,476,26.793040,0.203637,Mixed,0.203637,131.572272
8,8,2953,344,16.109991,0.144601,177,6.170199,0.055383,264,10.103149,0.090685,1,0.020455,0.000184,163,5.187015,0.046558,119,4.926655,0.044221,235,11.698091,0.105001,Mixed,0.144601,111.409623
9,9,2453,227,13.757990,0.128272,139,5.260565,0.049047,272,15.686143,0.146249,82,3.175997,0.029611,97,4.007765,0.037366,82,3.791491,0.035350,149,6.627011,0.061786,Mixed,0.146249,107.256621
10,10,569,16,1.437123,0.038095,20,1.308945,0.034697,12,1.020662,0.027056,35,2.023967,0.053651,0,0.000000,0.000000,51,5.480661,0.145281,9,0.381904,0.010123,Mixed,0.145281,37.724578
11,11,2216,197,13.745239,0.130775,188,8.431103,0.080215,177,11.170002,0.106273,8,0.269143,0.002561,93,3.359119,0.031959,61,3.628704,0.034524,8,0.235528,0.002241,Mixed,0.130775,105.106316
12,12,1933,207,12.294289,0.146357,114,4.976747,0.059245,167,8.608134,0.102475,6,0.160581,0.001912,21,0.783988,0.009333,57,2.876798,0.034247,5,0.099567,0.001185,Mixed,0.146357,84.002295
13,13,775,89,9.435711,0.204672,42,2.555389,0.055429,51,4.129634,0.089577,1,0.025525,0.000554,45,2.792393,0.060570,36,2.831327,0.061415,13,0.569536,0.012354,Mixed,0.204672,46.101712
14,14,730,64,6.942090,0.144391,34,2.332660,0.048518,38,3.241312,0.067417,0,0.000000,0.000000,41,3.132757,0.065159,15,1.320725,0.027470,7,0.311361,0.006476,Mixed,0.144391,48.078357

In [45]:
# Enriching topic outputs with premium-price and priority indicators

premium_price_bands = {"Premium", "Very premium"}

topic_price_band_enriched_dataframe = topic_price_band_comparison_dataframe.copy()
topic_price_band_enriched_dataframe["is_premium_band"] = (
    topic_price_band_enriched_dataframe["price_band"].isin(premium_price_bands)
)

premium_topic_summary_dataframe = (
    topic_price_band_enriched_dataframe
    .groupby("topic_id", dropna = False)
    .agg(
        premium_document_count_dissatisfaction = (
            "document_count_dissatisfaction",
            lambda values: values[
                topic_price_band_enriched_dataframe.loc[values.index, "is_premium_band"]
            ].sum()
        ),
        premium_document_count_satisfaction = (
            "document_count_satisfaction",
            lambda values: values[
                topic_price_band_enriched_dataframe.loc[values.index, "is_premium_band"]
            ].sum()
        ),
        total_document_count_dissatisfaction = ("document_count_dissatisfaction", "sum"),
        total_document_count_satisfaction = ("document_count_satisfaction", "sum")
    )
    .reset_index()
)

premium_topic_summary_dataframe["premium_document_share_dissatisfaction"] = (
    premium_topic_summary_dataframe["premium_document_count_dissatisfaction"] /
    premium_topic_summary_dataframe["total_document_count_dissatisfaction"].replace(0, np.nan)
)

premium_topic_summary_dataframe["premium_document_share_satisfaction"] = (
    premium_topic_summary_dataframe["premium_document_count_satisfaction"] /
    premium_topic_summary_dataframe["total_document_count_satisfaction"].replace(0, np.nan)
)

premium_topic_summary_dataframe["premium_share_lift_dissatisfaction_vs_satisfaction"] = (
    (premium_topic_summary_dataframe["premium_document_share_dissatisfaction"] + 1e-6) /
    (premium_topic_summary_dataframe["premium_document_share_satisfaction"] + 1e-6)
)

priority_topic_summary_dataframe = (
    topic_priority_comparison_dataframe.loc[
        topic_priority_comparison_dataframe["issue_priority_level"] == "Priority review",
        [
            "topic_id",
            "document_count_dissatisfaction",
            "document_count_satisfaction",
            "sampled_reviews_dissatisfaction",
            "sampled_reviews_satisfaction",
            "document_share_within_topic_dissatisfaction",
            "document_share_within_topic_satisfaction"
        ]
    ]
    .rename(columns = {
        "document_share_within_topic_dissatisfaction": "priority_document_share_dissatisfaction",
        "document_share_within_topic_satisfaction": "priority_document_share_satisfaction"
    })
    .copy()
)

priority_topic_summary_dataframe["priority_share_lift_dissatisfaction_vs_satisfaction"] = (
    (priority_topic_summary_dataframe["priority_document_share_dissatisfaction"] + 1e-6) /
    (priority_topic_summary_dataframe["priority_document_share_satisfaction"] + 1e-6)
)

topic_reporting_coverage_dataframe = (
    topic_segment_reporting_eligibility_dataframe
    .groupby("topic_id", dropna = False)
    .agg(
        eligible_segment_count = ("is_segment_reporting_eligible", "sum"),
        total_segment_count = ("is_segment_reporting_eligible", "count")
    )
    .reset_index()
)

topic_reporting_coverage_dataframe["eligible_segment_ratio"] = (
    topic_reporting_coverage_dataframe["eligible_segment_count"] /
    topic_reporting_coverage_dataframe["total_segment_count"].replace(0, np.nan)
)

topic_insight_mechanics_dataframe = (
    topic_driver_core_dataframe
    .merge(topic_breadth_summary_dataframe, on = "topic_id", how = "left")
    .merge(
        premium_topic_summary_dataframe[
            [
                "topic_id",
                "premium_document_share_dissatisfaction",
                "premium_document_share_satisfaction",
                "premium_share_lift_dissatisfaction_vs_satisfaction"
            ]
        ],
        on = "topic_id",
        how = "left"
    )
    .merge(
        priority_topic_summary_dataframe[
            [
                "topic_id",
                "priority_document_share_dissatisfaction",
                "priority_document_share_satisfaction",
                "priority_share_lift_dissatisfaction_vs_satisfaction"
            ]
        ],
        on = "topic_id",
        how = "left"
    )
    .merge(topic_reporting_coverage_dataframe, on = "topic_id", how = "left")
    .merge(topic_phrase_family_summary_dataframe, on = "topic_id", how = "left")
    .merge(accepted_topic_phrase_summary_dataframe, on = "topic_id", how = "left")
)

topic_insight_mechanics_dataframe["topic_breadth_type"] = np.select(
    [
        topic_insight_mechanics_dataframe["concentration_hhi"] >= 0.25,
        topic_insight_mechanics_dataframe["segment_count_above_05_share"] >= 6
    ],
    [
        "Concentrated",
        "Broad"
    ],
    default = "Moderate"
)

topic_insight_mechanics_dataframe["dissatisfaction_signal_strength"] = np.select(
    [
        topic_insight_mechanics_dataframe["document_share_lift_dissatisfaction_vs_satisfaction"] >= 1.15,
        topic_insight_mechanics_dataframe["document_share_lift_dissatisfaction_vs_satisfaction"] >= 1.08
    ],
    [
        "Strong",
        "Moderate"
    ],
    default = "Weak"
)

topic_insight_mechanics_dataframe["topic_assignment_confidence"] = np.select(
    [
        (
            topic_insight_mechanics_dataframe["average_topic_margin"] >= 0.06
        ) & (
            topic_insight_mechanics_dataframe["low_margin_document_ratio"] <= 0.25
        ),
        (
            topic_insight_mechanics_dataframe["average_topic_margin"] >= 0.04
        ) & (
            topic_insight_mechanics_dataframe["low_margin_document_ratio"] <= 0.35
        )
    ],
    [
        "High",
        "Moderate"
    ],
    default = "Watch"
)

signal_strength_rank_map = {
    "Strong": 3,
    "Moderate": 2,
    "Weak": 1
}

breadth_rank_map = {
    "Broad": 3,
    "Moderate": 2,
    "Concentrated": 1
}

confidence_rank_map = {
    "High": 3,
    "Moderate": 2,
    "Watch": 1
}

topic_insight_mechanics_dataframe["dissatisfaction_signal_strength_rank"] = (
    topic_insight_mechanics_dataframe["dissatisfaction_signal_strength"].map(signal_strength_rank_map)
)

topic_insight_mechanics_dataframe["topic_breadth_rank"] = (
    topic_insight_mechanics_dataframe["topic_breadth_type"].map(breadth_rank_map)
)

topic_insight_mechanics_dataframe["topic_assignment_confidence_rank"] = (
    topic_insight_mechanics_dataframe["topic_assignment_confidence"].map(confidence_rank_map)
)

display(
    topic_insight_mechanics_dataframe.sort_values(
        by = [
            "dissatisfaction_signal_strength_rank",
            "eligible_segment_ratio",
            "topic_assignment_confidence_rank",
            "document_share_lift_dissatisfaction_vs_satisfaction",
            "document_count"
        ],
        ascending = [False, False, False, False, False]
    )
)

,topic_id,document_count,total_sampled_reviews,average_topic_strength,average_rating,average_helpful_vote,top_terms,document_count_dissatisfaction,document_count_satisfaction,sampled_reviews_dissatisfaction,sampled_reviews_satisfaction,document_share_dissatisfaction,document_share_satisfaction,document_share_lift_dissatisfaction_vs_satisfaction,sampled_review_share_lift_dissatisfaction_vs_satisfaction,document_share_gap,max_top_term_jaccard_overlap,average_topic_margin,median_topic_margin,low_margin_document_count,topic_weight_share_dissatisfaction,topic_weight_share_satisfaction,topic_weight_share_lift_dissatisfaction_vs_satisfaction,topic_weight_share_gap,low_margin_document_ratio,covered_segment_count,segment_count_above_05_share,segment_count_above_10_share,max_segment_share,concentration_hhi,premium_document_share_dissatisfaction,premium_document_share_satisfaction,premium_share_lift_dissatisfaction_vs_satisfaction,priority_document_share_dissatisfaction,priority_document_share_satisfaction,priority_share_lift_dissatisfaction_vs_satisfaction,eligible_segment_count,total_segment_count,eligible_segment_ratio,accepted_phrase_count_x,transaction_or_remedy_phrase_count,transaction_or_remedy_gap_score,transaction_or_remedy_gap_share,delivery_or_marketplace_phrase_count,delivery_or_marketplace_gap_score,delivery_or_marketplace_gap_share,product_failure_or_breakdown_phrase_count,product_failure_or_breakdown_gap_score,product_failure_or_breakdown_gap_share,compatibility_or_fit_phrase_count,compatibility_or_fit_gap_score,compatibility_or_fit_gap_share,setup_or_connectivity_phrase_count,setup_or_connectivity_gap_score,setup_or_connectivity_gap_share,quality_or_durability_phrase_count,quality_or_durability_gap_score,quality_or_durability_gap_share,audio_or_visual_performance_phrase_count,audio_or_visual_performance_gap_score,audio_or_visual_performance_gap_share,dominant_driver_family,dominant_driver_family_share,total_phrase_gap_score,accepted_phrase_count_y,top_accepted_phrases,topic_breadth_type,dissatisfaction_signal_strength,topic_assignment_confidence,dissatisfaction_signal_strength_rank,topic_breadth_rank,topic_assignment_confidence_rank
8,12,1060,109780,0.071391,1.256757,2.432281,"charger, charge battery, hold charge, battery ...",1060,740,109780,60861,0.062897,0.040305,1.560507,1.796167,0.022592,0.111111,0.048695,0.023479,391,0.082268,0.050882,1.616824,0.031386,0.368868,9,7,4,0.240566,0.160048,0.226415,0.120270,1.882545,0.234906,0.183784,1.278162,7,9,0.777778,1933,207,12.294289,0.146357,114,4.976747,0.059245,167,8.608134,0.102475,6,0.160581,0.001912,21,0.783988,0.009333,57,2.876798,0.034247,5,0.099567,0.001185,Mixed,0.146357,84.002295,1933,"total waste_money, complete waste_money, wish ...",Broad,Strong,Watch,3,3,1
0,1,1937,285262,0.087805,1.358950,1.290585,"ear, headphone, earbuds, ears, buds, earbud, s...",1937,1926,285262,253887,0.114935,0.104902,1.095641,1.11885,0.010033,0.071429,0.065651,0.067718,160,0.089549,0.093391,0.958862,-0.003842,0.082602,9,8,6,0.207537,0.135442,0.230769,0.234164,0.985502,0.383067,0.388889,0.985028,9,9,1.000000,3711,399,17.097389,0.120397,138,4.590974,0.032329,433,17.797937,0.125330,36,0.978679,0.006892,273,11.568286,0.081462,178,6.339378,0.044641,275,12.689355,0.089356,Mixed,0.125330,142.008387,3711,"work waste_money, return waste, return not_wor...",Broad,Moderate,High,2,3,3
9,5,945,124495,0.089500,1.340732,1.209011,"mouse, keyboard, keys, logitech, mouse work, k...",945,933,124495,110320,0.056073,0.050817,1.103430,1.123739,0.005256,0.000000,0.068815,0.076124,158,0.059885,0.055270,1.083497,0.004615,0.167196,9,7,5,0.214815,0.138913,0.185185,0.210075,0.881520,0.334392,0.350482,0.954090,8,9,0.888889,2316,198,14.032182,0.116304,103,4.381949,0.036319,201,14.315412,0.118652,11,0.254744,0.002111,91,4.061798,0.033666,77,4.616656,0.038265,0,0.000000,0.000000,Mixed,0.118652,120.650460,2316,"stopped_working disappointed, disappointed ret...",Broad,Moderate,High,2,3,3
11,0,830,126020,0.061121,1.267146,2.398637,"router, wifi, network, internet, modem, netgea...",830,822,126020,113852,0.049249,0.044771,1.100021,1.102217,0.004478,0.034483,0.048389,0.055147,126,0.043807,0.034378,1.274283,0.009430,0.151807,9,6,5,0.250602,0.162334,0.419277,0.373479,1.122624,0.361446,0.388078,0.931375,7,9,0.777778,3284,273,22.223759,0.117320,192,12.578014,0.066400,109,7.618676,0.040219,17,0.531296,0.002805,667,40.039396,0.211370,46,3.407610,0.017989,0,0.000000,0.000000,Mixed,0.211370,189.428253,3284,"outside return_window, past return_window, com...",Broad,Moderate,Moderate,2,3,2
6,3,1231,162709,0.086244,1.256194,1.215423,"charge phone, cords, chargers, charger, not_ch...",1231,1171,162709,130872,0.073043,0.063780,1.145238,1.238034,0.009263,0.111111,0.067411,0.072081,330,0.076694,0.059047,1.298866,0.017647,0.268075,9,4,3,0.465475,0.304157,0.010561,0.017933,0.588898,0.287571,0.263877,1.089792,5,9,0.555556,2605,170,9.451748,0.075105,84,2.971944,0.023615,404,25.624154,0.203612,37,1.096855,0.008716,64,2.875793,0.022851,110,4.938919,0.039245,8,0.166494,0.001323,Mixed,0.203612,125.847917,2605,"stopped_working waste_money, return try, retur...",Concentrated,Moderate,Moderate,2,1,2
10,11,915,116085,0.077447,1.276203,2.052309,"remote, remote work, remotes, buttons, remote ...",915,923,116085,103688,0.054293,0.050272,1.079976,1.114848,0.004021,0.000000,0.055333,0.058762,224,0.060327,0.055149,1.093902,0.005179,0.244809,9,8,4,0.208743,0.144080,0.372678,0.352113,1.058404,0.293989,0.275190,1.068314,9,9,1.000000,2216,197,13.745239,0.130775,188,8.431103,0.080215,177,11.170002,0.106273,8,0.269143,0.002561,93,3.359119,0.031959,61,3.628704,0.034524,8,0.235528,0.002241,Mixed,0.130775,105.106316,2216,"late return, total waste_money, dont buy, miss...",Broad,Weak,Moderate,1,3,2
2,4,1545,183129,0.075803,1.231458,2.416205,"drive, drives, files, disk, data, hard_drive, ...",1545,1571,183129,171371,0.091675,0.085566,1.071390,1.064114,0.006109,0.000000,0.055108,0.044309,313,0.079433,0.069354,1.145317,0.010078,0.202589,9,6,4,0.209709,0.163492,0.324272,0.339274,0.955781,0.161165,0.154679,1.041935,9,9,1.000000,3223,349,16.675277,0.133299,223,8.042196,0.064288,241,9.338921,0.074654,39,1.112768,0.008895,76,2.714723,0.021701,87,3.643642,0.029127,20,0.471372,0.003768,Mixed,0.133299,125.096777,3223,"outside return_window, try multiple computers,...",Broad,Weak,Moderate,1,3,2
7,9,1109,116610,0.075755,1.261656,1.617113,"hdmi, monitor, hdmi cable, display, adapter, p...",1109,1163,116610,116659,0.065804,0.063344,1.038836,0.995374,0.002460,0.034483,0.050545,0.053225,258,0.069385,0.068057,1.019514,0.001328,0.232642,9,7,4,0.259693,0.156795,0.298467,0.292347,1.020933,0.220018,0.205503,1.070631,9,9,1.000000,2453,227,13.757990,0.128272,139,5.260565,0.049047,272,15.686143,0.146249,82,3.175997,0.029611,97,4.007765,0.037366,82,3.791491,0.035350,149,6.627011,0.061786,Mixed,0.146249,107.256621,2453,"does_not_work advertised, waste bought, return...",Broad,Weak,Moderate,1,3,2
3,8,1508,185948,0.061545,1.324395,1.637885,"speaker, sound_quality, music, bluetooth, bass...",1508,1767,185948,208146,0.089480,0.096242,0.929738,0.889596,-0.006762,0.071429,0.033555,0.030727,386,0.071682,0.080550,0.889906,-0.008868,0.255968,9,6,4,0.234748,0.159123,0.351459,0.371251,0.946689,0.256631,0.246180,1.042454,9,9,1.000000,2953,344,16.109991,0.144601,177,6.170199,0.055383,264,10.103149,0.090685,1,0.020455,0.000184,163,5.187015,0.046558,119,4.926655,0.044221,235,11.698091,0.105001,Mixed,0.144601,111.409623,2953,"return immediately, waste work, return waste, ...",Broad,Weak,Watch,1,3,1
12,13,558,66470,0.100459,1.314494,2.045112,"antenna, stations, reception, channels, miles,...",558,593,66470,67822,0.033110,0.032298,1.025120,0.975943,0.000811,0.034483,0.073351,0.044054,137,0.046565,0.052410,0.888472,-0.005845,0.245520,9,8,4,0.252688,0.148771,0.267025,0.264755,1.008572,0.344086,0.318718,1.079592,8,9,0.888889,775,89,9.435711,0.204672,42,2.555389,0.055429,51,4.129634,0.089577,1,0.025525,0.000554,45,2.792393,0.060570,36,2.831327,0.061415,13,0.569536,0.012354,Mixed,0.204672,46.101712,775,"window return, dont waste, work waste, does_no...",Broad,Weak,High,1,3,3
4,7,1339,156051,0.077219,1.303286,3.327786,"camera, camera work, motion, recording, view, ...",1339,1759,156051,182050,0.079452,0.095806,0.829299,0.853583,-0.016354,0.000000,0.053167,0.047307,297,0.074035,0.086589,0.855017,-0.012554,0.221807,9,6,4,0.296490,0.182711,0.530993,0.541217,0.981111,0.314414,0.262081,1.199682,8,9,0.888889,3272,307,15.351038,0.116674,224,8.703249,0.066148,149,6.795586,0.051649,15,0.362043,0.002752,235,9.531743,0.072445,91,4.716155,0.035845,476,26.793040,0.203637,Mixed,0.203637,131.572272,3272,"customer_service horrible, does_not_work adver...",Broad,Weak,Moderate,1,3,2
14,14,474,52127,0.106606,1.326081,2.023808,"fitbit, band, wrist, watch, bands, heart rate,...",474,545,52127,56722,0.028126,0.029684,0.947498,0.915127,-0.001559,0.000000,0.085495,0.102129,84,0.044610,0.054867,0.813049,-0.010258,0.177215,9,7,6,0.236287,0.142392,0.324895,0.310092,1.047737,0.377637,0.361468,1.044732,7,9,0.777778,730,64,6.942090,0.144391,34,2.332660,0.048518,38,3.241312,0.067417,0,0.000000,0.000000,41,3.132757,0.065159,15,1.320725,0.027470,7,0.311361,0.006476,Mixed,0.144391,48.078357,730,"total waste_money, return immediately, complet...",Broad,Weak,High,1,3,3
5,6,1246,105915,0.069002,1.359285,1.684490,"screws, mount, screw, mounting, bracket, tight...",1246,1664,105915,142767,0.073933,0.090632,0.815758,0.738755,-0.016698,0.000000,0.047992,0.036532,300,0.069892,0.088758,0.787445,-0.018866,0.240770,9,4,4,0.303371,0.209671,0.173355,0.174279,0.994698,0.117978,0.093750,1.258424,7,9,0.777778,1175,144,6.655610,0.150053,84,3.087447,0.069608,108,4.194723,0.094572,11,0.247664,0.005584,7,0.149336,0.003367,159,7.095841,0.159978,34,0.814897,0.018372,Mixed,0.159978,44.354976,1175,"complete waste_money, super disappointed, retu...",Moderate,Weak,Moderate,1,2,2
1,2,1649,151277,0.075462,1.377515,1.053450,"ipad, not_fit, protect, color, cases, fits, co...",1649,2268,151277,216156,0.097846,0.123529,0.792089,0.696909,-0.025683,0.034483,0.055432,0.055434,218,0.083400,0.107245,0.777654,-0.023846,0.132201,9,4,3,0.402668,0.266621,0.034566,0.056437,0.612480,0.131595,0.108907,1.208327,6,9,0.666667,1781,208,8.742860,0.126230,55,1.639866,0.023676,147,5.757577,0.083128,368,18.349154,0.264926,3,0.075318,0.001087,141,7.392076,0.106727,12,0.315889,0.004561,Mixed,0.264926,69.261557,1781,"total waste_money, waste_money case, case poor...",Concentrated,Weak,Moderate,1,1,2
13,10,507,51465,0.115678,1.300156,1.057393,"bubbles, screen_protector, protectors, screen ...",507,515,51465,49783,0.030084,0.028050,1.072495,1.029436,0.002034,0.000000,0.101886,0.128618,90,0.048469,0.044053,1.100252,0.004416,0.177515,8,3,3,0.568047,0.380935,0.023669,0.038835,0.609478,0.203156,0.213592,0.951139,3,9,0.333333,569,16,1.437123,0.038095,20,1.308945,0.034697,12,1.020662,0.027056,35,2.023967,0.053651,0,0.000000,0.000000,51,5.480661,0.145281,9,0.381904,0.010123,Mixed,0.145281,37.724578,569,"complete waste_money, buyer beware, total wast...",Concentrated,Weak,High,1,1,3

In [46]:
# Scoring topics for root-cause and product-failure relevance

driver_evaluation_dataframe = topic_insight_mechanics_dataframe.copy()

driver_evaluation_dataframe["root_cause_gap_score"] = (
    driver_evaluation_dataframe["product_failure_or_breakdown_gap_score"]
    + driver_evaluation_dataframe["compatibility_or_fit_gap_score"]
    + driver_evaluation_dataframe["setup_or_connectivity_gap_score"]
    + driver_evaluation_dataframe["quality_or_durability_gap_score"]
    + driver_evaluation_dataframe["audio_or_visual_performance_gap_score"]
)

driver_evaluation_dataframe["remedy_gap_score"] = (
    driver_evaluation_dataframe["transaction_or_remedy_gap_score"]
)

driver_evaluation_dataframe["total_driver_gap_score"] = (
    driver_evaluation_dataframe["root_cause_gap_score"]
    + driver_evaluation_dataframe["remedy_gap_score"]
)

driver_evaluation_dataframe["root_cause_share"] = (
    driver_evaluation_dataframe["root_cause_gap_score"] /
    driver_evaluation_dataframe["total_driver_gap_score"].replace(0, np.nan)
)

driver_evaluation_dataframe["remedy_share"] = (
    driver_evaluation_dataframe["remedy_gap_score"] /
    driver_evaluation_dataframe["total_driver_gap_score"].replace(0, np.nan)
)

driver_evaluation_dataframe["topic_breadth_type"] = np.select(
    [
        driver_evaluation_dataframe["concentration_hhi"] >= 0.25,
        driver_evaluation_dataframe["segment_count_above_05_share"] >= 6
    ],
    [
        "Concentrated",
        "Broad"
    ],
    default = "Moderate"
)

driver_evaluation_dataframe["dissatisfaction_signal_strength"] = np.select(
    [
        (
            driver_evaluation_dataframe["document_share_lift_dissatisfaction_vs_satisfaction"] >= 1.12
        ) & (
            driver_evaluation_dataframe["topic_weight_share_lift_dissatisfaction_vs_satisfaction"] >= 1.08
        ),
        (
            driver_evaluation_dataframe["document_share_lift_dissatisfaction_vs_satisfaction"] >= 1.05
        ) & (
            driver_evaluation_dataframe["topic_weight_share_lift_dissatisfaction_vs_satisfaction"] >= 1.03
        )
    ],
    [
        "Strong",
        "Moderate"
    ],
    default = "Weak"
)

driver_evaluation_dataframe["topic_assignment_confidence"] = np.select(
    [
        (
            driver_evaluation_dataframe["average_topic_margin"] >= 0.06
        ) & (
            driver_evaluation_dataframe["low_margin_document_ratio"] <= 0.25
        ),
        (
            driver_evaluation_dataframe["average_topic_margin"] >= 0.04
        ) & (
            driver_evaluation_dataframe["low_margin_document_ratio"] <= 0.35
        )
    ],
    [
        "High",
        "Moderate"
    ],
    default = "Watch"
)

driver_evaluation_dataframe["premium_exposure_level"] = np.select(
    [
        driver_evaluation_dataframe["premium_share_lift_dissatisfaction_vs_satisfaction"] >= 1.08,
        driver_evaluation_dataframe["premium_share_lift_dissatisfaction_vs_satisfaction"] <= 0.92
    ],
    [
        "Premium-tilted",
        "Non-premium-tilted"
    ],
    default = "Balanced"
)

driver_evaluation_dataframe["priority_exposure_level"] = np.select(
    [
        driver_evaluation_dataframe["priority_share_lift_dissatisfaction_vs_satisfaction"] >= 1.08,
        driver_evaluation_dataframe["priority_share_lift_dissatisfaction_vs_satisfaction"] <= 0.92
    ],
    [
        "Priority-product-tilted",
        "Monitor-product-tilted"
    ],
    default = "Balanced"
)

driver_evaluation_dataframe["driver_balance_type"] = np.select(
    [
        driver_evaluation_dataframe["root_cause_share"] >= 0.60,
        driver_evaluation_dataframe["remedy_share"] >= 0.60
    ],
    [
        "Root-cause heavy",
        "Remedy-heavy"
    ],
    default = "Mixed"
)

driver_evaluation_dataframe["is_high_coverage_topic"] = (
    driver_evaluation_dataframe["eligible_segment_ratio"] >= 0.75
)

driver_evaluation_dataframe["is_sufficiently_large"] = (
    driver_evaluation_dataframe["document_count_dissatisfaction"] >= 800
)

driver_evaluation_dataframe["is_assignment_reliable"] = (
    driver_evaluation_dataframe["topic_assignment_confidence"].isin(["High", "Moderate"])
)

driver_evaluation_dataframe["is_driver_candidate"] = (
    driver_evaluation_dataframe["is_high_coverage_topic"]
    & driver_evaluation_dataframe["is_sufficiently_large"]
    & driver_evaluation_dataframe["is_assignment_reliable"]
)

driver_evaluation_dataframe["driver_interpretation_status"] = np.select(
    [
        (
            driver_evaluation_dataframe["is_driver_candidate"]
            & driver_evaluation_dataframe["dissatisfaction_signal_strength"].eq("Strong")
            & driver_evaluation_dataframe["driver_balance_type"].eq("Root-cause heavy")
        ),
        (
            driver_evaluation_dataframe["is_driver_candidate"]
            & driver_evaluation_dataframe["dissatisfaction_signal_strength"].isin(["Strong", "Moderate"])
            & driver_evaluation_dataframe["driver_balance_type"].eq("Mixed")
        ),
        (
            driver_evaluation_dataframe["is_driver_candidate"]
            & driver_evaluation_dataframe["driver_balance_type"].eq("Remedy-heavy")
        )
    ],
    [
        "Root-cause dominant candidate",
        "Mixed candidate",
        "Remedy-heavy candidate"
    ],
    default = "Watch / low-confidence candidate"
)

driver_evaluation_result_dataframe = (
    driver_evaluation_dataframe[
        [
            "topic_id",
            "top_terms",
            "document_count_dissatisfaction",
            "document_count_satisfaction",
            "document_share_lift_dissatisfaction_vs_satisfaction",
            "topic_weight_share_lift_dissatisfaction_vs_satisfaction",
            "eligible_segment_ratio",
            "topic_assignment_confidence",
            "topic_breadth_type",
            "dominant_driver_family",
            "dominant_driver_family_share",
            "root_cause_share",
            "remedy_share",
            "premium_exposure_level",
            "priority_exposure_level",
            "driver_balance_type",
            "driver_interpretation_status",
            "top_accepted_phrases"
        ]
    ]
    .sort_values(
        by = [
            "driver_interpretation_status",
            "document_share_lift_dissatisfaction_vs_satisfaction",
            "eligible_segment_ratio",
            "document_count_dissatisfaction"
        ],
        ascending = [True, False, False, False]
    )
    .reset_index(drop = True)
)

display(driver_evaluation_result_dataframe)

,topic_id,top_terms,document_count_dissatisfaction,document_count_satisfaction,document_share_lift_dissatisfaction_vs_satisfaction,topic_weight_share_lift_dissatisfaction_vs_satisfaction,eligible_segment_ratio,topic_assignment_confidence,topic_breadth_type,dominant_driver_family,dominant_driver_family_share,root_cause_share,remedy_share,premium_exposure_level,priority_exposure_level,driver_balance_type,driver_interpretation_status,top_accepted_phrases
0,11,"remote, remote work, remotes, buttons, remote ...",915,923,1.079976,1.093902,1.000000,Moderate,Broad,Mixed,0.130775,0.575865,0.424135,Balanced,Balanced,Mixed,Mixed candidate,"late return, total waste_money, dont buy, miss..."
1,4,"drive, drives, files, disk, data, hard_drive, ...",1545,1571,1.071390,1.145317,1.000000,Moderate,Broad,Mixed,0.133299,0.508925,0.491075,Balanced,Balanced,Mixed,Mixed candidate,"outside return_window, try multiple computers,..."
2,12,"charger, charge battery, hold charge, battery ...",1060,740,1.560507,1.616824,0.777778,Watch,Broad,Mixed,0.146357,0.504729,0.495271,Premium-tilted,Priority-product-tilted,Mixed,Watch / low-confidence candidate,"total waste_money, complete waste_money, wish ..."
3,3,"charge phone, cords, chargers, charger, not_ch...",1231,1171,1.145238,1.298866,0.555556,Moderate,Concentrated,Mixed,0.203612,0.785937,0.214063,Non-premium-tilted,Priority-product-tilted,Root-cause heavy,Watch / low-confidence candidate,"stopped_working waste_money, return try, retur..."
4,5,"mouse, keyboard, keys, logitech, mouse work, k...",945,933,1.103430,1.083497,0.888889,High,Broad,Mixed,0.118652,0.623608,0.376392,Non-premium-tilted,Balanced,Root-cause heavy,Watch / low-confidence candidate,"stopped_working disappointed, disappointed ret..."
5,0,"router, wifi, network, internet, modem, netgea...",830,822,1.100021,1.274283,0.777778,Moderate,Broad,Mixed,0.211370,0.698950,0.301050,Premium-tilted,Balanced,Root-cause heavy,Watch / low-confidence candidate,"outside return_window, past return_window, com..."
6,1,"ear, headphone, earbuds, ears, buds, earbud, s...",1937,1926,1.095641,0.958862,1.000000,High,Broad,Mixed,0.125330,0.742784,0.257216,Balanced,Balanced,Root-cause heavy,Watch / low-confidence candidate,"work waste_money, return waste, return not_wor..."
7,10,"bubbles, screen_protector, protectors, screen ...",507,515,1.072495,1.100252,0.333333,High,Concentrated,Mixed,0.145281,0.861071,0.138929,Non-premium-tilted,Balanced,Root-cause heavy,Watch / low-confidence candidate,"complete waste_money, buyer beware, total wast..."
8,9,"hdmi, monitor, hdmi cable, display, adapter, p...",1109,1163,1.038836,1.019514,1.000000,Moderate,Broad,Mixed,0.146249,0.707565,0.292435,Balanced,Balanced,Root-cause heavy,Watch / low-confidence candidate,"does_not_work advertised, waste bought, return..."
9,13,"antenna, stations, reception, channels, miles,...",558,593,1.025120,0.888472,0.888889,High,Broad,Mixed,0.204672,0.523067,0.476933,Balanced,Balanced,Mixed,Watch / low-confidence candidate,"window return, dont waste, work waste, does_no..."
10,14,"fitbit, band, wrist, watch, bands, heart rate,...",474,545,0.947498,0.813049,0.777778,High,Broad,Mixed,0.144391,0.535592,0.464408,Balanced,Balanced,Mixed,Watch / low-confidence candidate,"total waste_money, return immediately, complet..."
11,8,"speaker, sound_quality, music, bluetooth, bass...",1508,1767,0.929738,0.889906,1.000000,Watch,Broad,Mixed,0.144601,0.664692,0.335308,Balanced,Balanced,Root-cause heavy,Watch / low-confidence candidate,"return immediately, waste work, return waste, ..."
12,7,"camera, camera work, motion, recording, view, ...",1339,1759,0.829299,0.855017,0.888889,Moderate,Broad,Mixed,0.203637,0.758440,0.241560,Balanced,Priority-product-tilted,Root-cause heavy,Watch / low-confidence candidate,"customer_service horrible, does_not_work adver..."
13,6,"screws, mount, screw, mounting, bracket, tight...",1246,1664,0.815758,0.787445,0.777778,Moderate,Moderate,Mixed,0.159978,0.652595,0.347405,Balanced,Priority-product-tilted,Root-cause heavy,Watch / low-confidence candidate,"complete waste_money, super disappointed, retu..."
14,2,"ipad, not_fit, protect, color, cases, fits, co...",1649,2268,0.792089,0.777654,0.666667,Moderate,Concentrated,Mixed,0.264926,0.784833,0.215167,Non-premium-tilted,Priority-product-tilted,Root-cause heavy,Watch / low-confidence candidate,"total waste_money, waste_money case, case poor..."

In [47]:
# Removing non-root-cause language from topic modeling text
root_cause_non_cause_tokens = (
    remedy_or_transaction_tokens
    .union(evaluative_outcome_tokens)
)

def build_root_cause_text(modeling_text_value):
    if not modeling_text_value:
        return ""

    filtered_tokens = [
        token
        for token in str(modeling_text_value).split()
        if token not in root_cause_non_cause_tokens
    ]

    return " ".join(filtered_tokens)

full_corpus_modeling_dataframe["root_cause_modeling_text"] = (
    full_corpus_modeling_dataframe["modeling_text_for_vectorizer"]
    .fillna("")
    .apply(build_root_cause_text)
    .str.replace(r"\s+", " ", regex = True)
    .str.strip()
)

full_corpus_modeling_dataframe["root_cause_token_count"] = (
    full_corpus_modeling_dataframe["root_cause_modeling_text"]
    .str.split()
    .str.len()
)

root_cause_text_quality_summary_dataframe = pd.DataFrame({
    "metric": [
        "full_modeling_document_count",
        "blank_root_cause_text_count",
        "documents_under_30_root_cause_tokens",
        "documents_under_50_root_cause_tokens",
        "average_root_cause_token_count",
        "median_root_cause_token_count"
    ],
    "value": [
        len(full_corpus_modeling_dataframe),
        full_corpus_modeling_dataframe["root_cause_modeling_text"].eq("").sum(),
        full_corpus_modeling_dataframe["root_cause_token_count"].lt(30).sum(),
        full_corpus_modeling_dataframe["root_cause_token_count"].lt(50).sum(),
        full_corpus_modeling_dataframe["root_cause_token_count"].mean(),
        full_corpus_modeling_dataframe["root_cause_token_count"].median()
    ]
})

display(root_cause_text_quality_summary_dataframe)

                                 metric         value
0          full_modeling_document_count  35213.000000
1           blank_root_cause_text_count      0.000000
2  documents_under_30_root_cause_tokens      0.000000
3  documents_under_50_root_cause_tokens      0.000000
4        average_root_cause_token_count   1277.601284
5         median_root_cause_token_count   1120.000000

In [48]:
# Preparing root-cause-focused dissatisfied documents for topic modeling
root_cause_dissatisfaction_dataframe = full_corpus_modeling_dataframe.loc[
    full_corpus_modeling_dataframe["analysis_pool_role"].eq("Topic modeling target")
    & full_corpus_modeling_dataframe["root_cause_modeling_text"].ne("")
].copy()

root_cause_tfidf_vectorizer = TfidfVectorizer(
    lowercase = False,
    stop_words = None,
    token_pattern = r"(?u)\b[a-z_][a-z0-9_]{2,}\b",
    ngram_range = (1, 2),
    min_df = 25,
    max_df = 0.35,
    max_features = 30000,
    sublinear_tf = True
)

root_cause_dissatisfaction_tfidf_matrix = root_cause_tfidf_vectorizer.fit_transform(
    root_cause_dissatisfaction_dataframe["root_cause_modeling_text"]
)

root_cause_selected_topic_count = 15

root_cause_nmf_model = NMF(
    n_components = root_cause_selected_topic_count,
    init = "nndsvda",
    random_state = 42,
    max_iter = 400
)

root_cause_document_topic_matrix = root_cause_nmf_model.fit_transform(
    root_cause_dissatisfaction_tfidf_matrix
)

root_cause_topic_term_matrix = root_cause_nmf_model.components_
root_cause_feature_names = np.array(root_cause_tfidf_vectorizer.get_feature_names_out())

root_cause_topic_rows = []

for topic_index, topic_weights in enumerate(root_cause_topic_term_matrix):
    top_term_indices = topic_weights.argsort()[ : : -1][ : 15]
    root_cause_topic_rows.append({
        "topic_id": topic_index,
        "top_terms": ", ".join(root_cause_feature_names[top_term_indices])
    })

root_cause_topic_terms_dataframe = pd.DataFrame(root_cause_topic_rows)
display(root_cause_topic_terms_dataframe)

    topic_id                                          top_terms
0          0  router, wifi, network, internet, modem, netgea...
1          1  ear, headphone, earbuds, ears, buds, earbud, s...
2          2  ipad, not_fit, protect, color, cases, fits, co...
3          3  charge phone, cords, chargers, charger, not_ch...
4          4  drive, drives, files, disk, data, hard_drive, ...
5          5  mouse, keyboard, keys, logitech, mouse work, k...
6          6  screws, mount, screw, mounting, bracket, tight...
7          7  camera, camera work, motion, recording, view, ...
8          8  speaker, sound_quality, music, bluetooth, bass...
9          9  hdmi, monitor, hdmi cable, display, adapter, p...
10        10  bubbles, screen_protector, protectors, screen ...
11        11  remote, remote work, remotes, buttons, remote ...
12        12  charger, charge battery, hold charge, battery ...
13        13  antenna, stations, reception, channels, miles,...
14        14  fitbit, band, wrist, watch, bands, heart rate,...

In [49]:
# Comparing topic counts for the root-cause-focused model

candidate_root_cause_topic_counts = [10, 12, 15, 18]

root_cause_topic_model_diagnostics = []

for topic_count in candidate_root_cause_topic_counts:
    candidate_root_cause_nmf_model = NMF(
        n_components = topic_count,
        init = "nndsvda",
        random_state = 42,
        max_iter = 400
    )

    candidate_root_cause_document_topic_matrix = candidate_root_cause_nmf_model.fit_transform(
        root_cause_dissatisfaction_tfidf_matrix
    )

    dominant_topic_assignment = candidate_root_cause_document_topic_matrix.argmax(axis = 1)
    dominant_topic_strength = candidate_root_cause_document_topic_matrix.max(axis = 1)

    topic_size_dataframe = (
        pd.DataFrame({
            "topic_id": dominant_topic_assignment,
            "topic_strength": dominant_topic_strength
        })
        .groupby("topic_id", dropna = False)
        .agg(
            document_count = ("topic_id", "count"),
            average_topic_strength = ("topic_strength", "mean"),
            median_topic_strength = ("topic_strength", "median")
        )
        .reset_index()
    )

    root_cause_topic_model_diagnostics.append({
        "topic_count": topic_count,
        "reconstruction_error": candidate_root_cause_nmf_model.reconstruction_err_,
        "mean_max_topic_strength": dominant_topic_strength.mean(),
        "median_max_topic_strength": np.median(dominant_topic_strength),
        "smallest_topic_document_count": topic_size_dataframe["document_count"].min(),
        "largest_topic_document_count": topic_size_dataframe["document_count"].max(),
        "topic_size_ratio_max_to_min": (
            topic_size_dataframe["document_count"].max() /
            topic_size_dataframe["document_count"].min()
        )
    })

root_cause_topic_model_diagnostics_dataframe = pd.DataFrame(root_cause_topic_model_diagnostics)
display(root_cause_topic_model_diagnostics_dataframe.sort_values("topic_count"))

,topic_count,reconstruction_error,mean_max_topic_strength,median_max_topic_strength,smallest_topic_document_count,largest_topic_document_count,topic_size_ratio_max_to_min
0,10,122.173674,0.073915,0.066940,493,3098,6.283976
1,12,121.625818,0.076147,0.072939,506,1987,3.926877
2,15,120.981810,0.078689,0.074678,468,1947,4.160256
3,18,120.415896,0.080843,0.075005,419,1952,4.658711

In [50]:
# Applying the root-cause topic model to comparison documents

root_cause_comparison_dataframe = full_corpus_modeling_dataframe.loc[
    ~full_corpus_modeling_dataframe["is_dissatisfaction"]
].copy()

root_cause_comparison_tfidf_matrix = root_cause_tfidf_vectorizer.transform(
    root_cause_comparison_dataframe["root_cause_modeling_text"]
)

root_cause_comparison_topic_matrix = root_cause_nmf_model.transform(
    root_cause_comparison_tfidf_matrix
)

root_cause_dissatisfaction_dataframe = root_cause_dissatisfaction_dataframe.reset_index(drop = True)
root_cause_comparison_dataframe = root_cause_comparison_dataframe.reset_index(drop = True)

root_cause_dissatisfaction_dataframe["topic_id"] = root_cause_document_topic_matrix.argmax(axis = 1)
root_cause_dissatisfaction_dataframe["topic_strength"] = root_cause_document_topic_matrix.max(axis = 1)

root_cause_comparison_dataframe["topic_id"] = root_cause_comparison_topic_matrix.argmax(axis = 1)
root_cause_comparison_dataframe["topic_strength"] = root_cause_comparison_topic_matrix.max(axis = 1)

root_cause_topic_assignment_dataframe = pd.concat(
    [
        root_cause_dissatisfaction_dataframe.assign(cohort_role = "Dissatisfaction"),
        root_cause_comparison_dataframe.assign(cohort_role = "Satisfaction")
    ],
    ignore_index = True
)

root_cause_topic_rows = []

for topic_index, topic_weights in enumerate(root_cause_topic_term_matrix):
    top_term_indices = topic_weights.argsort()[ : : -1][ : 15]
    root_cause_topic_rows.append({
        "topic_id": topic_index,
        "top_terms": ", ".join(root_cause_feature_names[top_term_indices])
    })

root_cause_topic_terms_dataframe = pd.DataFrame(root_cause_topic_rows)

display(root_cause_topic_terms_dataframe)
print(f"Root-cause topic assignment rows : {len(root_cause_topic_assignment_dataframe):,}")
display(root_cause_topic_assignment_dataframe["cohort_role"].value_counts(dropna = False))

    topic_id                                          top_terms
0          0  router, wifi, network, internet, modem, netgea...
1          1  ear, headphone, earbuds, ears, buds, earbud, s...
2          2  ipad, not_fit, protect, color, cases, fits, co...
3          3  charge phone, cords, chargers, charger, not_ch...
4          4  drive, drives, files, disk, data, hard_drive, ...
5          5  mouse, keyboard, keys, logitech, mouse work, k...
6          6  screws, mount, screw, mounting, bracket, tight...
7          7  camera, camera work, motion, recording, view, ...
8          8  speaker, sound_quality, music, bluetooth, bass...
9          9  hdmi, monitor, hdmi cable, display, adapter, p...
10        10  bubbles, screen_protector, protectors, screen ...
11        11  remote, remote work, remotes, buttons, remote ...
12        12  charger, charge battery, hold charge, battery ...
13        13  antenna, stations, reception, channels, miles,...
14        14  fitbit, band, wrist, watch, bands, heart rate,...

Root-cause topic assignment rows : 35,213

cohort_role
Satisfaction       18360
Dissatisfaction    16853
Name: count, dtype: int64

In [51]:
# Reviewing root-cause topic distribution across dissatisfied segments

root_cause_dissatisfaction_segment_distribution_dataframe = (
    root_cause_topic_assignment_dataframe.loc[
        root_cause_topic_assignment_dataframe["cohort_role"] == "Dissatisfaction"
    ]
    .groupby(["topic_id", "price_band", "issue_priority_level"], dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        sampled_reviews = ("sampled_review_count", "sum")
    )
    .reset_index()
)

root_cause_dissatisfaction_segment_distribution_dataframe["segment_document_share_within_topic"] = (
    root_cause_dissatisfaction_segment_distribution_dataframe["document_count"] /
    root_cause_dissatisfaction_segment_distribution_dataframe.groupby("topic_id")["document_count"].transform("sum")
)

root_cause_topic_breadth_summary_dataframe = (
    root_cause_dissatisfaction_segment_distribution_dataframe
    .groupby("topic_id", dropna = False)
    .agg(
        covered_segment_count = ("segment_document_share_within_topic", "count"),
        segment_count_above_05_share = ("segment_document_share_within_topic", lambda values: (values >= 0.05).sum()),
        segment_count_above_10_share = ("segment_document_share_within_topic", lambda values: (values >= 0.10).sum()),
        max_segment_share = ("segment_document_share_within_topic", "max"),
        concentration_hhi = ("segment_document_share_within_topic", lambda values: np.square(values).sum())
    )
    .reset_index()
)

display(
    root_cause_topic_breadth_summary_dataframe.sort_values(
        by = ["concentration_hhi", "max_segment_share"],
        ascending = [False, False]
    )
)

,topic_id,covered_segment_count,segment_count_above_05_share,segment_count_above_10_share,max_segment_share,concentration_hhi
10,10,8,3,3,0.570020,0.382149
3,3,9,4,3,0.462158,0.300806
2,2,9,4,3,0.402056,0.265955
6,6,9,4,4,0.305778,0.210719
7,7,9,6,4,0.295356,0.181152
4,4,9,6,4,0.210560,0.162824
0,0,9,6,5,0.250301,0.161870
12,12,9,7,4,0.245703,0.160750
8,8,9,6,4,0.236231,0.159741
9,9,9,7,4,0.259160,0.156537
13,13,9,8,4,0.255396,0.149358
11,11,9,8,4,0.210989,0.144821
14,14,9,7,6,0.235043,0.142861
5,5,9,7,5,0.213531,0.138520
1,1,9,8,6,0.206471,0.135249

In [52]:
# Preparing root-cause topic labels and top-term mappings

root_cause_topic_top_terms_map = {}

for topic_index, topic_weights in enumerate(root_cause_topic_term_matrix):
    top_term_indices = topic_weights.argsort()[ : : -1][ : 15]
    root_cause_topic_top_terms_map[topic_index] = root_cause_feature_names[top_term_indices].tolist()

root_cause_topic_assignment_dataframe["topic_margin"] = compute_assignment_margin(
    np.vstack([
        root_cause_document_topic_matrix,
        root_cause_comparison_topic_matrix
    ])
)

root_cause_topic_assignment_dataframe["is_topic_core_document"] = (
    (root_cause_topic_assignment_dataframe["topic_strength"] >= 0.06)
    & (root_cause_topic_assignment_dataframe["topic_margin"] >= 0.03)
)

root_cause_topic_core_summary_dataframe = (
    root_cause_topic_assignment_dataframe
    .groupby(["cohort_role", "topic_id"], dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        topic_core_document_count = ("is_topic_core_document", "sum"),
        average_topic_strength = ("topic_strength", "mean"),
        average_topic_margin = ("topic_margin", "mean")
    )
    .reset_index()
)

root_cause_topic_core_summary_dataframe["topic_core_ratio"] = (
    root_cause_topic_core_summary_dataframe["topic_core_document_count"] /
    root_cause_topic_core_summary_dataframe["document_count"].replace(0, np.nan)
)

display(
    root_cause_topic_core_summary_dataframe.sort_values(
        ["cohort_role", "topic_id"]
    )
)

,cohort_role,topic_id,document_count,topic_core_document_count,average_topic_strength,average_topic_margin,topic_core_ratio
0,Dissatisfaction,0,831,509,0.061015,0.048547,0.612515
1,Dissatisfaction,1,1947,1535,0.088046,0.066550,0.788392
2,Dissatisfaction,2,1654,1089,0.075338,0.055272,0.658404
3,Dissatisfaction,3,1242,746,0.086178,0.067602,0.600644
4,Dissatisfaction,4,1553,896,0.075913,0.055225,0.576948
5,Dissatisfaction,5,946,700,0.089248,0.069135,0.739958
6,Dissatisfaction,6,1246,592,0.068028,0.047184,0.475120
7,Dissatisfaction,7,1378,831,0.076247,0.052545,0.603048
8,Dissatisfaction,8,1507,618,0.061000,0.033495,0.410086
9,Dissatisfaction,9,1119,715,0.076120,0.051045,0.638963
10,Dissatisfaction,10,507,350,0.115506,0.101770,0.690335
11,Dissatisfaction,11,910,580,0.077667,0.055715,0.637363
12,Dissatisfaction,12,989,402,0.070092,0.048132,0.406471
13,Dissatisfaction,13,556,329,0.098418,0.071853,0.591727
14,Dissatisfaction,14,468,362,0.106479,0.086168,0.773504
15,Satisfaction,0,820,349,0.053132,0.038469,0.425610
16,Satisfaction,1,1930,1545,0.087748,0.070896,0.800518
17,Satisfaction,2,2285,1232,0.065037,0.045814,0.539168
18,Satisfaction,3,1185,638,0.067779,0.050756,0.538397
19,Satisfaction,4,1577,738,0.063353,0.043534,0.467977
20,Satisfaction,5,930,645,0.076905,0.057840,0.693548
21,Satisfaction,6,1644,579,0.058334,0.037417,0.352190
22,Satisfaction,7,1785,931,0.068286,0.048138,0.521569
23,Satisfaction,8,1765,851,0.060138,0.038100,0.482153
24,Satisfaction,9,1175,661,0.068395,0.044586,0.562553
25,Satisfaction,10,509,333,0.095682,0.081768,0.654224
26,Satisfaction,11,917,526,0.070613,0.051122,0.573610
27,Satisfaction,12,711,327,0.062641,0.044222,0.459916
28,Satisfaction,13,588,348,0.094635,0.069091,0.591837
29,Satisfaction,14,539,386,0.099458,0.084357,0.716141

In [53]:
# Defining terms to remove for pure product-cause analysis

pure_product_non_cause_text_tokens = (
    remedy_or_transaction_tokens
    .union(delivery_or_fulfillment_tokens)
    .union(evaluative_outcome_tokens)
)

def build_pure_product_cause_text(modeling_text_value):
    if not modeling_text_value:
        return ""

    filtered_tokens = [
        token
        for token in str(modeling_text_value).split()
        if token not in pure_product_non_cause_text_tokens
    ]

    return " ".join(filtered_tokens)

In [54]:
# Creating product-cause-focused text for issue analysis

full_corpus_modeling_dataframe["pure_product_cause_text"] = (
    full_corpus_modeling_dataframe["modeling_text_for_vectorizer"]
    .fillna("")
    .apply(build_pure_product_cause_text)
    .str.replace(r"\s+", " ", regex = True)
    .str.strip()
)

full_corpus_modeling_dataframe["pure_product_cause_token_count"] = (
    full_corpus_modeling_dataframe["pure_product_cause_text"].str.split().str.len()
)

pure_product_cause_quality_summary_dataframe = pd.DataFrame({
    "metric": [
        "document_count",
        "blank_pure_product_cause_text_count",
        "documents_under_30_tokens",
        "documents_under_50_tokens",
        "average_token_count",
        "median_token_count"
    ],
    "value": [
        len(full_corpus_modeling_dataframe),
        full_corpus_modeling_dataframe["pure_product_cause_text"].eq("").sum(),
        full_corpus_modeling_dataframe["pure_product_cause_token_count"].lt(30).sum(),
        full_corpus_modeling_dataframe["pure_product_cause_token_count"].lt(50).sum(),
        full_corpus_modeling_dataframe["pure_product_cause_token_count"].mean(),
        full_corpus_modeling_dataframe["pure_product_cause_token_count"].median()
    ]
})

display(pure_product_cause_quality_summary_dataframe)

                                metric         value
0                       document_count  35213.000000
1  blank_pure_product_cause_text_count      0.000000
2            documents_under_30_tokens      0.000000
3            documents_under_50_tokens      0.000000
4                  average_token_count   1263.107602
5                   median_token_count   1108.000000

In [55]:
# Checking whether non-product-cause language remains in the cleaned text
contamination_audit_rows = []

for token_family_name, token_family in {
    "remedy_or_transaction": remedy_or_transaction_tokens,
    "delivery_or_fulfillment": delivery_or_fulfillment_tokens
}.items():
    contamination_audit_rows.append({
        "token_family": token_family_name,
        "documents_with_family_signal": full_corpus_modeling_dataframe["modeling_text_for_vectorizer"]
            .apply(lambda value: any(token in str(value).split() for token in token_family))
            .sum(),
        "documents_with_family_signal_ratio": full_corpus_modeling_dataframe["modeling_text_for_vectorizer"]
            .apply(lambda value: any(token in str(value).split() for token in token_family))
            .mean()
    })

contamination_audit_dataframe = pd.DataFrame(contamination_audit_rows)
display(contamination_audit_dataframe)

,token_family,documents_with_family_signal,documents_with_family_signal_ratio
0,remedy_or_transaction,27979,0.794565
1,delivery_or_fulfillment,34476,0.979070

In [56]:
# Reviewing protected technical and business terms retained in the text

protected_and_business_tokens = sorted(
    protected_phrase_tokens.union(short_technical_tokens)
)

token_policy_audit_rows = []

for token_value in protected_and_business_tokens:
    document_count = full_corpus_modeling_dataframe["modeling_text_for_vectorizer"].str.contains(
        rf"\b{re.escape(token_value)}\b",
        regex = True,
        na = False
    ).sum()

    if document_count > 0:
        token_policy_audit_rows.append({
            "token": token_value,
            "document_count": document_count,
            "document_ratio": document_count / len(full_corpus_modeling_dataframe)
        })

token_policy_audit_dataframe = (
    pd.DataFrame(token_policy_audit_rows)
    .sort_values(["document_count", "token"], ascending = [False, True])
    .reset_index(drop = True)
)

full_clipping_effect_summary_dataframe = (
    full_topic_assignment_dataframe
    .groupby(["topic_id", "cohort_role", "clipping_applied"], dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        sampled_reviews = ("sampled_review_count", "sum")
    )
    .reset_index()
)

display(token_policy_audit_dataframe.head(120))
display(full_clipping_effect_summary_dataframe.sort_values(["topic_id", "cohort_role", "clipping_applied"]))

                  token  document_count  document_ratio
0          did_not_work           18028        0.511970
1         does_not_work           17850        0.506915
2      customer_service           15865        0.450544
3       stopped_working           15553        0.441683
4                   usb           15550        0.441598
5                    pc           12287        0.348934
6                    tv           12164        0.345441
7           not_working           11146        0.316531
8             bluetooth           10060        0.285690
9         sound_quality            9240        0.262403
10        return_window            8869        0.251867
11     on_time_delivery            8328        0.236504
12         battery_life            8146        0.231335
13         poor_quality            8088        0.229688
14                  led            7625        0.216539
15                 wifi            7489        0.212677
16              not_fit            6788        0.192770
17                   hd            6504        0.184705
18        build_quality            6115        0.173657
19         tech_support            5769        0.163832
20       not_compatible            5374        0.152614
21           not_charge            4681        0.132934
22      picture_quality            4522        0.128418
23                 hdmi            4492        0.127567
24                usb_c            4034        0.114560
25         not_charging            4022        0.114219
26             no_sound            3669        0.104194
27                   ac            3598        0.102178
28        return_policy            3464        0.098373
29          not_turn_on            3449        0.097947
30           hard_drive            3442        0.097748
31     noise_cancelling            2976        0.084514
32              sd_card            2946        0.083662
33             smart_tv            2668        0.075767
34                  ps4            2535        0.071990
35                  lcd            2416        0.068611
36          not_connect            2400        0.068157
37     will_not_turn_on            2380        0.067589
38             no_power            2316        0.065771
39                   sd            2285        0.064891
40                  ssd            2118        0.060148
41       not_connecting            2064        0.058615
42             micro_sd            1967        0.055860
43            no_signal            1811        0.051430
44      dead_on_arrival            1771        0.050294
45                  gps            1726        0.049016
46                usb_a            1291        0.036663
47                   dc            1184        0.033624
48                 dslr            1183        0.033596
49         battery_died            1049        0.029790
50  keeps_disconnecting             983        0.027916
51                  ps5             732        0.020788
52                   vr             542        0.015392
53                 oled             509        0.014455
54             not_pair             369        0.010479
55                 qled             183        0.005197
56        late_delivery             160        0.004544
57          not_pairing             129        0.003663

,topic_id,cohort_role,clipping_applied,document_count,sampled_reviews
0,0,Dissatisfaction,False,413,29761
1,0,Dissatisfaction,True,417,96259
2,0,Satisfaction,False,459,31658
3,0,Satisfaction,True,363,82194
4,1,Dissatisfaction,False,1007,72968
5,1,Dissatisfaction,True,930,212294
6,1,Satisfaction,False,1157,79855
7,1,Satisfaction,True,769,174032
8,2,Dissatisfaction,False,1319,79567
9,2,Dissatisfaction,True,330,71710
10,2,Satisfaction,False,1750,103140
11,2,Satisfaction,True,518,113016
12,3,Dissatisfaction,False,740,53337
13,3,Dissatisfaction,True,491,109372
14,3,Satisfaction,False,813,52298
15,3,Satisfaction,True,358,78574
16,4,Dissatisfaction,False,1038,69331
17,4,Dissatisfaction,True,507,113798
18,4,Satisfaction,False,1099,68154
19,4,Satisfaction,True,472,103217
20,5,Dissatisfaction,False,580,41119
21,5,Dissatisfaction,True,365,83376
22,5,Satisfaction,False,621,40127
23,5,Satisfaction,True,312,70193
24,6,Dissatisfaction,False,1036,60574
25,6,Dissatisfaction,True,210,45341
26,6,Satisfaction,False,1372,79101
27,6,Satisfaction,True,292,63666
28,7,Dissatisfaction,False,898,57575
29,7,Dissatisfaction,True,441,98476
30,7,Satisfaction,False,1282,77006
31,7,Satisfaction,True,477,105044
32,8,Dissatisfaction,False,982,66923
33,8,Dissatisfaction,True,526,119025
34,8,Satisfaction,False,1188,76196
35,8,Satisfaction,True,579,131950
36,9,Dissatisfaction,False,834,55963
37,9,Dissatisfaction,True,275,60647
38,9,Satisfaction,False,883,54857
39,9,Satisfaction,True,280,61802
40,10,Dissatisfaction,False,379,24483
41,10,Dissatisfaction,True,128,26982
42,10,Satisfaction,False,397,23748
43,10,Satisfaction,True,118,26035
44,11,Dissatisfaction,False,579,40074
45,11,Dissatisfaction,True,336,76011
46,11,Satisfaction,False,627,38100
47,11,Satisfaction,True,296,65588
48,12,Dissatisfaction,False,792,51799
49,12,Dissatisfaction,True,268,57981
50,12,Satisfaction,False,623,35145
51,12,Satisfaction,True,117,25716
52,13,Dissatisfaction,False,381,27145
53,13,Dissatisfaction,True,177,39325
54,13,Satisfaction,False,404,25643
55,13,Satisfaction,True,189,42179
56,14,Dissatisfaction,False,341,23682
57,14,Dissatisfaction,True,133,28445
58,14,Satisfaction,False,399,24495
59,14,Satisfaction,True,146,32227

In [57]:
# Summarizing root-cause topic exposure and cohort differences

root_cause_topic_summary_dataframe = (
    root_cause_topic_assignment_dataframe
    .groupby(["cohort_role", "topic_id"], dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        sampled_reviews = ("sampled_review_count", "sum"),
        average_topic_strength = ("topic_strength", "mean"),
        average_topic_margin = ("topic_margin", "mean")
    )
    .reset_index()
)

root_cause_cohort_totals_dataframe = (
    root_cause_topic_assignment_dataframe
    .groupby("cohort_role", dropna = False)
    .agg(
        total_documents = ("document_id", "count"),
        total_sampled_reviews = ("sampled_review_count", "sum")
    )
    .reset_index()
)

root_cause_topic_summary_dataframe = root_cause_topic_summary_dataframe.merge(
    root_cause_cohort_totals_dataframe,
    on = "cohort_role",
    how = "left"
)

root_cause_topic_summary_dataframe["document_share"] = (
    root_cause_topic_summary_dataframe["document_count"] /
    root_cause_topic_summary_dataframe["total_documents"]
)

root_cause_topic_summary_pivot_dataframe = (
    root_cause_topic_summary_dataframe[
        [
            "cohort_role",
            "topic_id",
            "document_count",
            "sampled_reviews",
            "document_share",
            "average_topic_strength",
            "average_topic_margin"
        ]
    ]
    .pivot(index = "topic_id", columns = "cohort_role")
)

root_cause_topic_summary_pivot_dataframe.columns = [
    f"{metric_name}_{cohort_name.lower()}"
    for metric_name, cohort_name in root_cause_topic_summary_pivot_dataframe.columns
]

root_cause_topic_summary_pivot_dataframe = root_cause_topic_summary_pivot_dataframe.reset_index()

root_cause_topic_summary_pivot_dataframe["document_share_lift_dissatisfaction_vs_satisfaction"] = (
    (root_cause_topic_summary_pivot_dataframe["document_share_dissatisfaction"] + 1e-6) /
    (root_cause_topic_summary_pivot_dataframe["document_share_satisfaction"] + 1e-6)
)

root_cause_topic_summary_pivot_dataframe["document_share_gap"] = (
    root_cause_topic_summary_pivot_dataframe["document_share_dissatisfaction"] -
    root_cause_topic_summary_pivot_dataframe["document_share_satisfaction"]
)

root_cause_topic_driver_dataframe = (
    root_cause_topic_summary_pivot_dataframe
    .merge(root_cause_topic_terms_dataframe, on = "topic_id", how = "left")
    .merge(
        root_cause_topic_breadth_summary_dataframe,
        on = "topic_id",
        how = "left"
    )
    .merge(
        root_cause_topic_core_summary_dataframe.loc[
            root_cause_topic_core_summary_dataframe["cohort_role"] == "Dissatisfaction",
            ["topic_id", "topic_core_ratio"]
        ],
        on = "topic_id",
        how = "left"
    )
)

root_cause_topic_driver_dataframe["breadth_type"] = np.select(
    [
        root_cause_topic_driver_dataframe["concentration_hhi"] >= 0.25,
        root_cause_topic_driver_dataframe["segment_count_above_05_share"] >= 6
    ],
    [
        "Concentrated",
        "Broad"
    ],
    default = "Moderate"
)

root_cause_topic_driver_dataframe["signal_strength"] = np.select(
    [
        root_cause_topic_driver_dataframe["document_share_lift_dissatisfaction_vs_satisfaction"] >= 1.12,
        root_cause_topic_driver_dataframe["document_share_lift_dissatisfaction_vs_satisfaction"] >= 1.05
    ],
    [
        "Strong",
        "Moderate"
    ],
    default = "Weak"
)

root_cause_topic_driver_dataframe["confidence_level"] = np.select(
    [
        (
            root_cause_topic_driver_dataframe["average_topic_margin_dissatisfaction"] >= 0.06
        ) & (
            root_cause_topic_driver_dataframe["topic_core_ratio"] >= 0.60
        ),
        (
            root_cause_topic_driver_dataframe["average_topic_margin_dissatisfaction"] >= 0.04
        ) & (
            root_cause_topic_driver_dataframe["topic_core_ratio"] >= 0.45
        )
    ],
    [
        "High",
        "Moderate"
    ],
    default = "Watch"
)

display(
    root_cause_topic_driver_dataframe.sort_values(
        by = [
            "signal_strength",
            "confidence_level",
            "document_share_lift_dissatisfaction_vs_satisfaction",
            "document_count_dissatisfaction"
        ],
        ascending = [True, True, False, False]
    )
)

,topic_id,document_count_dissatisfaction,document_count_satisfaction,sampled_reviews_dissatisfaction,sampled_reviews_satisfaction,document_share_dissatisfaction,document_share_satisfaction,average_topic_strength_dissatisfaction,average_topic_strength_satisfaction,average_topic_margin_dissatisfaction,average_topic_margin_satisfaction,document_share_lift_dissatisfaction_vs_satisfaction,document_share_gap,top_terms,covered_segment_count,segment_count_above_05_share,segment_count_above_10_share,max_segment_share,concentration_hhi,topic_core_ratio,breadth_type,signal_strength,confidence_level
5,5,946,930,124571,110335,0.056132,0.050654,0.089248,0.076905,0.069135,0.057840,1.108161,0.005479,"mouse, keyboard, keys, logitech, mouse work, k...",9,7,5,0.213531,0.138520,0.739958,Broad,Moderate,High
1,1,1947,1930,286298,254459,0.115528,0.105120,0.088046,0.087748,0.066550,0.070896,1.099015,0.010409,"ear, headphone, earbuds, ears, buds, earbud, s...",9,8,6,0.206471,0.135249,0.788392,Broad,Moderate,High
10,10,507,509,51105,48732,0.030084,0.027723,0.115506,0.095682,0.101770,0.081768,1.085137,0.002360,"bubbles, screen_protector, protectors, screen ...",8,3,3,0.570020,0.382149,0.690335,Concentrated,Moderate,High
0,0,831,820,126258,113611,0.049309,0.044662,0.061015,0.053132,0.048547,0.038469,1.104032,0.004646,"router, wifi, network, internet, modem, netgea...",9,6,5,0.250301,0.161870,0.612515,Broad,Moderate,Moderate
11,11,910,917,115719,103240,0.053996,0.049946,0.077667,0.070613,0.055715,0.051122,1.081102,0.004051,"remote, remote work, remotes, buttons, remote ...",9,8,4,0.210989,0.144821,0.637363,Broad,Moderate,Moderate
4,4,1553,1577,184418,171614,0.092150,0.085893,0.075913,0.063353,0.055225,0.043534,1.072840,0.006257,"drive, drives, files, disk, data, hard_drive, ...",9,6,4,0.210560,0.162824,0.576948,Broad,Moderate,Moderate
3,3,1242,1185,163692,131985,0.073696,0.064542,0.086178,0.067779,0.067602,0.050756,1.141821,0.009154,"charge phone, cords, chargers, charger, not_ch...",9,4,3,0.462158,0.300806,0.600644,Concentrated,Strong,High
12,12,989,711,101780,58266,0.058684,0.038725,0.070092,0.062641,0.048132,0.044222,1.515369,0.019958,"charger, charge battery, hold charge, battery ...",9,7,4,0.245703,0.160750,0.406471,Broad,Strong,Watch
14,14,468,539,51535,55977,0.027770,0.029357,0.106479,0.099458,0.086168,0.084357,0.945918,-0.001588,"fitbit, band, wrist, watch, bands, heart rate,...",9,7,6,0.235043,0.142861,0.773504,Broad,Weak,High
9,9,1119,1175,117394,117420,0.066398,0.063998,0.076120,0.068395,0.051045,0.044586,1.037498,0.002400,"hdmi, monitor, hdmi cable, display, adapter, p...",9,7,4,0.259160,0.156537,0.638963,Broad,Weak,Moderate
13,13,556,588,65858,67479,0.032991,0.032026,0.098418,0.094635,0.071853,0.069091,1.030131,0.000965,"antenna, stations, reception, channels, miles,...",9,8,4,0.255396,0.149358,0.591727,Broad,Weak,Moderate
7,7,1378,1785,160124,184292,0.081766,0.097222,0.076247,0.068286,0.052545,0.048138,0.841022,-0.015456,"camera, camera work, motion, recording, view, ...",9,6,4,0.295356,0.181152,0.603048,Broad,Weak,Moderate
6,6,1246,1644,105811,141740,0.073933,0.089542,0.068028,0.058334,0.047184,0.037417,0.825682,-0.015609,"screws, mount, screw, mounting, bracket, tight...",9,4,4,0.305778,0.210719,0.475120,Moderate,Weak,Moderate
2,2,1654,2285,152161,217927,0.098143,0.124455,0.075338,0.065037,0.055272,0.045814,0.788580,-0.026313,"ipad, not_fit, protect, color, cases, fits, co...",9,4,3,0.402056,0.265955,0.658404,Concentrated,Weak,Moderate
8,8,1507,1765,186619,207879,0.089420,0.096133,0.061000,0.060138,0.033495,0.038100,0.930174,-0.006713,"speaker, sound_quality, music, bluetooth, bass...",9,6,4,0.236231,0.159741,0.410086,Broad,Weak,Watch

In [58]:
# Preparing product-cause dissatisfied documents for final issue analysis

pure_product_cause_dissatisfaction_dataframe = full_corpus_modeling_dataframe.loc[
    full_corpus_modeling_dataframe["analysis_pool_role"].eq("Topic modeling target")
    & full_corpus_modeling_dataframe["pure_product_cause_text"].ne("")
].copy()

pure_product_cause_comparison_dataframe = full_corpus_modeling_dataframe.loc[
    ~full_corpus_modeling_dataframe["is_dissatisfaction"]
    & full_corpus_modeling_dataframe["pure_product_cause_text"].ne("")
].copy()

print(f"Dissatisfaction documents : {len(pure_product_cause_dissatisfaction_dataframe):,}")
print(f"Satisfaction documents : {len(pure_product_cause_comparison_dataframe):,}")

Dissatisfaction documents : 16,853
Satisfaction documents : 18,360

In [59]:
# Vectorizing product-cause text for topic modeling

pure_product_cause_tfidf_vectorizer = TfidfVectorizer(
    lowercase = False,
    stop_words = None,
    token_pattern = r"(?u)\b[a-z_][a-z0-9_]{2,}\b",
    ngram_range = (1, 2),
    min_df = 25,
    max_df = 0.35,
    max_features = 30000,
    sublinear_tf = True
)

pure_product_cause_dissatisfaction_tfidf_matrix = pure_product_cause_tfidf_vectorizer.fit_transform(
    pure_product_cause_dissatisfaction_dataframe["pure_product_cause_text"]
)

candidate_pure_product_topic_counts = [10, 12, 15, 18]

pure_product_topic_model_diagnostics = []

for topic_count in candidate_pure_product_topic_counts:
    candidate_model = NMF(
        n_components = topic_count,
        init = "nndsvda",
        random_state = 42,
        max_iter = 400
    )

    candidate_document_topic_matrix = candidate_model.fit_transform(
        pure_product_cause_dissatisfaction_tfidf_matrix
    )

    dominant_topic_assignment = candidate_document_topic_matrix.argmax(axis = 1)
    dominant_topic_strength = candidate_document_topic_matrix.max(axis = 1)

    topic_size_dataframe = (
        pd.DataFrame({
            "topic_id": dominant_topic_assignment,
            "topic_strength": dominant_topic_strength
        })
        .groupby("topic_id", dropna = False)
        .agg(
            document_count = ("topic_id", "count"),
            average_topic_strength = ("topic_strength", "mean"),
            median_topic_strength = ("topic_strength", "median")
        )
        .reset_index()
    )

    pure_product_topic_model_diagnostics.append({
        "topic_count": topic_count,
        "reconstruction_error": candidate_model.reconstruction_err_,
        "mean_max_topic_strength": dominant_topic_strength.mean(),
        "median_max_topic_strength": np.median(dominant_topic_strength),
        "smallest_topic_document_count": topic_size_dataframe["document_count"].min(),
        "largest_topic_document_count": topic_size_dataframe["document_count"].max(),
        "topic_size_ratio_max_to_min": (
            topic_size_dataframe["document_count"].max() /
            topic_size_dataframe["document_count"].min()
        )
    })

pure_product_topic_model_diagnostics_dataframe = pd.DataFrame(
    pure_product_topic_model_diagnostics
)

display(pure_product_topic_model_diagnostics_dataframe.sort_values("topic_count"))

,topic_count,reconstruction_error,mean_max_topic_strength,median_max_topic_strength,smallest_topic_document_count,largest_topic_document_count,topic_size_ratio_max_to_min
0,10,122.159686,0.074099,0.067141,493,3089,6.265720
1,12,121.607258,0.076324,0.072984,508,1989,3.915354
2,15,120.958521,0.080229,0.075667,504,1943,3.855159
3,18,120.388863,0.081156,0.075329,418,1953,4.672249

In [60]:
# Training the selected product-cause topic model

selected_pure_product_topic_count = 15

pure_product_cause_nmf_model = NMF(
    n_components = selected_pure_product_topic_count,
    init = "nndsvda",
    random_state = 42,
    max_iter = 400
)

pure_product_cause_document_topic_matrix = pure_product_cause_nmf_model.fit_transform(
    pure_product_cause_dissatisfaction_tfidf_matrix
)

pure_product_cause_topic_term_matrix = pure_product_cause_nmf_model.components_
pure_product_cause_feature_names = np.array(
    pure_product_cause_tfidf_vectorizer.get_feature_names_out()
)

pure_product_cause_comparison_tfidf_matrix = pure_product_cause_tfidf_vectorizer.transform(
    pure_product_cause_comparison_dataframe["pure_product_cause_text"]
)

pure_product_cause_comparison_topic_matrix = pure_product_cause_nmf_model.transform(
    pure_product_cause_comparison_tfidf_matrix
)

pure_product_cause_dissatisfaction_dataframe = pure_product_cause_dissatisfaction_dataframe.reset_index(drop = True)
pure_product_cause_comparison_dataframe = pure_product_cause_comparison_dataframe.reset_index(drop = True)

pure_product_cause_dissatisfaction_dataframe["topic_id"] = pure_product_cause_document_topic_matrix.argmax(axis = 1)
pure_product_cause_dissatisfaction_dataframe["topic_strength"] = pure_product_cause_document_topic_matrix.max(axis = 1)

pure_product_cause_comparison_dataframe["topic_id"] = pure_product_cause_comparison_topic_matrix.argmax(axis = 1)
pure_product_cause_comparison_dataframe["topic_strength"] = pure_product_cause_comparison_topic_matrix.max(axis = 1)

pure_product_cause_topic_rows = []

for topic_index, topic_weights in enumerate(pure_product_cause_topic_term_matrix):
    top_term_indices = topic_weights.argsort()[ : : -1][ : 15]
    pure_product_cause_topic_rows.append({
        "topic_id": topic_index,
        "top_terms": ", ".join(pure_product_cause_feature_names[top_term_indices])
    })

pure_product_cause_topic_terms_dataframe = pd.DataFrame(pure_product_cause_topic_rows)

display(pure_product_cause_topic_terms_dataframe)

    topic_id                                          top_terms
0          0  router, wifi, network, internet, modem, netgea...
1          1  ear, headphone, earbuds, ears, buds, earbud, s...
2          2  ipad, not_fit, protect, color, cases, fits, ca...
3          3  charge phone, cords, chargers, charger, not_ch...
4          4  drive, drives, files, disk, data, hard_drive, ...
5          5  mouse, keyboard, keys, logitech, mouse work, k...
6          6  screws, mount, screw, mounting, bracket, tight...
7          7  camera, camera work, motion, recording, view, ...
8          8  speaker, sound_quality, music, bluetooth, bass...
9          9  hdmi, monitor, hdmi cable, display, adapter, f...
10        10  bubbles, screen_protector, protectors, screen ...
11        11  remote, remote work, remotes, buttons, remote ...
12        12  fitbit, band, wrist, watch, bands, heart rate,...
13        13  antenna, stations, reception, channels, miles,...
14        14  charger, charge battery, hold charge, battery ...

In [61]:
# Assigning product-cause topics across dissatisfied and satisfied documents

pure_product_cause_topic_assignment_dataframe = pd.concat(
    [
        pure_product_cause_dissatisfaction_dataframe.assign(cohort_role = "Dissatisfaction"),
        pure_product_cause_comparison_dataframe.assign(cohort_role = "Satisfaction")
    ],
    ignore_index = True
)

pure_product_cause_topic_summary_dataframe = (
    pure_product_cause_topic_assignment_dataframe
    .groupby(["cohort_role", "topic_id"], dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        sampled_reviews = ("sampled_review_count", "sum"),
        average_topic_strength = ("topic_strength", "mean")
    )
    .reset_index()
)

pure_product_cause_cohort_totals_dataframe = (
    pure_product_cause_topic_assignment_dataframe
    .groupby("cohort_role", dropna = False)
    .agg(
        total_documents = ("document_id", "count"),
        total_sampled_reviews = ("sampled_review_count", "sum")
    )
    .reset_index()
)

pure_product_cause_topic_summary_dataframe = pure_product_cause_topic_summary_dataframe.merge(
    pure_product_cause_cohort_totals_dataframe,
    on = "cohort_role",
    how = "left"
)

pure_product_cause_topic_summary_dataframe["document_share"] = (
    pure_product_cause_topic_summary_dataframe["document_count"] /
    pure_product_cause_topic_summary_dataframe["total_documents"]
)

pure_product_cause_topic_summary_pivot_dataframe = (
    pure_product_cause_topic_summary_dataframe[
        [
            "cohort_role",
            "topic_id",
            "document_count",
            "sampled_reviews",
            "document_share",
            "average_topic_strength"
        ]
    ]
    .pivot(index = "topic_id", columns = "cohort_role")
)

pure_product_cause_topic_summary_pivot_dataframe.columns = [
    f"{metric_name}_{cohort_name.lower()}"
    for metric_name, cohort_name in pure_product_cause_topic_summary_pivot_dataframe.columns
]

pure_product_cause_topic_summary_pivot_dataframe = (
    pure_product_cause_topic_summary_pivot_dataframe.reset_index()
)

pure_product_cause_topic_summary_pivot_dataframe["document_share_lift_dissatisfaction_vs_satisfaction"] = (
    (pure_product_cause_topic_summary_pivot_dataframe["document_share_dissatisfaction"] + 1e-6) /
    (pure_product_cause_topic_summary_pivot_dataframe["document_share_satisfaction"] + 1e-6)
)

pure_product_cause_topic_summary_pivot_dataframe["document_share_gap"] = (
    pure_product_cause_topic_summary_pivot_dataframe["document_share_dissatisfaction"] -
    pure_product_cause_topic_summary_pivot_dataframe["document_share_satisfaction"]
)

pure_product_cause_topic_driver_dataframe = (
    pure_product_cause_topic_summary_pivot_dataframe
    .merge(pure_product_cause_topic_terms_dataframe, on = "topic_id", how = "left")
    .sort_values(
        by = ["document_share_lift_dissatisfaction_vs_satisfaction", "document_share_gap"],
        ascending = [False, False]
    )
    .reset_index(drop = True)
)

display(pure_product_cause_topic_driver_dataframe)

,topic_id,document_count_dissatisfaction,document_count_satisfaction,sampled_reviews_dissatisfaction,sampled_reviews_satisfaction,document_share_dissatisfaction,document_share_satisfaction,average_topic_strength_dissatisfaction,average_topic_strength_satisfaction,document_share_lift_dissatisfaction_vs_satisfaction,document_share_gap,top_terms
0,14,987,708,101346,57240,0.058565,0.038562,0.072934,0.065367,1.518712,0.020003,"charger, charge battery, hold charge, battery ..."
1,3,1235,1183,163189,131865,0.073281,0.064434,0.087539,0.068773,1.137305,0.008847,"charge phone, cords, chargers, charger, not_ch..."
2,5,948,935,124455,110844,0.056251,0.050926,0.090618,0.077804,1.104565,0.005325,"mouse, keyboard, keys, logitech, mouse work, k..."
3,1,1943,1923,285840,253556,0.115291,0.104739,0.088229,0.087839,1.100750,0.010552,"ear, headphone, earbuds, ears, buds, earbud, s..."
4,0,829,822,126048,113848,0.049190,0.044771,0.061512,0.053579,1.098695,0.004419,"router, wifi, network, internet, modem, netgea..."
5,11,889,899,112541,100945,0.052750,0.048965,0.079903,0.072212,1.077301,0.003785,"remote, remote work, remotes, buttons, remote ..."
6,10,504,510,50688,48753,0.029906,0.027778,0.116487,0.096013,1.076601,0.002128,"bubbles, screen_protector, protectors, screen ..."
7,4,1563,1588,185105,172334,0.092743,0.086492,0.077481,0.064503,1.072269,0.006251,"drive, drives, files, disk, data, hard_drive, ..."
8,9,1115,1172,117624,117609,0.066160,0.063834,0.077246,0.069280,1.036436,0.002326,"hdmi, monitor, hdmi cable, display, adapter, f..."
9,13,559,591,65891,67434,0.033169,0.032190,0.104388,0.099674,1.030432,0.000980,"antenna, stations, reception, channels, miles,..."
10,12,540,593,61628,63106,0.032042,0.032298,0.113165,0.108941,0.992052,-0.000257,"fitbit, band, wrist, watch, bands, heart rate,..."
11,8,1508,1767,186343,207786,0.089480,0.096242,0.062071,0.061152,0.929738,-0.006762,"speaker, sound_quality, music, bluetooth, bass..."
12,7,1340,1753,154727,181569,0.079511,0.095479,0.076480,0.068051,0.832759,-0.015968,"camera, camera work, motion, recording, view, ..."
13,6,1244,1655,106045,142748,0.073815,0.090142,0.069644,0.059319,0.818877,-0.016327,"screws, mount, screw, mounting, bracket, tight..."
14,2,1649,2261,151873,215319,0.097846,0.123148,0.075505,0.065433,0.794541,-0.025302,"ipad, not_fit, protect, color, cases, fits, ca..."

In [62]:
# Comparing broad, root-cause and product-cause topic models

model_comparison_summary_dataframe = pd.DataFrame({
    "model_name": [
        "full_topic_model",
        "root_cause_topic_model",
        "pure_product_cause_topic_model"
    ],
    "topic_count": [
        selected_topic_count,
        root_cause_selected_topic_count,
        selected_pure_product_topic_count
    ],
    "dissatisfaction_document_count": [
        len(full_dissatisfaction_topic_review_dataframe),
        len(root_cause_dissatisfaction_dataframe),
        len(pure_product_cause_dissatisfaction_dataframe)
    ],
    "top_signal_lift": [
        topic_comparison_summary_dataframe["document_share_lift_dissatisfaction_vs_satisfaction"].max(),
        root_cause_topic_driver_dataframe["document_share_lift_dissatisfaction_vs_satisfaction"].max(),
        pure_product_cause_topic_driver_dataframe["document_share_lift_dissatisfaction_vs_satisfaction"].max()
    ],
    "median_signal_lift": [
        topic_comparison_summary_dataframe["document_share_lift_dissatisfaction_vs_satisfaction"].median(),
        root_cause_topic_driver_dataframe["document_share_lift_dissatisfaction_vs_satisfaction"].median(),
        pure_product_cause_topic_driver_dataframe["document_share_lift_dissatisfaction_vs_satisfaction"].median()
    ]
})

display(model_comparison_summary_dataframe)

,model_name,topic_count,dissatisfaction_document_count,top_signal_lift,median_signal_lift
0,full_topic_model,15,16853,1.560507,1.071390
1,root_cause_topic_model,15,16853,1.515369,1.072840
2,pure_product_cause_topic_model,15,16853,1.518712,1.072269

In [63]:
# Measuring confidence for product-cause topic assignments

pure_product_cause_topic_assignment_dataframe["topic_margin"] = compute_assignment_margin(
    np.vstack([
        pure_product_cause_document_topic_matrix,
        pure_product_cause_comparison_topic_matrix
    ])
)

pure_product_cause_topic_assignment_dataframe["is_topic_core_document"] = (
    (pure_product_cause_topic_assignment_dataframe["topic_strength"] >= 0.06)
    & (pure_product_cause_topic_assignment_dataframe["topic_margin"] >= 0.03)
)

pure_product_cause_topic_core_summary_dataframe = (
    pure_product_cause_topic_assignment_dataframe
    .groupby(["cohort_role", "topic_id"], dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        topic_core_document_count = ("is_topic_core_document", "sum"),
        average_topic_strength = ("topic_strength", "mean"),
        median_topic_strength = ("topic_strength", "median"),
        average_topic_margin = ("topic_margin", "mean"),
        median_topic_margin = ("topic_margin", "median")
    )
    .reset_index()
)

pure_product_cause_topic_core_summary_dataframe["topic_core_ratio"] = (
    pure_product_cause_topic_core_summary_dataframe["topic_core_document_count"] /
    pure_product_cause_topic_core_summary_dataframe["document_count"].replace(0, np.nan)
)

display(
    pure_product_cause_topic_core_summary_dataframe.sort_values(
        ["cohort_role", "topic_id"]
    )
)

,cohort_role,topic_id,document_count,topic_core_document_count,average_topic_strength,median_topic_strength,average_topic_margin,median_topic_margin,topic_core_ratio
0,Dissatisfaction,0,829,512,0.061512,0.066629,0.048766,0.055668,0.617612
1,Dissatisfaction,1,1943,1533,0.088229,0.090027,0.066252,0.068180,0.788986
2,Dissatisfaction,2,1649,1082,0.075505,0.074454,0.054879,0.055389,0.656155
3,Dissatisfaction,3,1235,749,0.087539,0.091018,0.068660,0.073553,0.606478
4,Dissatisfaction,4,1563,914,0.077481,0.075784,0.056516,0.045806,0.584773
5,Dissatisfaction,5,948,702,0.090618,0.095105,0.070006,0.077528,0.740506
6,Dissatisfaction,6,1244,615,0.069644,0.062694,0.048504,0.036919,0.494373
7,Dissatisfaction,7,1340,820,0.076480,0.074334,0.052507,0.047110,0.611940
8,Dissatisfaction,8,1508,640,0.062071,0.062093,0.033923,0.031151,0.424403
9,Dissatisfaction,9,1115,725,0.077246,0.082235,0.051858,0.054196,0.650224
10,Dissatisfaction,10,504,350,0.116487,0.139169,0.102736,0.130588,0.694444
11,Dissatisfaction,11,889,580,0.079903,0.084594,0.057704,0.060459,0.652418
12,Dissatisfaction,12,540,377,0.113165,0.135467,0.091330,0.116824,0.698148
13,Dissatisfaction,13,559,343,0.104388,0.083219,0.076557,0.046962,0.613596
14,Dissatisfaction,14,987,413,0.072934,0.056780,0.050471,0.025075,0.418440
15,Satisfaction,0,822,353,0.053579,0.057920,0.038561,0.042596,0.429440
16,Satisfaction,1,1923,1540,0.087839,0.091697,0.070389,0.074800,0.800832
17,Satisfaction,2,2261,1227,0.065433,0.065991,0.045670,0.044218,0.542680
18,Satisfaction,3,1183,642,0.068773,0.069897,0.051502,0.054298,0.542688
19,Satisfaction,4,1588,754,0.064503,0.061155,0.044469,0.035436,0.474811
20,Satisfaction,5,935,647,0.077804,0.083352,0.058168,0.065024,0.691979
21,Satisfaction,6,1655,609,0.059319,0.051193,0.038111,0.025830,0.367976
22,Satisfaction,7,1753,915,0.068051,0.062827,0.047663,0.040025,0.521962
23,Satisfaction,8,1767,876,0.061152,0.061966,0.038462,0.038276,0.495756
24,Satisfaction,9,1172,672,0.069280,0.070956,0.045193,0.043785,0.573379
25,Satisfaction,10,510,334,0.096013,0.112614,0.081831,0.101970,0.654902
26,Satisfaction,11,899,531,0.072212,0.075001,0.052463,0.056340,0.590656
27,Satisfaction,12,593,393,0.108941,0.130906,0.092649,0.118448,0.662732
28,Satisfaction,13,591,370,0.099674,0.083402,0.073363,0.050003,0.626058
29,Satisfaction,14,708,335,0.065367,0.057226,0.046526,0.034499,0.473164

In [64]:
# Reviewing product-cause topic distribution by segment

pure_product_cause_segment_distribution_dataframe = (
    pure_product_cause_topic_assignment_dataframe
    .groupby(
        ["cohort_role", "topic_id", "price_band", "issue_priority_level"],
        dropna = False
    )
    .agg(
        document_count = ("document_id", "count"),
        sampled_reviews = ("sampled_review_count", "sum"),
        average_topic_strength = ("topic_strength", "mean")
    )
    .reset_index()
)

pure_product_cause_dissatisfaction_segment_distribution_dataframe = (
    pure_product_cause_segment_distribution_dataframe.loc[
        pure_product_cause_segment_distribution_dataframe["cohort_role"] == "Dissatisfaction"
    ].copy()
)

pure_product_cause_dissatisfaction_segment_distribution_dataframe["segment_document_share_within_topic"] = (
    pure_product_cause_dissatisfaction_segment_distribution_dataframe["document_count"] /
    pure_product_cause_dissatisfaction_segment_distribution_dataframe.groupby("topic_id")["document_count"].transform("sum")
)

pure_product_cause_topic_breadth_summary_dataframe = (
    pure_product_cause_dissatisfaction_segment_distribution_dataframe
    .groupby("topic_id", dropna = False)
    .agg(
        covered_segment_count = ("segment_document_share_within_topic", "count"),
        segment_count_above_05_share = (
            "segment_document_share_within_topic",
            lambda values: (values >= 0.05).sum()
        ),
        segment_count_above_10_share = (
            "segment_document_share_within_topic",
            lambda values: (values >= 0.10).sum()
        ),
        max_segment_share = ("segment_document_share_within_topic", "max"),
        concentration_hhi = (
            "segment_document_share_within_topic",
            lambda values: np.square(values).sum()
        )
    )
    .reset_index()
)

pure_product_cause_segment_reporting_eligibility_dataframe = (
    pure_product_cause_segment_distribution_dataframe
    .pivot(
        index = ["topic_id", "price_band", "issue_priority_level"],
        columns = "cohort_role",
        values = ["document_count", "sampled_reviews"]
    )
)

pure_product_cause_segment_reporting_eligibility_dataframe.columns = [
    f"{metric_name}_{cohort_name.lower()}"
    for metric_name, cohort_name in pure_product_cause_segment_reporting_eligibility_dataframe.columns
]

pure_product_cause_segment_reporting_eligibility_dataframe = (
    pure_product_cause_segment_reporting_eligibility_dataframe
    .reset_index()
    .fillna(0)
)

pure_product_cause_segment_reporting_eligibility_dataframe["is_segment_reporting_eligible"] = (
    (pure_product_cause_segment_reporting_eligibility_dataframe["document_count_dissatisfaction"] >= 25)
    & (pure_product_cause_segment_reporting_eligibility_dataframe["document_count_satisfaction"] >= 25)
    & (pure_product_cause_segment_reporting_eligibility_dataframe["sampled_reviews_dissatisfaction"] >= 3000)
    & (pure_product_cause_segment_reporting_eligibility_dataframe["sampled_reviews_satisfaction"] >= 3000)
)

display(pure_product_cause_topic_breadth_summary_dataframe.sort_values("topic_id"))
display(
    pure_product_cause_segment_reporting_eligibility_dataframe.sort_values(
        ["topic_id", "price_band", "issue_priority_level"]
    )
)

/var/folders/f1/ws24m5bs3cx9_1d_nclvhd1w0000gn/T/ipykernel_51314/1973121574.py:67: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .fillna(0)

,topic_id,covered_segment_count,segment_count_above_05_share,segment_count_above_10_share,max_segment_share,concentration_hhi
0,0,9,6,5,0.249698,0.161432
1,1,9,8,6,0.206382,0.135297
2,2,9,4,3,0.402668,0.266479
3,3,9,4,3,0.460729,0.300784
4,4,9,6,4,0.212412,0.163149
5,5,9,7,5,0.213080,0.138477
6,6,9,4,4,0.303859,0.210864
7,7,9,6,4,0.297015,0.182403
8,8,9,6,4,0.235411,0.159585
9,9,9,7,4,0.257399,0.155804
10,10,8,4,3,0.569444,0.381118
11,11,9,8,3,0.205849,0.144348
12,12,9,7,6,0.220370,0.140384
13,13,9,8,4,0.254025,0.148019
14,14,9,7,4,0.244174,0.161470

,topic_id,price_band,issue_priority_level,document_count_dissatisfaction,document_count_satisfaction,sampled_reviews_dissatisfaction,sampled_reviews_satisfaction,is_segment_reporting_eligible
0,0,Budget,Monitor,36,79,4727,9939,True
1,0,Budget,Priority review,16,21,3733,4831,False
2,0,Lower mid,Monitor,94,88,12647,8681,True
3,0,Lower mid,Priority review,44,52,6897,9354,True
4,0,Premium,Monitor,207,171,31599,21993,True
5,0,Premium,Priority review,108,109,16848,17030,True
6,0,Upper mid,Monitor,161,141,23862,15935,True
7,0,Upper mid,Priority review,131,135,20960,23164,True
8,0,Very premium,Monitor,32,26,4775,2921,False
9,1,Budget,Monitor,196,214,22508,21397,True
10,1,Budget,Priority review,163,154,25704,21315,True
11,1,Lower mid,Monitor,401,362,64122,48711,True
12,1,Lower mid,Priority review,158,170,23102,25381,True
13,1,Premium,Monitor,200,207,25030,22907,True
14,1,Premium,Priority review,204,197,38108,33525,True
15,1,Upper mid,Monitor,358,347,47600,40916,True
16,1,Upper mid,Priority review,220,226,35348,35296,True
17,1,Very premium,Monitor,43,46,4318,4108,True
18,2,Budget,Monitor,402,527,36031,46062,True
19,2,Budget,Priority review,51,49,5946,7002,True
20,2,Lower mid,Monitor,664,897,56156,78834,True
21,2,Lower mid,Priority review,106,106,16669,16537,True
22,2,Premium,Monitor,40,84,2836,8347,False
23,2,Premium,Priority review,15,26,1945,3268,False
24,2,Upper mid,Monitor,323,494,25619,45425,True
25,2,Upper mid,Priority review,46,64,6566,8771,True
26,2,Very premium,Monitor,2,14,105,1073,False
27,3,Budget,Monitor,569,529,72945,54269,True
28,3,Budget,Priority review,258,223,41734,34595,True
29,3,Lower mid,Monitor,240,252,26897,23261,True
30,3,Lower mid,Priority review,84,73,14049,11103,True
31,3,Premium,Monitor,9,14,979,1377,False
32,3,Premium,Priority review,4,3,446,312,False
33,3,Upper mid,Monitor,60,74,4462,5242,True
34,3,Upper mid,Priority review,9,10,1575,1459,False
35,3,Very premium,Monitor,2,5,102,247,False
36,4,Budget,Monitor,289,316,36661,34383,True
37,4,Budget,Priority review,49,43,7201,6501,True
38,4,Lower mid,Monitor,272,270,30516,26609,True
39,4,Lower mid,Priority review,57,50,7724,6033,True
40,4,Premium,Monitor,325,359,35369,35295,True
41,4,Premium,Priority review,89,93,11221,11748,True
42,4,Upper mid,Monitor,332,312,37003,34364,True
43,4,Upper mid,Priority review,61,58,9745,8823,True
44,4,Very premium,Monitor,89,87,9665,8578,True
45,5,Budget,Monitor,134,133,15591,13165,True
46,5,Budget,Priority review,78,91,13942,16833,True
47,5,Lower mid,Monitor,160,148,20752,15258,True
48,5,Lower mid,Priority review,90,85,14924,13875,True
49,5,Premium,Monitor,110,118,11581,10531,True
50,5,Premium,Priority review,41,47,4298,5353,True
51,5,Upper mid,Monitor,202,177,25228,17896,True
52,5,Upper mid,Priority review,107,107,15353,15800,True
53,5,Very premium,Monitor,26,29,2786,2133,False
54,6,Budget,Monitor,207,268,13688,17549,True
55,6,Budget,Priority review,47,38,6066,5227,True
56,6,Lower mid,Monitor,316,431,27455,37813,True
57,6,Lower mid,Priority review,49,53,6509,6973,True
58,6,Premium,Monitor,186,248,13361,19084,True
59,6,Premium,Priority review,15,21,2442,2868,False
60,6,Upper mid,Monitor,378,536,31511,45870,True
61,6,Upper mid,Priority review,34,42,4246,5952,True
62,6,Very premium,Monitor,12,18,767,1412,False
63,7,Budget,Monitor,61,134,4359,10441,True
64,7,Budget,Priority review,10,21,1035,2924,False
65,7,Lower mid,Monitor,83,114,7316,9181,True
66,7,Lower mid,Priority review,50,63,8546,10724,True
67,7,Premium,Monitor,398,531,36163,45942,True
68,7,Premium,Priority review,217,228,33813,35321,True
69,7,Upper mid,Monitor,281,320,32945,31664,True
70,7,Upper mid,Priority review,143,149,24075,24193,True
71,7,Very premium,Monitor,97,193,6475,11179,True
72,8,Budget,Monitor,127,155,12393,13783,True
73,8,Budget,Priority review,43,58,6526,8630,True
74,8,Lower mid,Monitor,225,242,32400,31077,True
75,8,Lower mid,Priority review,56,64,7422,8448,True
76,8,Premium,Monitor,343,436,35002,43339,True
77,8,Premium,Priority review,116,127,15591,18315,True
78,8,Upper mid,Monitor,355,406,46015,48827,True
79,8,Upper mid,Priority review,169,185,25614,28055,True
80,8,Very premium,Monitor,74,94,5380,7312,True
81,9,Budget,Monitor,287,326,27425,31217,True
82,9,Budget,Priority review,97,92,16350,15873,True
83,9,Lower mid,Monitor,180,192,17476,16907,True
84,9,Lower mid,Priority review,35,39,4404,5084,True
85,9,Premium,Monitor,199,201,18610,17224,True
86,9,Premium,Priority review,65,62,8185,8427,True
87,9,Upper mid,Monitor,129,129,13038,10818,True
88,9,Upper mid,Priority review,50,50,6871,6957,True
89,9,Very premium,Monitor,73,81,5265,5102,True
90,10,Budget,Monitor,287,277,27104,22784,True
91,10,Budget,Priority review,85,82,12445,12581,True
92,10,Lower mid,Monitor,79,77,6711,7279,True
93,10,Lower mid,Priority review,15,15,1608,1538,False
94,10,Premium,Monitor,8,15,512,886,False
95,10,Premium,Priority review,0,3,0,293,False
96,10,Upper mid,Monitor,26,32,1764,2566,False
97,10,Upper mid,Priority review,1,7,250,734,False
98,10,Very premium,Monitor,3,2,294,92,False
99,11,Budget,Monitor,169,188,15463,12559,True
100,11,Budget,Priority review,76,81,11669,13594,True
101,11,Lower mid,Monitor,59,77,6637,9783,True
102,11,Lower mid,Priority review,39,32,5332,3826,True
103,11,Premium,Monitor,183,174,24309,19976,True
104,11,Premium,Priority review,88,81,10089,9041,True
105,11,Upper mid,Monitor,166,155,25606,21185,True
106,11,Upper mid,Priority review,57,54,7910,6993,True
107,11,Very premium,Monitor,52,57,5526,3988,True
108,12,Budget,Monitor,119,144,10412,10152,True
109,12,Budget,Priority review,30,29,3783,4291,True
110,12,Lower mid,Monitor,58,68,5385,5003,True
111,12,Lower mid,Priority review,24,22,3627,3366,False
112,12,Premium,Monitor,78,83,8345,8850,True
113,12,Premium,Priority review,89,96,13987,15022,True
114,12,Upper mid,Monitor,63,69,5929,5702,True
115,12,Upper mid,Priority review,60,66,8339,9721,True
116,12,Very premium,Monitor,19,16,1821,999,False
117,13,Budget,Monitor,48,65,3705,4692,True
118,13,Budget,Priority review,30,32,4183,5772,True
119,13,Lower mid,Monitor,70,72,7844,6850,True
120,13,Lower mid,Priority review,54,57,8754,8922,True
121,13,Premium,Monitor,93,93,9189,8524,True
122,13,Premium,Priority review,40,40,5207,5600,True
123,13,Upper mid,Monitor,142,156,15862,16289,True
124,13,Upper mid,Priority review,68,60,10412,10017,True
125,13,Very premium,Monitor,14,16,735,768,False
126,14,Budget,Monitor,157,159,11447,9642,True
127,14,Budget,Priority review,22,23,2936,3246,False
128,14,Lower mid,Monitor,241,210,18628,12905,True
129,14,Lower mid,Priority review,58,45,8292,6690,True
130,14,Premium,Monitor,136,55,18281,5904,True
131,14,Premium,Priority review,56,24,7460,3495,False
132,14,Upper mid,Monitor,200,150,19088,10733,True
133,14,Upper mid,Priority review,92,38,13196,4451,True
134,14,Very premium,Monitor,25,4,2018,174,False

In [65]:
# Comparing product-cause topic exposure across price bands
pure_product_cause_price_band_comparison_dataframe = (
    pure_product_cause_topic_assignment_dataframe
    .groupby(["cohort_role", "topic_id", "price_band"], dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        sampled_reviews = ("sampled_review_count", "sum")
    )
    .reset_index()
)

pure_product_cause_price_band_totals_dataframe = (
    pure_product_cause_price_band_comparison_dataframe
    .groupby(["cohort_role", "topic_id"], dropna = False)
    .agg(
        total_documents = ("document_count", "sum")
    )
    .reset_index()
)

pure_product_cause_price_band_comparison_dataframe = pure_product_cause_price_band_comparison_dataframe.merge(
    pure_product_cause_price_band_totals_dataframe,
    on = ["cohort_role", "topic_id"],
    how = "left"
)

pure_product_cause_price_band_comparison_dataframe["document_share_within_topic"] = (
    pure_product_cause_price_band_comparison_dataframe["document_count"] /
    pure_product_cause_price_band_comparison_dataframe["total_documents"].replace(0, np.nan)
)

pure_product_cause_price_band_comparison_dataframe = (
    pure_product_cause_price_band_comparison_dataframe
    .pivot_table(
        index = ["topic_id", "price_band"],
        columns = "cohort_role",
        values = ["document_count", "sampled_reviews", "document_share_within_topic"],
        fill_value = 0
    )
)

pure_product_cause_price_band_comparison_dataframe.columns = [
    f"{metric_name}_{cohort_name.lower()}"
    for metric_name, cohort_name in pure_product_cause_price_band_comparison_dataframe.columns
]

pure_product_cause_price_band_comparison_dataframe = (
    pure_product_cause_price_band_comparison_dataframe
    .reset_index()
    .infer_objects(copy = False)
)

pure_product_cause_price_band_comparison_dataframe["price_band_document_share_lift_dissatisfaction_vs_satisfaction"] = (
    (pure_product_cause_price_band_comparison_dataframe["document_share_within_topic_dissatisfaction"] + 1e-6) /
    (pure_product_cause_price_band_comparison_dataframe["document_share_within_topic_satisfaction"] + 1e-6)
)

pure_product_cause_priority_comparison_dataframe = (
    pure_product_cause_topic_assignment_dataframe
    .groupby(["cohort_role", "topic_id", "issue_priority_level"], dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        sampled_reviews = ("sampled_review_count", "sum")
    )
    .reset_index()
)

pure_product_cause_priority_totals_dataframe = (
    pure_product_cause_priority_comparison_dataframe
    .groupby(["cohort_role", "topic_id"], dropna = False)
    .agg(
        total_documents = ("document_count", "sum")
    )
    .reset_index()
)

pure_product_cause_priority_comparison_dataframe = pure_product_cause_priority_comparison_dataframe.merge(
    pure_product_cause_priority_totals_dataframe,
    on = ["cohort_role", "topic_id"],
    how = "left"
)

pure_product_cause_priority_comparison_dataframe["document_share_within_topic"] = (
    pure_product_cause_priority_comparison_dataframe["document_count"] /
    pure_product_cause_priority_comparison_dataframe["total_documents"].replace(0, np.nan)
)

pure_product_cause_priority_comparison_dataframe = (
    pure_product_cause_priority_comparison_dataframe
    .pivot_table(
        index = ["topic_id", "issue_priority_level"],
        columns = "cohort_role",
        values = ["document_count", "sampled_reviews", "document_share_within_topic"],
        fill_value = 0
    )
)

pure_product_cause_priority_comparison_dataframe.columns = [
    f"{metric_name}_{cohort_name.lower()}"
    for metric_name, cohort_name in pure_product_cause_priority_comparison_dataframe.columns
]

pure_product_cause_priority_comparison_dataframe = (
    pure_product_cause_priority_comparison_dataframe
    .reset_index()
    .infer_objects(copy = False)
)

display(pure_product_cause_price_band_comparison_dataframe.sort_values(["topic_id", "price_band"]))
display(pure_product_cause_priority_comparison_dataframe.sort_values(["topic_id", "issue_priority_level"]))

,topic_id,price_band,document_count_dissatisfaction,document_count_satisfaction,document_share_within_topic_dissatisfaction,document_share_within_topic_satisfaction,sampled_reviews_dissatisfaction,sampled_reviews_satisfaction,price_band_document_share_lift_dissatisfaction_vs_satisfaction
0,0,Budget,52.0,100.0,0.062726,0.121655,8460.0,14770.0,0.515613
1,0,Lower mid,138.0,140.0,0.166466,0.170316,19544.0,18035.0,0.977391
2,0,Premium,315.0,280.0,0.379976,0.340633,48447.0,39023.0,1.115500
3,0,Upper mid,292.0,276.0,0.352232,0.335766,44822.0,39099.0,1.049037
4,0,Very premium,32.0,26.0,0.038601,0.031630,4775.0,2921.0,1.220370
5,1,Budget,359.0,368.0,0.184766,0.191368,48212.0,42712.0,0.965502
6,1,Lower mid,559.0,532.0,0.287699,0.276651,87224.0,74092.0,1.039936
7,1,Premium,404.0,404.0,0.207926,0.210088,63138.0,56432.0,0.989707
8,1,Upper mid,578.0,573.0,0.297478,0.297972,82948.0,76212.0,0.998343
9,1,Very premium,43.0,46.0,0.022131,0.023921,4318.0,4108.0,0.925164
10,2,Budget,453.0,576.0,0.274712,0.254755,41977.0,53064.0,1.078339
11,2,Lower mid,770.0,1003.0,0.466950,0.443609,72825.0,95371.0,1.052615
12,2,Premium,55.0,110.0,0.033354,0.048651,4781.0,11615.0,0.685573
13,2,Upper mid,369.0,558.0,0.223772,0.246793,32185.0,54196.0,0.906718
14,2,Very premium,2.0,14.0,0.001213,0.006192,105.0,1073.0,0.196006
15,3,Budget,827.0,752.0,0.669636,0.635672,114679.0,88864.0,1.053429
16,3,Lower mid,324.0,325.0,0.262348,0.274725,40946.0,34364.0,0.954948
17,3,Premium,13.0,17.0,0.010526,0.014370,1425.0,1689.0,0.732526
18,3,Upper mid,69.0,84.0,0.055870,0.071006,6037.0,6701.0,0.786845
19,3,Very premium,2.0,5.0,0.001619,0.004227,102.0,247.0,0.383304
20,4,Budget,338.0,359.0,0.216251,0.226071,43862.0,40884.0,0.956564
21,4,Lower mid,329.0,320.0,0.210493,0.201511,38240.0,32642.0,1.044570
22,4,Premium,414.0,452.0,0.264875,0.284635,46590.0,47043.0,0.930580
23,4,Upper mid,393.0,370.0,0.251440,0.232997,46748.0,43187.0,1.079151
24,4,Very premium,89.0,87.0,0.056942,0.054786,9665.0,8578.0,1.039350
25,5,Budget,212.0,224.0,0.223629,0.239572,29533.0,29998.0,0.933450
26,5,Lower mid,250.0,233.0,0.263713,0.249198,35676.0,29133.0,1.058248
27,5,Premium,151.0,165.0,0.159283,0.176471,15879.0,15884.0,0.902603
28,5,Upper mid,309.0,284.0,0.325949,0.303743,40581.0,33696.0,1.073108
29,5,Very premium,26.0,29.0,0.027426,0.031016,2786.0,2133.0,0.884261
30,6,Budget,254.0,306.0,0.204180,0.184894,19754.0,22776.0,1.104307
31,6,Lower mid,365.0,484.0,0.293408,0.292447,33964.0,44786.0,1.003287
32,6,Premium,201.0,269.0,0.161576,0.162538,15803.0,21952.0,0.994080
33,6,Upper mid,412.0,578.0,0.331190,0.349245,35757.0,51822.0,0.948303
34,6,Very premium,12.0,18.0,0.009646,0.010876,767.0,1412.0,0.886934
35,7,Budget,71.0,155.0,0.052985,0.088420,5394.0,13365.0,0.599249
36,7,Lower mid,133.0,177.0,0.099254,0.100970,15862.0,19905.0,0.983005
37,7,Premium,615.0,759.0,0.458955,0.432972,69976.0,81263.0,1.060011
38,7,Upper mid,424.0,469.0,0.316418,0.267541,57020.0,55857.0,1.182687
39,7,Very premium,97.0,193.0,0.072388,0.110097,6475.0,11179.0,0.657497
40,8,Budget,170.0,213.0,0.112732,0.120543,18919.0,22413.0,0.935201
41,8,Lower mid,281.0,306.0,0.186340,0.173175,39822.0,39525.0,1.076019
42,8,Premium,459.0,563.0,0.304377,0.318619,50593.0,61654.0,0.955300
43,8,Upper mid,524.0,591.0,0.347480,0.334465,71629.0,76882.0,1.038912
44,8,Very premium,74.0,94.0,0.049072,0.053198,5380.0,7312.0,0.922443
45,9,Budget,384.0,418.0,0.344395,0.356655,43775.0,47090.0,0.965623
46,9,Lower mid,215.0,231.0,0.192825,0.197099,21880.0,21991.0,0.978316
47,9,Premium,264.0,263.0,0.236771,0.224403,26795.0,25651.0,1.055117
48,9,Upper mid,179.0,179.0,0.160538,0.152730,19909.0,17775.0,1.051121
49,9,Very premium,73.0,81.0,0.065471,0.069113,5265.0,5102.0,0.947307
50,10,Budget,372.0,359.0,0.738095,0.703922,39549.0,35365.0,1.048547
51,10,Lower mid,94.0,92.0,0.186508,0.180392,8319.0,8817.0,1.033903
52,10,Premium,8.0,18.0,0.015873,0.035294,512.0,1179.0,0.449751
53,10,Upper mid,27.0,39.0,0.053571,0.076471,2014.0,3300.0,0.700553
54,10,Very premium,3.0,2.0,0.005952,0.003922,294.0,92.0,1.517725
55,11,Budget,245.0,269.0,0.275591,0.299221,27132.0,26153.0,0.921026
56,11,Lower mid,98.0,109.0,0.110236,0.121246,11969.0,13609.0,0.909197
57,11,Premium,271.0,255.0,0.304837,0.283648,34398.0,29017.0,1.074699
58,11,Upper mid,223.0,209.0,0.250844,0.232481,33516.0,28178.0,1.078987
59,11,Very premium,52.0,57.0,0.058493,0.063404,5526.0,3988.0,0.922544
60,12,Budget,149.0,173.0,0.275926,0.291737,14195.0,14443.0,0.945804
61,12,Lower mid,82.0,90.0,0.151852,0.151771,9012.0,8369.0,1.000535
62,12,Premium,167.0,179.0,0.309259,0.301855,22332.0,23872.0,1.024529
63,12,Upper mid,123.0,135.0,0.227778,0.227656,14268.0,15423.0,1.000535
64,12,Very premium,19.0,16.0,0.035185,0.026981,1821.0,999.0,1.304040
65,13,Budget,78.0,97.0,0.139535,0.164129,7888.0,10464.0,0.850157
66,13,Lower mid,124.0,129.0,0.221825,0.218274,16598.0,15772.0,1.016267
67,13,Premium,133.0,133.0,0.237925,0.225042,14396.0,14124.0,1.057245
68,13,Upper mid,210.0,216.0,0.375671,0.365482,26274.0,26306.0,1.027877
69,13,Very premium,14.0,16.0,0.025045,0.027073,735.0,768.0,0.925092
70,14,Budget,179.0,182.0,0.181358,0.257062,14383.0,12888.0,0.705502
71,14,Lower mid,299.0,255.0,0.302938,0.360169,26920.0,19595.0,0.841099
72,14,Premium,192.0,79.0,0.194529,0.111582,25741.0,9399.0,1.743366
73,14,Upper mid,292.0,188.0,0.295846,0.265537,32284.0,15184.0,1.114143
74,14,Very premium,25.0,4.0,0.025329,0.005650,2018.0,174.0,4.482666

,topic_id,issue_priority_level,document_count_dissatisfaction,document_count_satisfaction,document_share_within_topic_dissatisfaction,document_share_within_topic_satisfaction,sampled_reviews_dissatisfaction,sampled_reviews_satisfaction
0,0,Monitor,530.0,505.0,0.639324,0.614355,77610.0,59469.0
1,0,Priority review,299.0,317.0,0.360676,0.385645,48438.0,54379.0
2,1,Monitor,1198.0,1176.0,0.616572,0.611544,163578.0,138039.0
3,1,Priority review,745.0,747.0,0.383428,0.388456,122262.0,115517.0
4,2,Monitor,1431.0,2016.0,0.867799,0.891641,120747.0,179741.0
5,2,Priority review,218.0,245.0,0.132201,0.108359,31126.0,35578.0
6,3,Monitor,880.0,874.0,0.712551,0.738800,105385.0,84396.0
7,3,Priority review,355.0,309.0,0.287449,0.261200,57804.0,47469.0
8,4,Monitor,1307.0,1344.0,0.836212,0.846348,149214.0,139229.0
9,4,Priority review,256.0,244.0,0.163788,0.153652,35891.0,33105.0
10,5,Monitor,632.0,605.0,0.666667,0.647059,75938.0,58983.0
11,5,Priority review,316.0,330.0,0.333333,0.352941,48517.0,51861.0
12,6,Monitor,1099.0,1501.0,0.883441,0.906949,86782.0,121728.0
13,6,Priority review,145.0,154.0,0.116559,0.093051,19263.0,21020.0
14,7,Monitor,920.0,1292.0,0.686567,0.737022,87258.0,108407.0
15,7,Priority review,420.0,461.0,0.313433,0.262978,67469.0,73162.0
16,8,Monitor,1124.0,1333.0,0.745358,0.754386,131190.0,144338.0
17,8,Priority review,384.0,434.0,0.254642,0.245614,55153.0,63448.0
18,9,Monitor,868.0,929.0,0.778475,0.792662,81814.0,81268.0
19,9,Priority review,247.0,243.0,0.221525,0.207338,35810.0,36341.0
20,10,Monitor,403.0,403.0,0.799603,0.790196,36385.0,33607.0
21,10,Priority review,101.0,107.0,0.200397,0.209804,14303.0,15146.0
22,11,Monitor,629.0,651.0,0.707537,0.724138,77541.0,67491.0
23,11,Priority review,260.0,248.0,0.292463,0.275862,35000.0,33454.0
24,12,Monitor,337.0,380.0,0.624074,0.640809,31892.0,30706.0
25,12,Priority review,203.0,213.0,0.375926,0.359191,29736.0,32400.0
26,13,Monitor,367.0,402.0,0.656530,0.680203,37335.0,37123.0
27,13,Priority review,192.0,189.0,0.343470,0.319797,28556.0,30311.0
28,14,Monitor,759.0,578.0,0.768997,0.816384,69462.0,39358.0
29,14,Priority review,228.0,130.0,0.231003,0.183616,31884.0,17882.0

In [66]:
# Summarizing product-cause topics in premium price bands

pure_product_premium_price_bands = {"Premium", "Very premium"}

pure_product_premium_topic_summary_dataframe = (
    pure_product_cause_price_band_comparison_dataframe.assign(
        is_premium_band = lambda dataframe: dataframe["price_band"].isin(pure_product_premium_price_bands)
    )
    .groupby("topic_id", dropna = False)
    .agg(
        premium_document_count_dissatisfaction = (
            "document_count_dissatisfaction",
            lambda values: values[
                pure_product_cause_price_band_comparison_dataframe.loc[values.index, "price_band"].isin(pure_product_premium_price_bands)
            ].sum()
        ),
        premium_document_count_satisfaction = (
            "document_count_satisfaction",
            lambda values: values[
                pure_product_cause_price_band_comparison_dataframe.loc[values.index, "price_band"].isin(pure_product_premium_price_bands)
            ].sum()
        ),
        total_document_count_dissatisfaction = ("document_count_dissatisfaction", "sum"),
        total_document_count_satisfaction = ("document_count_satisfaction", "sum")
    )
    .reset_index()
)

pure_product_premium_topic_summary_dataframe["premium_document_share_dissatisfaction"] = (
    pure_product_premium_topic_summary_dataframe["premium_document_count_dissatisfaction"] /
    pure_product_premium_topic_summary_dataframe["total_document_count_dissatisfaction"].replace(0, np.nan)
)

pure_product_premium_topic_summary_dataframe["premium_document_share_satisfaction"] = (
    pure_product_premium_topic_summary_dataframe["premium_document_count_satisfaction"] /
    pure_product_premium_topic_summary_dataframe["total_document_count_satisfaction"].replace(0, np.nan)
)

pure_product_premium_topic_summary_dataframe["premium_share_lift_dissatisfaction_vs_satisfaction"] = (
    (pure_product_premium_topic_summary_dataframe["premium_document_share_dissatisfaction"] + 1e-6) /
    (pure_product_premium_topic_summary_dataframe["premium_document_share_satisfaction"] + 1e-6)
)

pure_product_priority_topic_summary_dataframe = (
    pure_product_cause_priority_comparison_dataframe.loc[
        pure_product_cause_priority_comparison_dataframe["issue_priority_level"] == "Priority review"
    ].copy()
)

pure_product_priority_topic_summary_dataframe["priority_share_lift_dissatisfaction_vs_satisfaction"] = (
    (pure_product_priority_topic_summary_dataframe["document_share_within_topic_dissatisfaction"] + 1e-6) /
    (pure_product_priority_topic_summary_dataframe["document_share_within_topic_satisfaction"] + 1e-6)
)

display(pure_product_premium_topic_summary_dataframe.sort_values("topic_id"))
display(pure_product_priority_topic_summary_dataframe.sort_values("topic_id"))

,topic_id,premium_document_count_dissatisfaction,premium_document_count_satisfaction,total_document_count_dissatisfaction,total_document_count_satisfaction,premium_document_share_dissatisfaction,premium_document_share_satisfaction,premium_share_lift_dissatisfaction_vs_satisfaction
0,0,347.0,306.0,829.0,822.0,0.418577,0.372263,1.124411
1,1,447.0,450.0,1943.0,1923.0,0.230057,0.234009,0.983109
2,2,57.0,124.0,1649.0,2261.0,0.034566,0.054843,0.630286
3,3,15.0,22.0,1235.0,1183.0,0.012146,0.018597,0.653129
4,4,503.0,539.0,1563.0,1588.0,0.321817,0.339421,0.948136
5,5,177.0,194.0,948.0,935.0,0.186709,0.207487,0.899860
6,6,213.0,287.0,1244.0,1655.0,0.171222,0.173414,0.987360
7,7,712.0,952.0,1340.0,1753.0,0.531343,0.543069,0.978408
8,8,533.0,657.0,1508.0,1767.0,0.353448,0.371817,0.950598
9,9,337.0,344.0,1115.0,1172.0,0.302242,0.293515,1.029732
10,10,11.0,20.0,504.0,510.0,0.021825,0.039216,0.556559
11,11,323.0,312.0,889.0,899.0,0.363330,0.347052,1.046901
12,12,186.0,195.0,540.0,593.0,0.344444,0.328836,1.047464
13,13,147.0,149.0,559.0,591.0,0.262970,0.252115,1.043054
14,14,217.0,83.0,987.0,708.0,0.219858,0.117232,1.875409

,topic_id,issue_priority_level,document_count_dissatisfaction,document_count_satisfaction,document_share_within_topic_dissatisfaction,document_share_within_topic_satisfaction,sampled_reviews_dissatisfaction,sampled_reviews_satisfaction,priority_share_lift_dissatisfaction_vs_satisfaction
1,0,Priority review,299.0,317.0,0.360676,0.385645,48438.0,54379.0,0.935253
3,1,Priority review,745.0,747.0,0.383428,0.388456,122262.0,115517.0,0.987057
5,2,Priority review,218.0,245.0,0.132201,0.108359,31126.0,35578.0,1.220027
7,3,Priority review,355.0,309.0,0.287449,0.261200,57804.0,47469.0,1.100494
9,4,Priority review,256.0,244.0,0.163788,0.153652,35891.0,33105.0,1.065961
11,5,Priority review,316.0,330.0,0.333333,0.352941,48517.0,51861.0,0.944445
13,6,Priority review,145.0,154.0,0.116559,0.093051,19263.0,21020.0,1.252633
15,7,Priority review,420.0,461.0,0.313433,0.262978,67469.0,73162.0,1.191860
17,8,Priority review,384.0,434.0,0.254642,0.245614,55153.0,63448.0,1.036756
19,9,Priority review,247.0,243.0,0.221525,0.207338,35810.0,36341.0,1.068423
21,10,Priority review,101.0,107.0,0.200397,0.209804,14303.0,15146.0,0.955163
23,11,Priority review,260.0,248.0,0.292463,0.275862,35000.0,33454.0,1.060180
25,12,Priority review,203.0,213.0,0.375926,0.359191,29736.0,32400.0,1.046592
27,13,Priority review,192.0,189.0,0.343470,0.319797,28556.0,30311.0,1.074027
29,14,Priority review,228.0,130.0,0.231003,0.183616,31884.0,17882.0,1.258077

In [67]:
# Combining product-cause topic evidence for interpretation
pure_product_topic_evidence_dataframe = (
    pure_product_cause_topic_driver_dataframe
    .merge(
        pure_product_cause_topic_breadth_summary_dataframe,
        on = "topic_id",
        how = "left"
    )
    .merge(
        pure_product_cause_topic_core_summary_dataframe.loc[
            pure_product_cause_topic_core_summary_dataframe["cohort_role"] == "Dissatisfaction",
            ["topic_id", "topic_core_ratio", "average_topic_margin", "median_topic_margin"]
        ].rename(
            columns = {
                "average_topic_margin": "average_topic_margin_dissatisfaction",
                "median_topic_margin": "median_topic_margin_dissatisfaction"
            }
        ),
        on = "topic_id",
        how = "left"
    )
    .merge(
        pure_product_premium_topic_summary_dataframe[
            [
                "topic_id",
                "premium_document_share_dissatisfaction",
                "premium_document_share_satisfaction",
                "premium_share_lift_dissatisfaction_vs_satisfaction"
            ]
        ],
        on = "topic_id",
        how = "left"
    )
    .merge(
        pure_product_priority_topic_summary_dataframe[
            [
                "topic_id",
                "document_share_within_topic_dissatisfaction",
                "document_share_within_topic_satisfaction",
                "priority_share_lift_dissatisfaction_vs_satisfaction"
            ]
        ].rename(
            columns = {
                "document_share_within_topic_dissatisfaction": "priority_document_share_dissatisfaction",
                "document_share_within_topic_satisfaction": "priority_document_share_satisfaction"
            }
        ),
        on = "topic_id",
        how = "left"
    )
    .merge(
        pure_product_cause_segment_reporting_eligibility_dataframe
        .groupby("topic_id", dropna = False)
        .agg(
            eligible_segment_count = ("is_segment_reporting_eligible", "sum"),
            total_segment_count = ("is_segment_reporting_eligible", "count")
        )
        .reset_index(),
        on = "topic_id",
        how = "left"
    )
)

pure_product_topic_evidence_dataframe["eligible_segment_ratio"] = (
    pure_product_topic_evidence_dataframe["eligible_segment_count"] /
    pure_product_topic_evidence_dataframe["total_segment_count"].replace(0, np.nan)
)

pure_product_topic_evidence_dataframe["breadth_type"] = np.select(
    [
        pure_product_topic_evidence_dataframe["concentration_hhi"] >= 0.25,
        pure_product_topic_evidence_dataframe["segment_count_above_05_share"] >= 6
    ],
    [
        "Concentrated",
        "Broad"
    ],
    default = "Moderate"
)

pure_product_topic_evidence_dataframe["signal_strength"] = np.select(
    [
        pure_product_topic_evidence_dataframe["document_share_lift_dissatisfaction_vs_satisfaction"] >= 1.12,
        pure_product_topic_evidence_dataframe["document_share_lift_dissatisfaction_vs_satisfaction"] >= 1.05
    ],
    [
        "Strong",
        "Moderate"
    ],
    default = "Weak"
)

pure_product_topic_evidence_dataframe["confidence_level"] = np.select(
    [
        (
            pure_product_topic_evidence_dataframe["average_topic_margin_dissatisfaction"] >= 0.06
        ) & (
            pure_product_topic_evidence_dataframe["topic_core_ratio"] >= 0.60
        ),
        (
            pure_product_topic_evidence_dataframe["average_topic_margin_dissatisfaction"] >= 0.04
        ) & (
            pure_product_topic_evidence_dataframe["topic_core_ratio"] >= 0.45
        )
    ],
    [
        "High",
        "Moderate"
    ],
    default = "Watch"
)

pure_product_topic_evidence_dataframe["premium_exposure_type"] = np.select(
    [
        pure_product_topic_evidence_dataframe["premium_share_lift_dissatisfaction_vs_satisfaction"] >= 1.08,
        pure_product_topic_evidence_dataframe["premium_share_lift_dissatisfaction_vs_satisfaction"] <= 0.92
    ],
    [
        "Premium-tilted",
        "Non-premium-tilted"
    ],
    default = "Balanced"
)

pure_product_topic_evidence_dataframe["priority_exposure_type"] = np.select(
    [
        pure_product_topic_evidence_dataframe["priority_share_lift_dissatisfaction_vs_satisfaction"] >= 1.08,
        pure_product_topic_evidence_dataframe["priority_share_lift_dissatisfaction_vs_satisfaction"] <= 0.92
    ],
    [
        "Priority-product-tilted",
        "Monitor-product-tilted"
    ],
    default = "Balanced"
)

display(
    pure_product_topic_evidence_dataframe.sort_values(
        by = [
            "signal_strength",
            "confidence_level",
            "eligible_segment_ratio",
            "document_share_lift_dissatisfaction_vs_satisfaction",
            "document_count_dissatisfaction"
        ],
        ascending = [False, False, False, False, False]
    )
)

,topic_id,document_count_dissatisfaction,document_count_satisfaction,sampled_reviews_dissatisfaction,sampled_reviews_satisfaction,document_share_dissatisfaction,document_share_satisfaction,average_topic_strength_dissatisfaction,average_topic_strength_satisfaction,document_share_lift_dissatisfaction_vs_satisfaction,document_share_gap,top_terms,covered_segment_count,segment_count_above_05_share,segment_count_above_10_share,max_segment_share,concentration_hhi,topic_core_ratio,average_topic_margin_dissatisfaction,median_topic_margin_dissatisfaction,premium_document_share_dissatisfaction,premium_document_share_satisfaction,premium_share_lift_dissatisfaction_vs_satisfaction,priority_document_share_dissatisfaction,priority_document_share_satisfaction,priority_share_lift_dissatisfaction_vs_satisfaction,eligible_segment_count,total_segment_count,eligible_segment_ratio,breadth_type,signal_strength,confidence_level,premium_exposure_type,priority_exposure_type
11,8,1508,1767,186343,207786,0.089480,0.096242,0.062071,0.061152,0.929738,-0.006762,"speaker, sound_quality, music, bluetooth, bass...",9,6,4,0.235411,0.159585,0.424403,0.033923,0.031151,0.353448,0.371817,0.950598,0.254642,0.245614,1.036756,9,9,1.000000,Broad,Weak,Watch,Balanced,Balanced
8,9,1115,1172,117624,117609,0.066160,0.063834,0.077246,0.069280,1.036436,0.002326,"hdmi, monitor, hdmi cable, display, adapter, f...",9,7,4,0.257399,0.155804,0.650224,0.051858,0.054196,0.302242,0.293515,1.029732,0.221525,0.207338,1.068423,9,9,1.000000,Broad,Weak,Moderate,Balanced,Balanced
12,7,1340,1753,154727,181569,0.079511,0.095479,0.076480,0.068051,0.832759,-0.015968,"camera, camera work, motion, recording, view, ...",9,6,4,0.297015,0.182403,0.611940,0.052507,0.047110,0.531343,0.543069,0.978408,0.313433,0.262978,1.191860,8,9,0.888889,Broad,Weak,Moderate,Balanced,Priority-product-tilted
13,6,1244,1655,106045,142748,0.073815,0.090142,0.069644,0.059319,0.818877,-0.016327,"screws, mount, screw, mounting, bracket, tight...",9,4,4,0.303859,0.210864,0.494373,0.048504,0.036919,0.171222,0.173414,0.987360,0.116559,0.093051,1.252633,7,9,0.777778,Moderate,Weak,Moderate,Balanced,Priority-product-tilted
14,2,1649,2261,151873,215319,0.097846,0.123148,0.075505,0.065433,0.794541,-0.025302,"ipad, not_fit, protect, color, cases, fits, ca...",9,4,3,0.402668,0.266479,0.656155,0.054879,0.055389,0.034566,0.054843,0.630286,0.132201,0.108359,1.220027,6,9,0.666667,Concentrated,Weak,Moderate,Non-premium-tilted,Priority-product-tilted
9,13,559,591,65891,67434,0.033169,0.032190,0.104388,0.099674,1.030432,0.000980,"antenna, stations, reception, channels, miles,...",9,8,4,0.254025,0.148019,0.613596,0.076557,0.046962,0.262970,0.252115,1.043054,0.343470,0.319797,1.074027,8,9,0.888889,Broad,Weak,High,Balanced,Balanced
10,12,540,593,61628,63106,0.032042,0.032298,0.113165,0.108941,0.992052,-0.000257,"fitbit, band, wrist, watch, bands, heart rate,...",9,7,6,0.220370,0.140384,0.698148,0.091330,0.116824,0.344444,0.328836,1.047464,0.375926,0.359191,1.046592,7,9,0.777778,Broad,Weak,High,Balanced,Balanced
0,14,987,708,101346,57240,0.058565,0.038562,0.072934,0.065367,1.518712,0.020003,"charger, charge battery, hold charge, battery ...",9,7,4,0.244174,0.161470,0.418440,0.050471,0.025075,0.219858,0.117232,1.875409,0.231003,0.183616,1.258077,6,9,0.666667,Broad,Strong,Watch,Premium-tilted,Priority-product-tilted
1,3,1235,1183,163189,131865,0.073281,0.064434,0.087539,0.068773,1.137305,0.008847,"charge phone, cords, chargers, charger, not_ch...",9,4,3,0.460729,0.300784,0.606478,0.068660,0.073553,0.012146,0.018597,0.653129,0.287449,0.261200,1.100494,5,9,0.555556,Concentrated,Strong,High,Non-premium-tilted,Priority-product-tilted
5,11,889,899,112541,100945,0.052750,0.048965,0.079903,0.072212,1.077301,0.003785,"remote, remote work, remotes, buttons, remote ...",9,8,3,0.205849,0.144348,0.652418,0.057704,0.060459,0.363330,0.347052,1.046901,0.292463,0.275862,1.060180,9,9,1.000000,Broad,Moderate,Moderate,Balanced,Balanced
7,4,1563,1588,185105,172334,0.092743,0.086492,0.077481,0.064503,1.072269,0.006251,"drive, drives, files, disk, data, hard_drive, ...",9,6,4,0.212412,0.163149,0.584773,0.056516,0.045806,0.321817,0.339421,0.948136,0.163788,0.153652,1.065961,9,9,1.000000,Broad,Moderate,Moderate,Balanced,Balanced
4,0,829,822,126048,113848,0.049190,0.044771,0.061512,0.053579,1.098695,0.004419,"router, wifi, network, internet, modem, netgea...",9,6,5,0.249698,0.161432,0.617612,0.048766,0.055668,0.418577,0.372263,1.124411,0.360676,0.385645,0.935253,7,9,0.777778,Broad,Moderate,Moderate,Premium-tilted,Balanced
3,1,1943,1923,285840,253556,0.115291,0.104739,0.088229,0.087839,1.100750,0.010552,"ear, headphone, earbuds, ears, buds, earbud, s...",9,8,6,0.206382,0.135297,0.788986,0.066252,0.068180,0.230057,0.234009,0.983109,0.383428,0.388456,0.987057,9,9,1.000000,Broad,Moderate,High,Balanced,Balanced
2,5,948,935,124455,110844,0.056251,0.050926,0.090618,0.077804,1.104565,0.005325,"mouse, keyboard, keys, logitech, mouse work, k...",9,7,5,0.213080,0.138477,0.740506,0.070006,0.077528,0.186709,0.207487,0.899860,0.333333,0.352941,0.944445,8,9,0.888889,Broad,Moderate,High,Non-premium-tilted,Balanced
6,10,504,510,50688,48753,0.029906,0.027778,0.116487,0.096013,1.076601,0.002128,"bubbles, screen_protector, protectors, screen ...",8,4,3,0.569444,0.381118,0.694444,0.102736,0.130588,0.021825,0.039216,0.556559,0.200397,0.209804,0.955163,3,9,0.333333,Concentrated,Moderate,High,Non-premium-tilted,Balanced

In [68]:
# Selecting representative product-cause documents for manual review
pure_product_representative_documents_dataframe = (
    pure_product_cause_topic_assignment_dataframe[
        [
            "cohort_role",
            "topic_id",
            "topic_strength",
            "price_band",
            "issue_priority_level",
            "product_display_name",
            "sampled_review_count",
            "pure_product_cause_text"
        ]
    ]
    .sort_values(
        ["cohort_role", "topic_id", "topic_strength"],
        ascending = [True, True, False]
    )
    .groupby(["cohort_role", "topic_id"], group_keys = False)
    .head(5)
    .reset_index(drop = True)
)

pure_product_representative_documents_dataframe["text_preview"] = (
    pure_product_representative_documents_dataframe["pure_product_cause_text"]
    .str.slice(0, 600)
)

display(
    pure_product_representative_documents_dataframe[
        [
            "cohort_role",
            "topic_id",
            "topic_strength",
            "price_band",
            "issue_priority_level",
            "product_display_name",
            "sampled_review_count",
            "text_preview"
        ]
    ]
)

,cohort_role,topic_id,topic_strength,price_band,issue_priority_level,product_display_name,sampled_review_count,text_preview
0,Dissatisfaction,0,0.088021,Very premium,Monitor,NETGEAR Nighthawk X6 Smart Wi-Fi Router (R8000...,250,pile scrap simplest activities router pass dns...
1,Dissatisfaction,0,0.087991,Premium,Priority review,NETGEAR R7500 Nighthawk X4 AC2350 Dual Band Wi...,108,constantly reset router buy open sent bought v...
2,Dissatisfaction,0,0.086958,Premium,Monitor,NETGEAR Nighthawk X4S Smart WiFi Router (R7800...,250,piece crap mouth owning started continued conn...
3,Dissatisfaction,0,0.086019,Premium,Priority review,NETGEAR Nighthawk 4-Stream AX4 Wi-fi 6 Router ...,250,purchased ago start constantly disconnect wife...
4,Dissatisfaction,0,0.085944,Very premium,Monitor,NETGEAR Nighthawk X6 Smart Wi-Fi Router (R8000...,250,router cheapo linksys bought powerful router v...
5,Dissatisfaction,1,0.137328,Upper mid,Monitor,TOZO NC2 Hybrid Active Noise Cancelling Wirele...,250,work ago earbuds cut watching listening music ...
6,Dissatisfaction,1,0.137180,Upper mid,Monitor,TOZO NC2 Hybrid Active Noise Cancelling Wirele...,250,completely dead_on_arrival no_power whatsoever...
7,Dissatisfaction,1,0.135325,Premium,Priority review,Sony WF-SP800N Truly Wireless Sports In-Ear No...,121,sound_quality earpiece left earpiece try earpi...
8,Dissatisfaction,1,0.134889,Lower mid,Monitor,TOZO T10 Bluetooth 5.3 Wireless Earbuds with W...,250,thought came case handy strap work try pair ip...
9,Dissatisfaction,1,0.134544,Lower mid,Monitor,MEE audio M6 X1 Wired In-Ear Sports Headphones...,250,sounds tin iphone hear kind awkward secure ear...
10,Dissatisfaction,2,0.138389,Budget,Monitor,MoKo Case Fit 2018/2017 iPad 9.7 6th/5th Gener...,250,case title misleading not_fit ipad release cou...
11,Dissatisfaction,2,0.137892,Budget,Monitor,ProCase Smart Case for iPad Air 2 (2014 Releas...,230,cheap feeling stand received yesterday complet...
12,Dissatisfaction,2,0.137073,Lower mid,Monitor,JETech Case for iPad Air 1st Edition (NOT for ...,250,hole camera lens line feel case crazy flaw tip...
13,Dissatisfaction,2,0.137005,Lower mid,Monitor,JETech Case for iPad 10.2-Inch (2021/2020/2019...,146,case surrounding ipad hard plastic zero shock ...
14,Dissatisfaction,2,0.136851,Budget,Monitor,MoKo Case Fit iPad Air 2 - Slim Lightweight Sm...,168,lightweight cheap hold everyday durable model ...
15,Dissatisfaction,3,0.154208,Budget,Monitor,JSAUX USB-C to USB A Cable 3.1A Fast Charging ...,250,cord randomly stopped_working super thought fi...
16,Dissatisfaction,3,0.150864,Lower mid,Priority review,[Apple MFi Certified] USB C to Lightning Cable...,250,bought thinking maybe round wrong messed bad b...
17,Dissatisfaction,3,0.150713,Budget,Monitor,[Apple MFi Certified] iPhone Fast Charger 3Pac...,152,bend cable stops work brand iphone cable scams...
18,Dissatisfaction,3,0.150270,Budget,Monitor,"DEEGO USB Type C Cable, 2Pack Extra Long USB A...",157,lock not_charge unless hold charge extremely s...
19,Dissatisfaction,3,0.150025,Lower mid,Priority review,FEEL2NICE iPhone Charger Cable [MFi Certified]...,123,bought cord length feature mean no_power trans...
20,Dissatisfaction,4,0.143660,Premium,Monitor,SanDisk 2TB Extreme Portable SSD - Up to 1050M...,185,failed connect mac organizational work video h...
21,Dissatisfaction,4,0.141958,Upper mid,Monitor,SanDisk SSD PLUS 1TB Internal SSD - SATA III 6...,250,hate rating ssd defective computer recognize p...
22,Dissatisfaction,4,0.140843,Premium,Monitor,(OLD MODEL) Seagate Expansion 3TB Desktop Exte...,250,bought drives backup business files personal f...
23,Dissatisfaction,4,0.139994,Budget,Monitor,"PNY 128GB Turbo Attache 3 USB 3.0 Flash Drive,...",250,stay likely deffective taken star seriousley r...
24,Dissatisfaction,4,0.139422,Premium,Priority review,SanDisk 1TB Extreme PRO Portable SSD - Up to 2...,201,according sandisk trusted store data reason ex...
25,Dissatisfaction,5,0.155946,Lower mid,Priority review,"Wireless Keyboard and Mouse Combo, UHURU 2.4G ...",243,quality bang keys mouse okay trouble tracking ...
26,Dissatisfaction,5,0.154295,Premium,Monitor,Logitech MK710 Wireless Keyboard and Mouse Com...,250,ergonomic design poor hand wrist supports keyb...
27,Dissatisfaction,5,0.152542,Upper mid,Monitor,Logitech MK320 Wireless Desktop Keyboard and M...,250,purchased pc connect projector wireless keyboa...
28,Dissatisfaction,5,0.151381,Upper mid,Priority review,Logitech MK570 Wireless Wave Keyboard and Mous...,193,keyboard random letter keys stopped_working so...
29,Dissatisfaction,5,0.150610,Premium,Monitor,Logitech MK710 Wireless Keyboard and Mouse Com...,107,mouse assist finding awesome replace battery t...
30,Dissatisfaction,6,0.159192,Lower mid,Monitor,WALI TV Wall Mount Articulating LCD Monitor Fu...,250,pay cheap tv mount fit tv screws hole light tv...
31,Dissatisfaction,6,0.157901,Budget,Monitor,VideoSecu ML411B Adjustable Tilt Swivel Rotati...,122,walk mount mounts office lcd screens monitor s...
32,Dissatisfaction,6,0.155971,Upper mid,Monitor,VIVO Extra Tall Single Monitor Desk Mount Stan...,183,monitor mount pain work mount save space monit...
33,Dissatisfaction,6,0.155335,Lower mid,Monitor,VideoSecu ML12 TV Wall Mount Articulating Arm ...,134,tiest screws pre drilled holes proper screws s...
34,Dissatisfaction,6,0.151315,Upper mid,Monitor,USX MOUNT Full Motion TV Wall Mount for Most 4...,173,wall base wide wall studs position luck meanin...
35,Dissatisfaction,7,0.148076,Premium,Priority review,Blink Whole Home Bundle | Video Doorbell Syste...,250,hopes letdown harsh poor optics class security...
36,Dissatisfaction,7,0.147744,Premium,Priority review,Blink Mini – Compact indoor plug-in smart secu...,250,mara gusta mucho hay que ponerle plan para pod...
37,Dissatisfaction,7,0.147472,Upper mid,Priority review,"YI 2pc Security Home Camera, 1080p 2.4G WiFi S...",250,camera work try access camera remotely iphone ...
38,Dissatisfaction,7,0.147281,Premium,Priority review,Blink Whole Home Bundle | Video Doorbell Syste...,250,town apparently power outage sync module conne...
39,Dissatisfaction,7,0.146534,Premium,Priority review,Blink Mini – Compact indoor plug-in smart secu...,250,camera work 2hrs not_working purchased cam gue...
40,Dissatisfaction,8,0.118865,Upper mid,Monitor,"TEWELL Computer Speaker, HD 24W Audio Vintage ...",109,stylish echo dot sounds nope shocked flat rela...
41,Dissatisfaction,8,0.107263,Premium,Monitor,Edifier R1280Ts Powered Bookshelf Speakers - 2...,250,sound expecting kind sad speaker audio technic...
42,Dissatisfaction,8,0.106653,Premium,Monitor,Edifier R1700BT Bluetooth Bookshelf Speakers -...,122,speaker sound price point issues buy bluetooth...
43,Dissatisfaction,8,0.105984,Premium,Monitor,Logitech Z333 2.1 Speakers – Easy-access Volum...,135,sub did_not_work volume sound distorted turned...
44,Dissatisfaction,8,0.105520,Upper mid,Monitor,Logitech X-140 2.0 Speakers,71,bought speaker excellent sound speaker loud be...
45,Dissatisfaction,9,0.145132,Upper mid,Monitor,Amazon Basics 5-Pack DisplayPort to HDMI Displ...,151,frayed spot plugs phone particularly rough mov...
46,Dissatisfaction,9,0.141962,Budget,Priority review,AVACON DisplayPort to HDMI 6 Feet Gold-Plated ...,246,did_not_work connect did_not_work uses cable p...
47,Dissatisfaction,9,0.139488,Lower mid,Monitor,"Warrky DisplayPort to HDMI Adapter 2-Pack (4K,...",100,suddenly lose monitor blue screened convert fi...
48,Dissatisfaction,9,0.138903,Lower mid,Monitor,Warrky 4K DisplayPort to HDMI Cable Adapter 15...,188,purchased hdmi end cable loose picture_quality...
49,Dissatisfaction,9,0.138517,Budget,Monitor,"BENFEI DisplayPort to HDMI, 4K@30Hz Gold-Plate...",104,despite slew buzzwords headline converter conv...
50,Dissatisfaction,10,0.200585,Budget,Priority review,Supershieldz (3 Pack) Anti Glare (Matte) Scree...,133,flimsy material bubbles install ipad worse ipa...
51,Dissatisfaction,10,0.199465,Budget,Priority review,Supershieldz (3 Pack) Anti-Glare (Matte) Scree...,196,anti glare adhere bubbles matter try smooth un...
52,Dissatisfaction,10,0.196138,Budget,Priority review,(3 Pack) Supershieldz Anti Glare and Anti Fing...,95,mentioned hard bubbles fit screen putting lett...
53,Dissatisfaction,10,0.195885,Budget,Priority review,Supershieldz (3 Pack) Anti Glare and Anti Fing...,182,glare ipad thought honestly eyes matte finish ...
54,Dissatisfaction,10,0.195434,Budget,Priority review,Supershieldz (3 Pack) Designed for Fire HD 10 ...,250,failed attempts inferior cut crooked line edge...
55,Dissatisfaction,11,0.156000,Budget,Priority review,Philips Universal Remote Control Replacement f...,124,work philips tv work went bought expecting ins...
56,Dissatisfaction,11,0.151918,Budget,Priority review,Philips Universal Remote Control Replacement f...,250,work receiver try auto method manual method re...
57,Dissatisfaction,11,0.151108,Budget,Monitor,GE 6-Device Backlit Universal Remote Control f...,250,buy took code work went code cleared did_not_w...
58,Dissatisfaction,11,0.150298,Budget,Monitor,GE 6-Device Backlit Universal Remote Control f...,250,asked roku remote numbers change channels voic...
59,Dissatisfaction,11,0.149383,Budget,Monitor,GE 6-Device Backlit Universal Remote Control f...,250,enjoyed work tv yamaha sound bar lost function...
60,Dissatisfaction,12,0.207131,Upper mid,Monitor,"Smart Watch for Men Women, 2022 Fitness Tracke...",110,smart phone watch fully function smart phone p...
61,Dissatisfaction,12,0.198407,Upper mid,Monitor,"EURANS Smart Watch 44mm, Fitness Tracker with ...",146,work charge keeps loosing alerts sleep trackin...
62,Dissatisfaction,12,0.197811,Upper mid,Priority review,Amazfit Bip U Pro Smart Watch with Alexa Built...,250,instruction booklet tiny gray print white back...
63,Dissatisfaction,12,0.196696,Premium,Priority review,Amazfit GTS Fitness Smartwatch with Heart Rate...,117,digital face rest subpar watch multitask funct...
64,Dissatisfaction,12,0.196018,Upper mid,Priority review,Fitpolo Smart Watch for Android and iOS Phones...,107,pedometer stopped_working refurbished came lin...
65,Dissatisfaction,13,0.238142,Upper mid,Priority review,1byone Outdoor TV Antenna 360° Omni-Directiona...,185,weak signal tune channels tv fades rabbit ears...
66,Dissatisfaction,13,0.236159,Upper mid,Monitor,1byone Amplified HD Digital TV Antenna - Suppo...,250,purchased antennas 1byone mile amplified mohu ...
67,Dissatisfaction,13,0.235200,Upper mid,Monitor,Antennas Direct ClearStream Eclipse Amplified ...,250,hopes cut cable cord unfortunately gave channe...
68,Dissatisfaction,13,0.233594,Upper mid,Priority review,RCA ANT1650F Flat Digital Amplified Indoor TV ...,250,bought refused pay tv higher hang work play re...
69,Dissatisfaction,13,0.233507,Upper mid,Priority review,"Mohu Leaf 50 Amplified Indoor TV Antenna, 60-M...",106,piece antenna dies service yesterday tv antenn...
70,Dissatisfaction,14,0.195745,Upper mid,Priority review,"4 Pack CR123A Lithium Batteries,QUICKHELP 3.7V...",135,battery fried flashlight longer turns cycles l...
71,Dissatisfaction,14,0.188152,Upper mid,Monitor,EBL 2800mAh Ni-MH AA Rechargeable Batteries (8...,250,broke charger quit work charger work battery n...
72,Dissatisfaction,14,0.184247,Lower mid,Priority review,Energizer Rechargeable AA and AAA Battery Char...,250,placed order packs battery intended flashlight...
73,Dissatisfaction,14,0.180266,Lower mid,Priority review,Energizer Rechargeable AA and AAA Battery Char...,250,battery xbox controller fully charge stop work...
74,Dissatisfaction,14,0.179843,Upper mid,Monitor,EBL 2800mAh Ni-MH AA Rechargeable Batteries (8...,250,charger work lights green battery charge purch...
75,Satisfaction,0,0.080361,Upper mid,Priority review,NETGEAR Wireless Router – AC1750 Dual Band Gig...,141,allows access wireless capabilities form modem...
76,Satisfaction,0,0.079500,Premium,Monitor,TP-Link AC1900 Smart Wireless Router - Beamfor...,226,setup fast speeds reliable router available wh...
77,Satisfaction,0,0.078456,Upper mid,Priority review,TP-Link AC2300 Wifi Router,139,route setting features work expected ive route...
78,Satisfaction,0,0.078049,Premium,Priority review,ASUS AX6000 WiFi 6 Gaming Router (RT-AX88U) - ...,217,hooked work desktop laptop iphones tvs arlo oo...
79,Satisfaction,0,0.077610,Premium,Monitor,TP-Link AX6000 WiFi 6 Router(Archer AX6000) -8...,250,admit doubts install unit mbps isp equipment m...
80,Satisfaction,1,0.136854,Upper mid,Monitor,"comiso Wireless Earbuds Bluetooth Headphones, ...",182,sound setup fit comfortable battery_life sound...
81,Satisfaction,1,0.134391,Premium,Priority review,"ACREO The Next Generation Open Ear Headphones,...",122,sound enjoy singing music open ear buds hear l...
82,Satisfaction,1,0.132480,Lower mid,Priority review,"JVC HAEBR80S Sports Clip Headphones (Silver), ...",231,simple headphone bass boost sound buds tend ea...
83,Satisfaction,1,0.132440,Premium,Priority review,"Jabra Elite 65t Earbuds – Alexa Built-in, True...",250,researched truly wireless headphone believe de...
84,Satisfaction,1,0.131304,Premium,Priority review,SAMSUNG Galaxy Buds Live True Wireless Bluetoo...,250,desperately try truly wireless bluetooth headp...
85,Satisfaction,2,0.121318,Premium,Monitor,"ZUGU Case for iPad Pro 11 inch (1st, 2nd, 3rd ...",133,worth puppy try chew fail don case terms textu...
86,Satisfaction,2,0.117205,Lower mid,Monitor,Ztotop Case for iPad Air 3rd Generation 2019/i...,204,pleased ipad case durable heavy elastic straps...
87,Satisfaction,2,0.116589,Lower mid,Monitor,Fintie Case for iPad Air 5th Generation (2022)...,176,sturdy colors value fits ipad air generation i...
88,Satisfaction,2,0.116467,Lower mid,Monitor,JETech Case for iPad Pro 10.5-Inch and iPad Ai...,173,cover strong durable fits ipad air highly jete...
89,Satisfaction,2,0.116119,Lower mid,Priority review,"Targus Slim Case for iPad 2, iPad 3 and iPad 4...",211,wish ability turn screen close cover covers ap...
90,Satisfaction,3,0.129481,Budget,Monitor,[Apple MFi Certified] iPhone Fast Charger 3Pac...,144,fits usb_c socket cord length allows connect f...
91,Satisfaction,3,0.128892,Budget,Priority review,"iPhone Charger, JAHMAI Nylon Braided Lightning...",250,quickly customer appears issues cord problem f...
92,Satisfaction,3,0.124843,Budget,Priority review,"iPhone Charger, JAHMAI Nylon Braided Lightning...",250,length durability cord charge power noticed no...
93,Satisfaction,3,0.123964,Budget,Priority review,"iPhone Fast Charger Cable,Apple Super Quick Li...",140,cords fast charge charge phone minutes length ...
94,Satisfaction,3,0.121778,Budget,Monitor,"Micro USB Cable,[2 Pack/3.3ft],Rampow QC 3.0 F...",250,skeptical braided usb lifetime received possib...
95,Satisfaction,4,0.124849,Premium,Priority review,(Old Model) Seagate Backup Plus 2TB Desktop Ex...,75,drive expected buy achieved promised simple se...
96,Satisfaction,4,0.124410,Upper mid,Monitor,Unitek USB 3.0 to IDE and SATA Converter Exter...,107,simple work personal data recovery transfer pr...
97,Satisfaction,4,0.121845,Premium,Priority review,"WD 8TB My Book Desktop External Hard Drive, US...",250,satisfied western digital hd design fast belie...
98,Satisfaction,4,0.121164,Premium,Priority review,(Old Model) Seagate Backup Plus 2TB Desktop Ex...,250,work install software machine thew rest instal...
99,Satisfaction,4,0.121148,Upper mid,Monitor,(Old Model) Seagate 1TB Desktop HDD Sata 6Gb/s...,250,super installation zero problems drive beat pr...
100,Satisfaction,5,0.134750,Premium,Monitor,Logitech MK710 Wireless Keyboard and Mouse Com...,244,constant living room work battery wore letter ...
101,Satisfaction,5,0.132659,Upper mid,Priority review,Logitech MK545 Advanced Wireless Keyboard and ...,250,keyboard work mouse problems keyboard exactly ...
102,Satisfaction,5,0.131249,Lower mid,Priority review,Eagletec K104 Wireless Keyboard and Mouse Comb...,189,touch keyboard feels expensive mouse work upda...
103,Satisfaction,5,0.130457,Upper mid,Monitor,Logitech MK295 Wireless Mouse & Keyboard Combo...,121,chose model white keyboard mouse silent touch ...
104,Satisfaction,5,0.129094,Premium,Priority review,Microsoft Sculpt Ergonomic Wireless Desktop Ke...,250,software developer lots keyboard shortcuts mic...
105,Satisfaction,6,0.139614,Upper mid,Monitor,"VideoSecu Tilt Swivel TV Wall Mount 32""- 70"" L...",213,mount solid heavy purchases past including pri...
106,Satisfaction,6,0.138070,Upper mid,Monitor,VideoSecu MW380B5 Full Motion Articulating TV ...,250,price expensive analogues stores mount plenty ...
107,Satisfaction,6,0.137937,Lower mid,Monitor,VideoSecu TV Wall Mount Tilt Swivel Low Profil...,78,value install work hisense tv comes hardware m...
108,Satisfaction,6,0.134597,Upper mid,Monitor,VideoSecu MW380B5 Full Motion Articulating TV ...,156,mounted unit wall rotated appx degrees wall ti...
109,Satisfaction,6,0.134028,Upper mid,Monitor,VideoSecu Tilt TV Wall Mount Bracket for Most ...,250,delivers supposed tv work holding behemoth lcd...
110,Satisfaction,7,0.146203,Lower mid,Priority review,"YI Home Security Camera, 1080p 2.4G WiFi IP In...",250,camera quality excellent compare price moves p...
111,Satisfaction,7,0.145247,Upper mid,Priority review,"WYZE Cam v3 with Color Night Vision, Wired 108...",250,muy buena super cil instalar puedo verla desde...
112,Satisfaction,7,0.144371,Premium,Monitor,Dzees 4MP Solar Security Camera Outdoor Wirele...,172,camera night vision terrific motion detection ...
113,Satisfaction,7,0.144262,Premium,Monitor,"Dzees Security Cameras Wireless Outdoor,2K Sol...",101,super order night visions smart service motion...
114,Satisfaction,7,0.142373,Upper mid,Monitor,ZUMIMALL Security Cameras Wireless Outdoor-2K ...,123,pic quality setup camera setup plugged wall ou...
115,Satisfaction,8,0.102267,Premium,Monitor,Creative Labs 51MF1610AA002 GigaWorks T20 Seri...,177,speaker remember kids computer speaker studio ...
116,Satisfaction,8,0.101319,Premium,Monitor,Logitech Speaker System Z323 with Subwoofer,180,speaker price spent decent shopping convinced ...
117,Satisfaction,8,0.101132,Premium,Monitor,Edifier R1280Ts Powered Bookshelf Speakers - 2...,250,speaker amazing ipod classic sound produced fa...
118,Satisfaction,8,0.100530,Premium,Monitor,Edifier R1280DB Powered Bluetooth Bookshelf Sp...,250,speaker sounds clean crisp bass boosts trebles...
119,Satisfaction,8,0.100514,Premium,Priority review,OontZ Pro Premium Speaker • Ultra Portable Spe...,250,boat work purchase took pair phone play stereo...
120,Satisfaction,9,0.130054,Lower mid,Monitor,"Warrky DisplayPort to HDMI Adapter 2-Pack (4K,...",133,feels quality did_not_work particular screen s...
121,Satisfaction,9,0.129800,Lower mid,Monitor,Selore&S-Global USB C to Dual HDMI Adapter 4K ...,129,simple connect issue configuring screen modes ...
122,Satisfaction,9,0.129001,Budget,Monitor,"Amazon Basics HDMI to DVI Adapter Cable, Bi-Di...",250,work wish ordered longer cord exactly hooked m...
123,Satisfaction,9,0.128685,Upper mid,Priority review,"BENFEI DisplayPort to HDMI Adapter 5 Pack, DP ...",250,adapter work connect 0ti graphics card hdmi po...
124,Satisfaction,9,0.126825,Budget,Priority review,"BENFEI DisplayPort to HDMI 3 Feet Cable,Gold-P...",250,added monitor video card cable display port hd...
125,Satisfaction,10,0.171283,Budget,Monitor,SPARIN 2 Pack Screen Protector Compatible with...,165,price work kids ipads tempered glass exactly k...
126,Satisfaction,10,0.168359,Lower mid,Monitor,OMOTON Screen Protector Compatible with Surfac...,250,simple install try future buy omoton brand eas...
127,Satisfaction,10,0.167115,Budget,Priority review,(3 Pack) Supershieldz Anti Glare and Anti Fing...,81,putting crazy quite lined screen rest anti gla...
128,Satisfaction,10,0.167076,Lower mid,Monitor,amFilm Screen Protector for iPad Pro 12.9 (202...,44,hands film glass protectors install quality gl...

In [69]:
# Saving intermediate NLP outputs for reuse

checkpoint_dir = Path("notebook_checkpoints")
checkpoint_dir.mkdir(exist_ok = True)

checkpoint_objects = {
    "pure_product_cause_topic_assignment_dataframe": pure_product_cause_topic_assignment_dataframe,
    "review_boundary_token": review_boundary_token,
    "remedy_or_transaction_tokens": remedy_or_transaction_tokens,
    "delivery_or_fulfillment_tokens": delivery_or_fulfillment_tokens,
    "evaluative_outcome_tokens": evaluative_outcome_tokens,
}

with open(checkpoint_dir / "review_analysis_checkpoint.pkl", "wb") as file:
    pickle.dump(checkpoint_objects, file)

print("Checkpoint saved :", checkpoint_dir / "review_analysis_checkpoint.pkl")

Checkpoint saved : notebook_checkpoints/review_analysis_checkpoint.pkl

In [70]:
# Reloading saved NLP outputs for continued analysis

checkpoint_dir = Path("notebook_checkpoints")

with open(checkpoint_dir / "review_analysis_checkpoint.pkl", "rb") as file:
    checkpoint_objects = pickle.load(file)

pure_product_cause_topic_assignment_dataframe = checkpoint_objects["pure_product_cause_topic_assignment_dataframe"]
review_boundary_token = checkpoint_objects["review_boundary_token"]
remedy_or_transaction_tokens = checkpoint_objects["remedy_or_transaction_tokens"]
delivery_or_fulfillment_tokens = checkpoint_objects["delivery_or_fulfillment_tokens"]
evaluative_outcome_tokens = checkpoint_objects["evaluative_outcome_tokens"]

print("Checkpoint loaded.")
print(pure_product_cause_topic_assignment_dataframe.shape)

Checkpoint loaded.
(35213, 53)

In [71]:
# Defining text normalization and issue-bucket matching rules
def normalize_text(value):
    if pd.isna(value):
        return ""
    return re.sub(r"\s+", " ", str(value).lower()).strip()

def split_document_reviews(value, boundary_token = review_boundary_token):
    if pd.isna(value):
        return []
    return [part.strip() for part in str(value).split(boundary_token) if part.strip()]

excluded_rule_tokens = (
    remedy_or_transaction_tokens
    .union(delivery_or_fulfillment_tokens)
    .union(evaluative_outcome_tokens)
)

def build_rule_text(review_text):
    tokens = [
        token
        for token in str(review_text).split()
        if token not in excluded_rule_tokens
    ]
    return " ".join(tokens).strip()

def has_pattern(text_value, patterns):
    return any(re.search(pattern, text_value) for pattern in patterns)

rule_definitions = {
    "charging_power_failure": {
        "title_terms": [
            r"\bcharger\b", r"\bcharging cable\b", r"\bcharging cord\b",
            r"\bbattery charger\b", r"\brechargeable battery\b", r"\bpower bank\b",
            r"\bbattery\b"
        ],
        "review_terms": [
            r"\bcharger\b", r"\bbattery\b", r"\bcharging\b", r"\bcharge\b",
            r"\bpower adapter\b", r"\bcharging port\b"
        ],
        "failure_terms": [
            r"\bnot_charging\b", r"\bnot_charge\b", r"\bno_power\b",
            r"\bnot_turn_on\b", r"\bwill_not_turn_on\b",
            r"\bbattery_died\b", r"\bdead_on_arrival\b"
        ],
        "exclude_terms": [
            r"\baudio cable\b", r"\bav cable\b", r"\bstereo cable\b",
            r"\bcomponent cable\b", r"\bcomposite cable\b", r"\bs[\- ]?video\b",
            r"\brca\b", r"\bcoax\b", r"\bantenna\b", r"\breception\b",
            r"\bchannels\b", r"\bstations\b", r"\bbackpack\b", r"\bbag\b"
        ],
        "title_only": False
    },
    "connectivity_pairing_failure": {
        "title_terms": [
            r"\brouter\b", r"\bmodem\b", r"\bwifi\b", r"\bbluetooth\b",
            r"\bnetwork adapter\b", r"\bwireless adapter\b",
            r"\breceiver\b", r"\bdongle\b", r"\bmesh\b", r"\bextender\b"
        ],
        "review_terms": [
            r"\brouter\b", r"\bmodem\b", r"\bwifi\b", r"\bbluetooth\b",
            r"\bnetwork\b", r"\binternet\b", r"\breceiver\b", r"\bdongle\b",
            r"\bpair\b"
        ],
        "failure_terms": [
            r"\bnot_connect\b", r"\bnot_connecting\b", r"\bkeeps_disconnecting\b",
            r"\bnot_pair\b", r"\bnot_pairing\b", r"\bloses connection\b",
            r"\bdrops connection\b", r"\bdisconnect(?:ed|ing)?\b",
            r"\bpairing failed\b", r"\bconnection drops\b"
        ],
        "exclude_terms": [
            r"\bantenna\b", r"\breception\b", r"\bchannels\b", r"\bstations\b",
            r"\btripod\b", r"\bmount\b", r"\bstrap\b",
            r"\baudio cable\b", r"\bav cable\b", r"\bstereo cable\b",
            r"\bheadphone jack\b", r"\baux\b",
            r"\bhdmi arc\b", r"\barc\b"
        ],
        "title_only": False
    },
    "storage_data_reliability": {
        "title_terms": [
            r"\bssd\b", r"\bhard drive\b", r"\bhard_drive\b", r"\bflash drive\b",
            r"\bmemory card\b", r"\bmicro_sd\b", r"\bsd_card\b",
            r"\bexternal drive\b", r"\bdisk\b"
        ],
        "review_terms": [
            r"\bssd\b", r"\bhard_drive\b", r"\bdrive\b", r"\bdisk\b",
            r"\bdata\b", r"\bfiles\b", r"\bmicro_sd\b", r"\bsd_card\b",
            r"\bmemory card\b", r"\bflash drive\b"
        ],
        "failure_terms": [
            r"\bnot recognized\b", r"\bfailed recognize\b", r"\bcorrupt(?:ed)?\b",
            r"\bdata loss\b", r"\blost all\b", r"\bfiles missing\b",
            r"\bwould not format\b", r"\bnot readable\b", r"\bcan not be read\b",
            r"\bread error\b", r"\bdrive failed\b", r"\bcard failed\b",
            r"\bdead_on_arrival\b"
        ],
        "exclude_terms": [
            r"\bapp\b", r"\bsync\b", r"\bcloud\b"
        ],
        "title_only": False
    },
    "compatibility_fit_issue": {
        "title_terms": [
            r"\bcase\b", r"\badapter\b", r"\bhdmi\b", r"\bscreen protector\b",
            r"\bscreen_protector\b", r"\busb c\b", r"\busb a\b",
            r"\bmicro sd\b", r"\bsd card\b"
        ],
        "review_terms": [
            r"\bcase\b", r"\badapter\b", r"\bhdmi\b", r"\bprotector\b",
            r"\bport\b", r"\bslot\b"
        ],
        "failure_terms": [
            r"\bnot_fit\b", r"\bnot_compatible\b", r"\bdoes not fit\b",
            r"\bwrong size\b", r"\btoo small\b", r"\btoo big\b"
        ],
        "exclude_terms": [],
        "title_only": False
    },
    "physical_build_installation_failure": {
        "title_terms": [
            r"\bmount\b", r"\bmounting\b", r"\bbracket\b", r"\bscrews\b",
            r"\bstrap\b", r"\bhinge\b", r"\bclip\b", r"\bscreen protector\b",
            r"\bscreen_protector\b"
        ],
        "review_terms": [
            r"\bmount\b", r"\bbracket\b", r"\bscrew\b", r"\bstrap\b",
            r"\bclip\b", r"\bprotector\b", r"\bcase\b"
        ],
        "failure_terms": [
            r"\bbroken\b", r"\bbroke\b", r"\bcracked\b", r"\bcracking\b",
            r"\bflimsy\b", r"\bstripped\b", r"\bbubbles\b", r"\bfell apart\b",
            r"\bpoor_quality\b"
        ],
        "exclude_terms": [
            r"\bfitbit\b", r"\bsmartwatch\b", r"\bsmart watch\b"
        ],
        "title_only": False
    },
    "audio_device_failure": {
        "title_terms": [
            r"\bearbuds?\b", r"\bheadphones?\b", r"\bspeaker\b",
            r"\bspeakers\b", r"\bmicrophone\b", r"\bmic\b"
        ],
        "review_terms": [
            r"\bearbuds?\b", r"\bheadphones?\b", r"\bspeaker\b",
            r"\bspeakers\b", r"\bmicrophone\b", r"\bmic\b",
            r"\bearpiece\b", r"\baudio\b"
        ],
        "failure_terms": [
            r"\bno_sound\b", r"\bdistorted\b", r"\bstatic\b", r"\bbuzzing\b",
            r"\bhissing\b", r"\bleft earpiece\b", r"\bright earpiece\b",
            r"\bone side\b", r"\bleft side\b", r"\bright side\b"
        ],
        "exclude_terms": [
            r"\bantenna\b", r"\bradio\b"
        ],
        "title_only": False
    },
    "video_display_failure": {
        "title_terms": [
            r"\bmonitor\b", r"\bdisplay\b", r"\bcamera\b", r"\bscreen\b",
            r"\bvideo\b", r"\bprojector\b", r"\bwebcam\b"
        ],
        "review_terms": [
            r"\bmonitor\b", r"\bdisplay\b", r"\bcamera\b", r"\bscreen\b",
            r"\bvideo\b", r"\brecording\b"
        ],
        "failure_terms": [
            r"\bflicker(?:ing)?\b", r"\bdead pixels?\b", r"\bblack screen\b",
            r"\bgreen horizontal lines\b", r"\bpixelated\b", r"\bblurry\b",
            r"\bnot recording\b", r"\bno_signal\b"
        ],
        "exclude_terms": [
            r"\bantenna\b", r"\breception\b", r"\bchannels\b", r"\bstations\b",
            r"\bradio\b"
        ],
        "title_only": False
    },
    "input_control_failure": {
        "title_terms": [
            r"\bkeyboard\b", r"\bmouse\b", r"\bremote\b", r"\bcontroller\b", r"\btrackpad\b"
        ],
        "review_terms": [
            r"\bkeyboard\b", r"\bmouse\b", r"\bremote\b", r"\bcontroller\b",
            r"\btrackpad\b", r"\bkeys\b", r"\bbuttons\b", r"\bscroll wheel\b",
            r"\bcursor\b", r"\bleft click\b", r"\bright click\b"
        ],
        "failure_terms": [
            r"\bdouble typing\b", r"\blag(?:ging)?\b", r"\bbuttons? stuck\b",
            r"\bkeys? stuck\b",
            r"\bscroll wheel\b.*\bnot_working\b",
            r"\bcursor\b.*\blag(?:ging)?\b",
            r"\bleft click\b.*\bnot_working\b",
            r"\bright click\b.*\bnot_working\b",
            r"\bkeyboard\b.*\bstopped_working\b", r"\bkeyboard\b.*\bnot_working\b",
            r"\bmouse\b.*\bstopped_working\b", r"\bmouse\b.*\bnot_working\b",
            r"\bremote\b.*\bstopped_working\b", r"\bremote\b.*\bnot_working\b",
            r"\bcontroller\b.*\bstopped_working\b", r"\bcontroller\b.*\bnot_working\b"
        ],
        "exclude_terms": [
            r"\bfitbit\b", r"\bsmartwatch\b", r"\bsmart watch\b"
        ],
        "title_only": False
    },
    "wearable_tracking_failure": {
        "title_terms": [
            r"\bfitbit\b", r"\bsmartwatch\b", r"\bsmart watch\b",
            r"\bactivity tracker\b", r"\bfitness tracker\b"
        ],
        "review_terms": [
            r"\bfitbit\b", r"\bsmartwatch\b", r"\bsmart watch\b",
            r"\btracking\b", r"\bheart rate\b", r"\bsteps\b", r"\bsleep\b"
        ],
        "failure_terms": [
            r"\binaccurate\b", r"\bnot_tracking\b", r"\bwon.t track\b",
            r"\bwrong heart rate\b", r"\bwrong step count\b",
            r"\binaccurate heart rate\b", r"\binaccurate sleep\b"
        ],
        "exclude_terms": [
            r"\bband\b", r"\bstrap\b", r"\bwrong size\b", r"\bnot_fit\b",
            r"\bmouse\b", r"\bkeyboard\b", r"\bremote\b", r"\bcable\b",
            r"\bcharger\b", r"\badapter\b", r"\bhard drive\b", r"\bssd\b", r"\bsd_card\b"
        ],
        "title_only": True
    },
    "antenna_reception_failure": {
        "title_terms": [
            r"\bantenna\b", r"\brabbit ears\b", r"\bradio antenna\b", r"\btv antenna\b"
        ],
        "review_terms": [
            r"\bantenna\b", r"\breception\b", r"\bchannels\b", r"\bstations\b"
        ],
        "failure_terms": [
            r"\bweak signal\b", r"\bpoor reception\b", r"\bchannels missing\b",
            r"\bchannels disappear\b", r"\bfuzzy\b", r"\bpixelated\b", r"\bno_signal\b"
        ],
        "exclude_terms": [
            r"\bhdmi\b", r"\badapter\b", r"\bmouse\b", r"\bkeyboard\b",
            r"\bfm transmitter\b", r"\bremote\b", r"\bdisplayport\b",
            r"\bdash cam\b", r"\bspeaker cable\b", r"\baudio cable\b"
        ],
        "title_only": True
    }
}

bucket_names = list(rule_definitions.keys())

bucket_priority = [
    "storage_data_reliability",
    "charging_power_failure",
    "connectivity_pairing_failure",
    "compatibility_fit_issue",
    "video_display_failure",
    "audio_device_failure",
    "input_control_failure",
    "physical_build_installation_failure",
    "wearable_tracking_failure",
    "antenna_reception_failure"
]

source_columns = [
    "document_id",
    "cohort_role",
    "price_band",
    "issue_priority_level",
    "product_display_name",
    "sampled_review_count",
    "modeling_text_clipped"
]

In [72]:
# Applying issue-bucket rules to Electronics review documents

review_rows = []

for record in pure_product_cause_topic_assignment_dataframe[source_columns].itertuples(index = False):
    title_text = normalize_text(record.product_display_name)
    review_list = split_document_reviews(record.modeling_text_clipped, boundary_token = review_boundary_token)
    review_total_count = len(review_list)

    for review_index, raw_review in enumerate(review_list, start = 1):
        review_text = normalize_text(build_rule_text(raw_review))
        if not review_text:
            continue

        row = {
            "document_id": record.document_id,
            "cohort_role": record.cohort_role,
            "price_band": record.price_band,
            "issue_priority_level": record.issue_priority_level,
            "product_display_name": record.product_display_name,
            "sampled_review_count": record.sampled_review_count,
            "review_total_count": review_total_count,
            "review_index": review_index,
            "review_text": review_text
        }

        for bucket_name, rule in rule_definitions.items():
            title_hit = has_pattern(title_text, rule["title_terms"])
            review_hit = has_pattern(review_text, rule["review_terms"])
            failure_hit = has_pattern(review_text, rule["failure_terms"])
            exclude_hit = has_pattern(title_text, rule["exclude_terms"]) or has_pattern(review_text, rule["exclude_terms"])
            object_gate = title_hit if rule["title_only"] else (title_hit or review_hit)

            row[bucket_name] = object_gate and failure_hit and not exclude_hit

        matched_buckets = [bucket for bucket in bucket_names if row[bucket]]
        row["matched_bucket_count"] = len(matched_buckets)
        row["review_primary_bucket"] = next((bucket for bucket in bucket_priority if row[bucket]), None)

        review_rows.append(row)

review_match_df = pd.DataFrame(review_rows)

document_base_df = (
    pure_product_cause_topic_assignment_dataframe[
        [
            "document_id",
            "cohort_role",
            "price_band",
            "issue_priority_level",
            "product_display_name",
            "sampled_review_count",
        ]
    ]
    .drop_duplicates("document_id")
    .copy()
)

review_bucket_counts_df = (
    review_match_df
    .melt(
        id_vars = [
            "document_id",
            "cohort_role",
            "price_band",
            "issue_priority_level",
            "product_display_name",
            "review_total_count",
        ],
        value_vars = bucket_names,
        var_name = "bucket_name",
        value_name = "matched",
    )
    .loc[lambda df: df["matched"]]
    .groupby(
        [
            "document_id",
            "cohort_role",
            "price_band",
            "issue_priority_level",
            "product_display_name",
            "review_total_count",
            "bucket_name",
        ],
        dropna = False,
    )
    .size()
    .reset_index(name = "matched_review_count")
)

review_bucket_counts_df["matched_review_ratio"] = (
    review_bucket_counts_df["matched_review_count"]
    / review_bucket_counts_df["review_total_count"].replace(0, np.nan)
)

review_bucket_counts_df["passes_document_threshold"] = (
    review_bucket_counts_df["matched_review_count"] >= 2
)

document_bucket_df = (
    review_bucket_counts_df
    .loc[review_bucket_counts_df["passes_document_threshold"]]
    .copy()
)

document_bucket_wide_df = (
    document_bucket_df
    .assign(bucket_flag = True)
    .pivot_table(
        index = "document_id",
        columns = "bucket_name",
        values = "bucket_flag",
        aggfunc = "max",
        fill_value = False,
    )
    .reset_index()
)

document_match_df = document_base_df.merge(
    document_bucket_wide_df,
    on = "document_id",
    how = "left",
)

for bucket_name in bucket_names:
    if bucket_name not in document_match_df.columns:
        document_match_df[bucket_name] = False

    document_match_df[bucket_name] = (
        document_match_df[bucket_name]
        .astype("boolean")
        .fillna(False)
        .astype(bool)
    )

document_match_df["matched_bucket_count"] = document_match_df[bucket_names].sum(axis = 1)
document_match_df["has_any_bucket"] = document_match_df["matched_bucket_count"] > 0
document_match_df["has_multiple_buckets"] = document_match_df["matched_bucket_count"] >= 2

document_primary_bucket_df = (
    document_bucket_df
    .sort_values(
        [
            "document_id",
            "matched_review_count",
            "matched_review_ratio",
            "bucket_name",
        ],
        ascending = [True, False, False, True],
    )
    .groupby("document_id", group_keys = False)
    .head(1)
    .reset_index(drop = True)
)

coverage_summary_df = (
    document_match_df
    .groupby("cohort_role", dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        any_bucket_count = ("has_any_bucket", "sum"),
        multi_bucket_count = ("has_multiple_buckets", "sum"),
        unclassified_count = ("has_any_bucket", lambda values: (~values).sum())
    )
    .reset_index()
)

coverage_summary_df["any_bucket_ratio"] = (
    coverage_summary_df["any_bucket_count"] / coverage_summary_df["document_count"]
)

coverage_summary_df["multi_bucket_ratio"] = (
    coverage_summary_df["multi_bucket_count"] / coverage_summary_df["document_count"]
)

coverage_summary_df["unclassified_ratio"] = (
    coverage_summary_df["unclassified_count"] / coverage_summary_df["document_count"]
)

dissatisfaction_total = document_match_df["cohort_role"].eq("Dissatisfaction").sum()
satisfaction_total = document_match_df["cohort_role"].eq("Satisfaction").sum()

bucket_summary_df = pd.DataFrame({
    "bucket_name": bucket_names,
    "dissatisfaction_document_count": [
        document_match_df.loc[
            document_match_df["cohort_role"].eq("Dissatisfaction"), bucket
        ].sum()
        for bucket in bucket_names
    ],
    "satisfaction_document_count": [
        document_match_df.loc[
            document_match_df["cohort_role"].eq("Satisfaction"), bucket
        ].sum()
        for bucket in bucket_names
    ]
})

bucket_summary_df["dissatisfaction_ratio"] = (
    bucket_summary_df["dissatisfaction_document_count"] / dissatisfaction_total
)

bucket_summary_df["satisfaction_ratio"] = (
    bucket_summary_df["satisfaction_document_count"] / satisfaction_total
)

bucket_summary_df["lift_vs_satisfaction"] = (
    (bucket_summary_df["dissatisfaction_ratio"] + 1e-6)
    / (bucket_summary_df["satisfaction_ratio"] + 1e-6)
)

bucket_summary_df["ratio_gap"] = (
    bucket_summary_df["dissatisfaction_ratio"]
    - bucket_summary_df["satisfaction_ratio"]
)

display(coverage_summary_df)
display(bucket_summary_df.sort_values(["lift_vs_satisfaction", "ratio_gap"], ascending = [False, False]))
display(document_primary_bucket_df.head(20))

,cohort_role,document_count,any_bucket_count,multi_bucket_count,unclassified_count,any_bucket_ratio,multi_bucket_ratio,unclassified_ratio
0,Dissatisfaction,16853,12665,4975,4188,0.751498,0.295200,0.248502
1,Satisfaction,18360,4227,481,14133,0.230229,0.026198,0.769771

,bucket_name,dissatisfaction_document_count,satisfaction_document_count,dissatisfaction_ratio,satisfaction_ratio,lift_vs_satisfaction,ratio_gap
8,wearable_tracking_failure,87,5,0.005162,0.000272,18.890220,0.004890
0,charging_power_failure,3198,298,0.189758,0.016231,11.690503,0.173528
2,storage_data_reliability,961,94,0.057022,0.005120,11.135604,0.051903
6,video_display_failure,1680,324,0.099686,0.017647,5.648582,0.082038
1,connectivity_pairing_failure,2771,561,0.164422,0.030556,5.380933,0.133866
3,compatibility_fit_issue,2806,579,0.166499,0.031536,5.279507,0.134963
5,audio_device_failure,2938,991,0.174331,0.053976,3.229744,0.120355
7,input_control_failure,1420,565,0.084258,0.030773,2.737956,0.053485
4,physical_build_installation_failure,3256,1302,0.193200,0.070915,2.724363,0.122285
9,antenna_reception_failure,98,42,0.005815,0.002288,2.541307,0.003527

,document_id,cohort_role,price_band,issue_priority_level,product_display_name,review_total_count,bucket_name,matched_review_count,matched_review_ratio,passes_document_threshold
0,Dissatisfaction|true|Budget|Monitor|B00004Z5M1...,Dissatisfaction,Budget,Monitor,Belkin - F3U133b10 (F3U133b10) Hi-Speed USB A/...,64,compatibility_fit_issue,3,0.046875,True
1,Dissatisfaction|true|Budget|Monitor|B00005MDZD...,Dissatisfaction,Budget,Monitor,Gam3Gear Component AV Audio Video Cable for PS...,131,video_display_failure,10,0.076336,True
2,Dissatisfaction|true|Budget|Monitor|B00005T3DX...,Dissatisfaction,Budget,Monitor,"Duracell CR2 3V Lithium Battery, 1 Count Pack,...",46,charging_power_failure,2,0.043478,True
3,Dissatisfaction|true|Budget|Monitor|B00005T3GH...,Dissatisfaction,Budget,Monitor,RCA AH216 Stereo Headphone Adapter Plug,50,audio_device_failure,4,0.080000,True
4,Dissatisfaction|true|Budget|Monitor|B00009UHJS...,Dissatisfaction,Budget,Monitor,Scosche MDA1B Compatible with 1988-05 GM Micro...,30,compatibility_fit_issue,5,0.166667,True
5,Dissatisfaction|true|Budget|Monitor|B0000D88FU...,Dissatisfaction,Budget,Monitor,"GE RG59 Coaxial Cable 25ft. (7.6m), Black, F-T...",46,physical_build_installation_failure,3,0.065217,True
6,Dissatisfaction|true|Budget|Monitor|B00029MTMQ...,Dissatisfaction,Budget,Monitor,Zalman ZM-MIC1 High Sensitivity Headphone Micr...,120,audio_device_failure,19,0.158333,True
7,Dissatisfaction|true|Budget|Monitor|B0002A4M4I...,Dissatisfaction,Budget,Monitor,Canon USB Cable IFC-400PCU for Canon Cameras &...,26,compatibility_fit_issue,2,0.076923,True
8,Dissatisfaction|true|Budget|Monitor|B0002GX1XA...,Dissatisfaction,Budget,Monitor,"C2G 43036 TAA Compliant Cable Ties, 4 Inch Lon...",63,physical_build_installation_failure,2,0.031746,True
9,Dissatisfaction|true|Budget|Monitor|B0002KR13M...,Dissatisfaction,Budget,Monitor,DTOL MC 3.5mm Audio Cable - 3.5mm TRS Female t...,111,audio_device_failure,16,0.144144,True
10,Dissatisfaction|true|Budget|Monitor|B00066Z9XG...,Dissatisfaction,Budget,Monitor,Kaito T-1 Radio Antenna,79,physical_build_installation_failure,5,0.063291,True
11,Dissatisfaction|true|Budget|Monitor|B00091S0WA...,Dissatisfaction,Budget,Monitor,Sony LCS-CST General Purpose Soft Carrying Cas...,39,compatibility_fit_issue,9,0.230769,True
12,Dissatisfaction|true|Budget|Monitor|B000ARAPQW...,Dissatisfaction,Budget,Monitor,Kodak U-8 USB Cable (Discontinued by Manufactu...,107,charging_power_failure,3,0.028037,True
13,Dissatisfaction|true|Budget|Monitor|B000BSJFFC...,Dissatisfaction,Budget,Monitor,DTOL Charger Charging Cable for PS5 Controller...,40,charging_power_failure,3,0.075000,True
14,Dissatisfaction|true|Budget|Monitor|B000BSJFJS...,Dissatisfaction,Budget,Monitor,SANOXY PS2 Keyboard to USB Adapter,38,compatibility_fit_issue,2,0.052632,True
15,Dissatisfaction|true|Budget|Monitor|B000BYH8EQ...,Dissatisfaction,Budget,Monitor,BARSKA Binocular Tripod Adaptor,47,physical_build_installation_failure,6,0.127660,True
16,Dissatisfaction|true|Budget|Monitor|B000EZL1EA...,Dissatisfaction,Budget,Monitor,Slinger Digital Storage Aluminum Case for Eigh...,41,physical_build_installation_failure,4,0.097561,True
17,Dissatisfaction|true|Budget|Monitor|B000HDJY7K...,Dissatisfaction,Budget,Monitor,"HDMI to DVI Cable, HDMI Male to DVI Male, CL2 ...",41,video_display_failure,2,0.048780,True
18,Dissatisfaction|true|Budget|Monitor|B000I23TTE...,Dissatisfaction,Budget,Monitor,C&E 6 Inch 3.5mm Female to 2 RCA Male Stereo A...,120,audio_device_failure,10,0.083333,True
19,Dissatisfaction|true|Budget|Monitor|B000I94FAE...,Dissatisfaction,Budget,Monitor,"RCA Audio Piggyback Cable, 2 RCA Male to 2 RCA...",39,audio_device_failure,3,0.076923,True

In [73]:
# Auditing document-level threshold effects on issue classification
document_review_count_df = (
    review_match_df
    .groupby("document_id", dropna = False)
    .agg(
        review_total_count = ("review_index", "count"),
        matched_review_count = ("matched_bucket_count", lambda values: (values > 0).sum())
    )
    .reset_index()
)

document_threshold_audit_df = document_base_df.merge(
    document_review_count_df,
    on = "document_id",
    how = "left"
)

document_threshold_audit_df["review_total_count"] = (
    document_threshold_audit_df["review_total_count"]
    .fillna(0)
    .astype(int)
)

document_threshold_audit_df["matched_review_count"] = (
    document_threshold_audit_df["matched_review_count"]
    .fillna(0)
    .astype(int)
)

document_threshold_audit_df["has_any_review_match"] = (
    document_threshold_audit_df["matched_review_count"] > 0
)

document_threshold_audit_df["below_two_review_document"] = (
    document_threshold_audit_df["review_total_count"] < 2
)

document_threshold_audit_df["lost_short_matched_document"] = (
    document_threshold_audit_df["below_two_review_document"] &
    document_threshold_audit_df["has_any_review_match"]
)

threshold_loss_summary_df = (
    document_threshold_audit_df
    .groupby("cohort_role", dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        below_two_review_document_count = ("below_two_review_document", "sum"),
        any_review_match_count = ("has_any_review_match", "sum"),
        lost_short_matched_document_count = ("lost_short_matched_document", "sum")
    )
    .reset_index()
)

threshold_loss_summary_df["below_two_review_document_ratio"] = (
    threshold_loss_summary_df["below_two_review_document_count"] /
    threshold_loss_summary_df["document_count"]
)

threshold_loss_summary_df["lost_short_matched_document_ratio"] = (
    threshold_loss_summary_df["lost_short_matched_document_count"] /
    threshold_loss_summary_df["document_count"]
)

display(threshold_loss_summary_df)

,cohort_role,document_count,below_two_review_document_count,any_review_match_count,lost_short_matched_document_count,below_two_review_document_ratio,lost_short_matched_document_ratio
0,Dissatisfaction,16853,0,15052,0,0.0,0.0
1,Satisfaction,18360,0,9949,0,0.0,0.0

In [74]:
# Saving issue-bucket outputs for validation and dashboard preparation
checkpoint_dir = "electronics_issue_bucket_checkpoint"

import os
os.makedirs(checkpoint_dir, exist_ok = True)

review_match_df.to_parquet(f"{checkpoint_dir}/review_match_df.parquet", index = False)
document_base_df.to_parquet(f"{checkpoint_dir}/document_base_df.parquet", index = False)
review_bucket_counts_df.to_parquet(f"{checkpoint_dir}/review_bucket_counts_df.parquet", index = False)
document_bucket_df.to_parquet(f"{checkpoint_dir}/document_bucket_df.parquet", index = False)
document_match_df.to_parquet(f"{checkpoint_dir}/document_match_df.parquet", index = False)
document_primary_bucket_df.to_parquet(f"{checkpoint_dir}/document_primary_bucket_df.parquet", index = False)
coverage_summary_df.to_parquet(f"{checkpoint_dir}/coverage_summary_df.parquet", index = False)
bucket_summary_df.to_parquet(f"{checkpoint_dir}/bucket_summary_df.parquet", index = False)

print("Electronics issue bucket checkpoint saved successfully.")
print(checkpoint_dir)

Electronics issue bucket checkpoint saved successfully.
electronics_issue_bucket_checkpoint

In [75]:
# Reloading issue-bucket outputs for validation and reporting
checkpoint_dir = "electronics_issue_bucket_checkpoint"

review_match_df = pd.read_parquet(f"{checkpoint_dir}/review_match_df.parquet")
document_base_df = pd.read_parquet(f"{checkpoint_dir}/document_base_df.parquet")
review_bucket_counts_df = pd.read_parquet(f"{checkpoint_dir}/review_bucket_counts_df.parquet")
document_bucket_df = pd.read_parquet(f"{checkpoint_dir}/document_bucket_df.parquet")
document_match_df = pd.read_parquet(f"{checkpoint_dir}/document_match_df.parquet")
document_primary_bucket_df = pd.read_parquet(f"{checkpoint_dir}/document_primary_bucket_df.parquet")
coverage_summary_df = pd.read_parquet(f"{checkpoint_dir}/coverage_summary_df.parquet")
bucket_summary_df = pd.read_parquet(f"{checkpoint_dir}/bucket_summary_df.parquet")

print("Electronics issue bucket checkpoint reloaded successfully.")

Electronics issue bucket checkpoint reloaded successfully.

In [76]:
# Creating a validation sample from surviving issue-bucket matches
validation_sample_size = 50
validation_seed = 42

validated_candidate_keys_df = document_bucket_df[
    ["document_id", "bucket_name"]
].drop_duplicates()

validation_candidates_df = (
    review_match_df
    .melt(
        id_vars = [
            "document_id",
            "price_band",
            "issue_priority_level",
            "product_display_name",
            "review_text"
        ],
        value_vars = bucket_names,
        var_name = "bucket_name",
        value_name = "matched"
    )
    .loc[lambda df: df["matched"]]
    .merge(
        validated_candidate_keys_df,
        on = ["document_id", "bucket_name"],
        how = "inner"
    )
    .copy()
)

validation_candidates_df["random_order"] = np.random.default_rng(
    validation_seed
).random(len(validation_candidates_df))

validation_sample_df = (
    validation_candidates_df
    .sort_values(["bucket_name", "random_order"])
    .groupby("bucket_name", group_keys = False)
    .head(validation_sample_size)
    .drop(columns = "random_order")
    .reset_index(drop = True)
)

def explain_match(product_name, review_text, bucket_name):
    rule = rule_definitions[bucket_name]
    title_text = normalize_text(product_name)
    text = normalize_text(review_text)

    title_hit = has_pattern(title_text, rule["title_terms"])
    review_hit = has_pattern(text, rule["review_terms"])
    failure_hit = has_pattern(text, rule["failure_terms"])
    exclude_hit = (
        has_pattern(title_text, rule["exclude_terms"]) or
        has_pattern(text, rule["exclude_terms"])
    )
    object_gate = title_hit if rule["title_only"] else (title_hit or review_hit)

    return pd.Series({
        "title_hit": title_hit,
        "review_hit": review_hit,
        "failure_hit": failure_hit,
        "exclude_hit": exclude_hit,
        "object_gate": object_gate
    })

validation_debug_df = validation_sample_df.apply(
    lambda row: explain_match(
        product_name = row["product_display_name"],
        review_text = row["review_text"],
        bucket_name = row["bucket_name"]
    ),
    axis = 1
)

validation_sample_df = pd.concat(
    [validation_sample_df, validation_debug_df],
    axis = 1
)

validation_sample_df["is_valid_match"] = pd.NA
validation_sample_df["error_type"] = ""
validation_sample_df["validation_note"] = ""

display(validation_sample_df)

,document_id,price_band,issue_priority_level,product_display_name,review_text,bucket_name,matched,title_hit,review_hit,failure_hit,exclude_hit,object_gate,is_valid_match,error_type,validation_note
0,Satisfaction|true|Premium|Monitor|B09BC2YNKF|c...,Premium,Monitor,HD7698A Long Range Outdoor HDTV Antenna - 65+ ...,this mile range antenna is replacing one adver...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
1,Dissatisfaction|true|Upper mid|Monitor|B0C46LB...,Upper mid,Monitor,2023 Amplified HD Digital TV Antenna Long 250+...,the product came with everything however it is...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
2,Dissatisfaction|true|Premium|Monitor|B0BWLZ5PM...,Premium,Monitor,[Newest 2021] Five Star Outdoor HDTV Antenna u...,this tv antenna is piece of crap have no_signa...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
3,Satisfaction|true|Upper mid|Priority review|B0...,Upper mid,Priority review,TV Antenna -Amplified HD Digital Indoor TV Ant...,does_not_work miles from stations no_signal do...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
4,Dissatisfaction|true|Lower mid|Priority review...,Lower mid,Priority review,"TV Antenna Amplified, HD Digital TV Antenna fo...",was not able to pick up any signal move it aro...,antenna_reception_failure,True,True,False,True,False,True,<NA>,,
5,Dissatisfaction|true|Upper mid|Monitor|B07HGQT...,Upper mid,Monitor,RONIN FACTORY Truck Radio Antenna Accessory fo...,as suspected this short antenna has good and p...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
6,Dissatisfaction|true|Premium|Monitor|B07465763...,Premium,Monitor,Channel Master Digital Advantage 100 Direction...,poor reception ended up purchasing different p...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
7,Satisfaction|true|Upper mid|Priority review|B0...,Upper mid,Priority review,TV Antenna -Amplified HD Digital Indoor TV Ant...,the antenna to me very quickly it was easy to ...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
8,Dissatisfaction|true|Lower mid|Priority review...,Lower mid,Priority review,CravenSpeed Stubby Antenna Compatible with Toy...,replaced the oem antenna on my toyota tundra b...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
9,Dissatisfaction|true|Budget|Priority review|B0...,Budget,Priority review,"TV Antenna Amplifier, 25dB High Gain Signal Bo...",ended up losing channels and it pixelated to f...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
10,Dissatisfaction|true|Upper mid|Priority review...,Upper mid,Priority review,"Mohu Leaf 50 Amplified Indoor TV Antenna, 60-M...",this product did_not_work with my foil covered...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
11,Dissatisfaction|true|Upper mid|Priority review...,Upper mid,Priority review,RCA ANT1650F Flat Digital Amplified Indoor TV ...,purchased this antenna because thought that it...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
12,Dissatisfaction|true|Lower mid|Monitor|B00KY4Q...,Lower mid,Monitor,Wilson Electronics 311125 Dual-Band Magnet Mou...,waited few months before doing this review liv...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
13,Satisfaction|true|Budget|Priority review|B08HV...,Budget,Priority review,"Philips LTE Filter for TV Antenna, Filters 4G ...",was expecting this to be minor to be honest ga...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
14,Dissatisfaction|true|Upper mid|Priority review...,Upper mid,Priority review,"Mohu Leaf 50 Amplified Indoor TV Antenna, 60-M...",ordered the mohu leaf amplified version of thi...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
15,Dissatisfaction|true|Lower mid|Priority review...,Lower mid,Priority review,"Vansky TV Antenna Indoor, Digital Amplified In...",the description of this item states mile range...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
16,Dissatisfaction|true|Premium|Monitor|B01FTX7M2...,Premium,Monitor,Channel Master CM-7777HD Amplify Adjustable Ga...,wanted an with more power had moderate signal ...,antenna_reception_failure,True,True,False,True,False,True,<NA>,,
17,Dissatisfaction|true|Lower mid|Priority review...,Lower mid,Priority review,"Vansky TV Antenna Indoor, Digital Amplified In...",live in the middle of raleigh nc bought differ...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
18,Dissatisfaction|true|Upper mid|Monitor|B0C4GMX...,Upper mid,Monitor,"GE Attic Mount HD Digital TV Antenna, Longe Ra...",bought of these antennas for different tv in d...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
19,Satisfaction|true|Lower mid|Priority review|B0...,Lower mid,Priority review,"GE Pro Outdoor Antenna Amplifier, Low Noise A...",only use this if your signal is poor on all th...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
20,Dissatisfaction|true|Lower mid|Priority review...,Lower mid,Priority review,Bose Wave FM Antenna,attached this to my bose radio and there is no...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
21,Satisfaction|true|Lower mid|Priority review|B0...,Lower mid,Priority review,"Vansky TV Antenna Indoor, Digital Amplified In...",works wonders am watching crystal clear tv now...,antenna_reception_failure,True,True,False,True,False,True,<NA>,,
22,Dissatisfaction|true|Upper mid|Monitor|B08P4VX...,Upper mid,Monitor,Winegard FL-5000 FlatWave Digital Indoor HDTV ...,unpluged cable input plugged fl into this inpu...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
23,Dissatisfaction|true|Premium|Priority review|B...,Premium,Priority review,Five Star [Newest 2020] HDTV Antenna - 360° Om...,no_signal at all had better reception with rot...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
24,Satisfaction|true|Lower mid|Priority review|B0...,Lower mid,Priority review,CravenSpeed Stubby Antenna Compatible with Toy...,very poor reception do not buy if you listen p...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
25,Dissatisfaction|true|Upper mid|Monitor|B074CGF...,Upper mid,Monitor,McDuory Amplified Digital Outdoor HDTV Antenna...,it lasted just long enough so can not it no_si...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
26,Dissatisfaction|true|Budget|Priority review|B0...,Budget,Priority review,Mediasonic Homeworx HW110AN Super Thin Indoor ...,did not like it very weak signal after couple ...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
27,Dissatisfaction|true|Lower mid|Priority review...,Lower mid,Priority review,"TV Antenna Amplified, HD Digital TV Antenna fo...",poor reception no matter where you position an...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
28,Dissatisfaction|true|Premium|Monitor|B089RD2CB...,Premium,Monitor,KING DT4400 DISH Tailgater Portable/Roof Mount...,have no idea because it does_not_work it recei...,antenna_reception_failure,True,True,False,True,False,True,<NA>,,
29,Dissatisfaction|true|Upper mid|Monitor|B0C4GMX...,Upper mid,Monitor,"GE Attic Mount HD Digital TV Antenna, Longe Ra...",had no_signal with other inside antennas have ...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
30,Dissatisfaction|true|Upper mid|Monitor|B0C46LB...,Upper mid,Monitor,2023 Amplified HD Digital TV Antenna Long 250+...,attached it to 1t fire recast and could not br...,antenna_reception_failure,True,True,False,True,False,True,<NA>,,
31,Dissatisfaction|true|Upper mid|Priority review...,Upper mid,Priority review,"Mohu Leaf 50 Amplified Indoor TV Antenna, 60-M...",went to the mohu website for help selecting th...,antenna_reception_failure,True,True,False,True,False,True,<NA>,,
32,Dissatisfaction|true|Upper mid|Priority review...,Upper mid,Priority review,"Winegard LNA-200 Boost XT HDTV Preamplifier, T...",bought this hoping that could eliminates some ...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
33,Dissatisfaction|true|Lower mid|Monitor|B00KY4Q...,Lower mid,Monitor,Wilson Electronics 311125 Dual-Band Magnet Mou...,lasted week now no_signal had to put my origin...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
34,Dissatisfaction|true|Lower mid|Priority review...,Lower mid,Priority review,"TV Antenna, Digital TV Antenna for Smart TV In...",the antenna did not pick up as many channel as...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
35,Dissatisfaction|true|Upper mid|Monitor|B08P4VX...,Upper mid,Monitor,Winegard FL-5000 FlatWave Digital Indoor HDTV ...,it works well for while but then after it star...,antenna_reception_failure,True,True,False,True,False,True,<NA>,,
36,Dissatisfaction|true|Upper mid|Priority review...,Upper mid,Priority review,RCA ANT1650F Flat Digital Amplified Indoor TV ...,poor reception most likely need to have it loc...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
37,Dissatisfaction|true|Premium|Monitor|B01FTX7M2...,Premium,Monitor,Channel Master CM-7777HD Amplify Adjustable Ga...,indoor antenna have couple of stations that so...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
38,Dissatisfaction|true|Lower mid|Priority review...,Lower mid,Priority review,TV Antenna HiDB 2023 Upgrade Digital TV Antenn...,device was very easy to install select all the...,antenna_reception_failure,True,True,False,True,False,True,<NA>,,
39,Dissatisfaction|true|Budget|Priority review|B0...,Budget,Priority review,Mediasonic Homeworx HW110AN Super Thin Indoor ...,really poor reception thought this would work ...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
40,Dissatisfaction|true|Upper mid|Priority review...,Upper mid,Priority review,RCA ANT1650F Flat Digital Amplified Indoor TV ...,only pulled in station in my area in northeast...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
41,Dissatisfaction|true|Budget|Priority review|B0...,Budget,Priority review,BOSS Audio Systems MRANT12W Marine Rubber Ante...,looks good and received quickly poor poor rece...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
42,Satisfaction|true|Lower mid|Priority review|B0...,Lower mid,Priority review,"Vansky TV Antenna Indoor, Digital Amplified In...",the picture_quality is so much better with dig...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
43,Satisfaction|true|Budget|Priority review|B08HV...,Budget,Priority review,"Philips LTE Filter for TV Antenna, Filters 4G ...",had great reception of local tv channels using...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
44,Dissatisfaction|true|Lower mid|Monitor|B08GYSS...,Lower mid,Monitor,DreamSky AM FM Portable Radio Plug in Wall or ...,poor reception difficult to tune in could only...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
45,Satisfaction|true|Budget|Priority review|B0BDX...,Budget,Priority review,Bingfu FM Radio Antenna FM Dipole Antenna FM A...,have yamaha receiver that always had poor rece...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
46,Dissatisfaction|true|Lower mid|Priority review...,Lower mid,Priority review,Magic Stick TV MS-60MAX Amplified Indoor TV An...,of no_signal at all,antenna_reception_failure,True,True,False,True,False,True,<NA>,,
47,Dissatisfaction|true|Upper mid|Priority review...,Upper mid,Priority review,24db Distribution Amplifier | Digital TV Anten...,this lowers your signal do not waist your mone...,antenna_reception_failure,True,True,False,True,False,True,<NA>,,
48,Satisfaction|true|Upper mid|Priority review|B0...,Upper mid,Priority review,24db Distribution Amplifier | Digital TV Anten...,one of my tv stations had very weak signal all...,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
49,Dissatisfaction|true|Lower mid|Priority review...,Lower mid,Priority review,3.2 Inch Antenna for 2010-2022 Jeep Cherokee G...,looks more sleek but has very poor reception,antenna_reception_failure,True,True,True,True,False,True,<NA>,,
50,Dissatisfaction|true|Lower mid|Priority review...,Lower mid,Priority review,"WamGra USB C Headphones, HiFi Stereo Type C Ea...",they fit fine and sound good but they do not l...,audio_device_failure,True,True,False,True,False,True,<NA>,,
51,Dissatisfaction|true|Budget|Priority review|B0...,Budget,Priority review,JVC Earclip Earbud Sport Earbud Earclip Black ...,the earbuds stopped_working in one month one s...,audio_device_failure,True,True,True,True,False,True,<NA>,,
52,Dissatisfaction|true|Lower mid|Monitor|B076WSW...,Lower mid,Monitor,GearIT 12AWG Premium Heavy Duty Braided Speake...,one of the cables on both ends made horribly l...,audio_device_failure,True,True,True,True,False,True,<NA>,,
53,Dissatisfaction|true|Budget|Priority review|B0...,Budget,Priority review,Samsung OEM 3.5mm Stereo Headset with Remote a...,received earphone after weeks which were broke...,audio_device_failure,True,True,False,True,False,True,<NA>,,
54,Dissatisfaction|true|Upper mid|Monitor|B08YF1V...,Upper mid,Monitor,"DOSS Bluetooth Speaker, SoundBox Touch Portabl...",it got back static noise the bass is inexistent,audio_device_failure,True,True,False,True,False,True,<NA>,,
55,Dissatisfaction|true|Upper mid|Monitor|B091K4W...,Upper mid,Monitor,"OneOdio Over Ear Headphone, Wired Bass Headset...",good overall but when guitar is connected thro...,audio_device_failure,True,True,False,True,False,True,<NA>,,
56,Dissatisfaction|true|Lower mid|Monitor|B08XPWD...,Lower mid,Monitor,TOZO T10 Bluetooth 5.3 Wireless Earbuds with W...,sometimes you would listen to music and think ...,audio_device_failure,True,True,True,True,False,True,<NA>,,
57,Dissatisfaction|true|Lower mid|Monitor|B08J83T...,Lower mid,Monitor,"iLuv myBuds Wireless Earbuds, Bluetooth 5.3, B...",not even month in and the left one stopped_wor...,audio_device_failure,True,True,False,True,False,True,<NA>,,
58,Satisfaction|true|Budget|Priority review|B0000...,Budget,Priority review,Cyber Acoustics USB Powered 2.0 Desktop Speake...,the sound_quality is okay for computer and tha...,audio_device_failure,True,True,True,True,False,True,<NA>,,
59,Dissatisfaction|true|Budget|Priority review|B0...,Budget,Priority review,Roberts Fojjers Special Foldable Over The Head...,this product does not go with its description ...,audio_device_failure,True,True,False,True,False,True,<NA>,,
60,Dissatisfaction|true|Premium|Monitor|B0BYSP967...,Premium,Monitor,Bose Companion 2 Series III Multimedia Speaker...,was with this product as expected little more ...,audio_device_failure,True,True,True,True,False,True,<NA>,,
61,Dissatisfaction|true|Lower mid|Monitor|B07N839...,Lower mid,Monitor,Snug Play+ Kids Headphones with Volume Limitin...,plugged into multiple devices no_sound,audio_device_failure,True,True,False,True,False,True,<NA>,,
62,Dissatisfaction|true|Very premium|Monitor|B09G...,Very premium,Monitor,"LG OLED C1 Series 55"" Alexa Built-in 4k Smart ...",hi lg says hours before pixel refresh is neede...,audio_device_failure,True,False,True,True,False,True,<NA>,,
63,Dissatisfaction|true|Upper mid|Monitor|B07C2H2...,Upper mid,Monitor,GOgroove Laptop Computer Speakers - SonaVERSE ...,these speakers buzzed loudly whenever they wer...,audio_device_failure,True,True,True,True,False,True,<NA>,,
64,Dissatisfaction|true|Lower mid|Priority review...,Lower mid,Priority review,SAMSUNG EE-UC10JUWEGUS USB-C to 3.5mm Headphon...,first bought this oem samsung adapter for my g...,audio_device_failure,True,True,False,True,False,True,<NA>,,
65,Dissatisfaction|true|Premium|Monitor|B0105VDCZ...,Premium,Monitor,Bose QuietComfort 25 Acoustic Noise Cancelling...,was very to have spent only to have these head...,audio_device_failure,True,True,True,True,False,True,<NA>,,
66,Dissatisfaction|true|Budget|Priority review|B0...,Budget,Priority review,SAMSUNG Earphones Corded Tuned by AKG (Galaxy ...,brand new out of the bag both earbuds were ful...,audio_device_failure,True,False,True,True,False,True,<NA>,,
67,Dissatisfaction|true|Lower mid|Monitor|B0002I5...,Lower mid,Monitor,JVC HA-V570 Supra-Aural Headphones,it was bad enough that they fit oddly on my he...,audio_device_failure,True,True,False,True,False,True,<NA>,,
68,Dissatisfaction|true|Lower mid|Monitor|B09WZBW...,Lower mid,Monitor,JLab Go Air Tones - True Wireless Earbuds Desi...,first to be fair my brother in law and daughte...,audio_device_failure,True,True,True,True,False,True,<NA>,,
69,Dissatisfaction|true|Lower mid|Priority review...,Lower mid,Priority review,Jaybird RUN True Wireless Headphones for Runni...,the sound is fine for music but for phone call...,audio_device_failure,True,True,True,True,False,True,<NA>,,
70,Satisfaction|true|Premium|Priority review|B0C3...,Premium,Priority review,Beats Powerbeats Pro Wireless Earbuds - Apple ...,establishes less than perfect connection with ...,audio_device_failure,True,True,False,True,False,True,<NA>,,
71,Dissatisfaction|true|Upper mid|Monitor|B087D9V...,Upper mid,Monitor,"OontZ Ultra SUP Paddleboard Bluetooth Speaker,...",got it and it worked for the first two minutes...,audio_device_failure,True,True,True,True,False,True,<NA>,,
72,Dissatisfaction|true|Lower mid|Monitor|B0BTP3T...,Lower mid,Monitor,Stouchi USB C to 3.5mm Dongle Adapter (2 Packs...,will not make good connection alot of static,audio_device_failure,True,True,False,True,False,True,<NA>,,
73,Dissatisfaction|true|Budget|Priority review|B0...,Budget,Priority review,USB Type C to 3.5mm Female Headphone Jack Adap...,bought this adapter because my new samsung pho...,audio_device_failure,True,True,True,True,False,True,<NA>,,
74,Dissatisfaction|true|Budget|Priority review|B0...,Budget,Priority review,Subynanal USB Type C to 3.5mm Female Headphone...,you get what you pay for guess wanted back up ...,audio_device_failure,True,True,True,True,False,True,<NA>,,
75,Dissatisfaction|true|Budget|Priority review|B0...,Budget,Priority review,"Wireless Earbuds, HSPRO Bluetooth Earbuds Touc...",bought this product and instead of it being no...,audio_device_failure,True,True,False,True,False,True,<NA>,,
76,Dissatisfaction|true|Upper mid|Monitor|B07QKX2...,Upper mid,Monitor,"KZ ZS10 Pro, Linsoul 4BA+1DD 5 Driver in Ear M...",left side broke up after weeks,audio_device_failure,True,True,False,True,False,True,<NA>,,
77,Dissatisfaction|true|Budget|Priority review|B0...,Budget,Priority review,COOYA USB C to 3.5mm Audio Jack for Samsung S2...,static heard every time product was used to ma...,audio_device_failure,True,True,False,True,False,True,<NA>,,
78,Dissatisfaction|true|Upper mid|Monitor|B0BZ7M9...,Upper mid,Monitor,"EAGLEND USB Headset with Mic for PC, On-Ear Co...",bought few months ago just had opportunity to ...,audio_device_failure,True,True,False,True,False,True,<NA>,,
79,Dissatisfaction|true|Lower mid|Priority review...,Lower mid,Priority review,"eKids Spiderman Kids Headphones, Adjustable He...",brought kids spiderman kids headphones for my ...,audio_device_failure,True,True,True,True,False,True,<NA>,,
80,Dissatisfaction|true|Lower mid|Priority review...,Lower mid,Priority review,"INTSUN Mini Portable Speaker, 3W Mobile Phone ...",look was not expecting bose quality speakers w...,audio_device_failure,True,True,True,True,False,True,<NA>,,
81,Dissatisfaction|true|Budget|Priority review|B0...,Budget,Priority review,"Maeline Headphone Splitter Adapter, 3.5mm Mic ...",started to crackle and pop and shortly after m...,audio_device_failure,True,True,False,True,False,True,<NA>,,
82,Dissatisfaction|true|Premium|Monitor|B0BYSP967...,Premium,Monitor,Bose Companion 2 Series III Multimedia Speaker...,was going to use these speakers for my compute...,audio_device_failure,True,True,True,True,False,True,<NA>,,

In [77]:
output_path = "validation_sample_df.csv"

validation_sample_df.to_csv(output_path, index = False)

print(f"Saved CSV : {output_path}")

Saved CSV : validation_sample_df.csv

#### Labeling the newly generated "validation_sample_df", saved as "validation_sample_df.csv". 
#### Saving the labeled version as a new file named "labeled_validation_sample_df.csv

Labeling Logic : reviewing sampled reviews and marking TRUE only when the review text explicitly and semantically reflects the assigned issue theme, otherwise FALSE.

In [78]:
# Loading externally labeled positive-match validation results
validation_sample_df = pd.read_csv("labeled_validation_sample_df.csv")

print(validation_sample_df.shape)

validation_sample_df.head()

(500, 15)

,document_id,price_band,issue_priority_level,product_display_name,review_text,bucket_name,matched,title_hit,review_hit,failure_hit,exclude_hit,object_gate,is_valid_match,error_type,validation_note
0,Satisfaction|true|Premium|Monitor|B09BC2YNKF|c...,Premium,Monitor,HD7698A Long Range Outdoor HDTV Antenna - 65+ ...,this mile range antenna is replacing one adver...,antenna_reception_failure,True,True,True,True,False,True,True,NaN,NaN
1,Dissatisfaction|true|Upper mid|Monitor|B0C46LB...,Upper mid,Monitor,2023 Amplified HD Digital TV Antenna Long 250+...,the product came with everything however it is...,antenna_reception_failure,True,True,True,True,False,True,True,NaN,NaN
2,Dissatisfaction|true|Premium|Monitor|B0BWLZ5PM...,Premium,Monitor,[Newest 2021] Five Star Outdoor HDTV Antenna u...,this tv antenna is piece of crap have no_signa...,antenna_reception_failure,True,True,True,True,False,True,True,NaN,NaN
3,Satisfaction|true|Upper mid|Priority review|B0...,Upper mid,Priority review,TV Antenna -Amplified HD Digital Indoor TV Ant...,does_not_work miles from stations no_signal do...,antenna_reception_failure,True,True,True,True,False,True,True,NaN,NaN
4,Dissatisfaction|true|Lower mid|Priority review...,Lower mid,Priority review,"TV Antenna Amplified, HD Digital TV Antenna fo...",was not able to pick up any signal move it aro...,antenna_reception_failure,True,True,False,True,False,True,True,NaN,NaN

In [79]:
# Calculating precision results for manually validated issue buckets

precision_thresholds = {
    "charging_power_failure": 0.85,
    "connectivity_pairing_failure": 0.85,
    "storage_data_reliability": 0.85,
    "compatibility_fit_issue": 0.85,
    "physical_build_installation_failure": 0.85,
    "audio_device_failure": 0.85,
    "video_display_failure": 0.85,
    "input_control_failure": 0.85,
    "wearable_tracking_failure": 0.75,
    "antenna_reception_failure": 0.75
}

validated_df = validation_sample_df.dropna(subset = ["is_valid_match"]).copy()

validated_df["is_valid_match"] = (
    validated_df["is_valid_match"]
    .astype(str)
    .str.upper()
    .map({"TRUE": True, "FALSE": False})
)

validated_df = validated_df.dropna(subset = ["is_valid_match"]).copy()

bucket_precision_df = (
    validated_df
    .groupby("bucket_name", dropna = False)
    .agg(
        reviewed_count = ("is_valid_match", "count"),
        valid_count = ("is_valid_match", "sum")
    )
    .reset_index()
)

bucket_precision_df["precision"] = (
    bucket_precision_df["valid_count"] / bucket_precision_df["reviewed_count"]
)

bucket_precision_df["target_precision"] = bucket_precision_df["bucket_name"].map(precision_thresholds)

bucket_precision_df["passes"] = (
    bucket_precision_df["precision"] >= bucket_precision_df["target_precision"]
)

bucket_precision_df["action"] = np.where(
    bucket_precision_df["passes"],
    "Keep as final",
    "Tighten rule"
)

error_breakdown_df = (
    validated_df.loc[~validated_df["is_valid_match"]]
    .groupby(["bucket_name", "error_type"], dropna = False)
    .size()
    .reset_index(name = "error_count")
    .sort_values(["bucket_name", "error_count"], ascending = [True, False])
)

display(bucket_precision_df.sort_values(["passes", "precision"]))
display(error_breakdown_df)
display(
    validated_df.loc[
        ~validated_df["is_valid_match"],
        [
            "bucket_name",
            "product_display_name",
            "review_text",
            "error_type",
            "validation_note"
        ]
    ]
)

,bucket_name,reviewed_count,valid_count,precision,target_precision,passes,action
0,antenna_reception_failure,50,50,1.0,0.75,True,Keep as final
1,audio_device_failure,50,50,1.0,0.85,True,Keep as final
2,charging_power_failure,50,50,1.0,0.85,True,Keep as final
3,compatibility_fit_issue,50,50,1.0,0.85,True,Keep as final
4,connectivity_pairing_failure,50,50,1.0,0.85,True,Keep as final
5,input_control_failure,50,50,1.0,0.85,True,Keep as final
6,physical_build_installation_failure,50,50,1.0,0.85,True,Keep as final
7,storage_data_reliability,50,50,1.0,0.85,True,Keep as final
8,video_display_failure,50,50,1.0,0.85,True,Keep as final
9,wearable_tracking_failure,50,50,1.0,0.75,True,Keep as final

Empty DataFrame
Columns: [bucket_name, error_type, error_count]
Index: []

Empty DataFrame
Columns: [bucket_name, product_display_name, review_text, error_type, validation_note]
Index: []

In [80]:
validation_sample_df["bucket_name"].value_counts().sort_index()

bucket_name
antenna_reception_failure              50
audio_device_failure                   50
charging_power_failure                 50
compatibility_fit_issue                50
connectivity_pairing_failure           50
input_control_failure                  50
physical_build_installation_failure    50
storage_data_reliability               50
video_display_failure                  50
wearable_tracking_failure              50
Name: count, dtype: int64

In [81]:
# Creating false-negative samples to check for missed issue matches

document_bucket_threshold_audit_df = (
    review_bucket_counts_df
    .groupby(["document_id", "bucket_name"], dropna = False)
    .agg(
        matched_review_count = ("matched_review_count", "max"),
        matched_review_ratio = ("matched_review_ratio", "max")
    )
    .reset_index()
)

threshold_sensitivity_df = (
    document_bucket_threshold_audit_df
    .assign(
        passes_threshold_1 = lambda df: df["matched_review_count"] >= 1,
        passes_threshold_2 = lambda df: df["matched_review_count"] >= 2,
        passes_threshold_3 = lambda df: df["matched_review_count"] >= 3
    )
    .groupby("bucket_name", dropna = False)
    .agg(
        document_bucket_pairs_threshold_1 = ("passes_threshold_1", "sum"),
        document_bucket_pairs_threshold_2 = ("passes_threshold_2", "sum"),
        document_bucket_pairs_threshold_3 = ("passes_threshold_3", "sum")
    )
    .reset_index()
)

threshold_sensitivity_df["lost_pairs_from_threshold_2"] = (
    threshold_sensitivity_df["document_bucket_pairs_threshold_1"]
    - threshold_sensitivity_df["document_bucket_pairs_threshold_2"]
)

threshold_sensitivity_df["lost_pair_ratio_from_threshold_2"] = (
    threshold_sensitivity_df["lost_pairs_from_threshold_2"]
    / threshold_sensitivity_df["document_bucket_pairs_threshold_1"].replace(0, np.nan)
)

display(
    threshold_sensitivity_df.sort_values(
        "lost_pair_ratio_from_threshold_2",
        ascending = False
    )
)

unclassified_or_threshold_lost_documents_df = (
    document_threshold_audit_df
    .merge(
        document_match_df[["document_id", "has_any_bucket", "matched_bucket_count"]],
        on = "document_id",
        how = "left"
    )
)

unclassified_or_threshold_lost_documents_df["has_any_bucket"] = (
    unclassified_or_threshold_lost_documents_df["has_any_bucket"]
    .fillna(False)
    .astype(bool)
)

unclassified_or_threshold_lost_documents_df["had_review_level_match_but_no_bucket"] = (
    unclassified_or_threshold_lost_documents_df["has_any_review_match"]
    & ~unclassified_or_threshold_lost_documents_df["has_any_bucket"]
)

threshold_loss_by_cohort_df = (
    unclassified_or_threshold_lost_documents_df
    .groupby("cohort_role", dropna = False)
    .agg(
        document_count = ("document_id", "count"),
        unclassified_document_count = ("has_any_bucket", lambda values: (~values).sum()),
        review_match_but_no_bucket_count = ("had_review_level_match_but_no_bucket", "sum")
    )
    .reset_index()
)

threshold_loss_by_cohort_df["unclassified_document_ratio"] = (
    threshold_loss_by_cohort_df["unclassified_document_count"]
    / threshold_loss_by_cohort_df["document_count"]
)

threshold_loss_by_cohort_df["review_match_but_no_bucket_ratio"] = (
    threshold_loss_by_cohort_df["review_match_but_no_bucket_count"]
    / threshold_loss_by_cohort_df["document_count"]
)

display(threshold_loss_by_cohort_df)

false_negative_candidate_documents_df = (
    unclassified_or_threshold_lost_documents_df
    .loc[
        ~unclassified_or_threshold_lost_documents_df["has_any_bucket"],
        ["document_id", "cohort_role", "price_band", "issue_priority_level", "product_display_name"]
    ]
    .copy()
)

false_negative_review_candidates_df = (
    review_match_df
    .loc[
        review_match_df["matched_bucket_count"].eq(0),
        [
            "document_id",
            "cohort_role",
            "price_band",
            "issue_priority_level",
            "product_display_name",
            "review_text"
        ]
    ]
    .merge(
        false_negative_candidate_documents_df[["document_id"]],
        on = "document_id",
        how = "inner"
    )
    .copy()
)

false_negative_review_candidates_df["random_order"] = np.random.default_rng(42).random(
    len(false_negative_review_candidates_df)
)

false_negative_validation_sample_df = (
    false_negative_review_candidates_df
    .sort_values(["cohort_role", "price_band", "issue_priority_level", "random_order"])
    .groupby(["cohort_role", "price_band", "issue_priority_level"], group_keys = False)
    .head(20)
    .drop(columns = "random_order")
    .reset_index(drop = True)
)

false_negative_validation_sample_df["is_missed_match"] = pd.NA
false_negative_validation_sample_df["missed_bucket_name"] = ""
false_negative_validation_sample_df["validation_note"] = ""

display(false_negative_validation_sample_df)
false_negative_validation_sample_df.to_csv("false_negative_validation_sample_df.csv", index = False)

print(f"Saved CSV : false_negative_validation_sample_df.csv")

,bucket_name,document_bucket_pairs_threshold_1,document_bucket_pairs_threshold_2,document_bucket_pairs_threshold_3,lost_pairs_from_threshold_2,lost_pair_ratio_from_threshold_2
3,compatibility_fit_issue,7327,3385,2117,3942,0.538010
8,video_display_failure,4031,2004,1283,2027,0.502853
6,physical_build_installation_failure,8939,4558,3236,4381,0.490100
7,storage_data_reliability,1967,1055,779,912,0.463650
5,input_control_failure,3669,1985,1321,1684,0.458981
4,connectivity_pairing_failure,5907,3332,2215,2575,0.435923
9,wearable_tracking_failure,160,92,66,68,0.425000
2,charging_power_failure,5796,3496,2533,2300,0.396825
0,antenna_reception_failure,221,140,83,81,0.366516
1,audio_device_failure,6149,3929,2924,2220,0.361034

,cohort_role,document_count,unclassified_document_count,review_match_but_no_bucket_count,unclassified_document_ratio,review_match_but_no_bucket_ratio
0,Dissatisfaction,16853,4188,2387,0.248502,0.141637
1,Satisfaction,18360,14133,5722,0.769771,0.311656

,document_id,cohort_role,price_band,issue_priority_level,product_display_name,review_text,is_missed_match,missed_bucket_name,validation_note
0,Dissatisfaction|true|Budget|Monitor|B011BIIO9I...,Dissatisfaction,Budget,Monitor,"Replacement Earpads, Mudder 2 Pieces Foam Ear ...",have the qs2 bose quite comfort headphones and...,<NA>,,
1,Dissatisfaction|true|Budget|Monitor|B07H3V1YQ6...,Dissatisfaction,Budget,Monitor,MOSISO Silicone Keyboard Cover Protective Skin...,this mosiso black keyboard cover does not keep...,<NA>,,
2,Dissatisfaction|true|Budget|Monitor|B093SVDY5V...,Dissatisfaction,Budget,Monitor,"Ethernet Cable,VANDESAIL CAT7 Network Cable RJ...",deployed about of these cables last year and a...,<NA>,,
3,Dissatisfaction|true|Budget|Monitor|B07ZCSL46C...,Dissatisfaction,Budget,Monitor,Tobfit Bands Compatible with Fitbit Versa 2 an...,ordered two of these one pink and one gray the...,<NA>,,
4,Dissatisfaction|true|Budget|Monitor|B079SCW1X8...,Dissatisfaction,Budget,Monitor,AK Bands Compatible for Fitbit Alta/Fitbit Alt...,missing of the turquoise band how do get the o...,<NA>,,
5,Dissatisfaction|true|Budget|Monitor|B07J4Q48X8...,Dissatisfaction,Budget,Monitor,Wepro Waterproof Bands Compatible with Fitbit ...,love the color of these bands so much they are...,<NA>,,
6,Dissatisfaction|true|Budget|Monitor|B01JPEKJYI...,Dissatisfaction,Budget,Monitor,"Rankie Micro USB Cable, Nylon Braided Extremel...",these break so easily actually had one break w...,<NA>,,
7,Dissatisfaction|true|Budget|Monitor|B083JLDPDP...,Dissatisfaction,Budget,Monitor,TotalMount Monitor Stand for Headphones and He...,this is overall great product if you are able ...,<NA>,,
8,Dissatisfaction|true|Budget|Monitor|B07TF7N15C...,Dissatisfaction,Budget,Monitor,NotoCity for Garmin Forerunner 35 Band Soft Si...,this is piece of crap spent two hours trying t...,<NA>,,
9,Dissatisfaction|true|Budget|Monitor|B08N6PZR6Y...,Dissatisfaction,Budget,Monitor,JETech Wireless FM Transmitter Radio Car Kit f...,so much static does_not_work very well,<NA>,,
10,Dissatisfaction|true|Budget|Monitor|B08KY6RWNS...,Dissatisfaction,Budget,Monitor,Macally 2.4G Wireless Mouse with USB Receiver ...,it was defective and would not stay engaged de...,<NA>,,
11,Dissatisfaction|true|Budget|Monitor|B07Q585X37...,Dissatisfaction,Budget,Monitor,ASURION 3 Year Electronics Protection Plan ($2...,you buy the protection plan but you are the wr...,<NA>,,
12,Dissatisfaction|true|Budget|Monitor|B07QC4WTNC...,Dissatisfaction,Budget,Monitor,ASURION 4 Year Kitchen Protection Plan ($20 - ...,did not like that had to mail back broken glas...,<NA>,,
13,Dissatisfaction|true|Budget|Monitor|B01N74NHXW...,Dissatisfaction,Budget,Monitor,StarTech.com 6 ft Mini USB Cable - A to Mini B...,usb to mini usb no good ordered micro usb to usb,<NA>,,
14,Dissatisfaction|true|Budget|Monitor|B0C3MJZCN9...,Dissatisfaction,Budget,Monitor,16inch Single Fan Lap Chill Mat - Aluminum Pan...,this is my advise do not buy this product plus...,<NA>,,
15,Dissatisfaction|true|Budget|Monitor|B08CK26MTZ...,Dissatisfaction,Budget,Monitor,Ablus 120 Pockets Photo Album for Fujifilm Ins...,do not get it you can not put the minis in her...,<NA>,,
16,Dissatisfaction|true|Budget|Monitor|B07ZTDXZHV...,Dissatisfaction,Budget,Monitor,TOROTOP Bracelet Compatible for Fitbit Versa B...,cute but scratchy and too tight,<NA>,,
17,Dissatisfaction|true|Budget|Monitor|B07QC4WTNC...,Dissatisfaction,Budget,Monitor,ASURION 4 Year Kitchen Protection Plan ($20 - ...,am this item because the following reasons you...,<NA>,,
18,Dissatisfaction|true|Budget|Monitor|B00DQGIHNW...,Dissatisfaction,Budget,Monitor,2-Year Protection Plan plus Accident Coverage ...,my expires in weeks my kindle stopped operatin...,<NA>,,
19,Dissatisfaction|true|Budget|Monitor|B0C2Q6WMKL...,Dissatisfaction,Budget,Monitor,Geekria QuickFit Protein Leather Replacement E...,durability is woeful these lasted long haul fl...,<NA>,,
20,Dissatisfaction|true|Budget|Priority review|B0...,Dissatisfaction,Budget,Priority review,"Laptop Camera Cover Slide, [8 Pack]Ultra-Thin ...",they do not stick they kept falling off found ...,<NA>,,
21,Dissatisfaction|true|Budget|Priority review|B0...,Dissatisfaction,Budget,Priority review,Professional Cable ST35MM-06 Stereo 3.5 mm 6 F...,the item was called professional cable hahahah...,<NA>,,
22,Dissatisfaction|true|Budget|Priority review|B0...,Dissatisfaction,Budget,Priority review,Goliton Universal Silicone Keyboard Protector ...,bought this to protect the keyboard and keep t...,<NA>,,
23,Dissatisfaction|true|Budget|Priority review|B0...,Dissatisfaction,Budget,Priority review,"elago Ear Hooks Designed for AirPods Pro 2, Ai...",honestly they do not really work for me nor ma...,<NA>,,
24,Dissatisfaction|true|Budget|Priority review|B0...,Dissatisfaction,Budget,Priority review,Protected by Blink Video Security Window Decal...,poor adhesion to clean glass keep falling off ...,<NA>,,
25,Dissatisfaction|true|Budget|Priority review|B0...,Dissatisfaction,Budget,Priority review,ZWGKKYGYH Compatible with Fitbit Sense 2 Bands...,the watch band becomes disconnected from the w...,<NA>,,
26,Dissatisfaction|true|Budget|Priority review|B0...,Dissatisfaction,Budget,Priority review,Belkin Cord Concealer with Double-Sided Adhesi...,never truly unrolls could not use the adhesive...,<NA>,,
27,Dissatisfaction|true|Budget|Priority review|B0...,Dissatisfaction,Budget,Priority review,Bingfu FM Radio Antenna FM Dipole Antenna FM A...,did not help my signal at all,<NA>,,
28,Dissatisfaction|true|Budget|Priority review|B0...,Dissatisfaction,Budget,Priority review,"Amaz247 Standard IR Remote for Roku 1,2,3,4 (H...",after months unit has hard time locating my ro...,<NA>,,
29,Dissatisfaction|true|Budget|Priority review|B0...,Dissatisfaction,Budget,Priority review,ASURION 3 Year Electronics Protection Plan ($5...,received the email with the protection plan ha...,<NA>,,
30,Dissatisfaction|true|Budget|Priority review|B0...,Dissatisfaction,Budget,Priority review,Endust for Electronics; Screen & Surface Clean...,do not waste your money does not do what it ad...,<NA>,,
31,Dissatisfaction|true|Budget|Priority review|B0...,Dissatisfaction,Budget,Priority review,"GE Indoor HD Digital TV Antenna Amplifier, Low...",did not add any channels to my tv reception wa...,<NA>,,
32,Dissatisfaction|true|Budget|Priority review|B0...,Dissatisfaction,Budget,Priority review,Gvirtue Lost Remote Control Replacement Compat...,it does_not_work very well it takes several ti...,<NA>,,
33,Dissatisfaction|true|Budget|Priority review|B0...,Dissatisfaction,Budget,Priority review,"fire-Cable Plus Wireless Adapter, Powers Strea...",this product does_not_work do not buy this pro...,<NA>,,
34,Dissatisfaction|true|Budget|Priority review|B0...,Dissatisfaction,Budget,Priority review,"fire-Cable Plus Wireless Adapter, Powers Strea...",warning misleading advertising totally differe...,<NA>,,
35,Dissatisfaction|true|Budget|Priority review|B0...,Dissatisfaction,Budget,Priority review,100 Pieces Cable Clips Outdoor Light Clips Cor...,these were purchased to use for outdoor lighti...,<NA>,,
36,Dissatisfaction|true|Budget|Priority review|B0...,Dissatisfaction,Budget,Priority review,Intoval Metal Bands for Fitbit Inspire 2 / Ins...,opened on its own and lost my fitbit it is so ...,<NA>,,
37,Dissatisfaction|true|Budget|Priority review|B0...,Dissatisfaction,Budget,Priority review,"HDMI Switch, GANA 4K HDMI Splitter 3 in 1 Out,...",it lasted about weeks before it quit working u...,<NA>,,
38,Dissatisfaction|true|Budget|Priority review|B0...,Dissatisfaction,Budget,Priority review,OMAIC Replacement Remote Control Suitable for ...,it just did_not_work will try it again if can ...,<NA>,,
39,Dissatisfaction|true|Budget|Priority review|B0...,Dissatisfaction,Budget,Priority review,Goliton Universal Silicone Keyboard Protector ...,have gateway laptop and bought this for it spe...,<NA>,,
40,Dissatisfaction|true|Lower mid|Monitor|B0C6KM9...,Dissatisfaction,Lower mid,Monitor,DIUARA Wireless Earbuds V5.3 Bluetooth Headpho...,too good to be true quickly comes out of case ...,<NA>,,
41,Dissatisfaction|true|Lower mid|Monitor|B0B993N...,Dissatisfaction,Lower mid,Monitor,Julius Studio 6 x 9 ft. (72 x 108 inch) Pure W...,very flimsy and stays wrinkly very bummed abou...,<NA>,,
42,Dissatisfaction|true|Lower mid|Monitor|B0BQ2FW...,Dissatisfaction,Lower mid,Monitor,TOMSHOO Portable Folding Windproof Wood Burnin...,first of all it does work you put dry wood on ...,<NA>,,
43,Dissatisfaction|true|Lower mid|Monitor|B09JF3B...,Dissatisfaction,Lower mid,Monitor,Canon EW-63C Lens Hood For EF-S 18-55mm f/3.5-...,this lens hood not_fit the lens it was ordered...,<NA>,,
44,Dissatisfaction|true|Lower mid|Monitor|B07KTYJ...,Dissatisfaction,Lower mid,Monitor,"Amazon Smart Plug, for home automation, Works ...",after days it stopped_working,<NA>,,
45,Dissatisfaction|true|Lower mid|Monitor|B07GV5D...,Dissatisfaction,Lower mid,Monitor,WC Wicked Cushions PadZ - Thick & Soft Ear Pad...,they bring the drivers further away from your ...,<NA>,,
46,Dissatisfaction|true|Lower mid|Monitor|B08698C...,Dissatisfaction,Lower mid,Monitor,CyberPower CSP300WUR1 Professional Surge Prote...,usb ports do not work outlet spacing too narro...,<NA>,,
47,Dissatisfaction|true|Lower mid|Monitor|B07Y5WY...,Dissatisfaction,Lower mid,Monitor,bayite Bling Bands Compatible with Fitbit Vers...,could not get it to attach to my new versa so,<NA>,,
48,Dissatisfaction|true|Lower mid|Monitor|B00DTPY...,Dissatisfaction,Lower mid,Monitor,HUION 420 OSU Tablet Graphics Drawing Pen Tabl...,bad at many dimensions just ok for those who m...,<NA>,,
49,Dissatisfaction|true|Lower mid|Monitor|B0B63VL...,Dissatisfaction,Lower mid,Monitor,"ivoler Laptop Stand, Laptop Holder Riser Compu...",did not like is too small for my computer chec...,<NA>,,
50,Dissatisfaction|true|Lower mid|Monitor|B01LY8V...,Dissatisfaction,Lower mid,Monitor,"Vodeson Key Finder TV Remote Control Finder, N...",bought for my wife attached one to her phone a...,<NA>,,
51,Dissatisfaction|true|Lower mid|Monitor|B0936KY...,Dissatisfaction,Lower mid,Monitor,"Key Finder with Extra 4 Long Chains, Simjar Wi...",you have to click it like times in order to he...,<NA>,,
52,Dissatisfaction|true|Lower mid|Monitor|B07C1Q1...,Dissatisfaction,Lower mid,Monitor,Kinter MA170+ 2-Channel Auto Home Cycle Arcade...,mine as defective it was not only making far l...,<NA>,,
53,Dissatisfaction|true|Lower mid|Monitor|B0BWPL4...,Dissatisfaction,Lower mid,Monitor,Mission Darkness Non-Window Faraday Bag for Ph...,was at specific location two times in week and...,<NA>,,
54,Dissatisfaction|true|Lower mid|Monitor|B003XRE...,Dissatisfaction,Lower mid,Monitor,SanDisk Cruzer 16 GB Cruzer USB 2.0 Flash Driv...,this memory stick works good it has very good ...,<NA>,,
55,Dissatisfaction|true|Lower mid|Monitor|B0912R5...,Dissatisfaction,Lower mid,Monitor,UpNorth Sandbags - Qty of 20 - Empty Woven Pol...,these fell apart after couple of months,<NA>,,
56,Dissatisfaction|true|Lower mid|Monitor|B0BTYHL...,Dissatisfaction,Lower mid,Monitor,UbiGear 200ft Blue RJ45 CAT6 Ethernet LAN Netw...,not cat6 no marking on the jacket and will not do,<NA>,,
57,Dissatisfaction|true|Lower mid|Monitor|B00E1CR...,Dissatisfaction,Lower mid,Monitor,Amazon Basics Wireless Remote Control for Spec...,this did_not_work on my 6d save your money it is,<NA>,,
58,Dissatisfaction|true|Lower mid|Monitor|B078M32...,Dissatisfaction,Lower mid,Monitor,SAUNORCH Universal International Travel Power ...,stopped_working in months with hardly any use,<NA>,,
59,Dissatisfaction|true|Lower mid|Monitor|B078MBL...,Dissatisfaction,Lower mid,Monitor,PERLESMITH Universal Table Top TV Stand for 22...,this stand looks so awkward that it might as w...,<NA>,,
60,Dissatisfaction|true|Lower mid|Priority review...,Dissatisfaction,Lower mid,Priority review,"MYMAHDI Support TF Cards Slim 1.8"" LCD Mp3 Mp4...",the item could not get it to work the item tur...,<NA>,,
61,Dissatisfaction|true|Lower mid|Priority review...,Dissatisfaction,Lower mid,Priority review,"MYMAHDI Support TF Cards Slim 1.8"" LCD Mp3 Mp4...",it is not 4gb it has you need memory card to u...,<NA>,,
62,Dissatisfaction|true|Lower mid|Priority review...,Dissatisfaction,Lower mid,Priority review,"Vondior Portable Radio, Digital AM/FM Radio wi...",this radio will suck battery like it is high e...,<NA>,,
63,Dissatisfaction|true|Lower mid|Priority review...,Dissatisfaction,Lower mid,Priority review,915P049010 - Lamp with Housing,needed to take the lamp out and put it in the ...,<NA>,,
64,Dissatisfaction|true|Lower mid|Priority review...,Dissatisfaction,Lower mid,Priority review,KOREDA Compatible with Fitbit Charge 5 Bands S...,bought this for the large link band but the co...,<NA>,,
65,Dissatisfaction|true|Lower mid|Priority review...,Dissatisfaction,Lower mid,Priority review,"Fancii Small Personal Desk USB Fan, Portable M...",when received this fan and first plugged it in...,<NA>,,
66,Dissatisfaction|true|Lower mid|Priority review...,Dissatisfaction,Lower mid,Priority review,SANOXY Laptop Notebook Cool Pad-Portable Cooler,it did not last long at all the fans worked fi...,<NA>,,
67,Dissatisfaction|true|Lower mid|Priority review...,Dissatisfaction,Lower mid,Priority review,Emerson SmartSet Alarm Clock Radio with AM/FM ...,the display was bright white and not green it ...,<NA>,,
68,Dissatisfaction|true|Lower mid|Priority review...,Dissatisfaction,Lower mid,Priority review,COMPLY Foam Ear Tips for Apple AirPods Pro Gen...,hope can get use these ear tips for couple of ...,<NA>,,
69,Dissatisfaction|true|Lower mid|Priority review...,Dissatisfaction,Lower mid,Priority review,Magnasonic Digital AM/FM Clock Radio with Batt...,it does_not_work can not set times hard to use,<NA>,,
70,Dissatisfaction|true|Lower mid|Priority review...,Dissatisfaction,Lower mid,Priority review,Timex Alarm Clock With AM/FM Radio And 20 Stat...,this was the most difficult clock to set the d...,<NA>,,
71,Dissatisfaction|true|Lower mid|Priority review...,Dissatisfaction,Lower mid,Priority review,"PULUZ 20cm Ring Light Photo Studio Light Box, ...",this product can barely pass for dollar store ...,<NA>,,
72,Dissatisfaction|true|Lower mid|Priority review...,Dissatisfaction,Lower mid,Priority review,915P049010 - Lamp with Housing,worked great for days and then blew up the tim...,<NA>,,
73,Dissatisfaction|true|Lower mid|Priority review...,Dissatisfaction,Lower mid,Priority review,SANOXY USB 2.0 Slim External DVD ROM CD-RW Com...,it right away will only work with very old sof...,<NA>,,
74,Dissatisfaction|true|Lower mid|Priority review...,Dissatisfaction,Lower mid,Priority review,"Voice Replacement for Samsung-Smart-TV-Remote,...",we have to push every button several times bef...,<NA>,,
75,Dissatisfaction|true|Lower mid|Priority review...,Dissatisfaction,Lower mid,Priority review,"Tenergy 3V CR123A Lithium Battery, High Perfor...",went to use it in my camera and next thing kno...,<NA>,,
76,Dissatisfaction|true|Lower mid|Priority review...,Dissatisfaction,Lower mid,Priority review,"Uogic Pen for Microsoft Surface, Palm Rejectio...",this pen did_not_work at all for me followed a...,<NA>,,
77,Dissatisfaction|true|Lower mid|Priority review...,Dissatisfaction,Lower mid,Priority review,COMPLY Foam Ear Tips for Apple AirPods Pro Gen...,purchased the large version of these foam tips...,<NA>,,
78,Dissatisfaction|true|Lower mid|Priority review...,Dissatisfaction,Lower mid,Priority review,"GE 4-Way HD Digital TV Antenna Amplifier, Low ...",does not increase signal or picture_quality,<NA>,,
79,Dissatisfaction|true|Lower mid|Priority review...,Dissatisfaction,Lower mid,Priority review,COMPLY Foam Ear Tips for Sony TrueWireless WF-...,picked these up as replacement for the xm4 bud...,<NA>,,
80,Dissatisfaction|true|Premium|Monitor|B00XITFQP...,Dissatisfaction,Premium,Monitor,Bose SoundDock Portable 30-Pin iPod/iPhone Spe...,ok sound_quality one of the speakers vibrates ...,<NA>,,
81,Dissatisfaction|true|Premium|Monitor|B0BZSYPRR...,Dissatisfaction,Premium,Monitor,FULLJA WiFi Digital Picture Frame - 10.1 Inch ...,do not buy the first one bought as christmas g...,<NA>,,
82,Dissatisfaction|true|Premium|Monitor|B00AJHDZS...,Dissatisfaction,Premium,Monitor,ARRIS SURFboard SB6141 8x4 DOCSIS 3.0 Cable Mo...,all good except for one issue cannot connect w...,<NA>,,
83,Dissatisfaction|true|Premium|Monitor|B079JM45P...,Dissatisfaction,Premium,Monitor,"Garmin fenix 3 GPS Watch, Gray",bought the watch year ago right now the watch ...,<NA>,,
84,Dissatisfaction|true|Premium|Monitor|B00WUIG25...,Dissatisfaction,Premium,Monitor,Canon PowerShot D20 12.1 MP CMOS Waterproof Di...,it is been month and the camera has water insi...,<NA>,,
85,Dissatisfaction|true|Premium|Monitor|B0BTPBBL5...,Dissatisfaction,Premium,Monitor,SAMSUNG 32-inch Class LED Smart FHD TV 1080P (...,it is defect product audio out of control in w...,<NA>,,
86,Dissatisfaction|true|Premium|Monitor|B01L7UBBJ...,Dissatisfaction,Premium,Monitor,"DELL Optiplex 980 Desktop Computer, i5-650 3.2...",power supply malfunctioned had not had it long...,<NA>,,
87,Dissatisfaction|true|Premium|Monitor|B008H0QXT...,Dissatisfaction,Premium,Monitor,Sangean PR-D5 Portable Radio with Digital Tuni...,was so excited about this radio the reception ...,<NA>,,
88,Dissatisfaction|true|Premium|Monitor|B074PXS24...,Dissatisfaction,Premium,Monitor,"Apple iPad 9.7 with WiFi, 128GB- Space Gray (2...",the ipad itself looked to be in really great c...,<NA>,,
89,Dissatisfaction|true|Premium|Monitor|B07CPMG2L...,Dissatisfaction,Premium,Monitor,KEiiD CD Player for Home with Bluetooth Stereo...,instructions are very vague remote control onl...,<NA>,,
90,Dissatisfaction|true|Premium|Monitor|B07WW6CDK...,Dissatisfaction,Premium,Monitor,SiriusXM SXSD2 Portable Speaker Dock Audio Sys...,the first one we ordered did_not_work it would...,<NA>,,
91,Dissatisfaction|true|Premium|Monitor|B0BR366RV...,Dissatisfaction,Premium,Monitor,Projector Screen with Stand 100 inch Portable ...,it came with snags in it brand new not do not ...,<NA>,,
92,Dissatisfaction|true|Premium|Monitor|B00HXT8R2...,Dissatisfaction,Premium,Monitor,Ubiquiti Networks Enterprise AP Unifi,the only good thing can say about this product...,<NA>,,
93,Dissatisfaction|true|Premium|Monitor|B00GZ1GV3...,Dissatisfaction,Premium,Monitor,"Acer C720 Chromebook (11.6-Inch, 2GB & 32GB SSD)",coming from person who owns laptop the chromeb...,<NA>,,
94,Dissatisfaction|true|Premium|Monitor|B01MTJTO2...,Dissatisfaction,Premium,Monitor,"EVGA 110-BQ-0600-K1 600 BQ, 80+ Bronze 600W, S...",plugged it in and fired it up and there is sup...,<NA>,,
95,Dissatisfaction|true|Premium|Monitor|B0BJ1RG3M...,Dissatisfaction,Premium,Monitor,LEXIN LX-Q3 Motorcycle Speakers for Harley Dav...,installed these on my vrod at mph cannot here ...,<NA>,,
96,Dissatisfaction|true|Premium|Monitor|B0CDPNKNJ...,Dissatisfaction,Premium,Monitor,[Upgrade] PLZ Wireless Apple Carplay and Andro...,poorly made and looks and the phone mirror fun...,<NA>,,
97,Dissatisfaction|true|Premium|Monitor|B075GD32W...,Dissatisfaction,Premium,Monitor,Gigabyte GeForce GTX 1070 WINDFORCE OC 8G REV2...,compre este art culo hace unos meses ahora fue...,<NA>,,
98,Dissatisfaction|true|Premium|Monitor|B0C3YXPFT...,Dissatisfaction,Premium,Monitor,MSI MAG B550 TOMAHAWK Gaming Motherboard (AMD ...,have had this board for about month was not to...,<NA>,,
99,Dissatisfaction|true|Premium|Monitor|B07HZLHPK...,Dissatisfaction,Premium,Monitor,"Echo Show 5 (1st Gen, 2019 release) -- Smart d...",device does not hear properly device has the s...,<NA>,,
100,Dissatisfaction|true|Premium|Priority review|B...,Dissatisfaction,Premium,Priority review,Blink Whole Home Bundle | Video Doorbell Syste...,it immediately was catching everything had to ...,<NA>,,
101,Dissatisfaction|true|Premium|Priority review|B...,Dissatisfaction,Premium,Priority review,Lanzar 15in Car Subwoofer Speaker - Black Non-...,ran watt fosgate punch and the first speaker b...,<NA>,,

Saved CSV : false_negative_validation_sample_df.csv

#### Labeling the newly generated "false_negative_validation_sample_df", saved as "false_negative_validation_sample_df.csv". 
#### Saving the labeled version as a new file named "labeled_false_negative_validation_sample_df.csv

Labeling Logic : reviewing unbucketed reviews and marking TRUE only when the review clearly contains a missed issue theme that should have been assigned to a predefined bucket.

In [82]:
# Loading externally labeled missed-issue validation results

false_negative_validation_sample_df = pd.read_csv("labeled_false_negative_validation_sample_df.csv")

false_negative_validated_df = false_negative_validation_sample_df.dropna(
    subset = ["is_missed_match"]
).copy()

false_negative_validated_df["is_missed_match"] = (
    false_negative_validated_df["is_missed_match"]
    .astype(str)
    .str.upper()
    .map({"TRUE": True, "FALSE": False})
)

false_negative_validated_df = false_negative_validated_df.dropna(
    subset = ["is_missed_match"]
).copy()

false_negative_summary_df = (
    false_negative_validated_df
    .groupby(["cohort_role"], dropna = False)
    .agg(
        reviewed_count = ("is_missed_match", "count"),
        missed_match_count = ("is_missed_match", "sum")
    )
    .reset_index()
)

false_negative_summary_df["estimated_false_negative_rate"] = (
    false_negative_summary_df["missed_match_count"]
    / false_negative_summary_df["reviewed_count"]
)

missed_bucket_breakdown_df = (
    false_negative_validated_df
    .loc[false_negative_validated_df["is_missed_match"]]
    .groupby(["missed_bucket_name"], dropna = False)
    .size()
    .reset_index(name = "missed_count")
    .sort_values("missed_count", ascending = False)
)

display(false_negative_summary_df)
display(missed_bucket_breakdown_df)
display(
    false_negative_validated_df.loc[
        false_negative_validated_df["is_missed_match"],
        [
            "cohort_role",
            "price_band",
            "issue_priority_level",
            "product_display_name",
            "review_text",
            "missed_bucket_name",
            "validation_note"
        ]
    ]
)

,cohort_role,reviewed_count,missed_match_count,estimated_false_negative_rate
0,Dissatisfaction,180,126,0.7
1,Satisfaction,180,18,0.1

                    missed_bucket_name  missed_count
6  physical_build_installation_failure            25
1                 audio_device_failure            23
3              compatibility_fit_issue            23
2               charging_power_failure            20
4         connectivity_pairing_failure            15
8                video_display_failure            13
5                input_control_failure            11
0            antenna_reception_failure             7
7             storage_data_reliability             4
9            wearable_tracking_failure             3

,cohort_role,price_band,issue_priority_level,product_display_name,review_text,missed_bucket_name,validation_note
0,Dissatisfaction,Budget,Monitor,"Replacement Earpads, Mudder 2 Pieces Foam Ear ...",have the qs2 bose quite comfort headphones and...,physical_build_installation_failure,Earpads become dislodged and do not stay attac...
1,Dissatisfaction,Budget,Monitor,MOSISO Silicone Keyboard Cover Protective Skin...,this mosiso black keyboard cover does not keep...,physical_build_installation_failure,Keyboard cover loses shape and blocks keyboard...
3,Dissatisfaction,Budget,Monitor,Tobfit Bands Compatible with Fitbit Versa 2 an...,ordered two of these one pink and one gray the...,compatibility_fit_issue,"Fitbit band will not attach to the device, ind..."
5,Dissatisfaction,Budget,Monitor,Wepro Waterproof Bands Compatible with Fitbit ...,love the color of these bands so much they are...,physical_build_installation_failure,"Bands scuff very easily after minimal use, ind..."
6,Dissatisfaction,Budget,Monitor,"Rankie Micro USB Cable, Nylon Braided Extremel...",these break so easily actually had one break w...,physical_build_installation_failure,Charging cables break easily and leave pieces ...
7,Dissatisfaction,Budget,Monitor,TotalMount Monitor Stand for Headphones and He...,this is overall great product if you are able ...,physical_build_installation_failure,Holder/stand falls off because it does not sti...
8,Dissatisfaction,Budget,Monitor,NotoCity for Garmin Forerunner 35 Band Soft Si...,this is piece of crap spent two hours trying t...,compatibility_fit_issue,One side fits but the other side does not alig...
9,Dissatisfaction,Budget,Monitor,JETech Wireless FM Transmitter Radio Car Kit f...,so much static does_not_work very well,audio_device_failure,Review reports heavy static and poor function ...
10,Dissatisfaction,Budget,Monitor,Macally 2.4G Wireless Mouse with USB Receiver ...,it was defective and would not stay engaged de...,input_control_failure,"Mouse is defective and will not stay engaged, ..."
15,Dissatisfaction,Budget,Monitor,Ablus 120 Pockets Photo Album for Fujifilm Ins...,do not get it you can not put the minis in her...,compatibility_fit_issue,Photo sleeves only fit sideways rather than up...
16,Dissatisfaction,Budget,Monitor,TOROTOP Bracelet Compatible for Fitbit Versa B...,cute but scratchy and too tight,compatibility_fit_issue,"Band is too tight, indicating a fit issue."
19,Dissatisfaction,Budget,Monitor,Geekria QuickFit Protein Leather Replacement E...,durability is woeful these lasted long haul fl...,physical_build_installation_failure,Replacement ear pads start falling apart after...
20,Dissatisfaction,Budget,Priority review,"Laptop Camera Cover Slide, [8 Pack]Ultra-Thin ...",they do not stick they kept falling off found ...,physical_build_installation_failure,Webcam covers do not stick and keep falling of...
22,Dissatisfaction,Budget,Priority review,Goliton Universal Silicone Keyboard Protector ...,bought this to protect the keyboard and keep t...,physical_build_installation_failure,Keyboard skin keeps coming off and sticking to...
24,Dissatisfaction,Budget,Priority review,Protected by Blink Video Security Window Decal...,poor adhesion to clean glass keep falling off ...,physical_build_installation_failure,Window decals have poor adhesion and keep fall...
25,Dissatisfaction,Budget,Priority review,ZWGKKYGYH Compatible with Fitbit Sense 2 Bands...,the watch band becomes disconnected from the w...,physical_build_installation_failure,"Watch band disconnects and keeps falling off, ..."
27,Dissatisfaction,Budget,Priority review,Bingfu FM Radio Antenna FM Dipole Antenna FM A...,did not help my signal at all,antenna_reception_failure,"Antenna did not improve signal, indicating a r..."
28,Dissatisfaction,Budget,Priority review,"Amaz247 Standard IR Remote for Roku 1,2,3,4 (H...",after months unit has hard time locating my ro...,input_control_failure,Remote requires button mashing and later gives...
31,Dissatisfaction,Budget,Priority review,"GE Indoor HD Digital TV Antenna Amplifier, Low...",did not add any channels to my tv reception wa...,antenna_reception_failure,Antenna amplifier did not add channels or impr...
32,Dissatisfaction,Budget,Priority review,Gvirtue Lost Remote Control Replacement Compat...,it does_not_work very well it takes several ti...,input_control_failure,Replacement remote requires repeated attempts ...
33,Dissatisfaction,Budget,Priority review,"fire-Cable Plus Wireless Adapter, Powers Strea...",this product does_not_work do not buy this pro...,charging_power_failure,Power adapter for streaming stick does not wor...
34,Dissatisfaction,Budget,Priority review,"fire-Cable Plus Wireless Adapter, Powers Strea...",warning misleading advertising totally differe...,charging_power_failure,"Streaming-stick power cable does not work, ind..."
35,Dissatisfaction,Budget,Priority review,100 Pieces Cable Clips Outdoor Light Clips Cor...,these were purchased to use for outdoor lighti...,physical_build_installation_failure,Cable clips do not stick and are too small for...
36,Dissatisfaction,Budget,Priority review,Intoval Metal Bands for Fitbit Inspire 2 / Ins...,opened on its own and lost my fitbit it is so ...,physical_build_installation_failure,Fitbit band opened on its own and caused the d...
37,Dissatisfaction,Budget,Priority review,"HDMI Switch, GANA 4K HDMI Splitter 3 in 1 Out,...",it lasted about weeks before it quit working u...,video_display_failure,"HDMI switch quit working, indicating a video/d..."
38,Dissatisfaction,Budget,Priority review,OMAIC Replacement Remote Control Suitable for ...,it just did_not_work will try it again if can ...,input_control_failure,"Replacement remote did not work, indicating in..."
39,Dissatisfaction,Budget,Priority review,Goliton Universal Silicone Keyboard Protector ...,have gateway laptop and bought this for it spe...,physical_build_installation_failure,Keyboard protector lifts during installation a...
40,Dissatisfaction,Lower mid,Monitor,DIUARA Wireless Earbuds V5.3 Bluetooth Headpho...,too good to be true quickly comes out of case ...,charging_power_failure,Earbuds show low-battery warnings after only m...
41,Dissatisfaction,Lower mid,Monitor,Julius Studio 6 x 9 ft. (72 x 108 inch) Pure W...,very flimsy and stays wrinkly very bummed abou...,physical_build_installation_failure,"Backdrop is very flimsy and stays wrinkled, in..."
43,Dissatisfaction,Lower mid,Monitor,Canon EW-63C Lens Hood For EF-S 18-55mm f/3.5-...,this lens hood not_fit the lens it was ordered...,compatibility_fit_issue,Lens hood does not fit the intended lens and w...
44,Dissatisfaction,Lower mid,Monitor,"Amazon Smart Plug, for home automation, Works ...",after days it stopped_working,charging_power_failure,"Smart plug stopped working after a few days, i..."
45,Dissatisfaction,Lower mid,Monitor,WC Wicked Cushions PadZ - Thick & Soft Ear Pad...,they bring the drivers further away from your ...,audio_device_failure,Replacement ear pads negatively affect frequen...
46,Dissatisfaction,Lower mid,Monitor,CyberPower CSP300WUR1 Professional Surge Prote...,usb ports do not work outlet spacing too narro...,charging_power_failure,USB charging ports on the surge protector do n...
47,Dissatisfaction,Lower mid,Monitor,bayite Bling Bands Compatible with Fitbit Vers...,could not get it to attach to my new versa so,compatibility_fit_issue,"Band could not attach to the Versa, indicating..."
48,Dissatisfaction,Lower mid,Monitor,HUION 420 OSU Tablet Graphics Drawing Pen Tabl...,bad at many dimensions just ok for those who m...,input_control_failure,"Drawing tablet cursor behaves randomly, indica..."
49,Dissatisfaction,Lower mid,Monitor,"ivoler Laptop Stand, Laptop Holder Riser Compu...",did not like is too small for my computer chec...,compatibility_fit_issue,"Laptop stand is too small for the computer, in..."
52,Dissatisfaction,Lower mid,Monitor,Kinter MA170+ 2-Channel Auto Home Cycle Arcade...,mine as defective it was not only making far l...,audio_device_failure,"Amplifier produces buzz and static, indicating..."
55,Dissatisfaction,Lower mid,Monitor,UpNorth Sandbags - Qty of 20 - Empty Woven Pol...,these fell apart after couple of months,physical_build_installation_failure,"Sandbags fell apart after a couple months, ind..."
58,Dissatisfaction,Lower mid,Monitor,SAUNORCH Universal International Travel Power ...,stopped_working in months with hardly any use,charging_power_failure,Travel power adapter stopped working after lig...
60,Dissatisfaction,Lower mid,Priority review,"MYMAHDI Support TF Cards Slim 1.8"" LCD Mp3 Mp4...",the item could not get it to work the item tur...,storage_data_reliability,MP3 player/storage device is unrecognizable to...
62,Dissatisfaction,Lower mid,Priority review,"Vondior Portable Radio, Digital AM/FM Radio wi...",this radio will suck battery like it is high e...,charging_power_failure,"Radio drains batteries extremely quickly, indi..."
63,Dissatisfaction,Lower mid,Priority review,915P049010 - Lamp with Housing,needed to take the lamp out and put it in the ...,compatibility_fit_issue,"Lamp housing did not fit the TV, indicating co..."
64,Dissatisfaction,Lower mid,Priority review,KOREDA Compatible with Fitbit Charge 5 Bands S...,bought this for the large link band but the co...,physical_build_installation_failure,"Fitbit band connection is loose and pops off, ..."
65,Dissatisfaction,Lower mid,Priority review,"Fancii Small Personal Desk USB Fan, Portable M...",when received this fan and first plugged it in...,physical_build_installation_failure,Fan has loose connections and locks up repeate...
67,Dissatisfaction,Lower mid,Priority review,Emerson SmartSet Alarm Clock Radio with AM/FM ...,the display was bright white and not green it ...,video_display_failure,Clock display is incorrect/overbright and the ...
72,Dissatisfaction,Lower mid,Priority review,915P049010 - Lamp with Housing,worked great for days and then blew up the tim...,video_display_failure,TV/projector lamp worked briefly and then blew...
73,Dissatisfaction,Lower mid,Priority review,SANOXY USB 2.0 Slim External DVD ROM CD-RW Com...,it right away will only work with very old sof...,compatibility_fit_issue,External DVD drive only works with very old so...
74,Dissatisfaction,Lower mid,Priority review,"Voice Replacement for Samsung-Smart-TV-Remote,...",we have to push every button several times bef...,input_control_failure,Remote requires every button to be pushed seve...
75,Dissatisfaction,Lower mid,Priority review,"Tenergy 3V CR123A Lithium Battery, High Perfor...",went to use it in my camera and next thing kno...,charging_power_failure,"Battery was dead when used in the camera, indi..."
76,Dissatisfaction,Lower mid,Priority review,"Uogic Pen for Microsoft Surface, Palm Rejectio...",this pen did_not_work at all for me followed a...,input_control_failure,"Surface pen did not work at all, indicating in..."
77,Dissatisfaction,Lower mid,Priority review,COMPLY Foam Ear Tips for Apple AirPods Pro Gen...,purchased the large version of these foam tips...,compatibility_fit_issue,Ear tips are smaller than expected and fail th...
78,Dissatisfaction,Lower mid,Priority review,"GE 4-Way HD Digital TV Antenna Amplifier, Low ...",does not increase signal or picture_quality,antenna_reception_failure,Antenna amplifier does not improve signal or p...
79,Dissatisfaction,Lower mid,Priority review,COMPLY Foam Ear Tips for Sony TrueWireless WF-...,picked these up as replacement for the xm4 bud...,compatibility_fit_issue,Replacement ear tips are too short and fall ou...
80,Dissatisfaction,Premium,Monitor,Bose SoundDock Portable 30-Pin iPod/iPhone Spe...,ok sound_quality one of the speakers vibrates ...,audio_device_failure,Speaker vibrates as if something is loose duri...
81,Dissatisfaction,Premium,Monitor,FULLJA WiFi Digital Picture Frame - 10.1 Inch ...,do not buy the first one bought as christmas g...,video_display_failure,Digital frame screen went blank/display failed...
82,Dissatisfaction,Premium,Monitor,ARRIS SURFboard SB6141 8x4 DOCSIS 3.0 Cable Mo...,all good except for one issue cannot connect w...,connectivity_pairing_failure,Cable modem cannot connect with the Airport Ex...
83,Dissatisfaction,Premium,Monitor,"Garmin fenix 3 GPS Watch, Gray",bought the watch year ago right now the watch ...,wearable_tracking_failure,Garmin watch reports incorrect calories burned...
84,Dissatisfaction,Premium,Monitor,Canon PowerShot D20 12.1 MP CMOS Waterproof Di...,it is been month and the camera has water insi...,video_display_failure,"Camera has water inside and will not work, ind..."
85,Dissatisfaction,Premium,Monitor,SAMSUNG 32-inch Class LED Smart FHD TV 1080P (...,it is defect product audio out of control in w...,audio_device_failure,TV audio becomes out of control after a few we...
86,Dissatisfaction,Premium,Monitor,"DELL Optiplex 980 Desktop Computer, i5-650 3.2...",power supply malfunctioned had not had it long...,charging_power_failure,Computer power supply malfunctioned.
87,Dissatisfaction,Premium,Monitor,Sangean PR-D5 Portable Radio with Digital Tuni...,was so excited about this radio the reception ...,audio_device_failure,Radio speakers cut in and out and then stopped...
88,Dissatisfaction,Premium,Monitor,"Apple iPad 9.7 with WiFi, 128GB- Space Gray (2...",the ipad itself looked to be in really great c...,charging_power_failure,"iPad battery died, stopped charging, and will ..."
89,Dissatisfaction,Premium,Monitor,KEiiD CD Player for Home with Bluetooth Stereo...,instructions are very vague remote control onl...,input_control_failure,Radio remote only turns power on/off and other...
90,Dissatisfaction,Premium,Monitor,SiriusXM SXSD2 Portable Speaker Dock Audio Sys...,the first one we ordered did_not_work it would...,antenna_reception_failure,Speaker dock cannot receive signal and reports...
91,Dissatisfaction,Premium,Monitor,Projector Screen with Stand 100 inch Portable ...,it came with snags in it brand new not do not ...,physical_build_installation_failure,Projection screen arrived with snags and is le...
96,Dissatisfaction,Premium,Monitor,[Upgrade] PLZ Wireless Apple Carplay and Andro...,poorly made and looks and the phone mirror fun...,connectivity_pairing_failure,Phone mirror function works only once and then...
97,Dissatisfaction,Premium,Monitor,Gigabyte GeForce GTX 1070 WINDFORCE OC 8G REV2...,compre este art culo hace unos meses ahora fue...,video_display_failure,Graphics card is not recognized by the PC and ...
99,Dissatisfaction,Premium,Monitor,"Echo Show 5 (1st Gen, 2019 release) -- Smart d...",device does not hear properly device has the s...,audio_device_failure,"Echo device does not hear properly, indicating..."
101,Dissatisfaction,Premium,Priority review,Lanzar 15in Car Subwoofer Speaker - Black Non-...,ran watt fosgate punch and the first speaker b...,audio_device_failure,"Car subwoofer speakers blew quickly, indicatin..."
102,Dissatisfaction,Premium,Priority review,Margaritaville Tiki Torch - Waterproof Bluetoo...,one is already broken and the other does not h...,charging_power_failure,Bluetooth speaker is broken and does not hold ...
103,Dissatisfaction,Premium,Priority review,IOGEAR Wireless 3D Digital Kit with Full HD 10...,it worked once then never again,connectivity_pairing_failure,Wireless HDMI/digital kit worked once and neve...
105,Dissatisfaction,Premium,Priority review,BOSS Audio Systems BVB9351RC Car Stereo System...,do not buy it just went out had it for two wee...,audio_device_failure,"Car stereo went out after two weeks, indicatin..."
106,Dissatisfaction,Premium,Priority review,"HP Chromebook 14 Laptop, Intel Celeron N4000 P...",some times it comes on and some times it does ...,charging_power_failure,Chromebook intermittently powers on and someti...
109,Dissatisfaction,Premium,Priority review,ZOSI 5MP 8CH PoE Home Security Camera System w...,fail received the item today and spent the mor...,storage_data_reliability,"Security system reports HDD not found, prevent..."
112,Dissatisfaction,Premium,Priority review,SAMSUNG Galaxy Watch 4 Classic 46mm Smartwatch...,thought this would be the watch nope poor batt...,charging_power_failure,Smartwatch battery drains quickly and charges ...
113,Dissatisfaction,Premium,Priority review,ARRIS SURFboard SBG10 DOCSIS 3.0 16 x 4 Gigabi...,this was easy enough to install but it does no...,connectivity_pairing_failure,Modem/router does not maintain signal and will...
114,Dissatisfaction,Premium,Priority review,"Lenovo Tab M10 Plus Tablet, FHD Android Tablet...",so battery is lucky to last week just watching...,charging_power_failure,"Tablet has very poor battery life, indicating ..."
115,Dissatisfaction,Premium,Priority review,Samsung Galaxy A10e 32GB A102U GSM Unlocked Ph...,battery_life is and the charger is weak cheap ...,charging_power_failure,Phone battery life is poor and charger is weak.
116,Dissatisfaction,Premium,Priority review,BOSS Audio Systems Elite Series BV960NV GPS Ca...,this was the second one purchased in one month...,charging_power_failure,Car stereo units would not turn on.
118,Dissatisfaction,Premium,Priority review,RCA DRC6272 7-Inch Twin Mobile DVD Players - p...,bought this originally for long road trip from...,video_display_failure,"DVD players get stuck loading, make noise, and..."
119,Dissatisfaction,Premium,Priority review,Furinno JAYA Large Entertainment Stand for TV ...,received broke parts did not receive the secon...,physical_build_installation_failure,Entertainment stand arrived with broken parts.
120,Dissatisfaction,Upper mid,Monitor,XPPen Star03 V2 Drawing Tablet Graphics Drawin...,unusable gave this as gift that was not even u...,input_control_failure,Drawing tablet has tracking problems and butto...
121,Dissatisfaction,Upper mid,Monitor,Garmin GTM 25 Traffic Receiver (Discontinued b...,was miss informed the item does not with my ga...,compatibility_fit_issue,Traffic receiver does not work with the user's...
122,Dissatisfaction,Upper mid,Monitor,40GB Digital Voice Recorder for Lectures Meeti...,could not believe the sound_quality to come ou...,audio_device_failure,Voice recorder produces very poor sound quality.
123,Dissatisfaction,Upper mid,Monitor,ID-COOLING FROSTFLOW X 240 CPU Water Cooler AI...,mounting on lga one offset screw not_fit,compatibility_fit_issue,Cooler mounting screw does not fit the socket.
124,Dissatisfaction,Upper mid,Monitor,"Neewer Photo Studio Backdrop Support System, 1...",was very that the correct poles were not all o...,compatibility_fit_issue,Backdrop support includes incorrect poles that...
125,Dissatisfaction,Upper mid,Monitor,1byone Amplified HD Digital TV Antenna - Suppo...,poor_quality se pierde mucho la se al incluso ...,antenna_reception_failure,Antenna loses/distorts signal when someone pas...
128,Dissatisfaction,Upper mid,Monitor,"Kensington Orbit Trackball Mouse (K64327F), Si...",too sensitive for day to day use probably good...,input_control_failure,Trackball mouse is too sensitive for normal use.
129,Dissatisfaction,Upper mid,Monitor,Smart Watch for Men Women Fitness: (Make/Answe...,really only the time worked well,wearable_tracking_failure,Smartwatch functions mostly fail beyond basic ...
130,Dissatisfaction,Upper mid,Monitor,Sony DVPSR210P DVD Player,directions are states hdmi and is not the cabl...,video_display_failure,DVD player has cable/output mismatch and freez...
132,Dissatisfaction,Upper mid,Monitor,Cable Matters 2-Pack 6 Outlet Surge Protector ...,this strip was great until the usb ports stop ...,charging_power_failure,Power strip USB ports stopped working.
133,Dissatisfaction,Upper mid,Monitor,Dish Network 179048 Wi-Fi Adapter USB Wireless...,does not support wifi passwords of more than c...,connectivity_pairing_failure,Wi-Fi adapter does not support longer Wi-Fi pa...
134,Dissatisfaction,Upper mid,Monitor,OIWAS Messenger Bag for Women - Canvas 15.6 In...,absolutely love this bag and it fits everythin...,physical_build_installation_failure,Laptop bag stitching came apart and split at t...

In [83]:
# Comparing issue-theme exposure between dissatisfied and satisfied documents
cohort_bucket_exposure_df = (
    document_match_df
    .groupby("cohort_role", dropna = False)[bucket_names]
    .mean()
    .reset_index()
    .melt(
        id_vars = "cohort_role",
        value_vars = bucket_names,
        var_name = "bucket_name",
        value_name = "bucket_exposure_ratio"
    )
)

cohort_bucket_pivot_df = (
    cohort_bucket_exposure_df
    .pivot(
        index = "bucket_name",
        columns = "cohort_role",
        values = "bucket_exposure_ratio"
    )
    .reset_index()
)

cohort_bucket_pivot_df["dissatisfaction_lift_vs_satisfaction"] = (
    (cohort_bucket_pivot_df.get("Dissatisfaction", 0) + 1e-6) /
    (cohort_bucket_pivot_df.get("Satisfaction", 0) + 1e-6)
)

cohort_bucket_pivot_df["exposure_gap"] = (
    cohort_bucket_pivot_df.get("Dissatisfaction", 0) -
    cohort_bucket_pivot_df.get("Satisfaction", 0)
)

display(
    cohort_bucket_pivot_df.sort_values(
        ["dissatisfaction_lift_vs_satisfaction", "exposure_gap"],
        ascending = [False, False]
    )
)

cohort_role,bucket_name,Dissatisfaction,Satisfaction,dissatisfaction_lift_vs_satisfaction,exposure_gap
9,wearable_tracking_failure,0.005162,0.000272,18.890220,0.004890
2,charging_power_failure,0.189758,0.016231,11.690503,0.173528
7,storage_data_reliability,0.057022,0.005120,11.135604,0.051903
8,video_display_failure,0.099686,0.017647,5.648582,0.082038
4,connectivity_pairing_failure,0.164422,0.030556,5.380933,0.133866
3,compatibility_fit_issue,0.166499,0.031536,5.279507,0.134963
1,audio_device_failure,0.174331,0.053976,3.229744,0.120355
5,input_control_failure,0.084258,0.030773,2.737956,0.053485
6,physical_build_installation_failure,0.193200,0.070915,2.724363,0.122285
0,antenna_reception_failure,0.005815,0.002288,2.541307,0.003527

In [84]:
# Reviewing issue-theme exposure across price bands
price_band_bucket_exposure_df = (
    document_match_df
    .groupby(["cohort_role", "price_band"], dropna = False)[bucket_names]
    .mean()
    .reset_index()
    .melt(
        id_vars = ["cohort_role", "price_band"],
        value_vars = bucket_names,
        var_name = "bucket_name",
        value_name = "bucket_exposure_ratio"
    )
)

display(
    price_band_bucket_exposure_df.sort_values(
        ["cohort_role", "bucket_name", "bucket_exposure_ratio"],
        ascending = [True, True, False]
    )
)

,cohort_role,price_band,bucket_name,bucket_exposure_ratio
91,Dissatisfaction,Lower mid,antenna_reception_failure,0.007880
93,Dissatisfaction,Upper mid,antenna_reception_failure,0.007459
90,Dissatisfaction,Budget,antenna_reception_failure,0.005069
92,Dissatisfaction,Premium,antenna_reception_failure,0.003277
94,Dissatisfaction,Very premium,antenna_reception_failure,0.000000
52,Dissatisfaction,Premium,audio_device_failure,0.197979
53,Dissatisfaction,Upper mid,audio_device_failure,0.190099
51,Dissatisfaction,Lower mid,audio_device_failure,0.189116
54,Dissatisfaction,Very premium,audio_device_failure,0.161634
50,Dissatisfaction,Budget,audio_device_failure,0.123823
2,Dissatisfaction,Premium,charging_power_failure,0.200437
1,Dissatisfaction,Lower mid,charging_power_failure,0.196750
0,Dissatisfaction,Budget,charging_power_failure,0.187545
3,Dissatisfaction,Upper mid,charging_power_failure,0.182414
4,Dissatisfaction,Very premium,charging_power_failure,0.143872
30,Dissatisfaction,Budget,compatibility_fit_issue,0.268163
31,Dissatisfaction,Lower mid,compatibility_fit_issue,0.260281
33,Dissatisfaction,Upper mid,compatibility_fit_issue,0.101040
32,Dissatisfaction,Premium,compatibility_fit_issue,0.048061
34,Dissatisfaction,Very premium,compatibility_fit_issue,0.026643
12,Dissatisfaction,Premium,connectivity_pairing_failure,0.253140
13,Dissatisfaction,Upper mid,connectivity_pairing_failure,0.233499
14,Dissatisfaction,Very premium,connectivity_pairing_failure,0.172291
11,Dissatisfaction,Lower mid,connectivity_pairing_failure,0.135681
10,Dissatisfaction,Budget,connectivity_pairing_failure,0.039343
73,Dissatisfaction,Upper mid,input_control_failure,0.106691
74,Dissatisfaction,Very premium,input_control_failure,0.097691
71,Dissatisfaction,Lower mid,input_control_failure,0.076828
70,Dissatisfaction,Budget,input_control_failure,0.076515
72,Dissatisfaction,Premium,input_control_failure,0.072092
41,Dissatisfaction,Lower mid,physical_build_installation_failure,0.256587
40,Dissatisfaction,Budget,physical_build_installation_failure,0.207820
43,Dissatisfaction,Upper mid,physical_build_installation_failure,0.186709
42,Dissatisfaction,Premium,physical_build_installation_failure,0.129711
44,Dissatisfaction,Very premium,physical_build_installation_failure,0.092362
22,Dissatisfaction,Premium,storage_data_reliability,0.075915
24,Dissatisfaction,Very premium,storage_data_reliability,0.072824
23,Dissatisfaction,Upper mid,storage_data_reliability,0.054476
20,Dissatisfaction,Budget,storage_data_reliability,0.052136
21,Dissatisfaction,Lower mid,storage_data_reliability,0.045555
64,Dissatisfaction,Very premium,video_display_failure,0.312611
62,Dissatisfaction,Premium,video_display_failure,0.186783
63,Dissatisfaction,Upper mid,video_display_failure,0.081826
60,Dissatisfaction,Budget,video_display_failure,0.063481
61,Dissatisfaction,Lower mid,video_display_failure,0.048018
83,Dissatisfaction,Upper mid,wearable_tracking_failure,0.009268
82,Dissatisfaction,Premium,wearable_tracking_failure,0.009011
84,Dissatisfaction,Very premium,wearable_tracking_failure,0.005329
81,Dissatisfaction,Lower mid,wearable_tracking_failure,0.002462
80,Dissatisfaction,Budget,wearable_tracking_failure,0.000000
98,Satisfaction,Upper mid,antenna_reception_failure,0.003369
96,Satisfaction,Lower mid,antenna_reception_failure,0.002937
95,Satisfaction,Budget,antenna_reception_failure,0.001978
97,Satisfaction,Premium,antenna_reception_failure,0.001014
99,Satisfaction,Very premium,antenna_reception_failure,0.000000
57,Satisfaction,Premium,audio_device_failure,0.064369
56,Satisfaction,Lower mid,audio_device_failure,0.056936
58,Satisfaction,Upper mid,audio_device_failure,0.056012
55,Satisfaction,Budget,audio_device_failure,0.043067
59,Satisfaction,Very premium,audio_device_failure,0.033430
5,Satisfaction,Budget,charging_power_failure,0.020655
6,Satisfaction,Lower mid,charging_power_failure,0.018301
7,Satisfaction,Premium,charging_power_failure,0.014952
8,Satisfaction,Upper mid,charging_power_failure,0.013266
9,Satisfaction,Very premium,charging_power_failure,0.001453
36,Satisfaction,Lower mid,compatibility_fit_issue,0.051740
35,Satisfaction,Budget,compatibility_fit_issue,0.033619
38,Satisfaction,Upper mid,compatibility_fit_issue,0.023794
37,Satisfaction,Premium,compatibility_fit_issue,0.019767
39,Satisfaction,Very premium,compatibility_fit_issue,0.008721
17,Satisfaction,Premium,connectivity_pairing_failure,0.051191
18,Satisfaction,Upper mid,connectivity_pairing_failure,0.042325
16,Satisfaction,Lower mid,connectivity_pairing_failure,0.024401
19,Satisfaction,Very premium,connectivity_pairing_failure,0.018895
15,Satisfaction,Budget,connectivity_pairing_failure,0.008130
78,Satisfaction,Upper mid,input_control_failure,0.043588
75,Satisfaction,Budget,input_control_failure,0.027247
76,Satisfaction,Lower mid,input_control_failure,0.026435
77,Satisfaction,Premium,input_control_failure,0.025849
79,Satisfaction,Very premium,input_control_failure,0.021802
45,Satisfaction,Budget,physical_build_installation_failure,0.101736
46,Satisfaction,Lower mid,physical_build_installation_failure,0.093086
48,Satisfaction,Upper mid,physical_build_installation_failure,0.056854
47,Satisfaction,Premium,physical_build_installation_failure,0.036239
49,Satisfaction,Very premium,physical_build_installation_failure,0.020349
27,Satisfaction,Premium,storage_data_reliability,0.006082
29,Satisfaction,Very premium,storage_data_reliability,0.005814
25,Satisfaction,Budget,storage_data_reliability,0.005054
28,Satisfaction,Upper mid,storage_data_reliability,0.004843
26,Satisfaction,Lower mid,storage_data_reliability,0.004519
69,Satisfaction,Very premium,video_display_failure,0.075581
67,Satisfaction,Premium,video_display_failure,0.041561
68,Satisfaction,Upper mid,video_display_failure,0.008633
66,Satisfaction,Lower mid,video_display_failure,0.007908
65,Satisfaction,Budget,video_display_failure,0.007031
88,Satisfaction,Upper mid,wearable_tracking_failure,0.000632
87,Satisfaction,Premium,wearable_tracking_failure,0.000507
85,Satisfaction,Budget,wearable_tracking_failure,0.000000
86,Satisfaction,Lower mid,wearable_tracking_failure,0.000000
89,Satisfaction,Very premium,wearable_tracking_failure,0.000000

In [85]:
# Reviewing issue-theme exposure across product priority groups
priority_bucket_exposure_df = (
    document_match_df
    .groupby(["cohort_role", "issue_priority_level"], dropna = False)[bucket_names]
    .mean()
    .reset_index()
    .melt(
        id_vars = ["cohort_role", "issue_priority_level"],
        value_vars = bucket_names,
        var_name = "bucket_name",
        value_name = "bucket_exposure_ratio"
    )
)

display(
    priority_bucket_exposure_df.sort_values(
        ["cohort_role", "issue_priority_level", "bucket_exposure_ratio"],
        ascending = [True, True, False]
    )
)

,cohort_role,issue_priority_level,bucket_name,bucket_exposure_ratio
16,Dissatisfaction,Monitor,physical_build_installation_failure,0.209949
12,Dissatisfaction,Monitor,compatibility_fit_issue,0.179109
0,Dissatisfaction,Monitor,charging_power_failure,0.167975
20,Dissatisfaction,Monitor,audio_device_failure,0.158122
4,Dissatisfaction,Monitor,connectivity_pairing_failure,0.137136
24,Dissatisfaction,Monitor,video_display_failure,0.095883
28,Dissatisfaction,Monitor,input_control_failure,0.074656
8,Dissatisfaction,Monitor,storage_data_reliability,0.064963
36,Dissatisfaction,Monitor,antenna_reception_failure,0.003124
32,Dissatisfaction,Monitor,wearable_tracking_failure,0.002483
1,Dissatisfaction,Priority review,charging_power_failure,0.252003
5,Dissatisfaction,Priority review,connectivity_pairing_failure,0.242390
21,Dissatisfaction,Priority review,audio_device_failure,0.220645
17,Dissatisfaction,Priority review,physical_build_installation_failure,0.145342
13,Dissatisfaction,Priority review,compatibility_fit_issue,0.130465
29,Dissatisfaction,Priority review,input_control_failure,0.111696
25,Dissatisfaction,Priority review,video_display_failure,0.110552
9,Dissatisfaction,Priority review,storage_data_reliability,0.034333
37,Dissatisfaction,Priority review,antenna_reception_failure,0.013504
33,Dissatisfaction,Priority review,wearable_tracking_failure,0.012818
18,Satisfaction,Monitor,physical_build_installation_failure,0.070555
22,Satisfaction,Monitor,audio_device_failure,0.038745
14,Satisfaction,Monitor,compatibility_fit_issue,0.026521
30,Satisfaction,Monitor,input_control_failure,0.022303
6,Satisfaction,Monitor,connectivity_pairing_failure,0.018800
26,Satisfaction,Monitor,video_display_failure,0.016013
2,Satisfaction,Monitor,charging_power_failure,0.009150
10,Satisfaction,Monitor,storage_data_reliability,0.005290
38,Satisfaction,Monitor,antenna_reception_failure,0.001001
34,Satisfaction,Monitor,wearable_tracking_failure,0.000000
23,Satisfaction,Priority review,audio_device_failure,0.102722
19,Satisfaction,Priority review,physical_build_installation_failure,0.072066
7,Satisfaction,Priority review,connectivity_pairing_failure,0.068177
31,Satisfaction,Priority review,input_control_failure,0.057881
15,Satisfaction,Priority review,compatibility_fit_issue,0.047586
3,Satisfaction,Priority review,charging_power_failure,0.038893
27,Satisfaction,Priority review,video_display_failure,0.022878
39,Satisfaction,Priority review,antenna_reception_failure,0.006406
11,Satisfaction,Priority review,storage_data_reliability,0.004576
35,Satisfaction,Priority review,wearable_tracking_failure,0.001144

In [86]:
# Calculating how often issue themes appear together
cooccurrence_rows = []

for i, bucket_a in enumerate(bucket_names):
    for bucket_b in bucket_names[i + 1:]:
        both_count = (
            document_match_df[bucket_a] &
            document_match_df[bucket_b]
        ).sum()

        bucket_a_count = document_match_df[bucket_a].sum()
        bucket_b_count = document_match_df[bucket_b].sum()

        cooccurrence_rows.append({
            "bucket_a": bucket_a,
            "bucket_b": bucket_b,
            "both_document_count": both_count,
            "bucket_a_count": bucket_a_count,
            "bucket_b_count": bucket_b_count,
            "cooccurrence_ratio_with_bucket_a": both_count / bucket_a_count if bucket_a_count else 0,
            "cooccurrence_ratio_with_bucket_b": both_count / bucket_b_count if bucket_b_count else 0
        })

bucket_cooccurrence_df = pd.DataFrame(cooccurrence_rows)

display(
    bucket_cooccurrence_df.sort_values(
        "both_document_count",
        ascending = False
    )
)

,bucket_a,bucket_b,both_document_count,bucket_a_count,bucket_b_count,cooccurrence_ratio_with_bucket_a,cooccurrence_ratio_with_bucket_b
24,compatibility_fit_issue,physical_build_installation_failure,1496,3385,4558,0.441950,0.328214
12,connectivity_pairing_failure,audio_device_failure,1138,3332,3929,0.341537,0.289641
4,charging_power_failure,audio_device_failure,896,3496,3929,0.256293,0.228048
0,charging_power_failure,connectivity_pairing_failure,885,3496,3332,0.253146,0.265606
2,charging_power_failure,compatibility_fit_issue,460,3496,3385,0.131579,0.135894
14,connectivity_pairing_failure,input_control_failure,419,3332,1985,0.125750,0.211083
30,physical_build_installation_failure,audio_device_failure,361,4558,3929,0.079201,0.091881
25,compatibility_fit_issue,audio_device_failure,326,3385,3929,0.096307,0.082973
3,charging_power_failure,physical_build_installation_failure,317,3496,4558,0.090675,0.069548
10,connectivity_pairing_failure,compatibility_fit_issue,275,3332,3385,0.082533,0.081241
26,compatibility_fit_issue,video_display_failure,251,3385,2004,0.074151,0.125250
11,connectivity_pairing_failure,physical_build_installation_failure,233,3332,4558,0.069928,0.051119
6,charging_power_failure,input_control_failure,228,3496,1985,0.065217,0.114861
13,connectivity_pairing_failure,video_display_failure,225,3332,2004,0.067527,0.112275
31,physical_build_installation_failure,video_display_failure,221,4558,2004,0.048486,0.110279
5,charging_power_failure,video_display_failure,204,3496,2004,0.058352,0.101796
39,video_display_failure,input_control_failure,168,2004,1985,0.083832,0.084635
35,audio_device_failure,video_display_failure,158,3929,2004,0.040214,0.078842
27,compatibility_fit_issue,input_control_failure,153,3385,1985,0.045199,0.077078
17,storage_data_reliability,compatibility_fit_issue,139,1055,3385,0.131754,0.041064
32,physical_build_installation_failure,input_control_failure,131,4558,1985,0.028741,0.065995
36,audio_device_failure,input_control_failure,78,3929,1985,0.019852,0.039295
18,storage_data_reliability,physical_build_installation_failure,68,1055,4558,0.064455,0.014919
7,charging_power_failure,wearable_tracking_failure,48,3496,92,0.013730,0.521739
20,storage_data_reliability,video_display_failure,43,1055,2004,0.040758,0.021457
1,charging_power_failure,storage_data_reliability,36,3496,1055,0.010297,0.034123
9,connectivity_pairing_failure,storage_data_reliability,28,3332,1055,0.008403,0.026540
21,storage_data_reliability,input_control_failure,21,1055,1985,0.019905,0.010579
34,physical_build_installation_failure,antenna_reception_failure,17,4558,140,0.003730,0.121429
19,storage_data_reliability,audio_device_failure,11,1055,3929,0.010427,0.002800
15,connectivity_pairing_failure,wearable_tracking_failure,10,3332,92,0.003001,0.108696
40,video_display_failure,wearable_tracking_failure,5,2004,92,0.002495,0.054348
41,video_display_failure,antenna_reception_failure,0,2004,140,0.000000,0.000000
37,audio_device_failure,wearable_tracking_failure,0,3929,92,0.000000,0.000000
42,input_control_failure,wearable_tracking_failure,0,1985,92,0.000000,0.000000
43,input_control_failure,antenna_reception_failure,0,1985,140,0.000000,0.000000
38,audio_device_failure,antenna_reception_failure,0,3929,140,0.000000,0.000000
22,storage_data_reliability,wearable_tracking_failure,0,1055,92,0.000000,0.000000
33,physical_build_installation_failure,wearable_tracking_failure,0,4558,92,0.000000,0.000000
29,compatibility_fit_issue,antenna_reception_failure,0,3385,140,0.000000,0.000000
28,compatibility_fit_issue,wearable_tracking_failure,0,3385,92,0.000000,0.000000
23,storage_data_reliability,antenna_reception_failure,0,1055,140,0.000000,0.000000
16,connectivity_pairing_failure,antenna_reception_failure,0,3332,140,0.000000,0.000000
8,charging_power_failure,antenna_reception_failure,0,3496,140,0.000000,0.000000
44,wearable_tracking_failure,antenna_reception_failure,0,92,140,0.000000,0.000000

In [87]:
# Identifying top Electronics products linked to each issue theme
product_bucket_risk_df = (
    document_match_df
    .melt(
        id_vars = [
            "document_id",
            "cohort_role",
            "price_band",
            "issue_priority_level",
            "product_display_name"
        ],
        value_vars = bucket_names,
        var_name = "bucket_name",
        value_name = "has_bucket"
    )
    .loc[lambda df: df["has_bucket"]]
    .copy()
)

top_products_by_bucket_df = (
    product_bucket_risk_df
    .groupby(
        ["bucket_name", "product_display_name", "price_band", "issue_priority_level"],
        dropna = False
    )
    .size()
    .reset_index(name = "document_count")
    .sort_values(["bucket_name", "document_count"], ascending = [True, False])
    .groupby("bucket_name", group_keys = False)
    .head(20)
    .reset_index(drop = True)

)

display(top_products_by_bucket_df)

,bucket_name,product_display_name,price_band,issue_priority_level,document_count
0,antenna_reception_failure,Mediasonic Homeworx HW110AN Super Thin Indoor ...,Budget,Priority review,8
1,antenna_reception_failure,"Vansky TV Antenna Indoor, Digital Amplified In...",Lower mid,Priority review,7
2,antenna_reception_failure,"Mohu Leaf 50 Amplified Indoor TV Antenna, 60-M...",Upper mid,Priority review,5
3,antenna_reception_failure,"Winegard LNA-200 Boost XT HDTV Preamplifier, T...",Upper mid,Priority review,5
4,antenna_reception_failure,2023 Amplified HD Digital TV Antenna Long 250+...,Upper mid,Monitor,4
5,antenna_reception_failure,CravenSpeed Stubby Antenna Compatible with Toy...,Lower mid,Priority review,4
6,antenna_reception_failure,RCA ANT1650F Flat Digital Amplified Indoor TV ...,Upper mid,Priority review,3
7,antenna_reception_failure,RCA Compact Outdoor or Attic Yagi TV Antenna –...,Upper mid,Monitor,3
8,antenna_reception_failure,24db Distribution Amplifier | Digital TV Anten...,Upper mid,Priority review,2
9,antenna_reception_failure,BOSS Audio Systems MRANT12W Marine Rubber Ante...,Budget,Priority review,2
10,antenna_reception_failure,Bose Wave FM Antenna,Lower mid,Priority review,2
11,antenna_reception_failure,Channel Master CM-7777HD Amplify Adjustable Ga...,Premium,Monitor,2
12,antenna_reception_failure,Chaowei Digital HDTV Antenna with Magnetic Bas...,Lower mid,Monitor,2
13,antenna_reception_failure,Clearstream View Wall Frame Amplified Indoor H...,Upper mid,Priority review,2
14,antenna_reception_failure,Five Star [Newest 2020] HDTV Antenna - 360° Om...,Premium,Priority review,2
15,antenna_reception_failure,"GE Attic Mount HD Digital TV Antenna, Longe Ra...",Upper mid,Monitor,2
16,antenna_reception_failure,"GE Outdoor HD Digital TV Antenna, Long Range S...",Upper mid,Monitor,2
17,antenna_reception_failure,"GE Pro Outdoor Antenna Amplifier, Low Noise A...",Lower mid,Priority review,2
18,antenna_reception_failure,HD Digital TV Antenna Small Indoor Outdoor Ant...,Lower mid,Priority review,2
19,antenna_reception_failure,"Philips LTE Filter for TV Antenna, Filters 4G ...",Budget,Priority review,2
20,audio_device_failure,TOZO T10 Bluetooth 5.3 Wireless Earbuds with W...,Lower mid,Monitor,44
21,audio_device_failure,"Panasonic ErgoFit Wired Earbuds, In-Ear Headph...",Budget,Monitor,37
22,audio_device_failure,"Senso Bluetooth Headphones, Best Wireless Spor...",Lower mid,Monitor,25
23,audio_device_failure,TOZO T6 True Wireless Earbuds Bluetooth 5.3 He...,Upper mid,Monitor,25
24,audio_device_failure,"OontZ Angle 3 Bluetooth Speaker, Portable Wire...",Lower mid,Monitor,20
25,audio_device_failure,Logitech G Wireless Gaming Headset G930 with 7...,Premium,Priority review,15
26,audio_device_failure,Apple AirPods (2nd Generation) Wireless Earbud...,Premium,Monitor,14
27,audio_device_failure,"Jabra Elite 65t Earbuds – Alexa Built-in, True...",Premium,Priority review,14
28,audio_device_failure,"iJoy Bluetooth Headphones Over Ear, Wireless a...",Lower mid,Monitor,14
29,audio_device_failure,Beats Studio Buds – True Wireless Noise Cancel...,Premium,Priority review,13
30,audio_device_failure,Beats Powerbeats Pro Wireless Earbuds - Apple ...,Premium,Priority review,12
31,audio_device_failure,"DOSS Bluetooth Speaker, SoundBox Touch Portabl...",Upper mid,Monitor,11
32,audio_device_failure,Skullcandy Sesh Evo True Wireless In-Ear Bluet...,Lower mid,Priority review,11
33,audio_device_failure,Turtle Beach Stealth 600 Gen 2 Wireless Gaming...,Premium,Priority review,11
34,audio_device_failure,"ZIHNIC Bluetooth Headphones Over-Ear, Foldable...",Upper mid,Priority review,11
35,audio_device_failure,Anker Soundcore Bluetooth Speaker with 24-Hour...,Upper mid,Monitor,10
36,audio_device_failure,Echo Dot (2nd Generation) - Smart speaker with...,Upper mid,Monitor,10
37,audio_device_failure,Jaybird Bluebuds X Bluetooth Headphones - Whit...,Upper mid,Priority review,10
38,audio_device_failure,Nulaxy Bluetooth Car FM Transmitter Audio Adap...,Lower mid,Monitor,10
39,audio_device_failure,"Otium Bluetooth Headphones, Wireless Headphone...",Lower mid,Monitor,10
40,charging_power_failure,TOZO T10 Bluetooth 5.3 Wireless Earbuds with W...,Lower mid,Monitor,29
41,charging_power_failure,"OontZ Angle 3 Bluetooth Speaker, Portable Wire...",Lower mid,Monitor,20
42,charging_power_failure,"[Apple MFi Certified] iPhone Charger, YUNSONG ...",Budget,Priority review,18
43,charging_power_failure,Kindle Paperwhite – (previous generation - 201...,Premium,Monitor,17
44,charging_power_failure,"Senso Bluetooth Headphones, Best Wireless Spor...",Lower mid,Monitor,14
45,charging_power_failure,TOZO T6 True Wireless Earbuds Bluetooth 5.3 He...,Upper mid,Monitor,14
46,charging_power_failure,Apple AirPods (2nd Generation) Wireless Earbud...,Premium,Monitor,13
47,charging_power_failure,Skullcandy Sesh Evo True Wireless In-Ear Bluet...,Lower mid,Priority review,10
48,charging_power_failure,Soundbot SB510 Bluetooth Shower Speaker HD Wat...,Lower mid,Monitor,10
49,charging_power_failure,"Amazon Fire HD 8 tablet, 8"" HD display, 64 GB,...",Premium,Monitor,9
50,charging_power_failure,Beats Powerbeats Pro Wireless Earbuds - Apple ...,Premium,Priority review,9
51,charging_power_failure,"Fitbit Charge Wireless Activity Wristband, Bla...",Premium,Priority review,9
52,charging_power_failure,Long iPhone Charger Cable 10 Ft Lightning Appl...,Budget,Priority review,9
53,charging_power_failure,"TECKNET Wireless Mouse, 2.4G Ergonomic Optical...",Budget,Monitor,9
54,charging_power_failure,Turtle Beach Stealth 600 Gen 2 Wireless Gaming...,Premium,Priority review,9
55,charging_power_failure,APFEN [3-Pack] 6FT/2M iPhone Gaming Charger Ca...,Budget,Priority review,8
56,charging_power_failure,Apple MagSafe Charger - Wireless Charger with ...,Upper mid,Priority review,8
57,charging_power_failure,JSAUX USB-C to USB A Cable 3.1A Fast Charging ...,Budget,Monitor,8
58,charging_power_failure,"Uiosmuph LED Wireless Mouse, G12 Slim Recharge...",Budget,Priority review,8
59,charging_power_failure,occiam Wireless Earbuds Bluetooth Headphones 4...,Lower mid,Monitor,8
60,compatibility_fit_issue,TOZO T10 Bluetooth 5.3 Wireless Earbuds with W...,Lower mid,Monitor,25
61,compatibility_fit_issue,MOSISO Compatible with MacBook Air 13 inch Cas...,Lower mid,Priority review,11
62,compatibility_fit_issue,MOSISO Compatible with MacBook Air 13 inch Cas...,Lower mid,Priority review,10
63,compatibility_fit_issue,MOSISO Compatible with MacBook Pro 13 inch Cas...,Lower mid,Priority review,9
64,compatibility_fit_issue,SAMSUNG Galaxy Buds Live True Wireless Bluetoo...,Premium,Priority review,9
65,compatibility_fit_issue,TOZO T12 Wireless Earbuds Bluetooth Headphones...,Upper mid,Monitor,9
66,compatibility_fit_issue,Apple Lightning to 3.5 mm Headphone Jack Adapter,Budget,Monitor,8
67,compatibility_fit_issue,"Jabra Elite 65t Earbuds – Alexa Built-in, True...",Premium,Priority review,8
68,compatibility_fit_issue,MOSISO Compatible with MacBook Air 13 inch Cas...,Lower mid,Monitor,8
69,compatibility_fit_issue,"SANOXY 9.7"" Tablet Stand with USB Keyboard - B...",Lower mid,Priority review,8
70,compatibility_fit_issue,TOZO T6 True Wireless Earbuds Bluetooth 5.3 He...,Upper mid,Monitor,8
71,compatibility_fit_issue,"Amazon Basics 11.6-Inch Laptop Sleeve, Protect...",Budget,Monitor,7
72,compatibility_fit_issue,JSAUX USB-C to USB A Cable 3.1A Fast Charging ...,Budget,Monitor,7
73,compatibility_fit_issue,IBENZER Compatible with New MacBook Air 13 inc...,Lower mid,Priority review,6
74,compatibility_fit_issue,JETech Case Compatible with iPad 2 3 4 (Old Mo...,Lower mid,Monitor,6
75,compatibility_fit_issue,TOZO A1 Mini Wireless Earbuds Bluetooth 5.3 in...,Lower mid,Monitor,6
76,compatibility_fit_issue,Amazon Basics 4 Port USB to USB 3.0 Hub with 5...,Lower mid,Monitor,5
77,compatibility_fit_issue,"BRG Compatible with Airpods Pro Case,Soft Sili...",Budget,Monitor,5
78,compatibility_fit_issue,IBENZER Compatible with 2022 M2 MacBook Pro 13...,Lower mid,Priority review,5
79,compatibility_fit_issue,Lifeproof FRĒ SERIES iPhone 6/6s Waterproof Ca...,Upper mid,Priority review,5
80,connectivity_pairing_failure,TOZO T10 Bluetooth 5.3 Wireless Earbuds with W...,Lower mid,Monitor,42
81,connectivity_pairing_failure,Echo Dot (2nd Generation) - Smart speaker with...,Upper mid,Monitor,26
82,connectivity_pairing_failure,TOZO T6 True Wireless Earbuds Bluetooth 5.3 He...,Upper mid,Monitor,23
83,connectivity_pairing_failure,Echo Auto (1st gen) - Hands-free Alexa in your...,Upper mid,Priority review,22
84,connectivity_pairing_failure,TP-Link N300 WiFi Extender(TL-WA855RE)-WiFi Ra...,Budget,Priority review,19
85,connectivity_pairing_failure,"OontZ Angle 3 Bluetooth Speaker, Portable Wire...",Lower mid,Monitor,17
86,connectivity_pairing_failure,"Senso Bluetooth Headphones, Best Wireless Spor...",Lower mid,Monitor,17
87,connectivity_pairing_failure,NETGEAR Wi-Fi Range Extender EX3700 - Coverage...,Upper mid,Priority review,15
88,connectivity_pairing_failure,"TP-Link AC1200 WiFi Range Extender (RE330), Co...",Upper mid,Priority review,14
89,connectivity_pairing_failure,Apple AirPods (2nd Generation) Wireless Earbud...,Premium,Monitor,13
90,connectivity_pairing_failure,"Jabra Elite 65t Earbuds – Alexa Built-in, True...",Premium,Priority review,13
91,connectivity_pairing_failure,Logitech G Wireless Gaming Headset G930 with 7...,Premium,Priority review,13
92,connectivity_pairing_failure,TP-Link N300 Wi-Fi Range Extender (TL-WA850RE),Lower mid,Priority review,13
93,connectivity_pairing_failure,"NETGEAR Nighthawk Smart Wi-Fi Router, R6700 - ...",Premium,Monitor,12
94,connectivity_pairing_failure,NETGEAR Wi-Fi Range Extender EX2700 - Coverage...,Upper mid,Monitor,12
95,connectivity_pairing_failure,Beats Powerbeats Pro Wireless Earbuds - Apple ...,Premium,Priority review,11
96,connectivity_pairing_failure,Beats Studio Buds – True Wireless Noise Cancel...,Premium,Priority review,11
97,connectivity_pairing_failure,Blink Whole Home Bundle | Video Doorbell Syste...,Premium,Priority review,11
98,connectivity_pairing_failure,"iJoy Bluetooth Headphones Over Ear, Wireless a...",Lower mid,Monitor,11
99,connectivity_pairing_failure,"Amazon Smart Plug, for home automation, Works ...",Lower mid,Monitor,10
100,input_control_failure,Amazon Fire TV with 4K Ultra HD,Upper mid,Monitor,16
101,input_control_failure,Fire TV Stick (3rd Gen) with Alexa Voice Remot...,Upper mid,Monitor,16
102,input_control_failure,Logitech MK270 Wireless Keyboard And Mouse Com...,Lower mid,Priority review,15
103,input_control_failure,"Uiosmuph LED Wireless Mouse, G12 Slim Recharge...",Budget,Priority review,13
104,input_control_failure,"seenda Wireless Mouse, 2.4G Noiseless Mouse wi...",Budget,Monitor,12
105,input_control_failure,Anker 2.4G Wireless Vertical Ergonomic Optical...,Lower mid,Monitor,11
106,input_control_failure,Fire TV Stick with Voice Remote,Upper mid,Monitor,11
107,input_control_failure,"TECKNET Wireless Mouse, 2.4G Ergonomic Optical...",Budget,Monitor,11
108,input_control_failure,"【Upgrade】 LED Wireless Mouse, Rechargeable Sli...",Lower mid,Priority review,11
109,input_control_failure,Logitech M570 Wireless Trackball Mouse – Ergon...,Upper mid,Monitor,10
110,input_control_failure,"TECKNET Bluetooth Wireless Mouse, Computer Mou...",Budget,Priority review,10
111,input_control_failure,Logitech MK345 Wireless Combo Full-Sized Keybo...,Upper mid,Priority review,9
112,input_control_failure,Fire TV Gaming Bundle with Fire TV Stick 4K Ma...,Premium,Monitor,8
113,input_control_failure,Logitech M510 Wireless Computer Mouse – Comfor...,Lower mid,Monitor,8
114,input_control_failure,Logitech MK550 Wireless Wave Keyboard and Mous...,Upper mid,Monitor,8
115,input_control_failure,"TP-Link USB Bluetooth Adapter for PC(UB400), 4...",Budget,Priority review,8
116,input_control_failure,"Wireless Keyboard and Mouse,J JOYACCESS 2.4G E...",Upper mid,Priority review,8
117,input_control_failure,"Fire TV Stick 4K, brilliant 4K streaming quali...",Upper mid,Monitor,7
118,input_control_failure,"Fire TV Stick Lite, free and live TV, Alexa Vo...",Lower mid,Monitor,7
119,input_control_failure,KLO Bluetooth Mouse for MacBook/MacBook air/Pr...,Lower mid,Priority review,7
120,physical_build_installation_failure,Lifeproof FRĒ SERIES iPhone 6/6s Waterproof Ca...,Upper mid,Priority review,13
121,physical_build_installation_failure,MOSISO Compatible with MacBook Air 13 inch Cas...,Lower mid,Priority review,12
122,physical_build_installation_failure,MOSISO Compatible with MacBook Pro 13 inch Cas...,Lower mid,Priority review,11
123,physical_build_installation_failure,VideoSecu ML531BE2 TV Wall Mount kit with Free...,Lower mid,Monitor,10
124,physical_build_installation_failure,MOSISO Compatible with MacBook Air 13 inch Cas...,Lower mid,Priority review,9
125,physical_build_installation_failure,"SanDisk 8GB Clip Jam MP3 Player, Blue - microS...",Upper mid,Priority review,9
126,physical_build_installation_failure,"BRG Compatible with Airpods Pro Case,Soft Sili...",Budget,Monitor,8
127,physical_build_installation_failure,"Blink Video Doorbell | Two-way audio, HD video...",Upper mid,Priority review,8
128,physical_build_installation_failure,MOSISO Compatible with MacBook Air 13 inch Cas...,Lower mid,Monitor,8
129,physical_build_installation_failure,SPARIN Screen Protector Compatible with iPad 6...,Budget,Monitor,8
130,physical_build_installation_failure,Amazon Basics 50-inch Lightweight Camera Mount...,Lower mid,Monitor,7
131,physical_build_installation_failure,"JETech Screen Protector for iPad (10.2-Inch, 2...",Budget,Monitor,7
132,physical_build_installation_failure,"Lamicall Gooseneck Tablet Holder, Tablet Mount...",Upper mid,Monitor,7
133,physical_build_installation_failure,AKASO EK7000 4K30FPS 20MP Action Camera Ultra ...,Premium,Monitor,6
134,physical_build_installation_failure,IBENZER Compatible with 2022 2021 2020 MacBook...,Lower mid,Priority review,6
135,physical_build_installation_failure,IBENZER Compatible with New MacBook Air 13 inc...,Lower mid,Priority review,6
136,physical_build_installation_failure,JETech Case Compatible with iPad 2 3 4 (Old Mo...,Lower mid,Monitor,6
137,physical_build_installation_failure,OtterBox iPhone 6 / 6s Defender Series Case - ...,Upper mid,Monitor,6
138,physical_build_installation_failure,"R-fun AirPods Pro Case Cover with Keychain, Fu...",Budget,Priority review,6
139,physical_build_installation_failure,"VIVO Dual Monitor Desk Mount, Heavy Duty Fully...",Upper mid,Monitor,6
140,storage_data_reliability,Seagate Expansion 16TB External Hard Drive HDD...,Premium,Monitor,13
141,storage_data_reliability,Seagate Backup Plus Portable 5TB External Hard...,Very premium,Monitor,11
142,storage_data_reliability,SanDisk Ultra 32GB microSDHC UHS-I Card with A...,Budget,Monitor,10
143,storage_data_reliability,"PNY 128GB Turbo Attache 3 USB 3.0 Flash Drive,...",Budget,Monitor,9
144,storage_data_reliability,SanDisk Ultra 64GB MicroSDXC Class 10 UHS Memo...,Budget,Monitor,9
145,storage_data_reliability,"WD 2TB Elements Portable HDD, External Hard Dr...",Upper mid,Monitor,9
146,storage_data_reliability,Samsung EVO 64GB 48/MB/s Micro SDXC Memory Car...,Upper mid,Monitor,8
147,storage_data_reliability,External DVD Drive USB 3.0 TYPE C Portable CD/...,Upper mid,Priority review,6
148,storage_data_reliability,Made for Amazon SanDisk 64GB microSD Memory Ca...,Budget,Monitor,6
149,storage_data_reliability,Seagate Expansion Portable 2TB External Hard D...,Premium,Monitor,6
150,storage_data_reliability,(Old Model) Seagate 1TB Desktop HDD Sata 6Gb/s...,Upper mid,Monitor,5
151,storage_data_reliability,(Old Model) WD My Passport Ultra 500 GB Portab...,Upper mid,Monitor,5
152,storage_data_reliability,External CD/DVD Drive for Laptop USB 3.0 CD/DV...,Lower mid,Monitor,5
153,storage_data_reliability,SanDisk 32GB 2-Pack Ultra MicroSDHC UHS-I Memo...,Budget,Monitor,5
154,storage_data_reliability,SanDisk Ultra 16GB Class 10 SDHC UHS-I Memory ...,Budget,Monitor,5
155,storage_data_reliability,SanDisk Ultra 32GB UHS-I/Class 10 Micro SDHC M...,Budget,Monitor,5
156,storage_data_reliability,Seagate BarraCuda 4TB Internal Hard Drive HDD ...,Premium,Monitor,5
157,storage_data_reliability,"Anker 2-in-1 USB 3.0 SD Card Reader for SDXC, ...",Budget,Monitor,4
158,storage_data_reliability,SABRENT 10 Port 60W USB 3.0 Hub with Individua...,Upper mid,Monitor,4
159,storage_data_reliability,SABRENT 2.5 Inch SATA to USB 3.0 Tool Free Cle...,Budget,Monitor,4
160,video_display_failure,Blink Whole Home Bundle | Video Doorbell Syste...,Premium,Priority review,18
161,video_display_failure,Blink Mini – Compact indoor plug-in smart secu...,Premium,Priority review,12
162,video_display_failure,Echo Show - 1st Generation Black,Upper mid,Monitor,10
163,video_display_failure,"Fosmon 3-Port HDMI Switcher, Intelligent 3x1 A...",Budget,Priority review,9
164,video_display_failure,"AOC I1601FWUX 15.6"" USB-C powered portable mon...",Premium,Priority review,6
165,video_display_failure,Amazon Fire TV with 4K Ultra HD,Upper mid,Monitor,6
166,video_display_failure,AKASO EK7000 4K30FPS 20MP Action Camera Ultra ...,Premium,Monitor,5
167,video_display_failure,"Amazon Basics HDMI Cable, 18Gbps High-Speed, 4...",Budget,Monitor,5
168,video_display_failure,"Blink Video Doorbell | Two-way audio, HD video...",Upper mid,Priority review,5
169,video_display_failure,Blink XT2 Outdoor/Indoor Smart Security Camera...,Premium,Priority review,5
170,video_display_failure,"Echo Show 5 (1st Gen, 2019 release) -- Smart d...",Premium,Monitor,5
171,video_display_failure,Fire TV Stick (3rd Gen) with Alexa Voice Remot...,Upper mid,Monitor,5
172,video_display_failure,KODAK Printomatic Digital Instant Print Camera...,Upper mid,Priority review,5
173,video_display_failure,Kindle Paperwhite – (previous generation - 201...,Premium,Monitor,5
174,video_display_failure,Lepow Portable Monitor - 2023 C2 15.6 inch FHD...,Premium,Monitor,5
175,video_display_failure,Ring Video Doorbell - Venetian Bronze with Rin...,Premium,Priority review,5
176,video_display_failure,"Ring Video Doorbell Pro – Upgraded, with added...",Premium,Monitor,5
177,video_display_failure,Sceptre E249W-19203R 24-inch FHD LED Gaming Mo...,Premium,Monitor,5
178,video_display_failure,"ABLEWE USB to HDMI Adapter, USB 3.0/2.0 to HDM...",Budget,Priority review,4
179,video_display_failure,"Acer R241Y Bbix 23.8"" Full HD (1920 x 1080) IP...",Premium,Monitor,4
180,wearable_tracking_failure,Fitbit Sense Advanced Smartwatch with Tools fo...,Premium,Priority review,5
181,wearable_tracking_failure,"Fitbit Charge Wireless Activity Wristband, Bla...",Premium,Priority review,4
182,wearable_tracking_failure,CanMixs Smart Watch for Android Phones iOS Wat...,Upper mid,Priority review,3
183,wearable_tracking_failure,"Garmin 010-01769-01 Vivoactive 3, GPS Smartwat...",Premium,Priority review,3
184,wearable_tracking_failure,"KALINCO Smart Watch, Fitness Tracker with Hear...",Lower mid,Priority review,3
185,wearable_tracking_failure,"Popglory Smart Watch, Smartwatch with Blood Pr...",Lower mid,Priority review,3
186,wearable_tracking_failure,"Samsung Gear Fit Smart Watch, Black (US Version)",Upper mid,Priority review,3
187,wearable_tracking_failure,"AGPTEK Smart Watch for Women, Smartwatch for A...",Upper mid,Priority review,2
188,wearable_tracking_failure,Amazfit Bip U Pro Smart Watch with Alexa Built...,Upper mid,Priority review,2
189,wearable_tracking_failure,"Garmin vívofit 2 Activity Tracker, White",Premium,Monitor,2
190,wearable_tracking_failure,"Motast Smart Watch 2022 Watches for Women, Fit...",Upper mid,Priority review,2
191,wearable_tracking_failure,"1.7'' Phone Smart Watch Answer/Make Calls, Fit...",Upper mid,Monitor,1
192,wearable_tracking_failure,"A-TGTGA Smart Watches for Men,SmartWatch with ...",Upper mid,Priority review,1
193,wearable_tracking_failure,"AGPTEK Smart Watch, 1.69""(43mm) Smartwatch for...",Upper mid,Priority review,1
194,wearable_tracking_failure,"AMAZTIM Smart Watch, 60 Days Extra-Long Batter...",Premium,Monitor,1

In [88]:
# Combining issue-theme metrics into a business insight summary
business_insight_summary_df = (
    cohort_bucket_pivot_df
    .merge(
        bucket_summary_df[
            [
                "bucket_name",
                "dissatisfaction_document_count",
                "satisfaction_document_count",
                "dissatisfaction_ratio",
                "satisfaction_ratio",
                "lift_vs_satisfaction",
                "ratio_gap"
            ]
        ],
        on = "bucket_name",
        how = "left"
    )
    .sort_values(["lift_vs_satisfaction", "ratio_gap"], ascending = [False, False])
)

display(business_insight_summary_df)

,bucket_name,Dissatisfaction,Satisfaction,dissatisfaction_lift_vs_satisfaction,exposure_gap,dissatisfaction_document_count,satisfaction_document_count,dissatisfaction_ratio,satisfaction_ratio,lift_vs_satisfaction,ratio_gap
9,wearable_tracking_failure,0.005162,0.000272,18.890220,0.004890,87,5,0.005162,0.000272,18.890220,0.004890
2,charging_power_failure,0.189758,0.016231,11.690503,0.173528,3198,298,0.189758,0.016231,11.690503,0.173528
7,storage_data_reliability,0.057022,0.005120,11.135604,0.051903,961,94,0.057022,0.005120,11.135604,0.051903
8,video_display_failure,0.099686,0.017647,5.648582,0.082038,1680,324,0.099686,0.017647,5.648582,0.082038
4,connectivity_pairing_failure,0.164422,0.030556,5.380933,0.133866,2771,561,0.164422,0.030556,5.380933,0.133866
3,compatibility_fit_issue,0.166499,0.031536,5.279507,0.134963,2806,579,0.166499,0.031536,5.279507,0.134963
1,audio_device_failure,0.174331,0.053976,3.229744,0.120355,2938,991,0.174331,0.053976,3.229744,0.120355
5,input_control_failure,0.084258,0.030773,2.737956,0.053485,1420,565,0.084258,0.030773,2.737956,0.053485
6,physical_build_installation_failure,0.193200,0.070915,2.724363,0.122285,3256,1302,0.193200,0.070915,2.724363,0.122285
0,antenna_reception_failure,0.005815,0.002288,2.541307,0.003527,98,42,0.005815,0.002288,2.541307,0.003527

In [89]:
# Creating final dashboard-ready Electronics NLP analytical tables

price_band_order_map = {
    "Budget": 1,
    "Lower mid": 2,
    "Upper mid": 3,
    "Premium": 4,
    "Very premium": 5
}

bucket_order_map = {
    "charging_power_failure": 1,
    "connectivity_pairing_failure": 2,
    "storage_data_reliability": 3,
    "compatibility_fit_issue": 4,
    "physical_build_installation_failure": 5,
    "audio_device_failure": 6,
    "video_display_failure": 7,
    "input_control_failure": 8,
    "wearable_tracking_failure": 9,
    "antenna_reception_failure": 10
}

bucket_label_map = {
    "charging_power_failure": "Charging / Power Failure",
    "connectivity_pairing_failure": "Connectivity / Pairing Failure",
    "storage_data_reliability": "Storage / Data Reliability",
    "compatibility_fit_issue": "Compatibility / Fit Issue",
    "physical_build_installation_failure": "Physical Build / Installation Failure",
    "audio_device_failure": "Audio Device Failure",
    "video_display_failure": "Video / Display Failure",
    "input_control_failure": "Input / Control Failure",
    "wearable_tracking_failure": "Wearable Tracking Failure",
    "antenna_reception_failure": "Antenna / Reception Failure"
}

bucket_description_map = {
    "charging_power_failure": "Charging, battery, power-on, and power-supply reliability issues",
    "connectivity_pairing_failure": "Wireless, network, Bluetooth, pairing, and disconnect issues",
    "storage_data_reliability": "Drive, memory-card, formatting, recognition, and data-loss issues",
    "compatibility_fit_issue": "Fit, model, port, size, adapter, and compatibility mismatch issues",
    "physical_build_installation_failure": "Breakage, mounting, screws, case, protector, and installation friction",
    "audio_device_failure": "Headphone, earbud, speaker, microphone, static, no-sound, and distortion issues",
    "video_display_failure": "Monitor, display, camera, screen, flicker, no-signal, and recording issues",
    "input_control_failure": "Keyboard, mouse, remote, controller, button, lag, and response issues",
    "wearable_tracking_failure": "Smartwatch, tracker, heart-rate, sleep, step, and measurement issues",
    "antenna_reception_failure": "TV/radio antenna signal, reception, channel, and no-signal issues"
}

bucket_interpretation_df = (
    pd.DataFrame({"bucket_name": bucket_names})
    .assign(
        bucket_order = lambda df: df["bucket_name"].map(bucket_order_map),
        business_label = lambda df: df["bucket_name"].map(bucket_label_map),
        dashboard_description = lambda df: df["bucket_name"].map(bucket_description_map)
    )
    .sort_values("bucket_order")
    .reset_index(drop = True)
)

document_match_final_df = document_match_df.copy()

document_id_parts = document_match_final_df["document_id"].astype(str).str.split(r"\|", regex = True)

document_match_final_df["parent_asin"] = document_id_parts.str[4]

electronics_nlp_scope_quality_df = coverage_summary_df.copy()
electronics_nlp_scope_quality_df["evidence_scope"] = (
    "Validated rule-based issue buckets applied to comparison-eligible Electronics NLP documents"
)

electronics_nlp_validation_quality_df = (
    bucket_precision_df
    .merge(bucket_interpretation_df, on = "bucket_name", how = "left")
    .sort_values("bucket_order")
    .reset_index(drop = True)
)

electronics_nlp_false_negative_quality_df = false_negative_summary_df.copy()

electronics_nlp_bucket_overview_df = (
    bucket_summary_df[
        [
            "bucket_name",
            "dissatisfaction_document_count",
            "satisfaction_document_count",
            "dissatisfaction_ratio",
            "satisfaction_ratio",
            "lift_vs_satisfaction",
            "ratio_gap"
        ]
    ]
    .merge(bucket_interpretation_df, on = "bucket_name", how = "left")
)

electronics_nlp_bucket_overview_df["business_signal_type"] = np.select(
    [
        (electronics_nlp_bucket_overview_df["dissatisfaction_document_count"] < 100),
        (electronics_nlp_bucket_overview_df["lift_vs_satisfaction"] >= 8)
        & (electronics_nlp_bucket_overview_df["dissatisfaction_ratio"] >= 0.03),
        (electronics_nlp_bucket_overview_df["lift_vs_satisfaction"] >= 4)
        & (electronics_nlp_bucket_overview_df["dissatisfaction_ratio"] >= 0.03),
        (electronics_nlp_bucket_overview_df["dissatisfaction_ratio"] >= 0.08)
    ],
    [
        "Niche signal",
        "Strong dissatisfaction separator",
        "Moderate dissatisfaction separator",
        "Broad operational risk"
    ],
    default = "Supporting signal"
)

electronics_nlp_bucket_overview_df["evidence_level"] = np.select(
    [
        electronics_nlp_bucket_overview_df["dissatisfaction_document_count"] >= 1000,
        electronics_nlp_bucket_overview_df["dissatisfaction_document_count"] >= 300,
        electronics_nlp_bucket_overview_df["dissatisfaction_document_count"] >= 100
    ],
    ["High", "Moderate", "Limited"],
    default = "Low"
)

electronics_nlp_bucket_overview_df["interpretation_caution"] = np.select(
    [
        electronics_nlp_bucket_overview_df["dissatisfaction_document_count"] < 100,
        electronics_nlp_bucket_overview_df["satisfaction_document_count"] < 50
    ],
    [
        "Low volume; use as niche signal",
        "Small comparison baseline; interpret lift cautiously"
    ],
    default = "Suitable for business interpretation"
)

electronics_nlp_bucket_overview_df = (
    electronics_nlp_bucket_overview_df
    .sort_values(["bucket_order"])
    .reset_index(drop = True)
)

electronics_nlp_price_bucket_exposure_df = (
    document_match_final_df
    .groupby(["cohort_role", "price_band"], dropna = False)[bucket_names]
    .mean()
    .reset_index()
    .melt(
        id_vars = ["cohort_role", "price_band"],
        value_vars = bucket_names,
        var_name = "bucket_name",
        value_name = "bucket_exposure_ratio"
    )
    .pivot_table(
        index = ["price_band", "bucket_name"],
        columns = "cohort_role",
        values = "bucket_exposure_ratio",
        aggfunc = "mean",
        fill_value = 0
    )
    .reset_index()
    .rename(columns = {
        "Dissatisfaction": "dissatisfaction_exposure_ratio",
        "Satisfaction": "satisfaction_exposure_ratio"
    })
    .merge(bucket_interpretation_df, on = "bucket_name", how = "left")
)

electronics_nlp_price_bucket_exposure_df["lift_vs_satisfaction"] = (
    (electronics_nlp_price_bucket_exposure_df["dissatisfaction_exposure_ratio"] + 1e-6)
    / (electronics_nlp_price_bucket_exposure_df["satisfaction_exposure_ratio"] + 1e-6)
)

electronics_nlp_price_bucket_exposure_df["exposure_gap"] = (
    electronics_nlp_price_bucket_exposure_df["dissatisfaction_exposure_ratio"]
    - electronics_nlp_price_bucket_exposure_df["satisfaction_exposure_ratio"]
)

electronics_nlp_price_bucket_exposure_df["price_band_order"] = (
    electronics_nlp_price_bucket_exposure_df["price_band"].map(price_band_order_map)
)

electronics_nlp_price_bucket_exposure_df = (
    electronics_nlp_price_bucket_exposure_df
    .sort_values(["price_band_order", "bucket_order"])
    .reset_index(drop = True)
)

electronics_nlp_priority_bucket_exposure_df = (
    document_match_final_df
    .groupby(["cohort_role", "issue_priority_level"], dropna = False)[bucket_names]
    .mean()
    .reset_index()
    .melt(
        id_vars = ["cohort_role", "issue_priority_level"],
        value_vars = bucket_names,
        var_name = "bucket_name",
        value_name = "bucket_exposure_ratio"
    )
    .pivot_table(
        index = ["cohort_role", "bucket_name"],
        columns = "issue_priority_level",
        values = "bucket_exposure_ratio",
        aggfunc = "mean",
        fill_value = 0
    )
    .reset_index()
    .rename(columns = {
        "Monitor": "monitor_exposure_ratio",
        "Priority review": "priority_review_exposure_ratio"
    })
    .merge(bucket_interpretation_df, on = "bucket_name", how = "left")
)

electronics_nlp_priority_bucket_exposure_df["priority_lift_vs_monitor"] = (
    (electronics_nlp_priority_bucket_exposure_df["priority_review_exposure_ratio"] + 1e-6)
    / (electronics_nlp_priority_bucket_exposure_df["monitor_exposure_ratio"] + 1e-6)
)

electronics_nlp_priority_bucket_exposure_df["priority_gap_vs_monitor"] = (
    electronics_nlp_priority_bucket_exposure_df["priority_review_exposure_ratio"]
    - electronics_nlp_priority_bucket_exposure_df["monitor_exposure_ratio"]
)

electronics_nlp_priority_bucket_exposure_df = (
    electronics_nlp_priority_bucket_exposure_df
    .sort_values(["cohort_role", "bucket_order"])
    .reset_index(drop = True)
)

cooccurrence_rows = []

for cohort in sorted(document_match_final_df["cohort_role"].dropna().unique()):
    cohort_df = document_match_final_df.loc[document_match_final_df["cohort_role"].eq(cohort)]
    total_documents = len(cohort_df)

    for i, bucket_a in enumerate(bucket_names):
        for bucket_b in bucket_names[i + 1:]:
            both_count = int((cohort_df[bucket_a] & cohort_df[bucket_b]).sum())
            bucket_a_count = int(cohort_df[bucket_a].sum())
            bucket_b_count = int(cohort_df[bucket_b].sum())

            cooccurrence_rows.append({
                "cohort_role": cohort,
                "bucket_a": bucket_a,
                "bucket_b": bucket_b,
                "both_document_count": both_count,
                "bucket_a_count": bucket_a_count,
                "bucket_b_count": bucket_b_count,
                "total_documents": total_documents,
                "cooccurrence_ratio_total": both_count / total_documents if total_documents else 0,
                "cooccurrence_ratio_with_bucket_a": both_count / bucket_a_count if bucket_a_count else 0,
                "cooccurrence_ratio_with_bucket_b": both_count / bucket_b_count if bucket_b_count else 0
            })

electronics_nlp_bucket_cooccurrence_df = (
    pd.DataFrame(cooccurrence_rows)
    .merge(
        bucket_interpretation_df[["bucket_name", "business_label", "bucket_order"]].rename(
            columns = {
                "bucket_name": "bucket_a",
                "business_label": "bucket_a_label",
                "bucket_order": "bucket_a_order"
            }
        ),
        on = "bucket_a",
        how = "left"
    )
    .merge(
        bucket_interpretation_df[["bucket_name", "business_label", "bucket_order"]].rename(
            columns = {
                "bucket_name": "bucket_b",
                "business_label": "bucket_b_label",
                "bucket_order": "bucket_b_order"
            }
        ),
        on = "bucket_b",
        how = "left"
    )
    .sort_values(["cohort_role", "both_document_count"], ascending = [True, False])
    .reset_index(drop = True)
)

electronics_nlp_multibucket_intensity_df = (
    document_match_final_df
    .groupby(["cohort_role", "matched_bucket_count"], dropna = False)
    .size()
    .reset_index(name = "document_count")
)

electronics_nlp_multibucket_intensity_df = electronics_nlp_multibucket_intensity_df.merge(
    document_match_final_df
    .groupby("cohort_role", dropna = False)
    .size()
    .reset_index(name = "cohort_document_count"),
    on = "cohort_role",
    how = "left"
)

electronics_nlp_multibucket_intensity_df["document_ratio"] = (
    electronics_nlp_multibucket_intensity_df["document_count"]
    / electronics_nlp_multibucket_intensity_df["cohort_document_count"]
)

product_bucket_risk_df = (
    document_match_final_df
    .loc[document_match_final_df["cohort_role"].eq("Dissatisfaction")]
    .melt(
        id_vars = [
            "document_id",
            "parent_asin",
            "price_band",
            "issue_priority_level",
            "product_display_name"
        ],
        value_vars = bucket_names,
        var_name = "bucket_name",
        value_name = "has_bucket"
    )
    .loc[lambda df: df["has_bucket"]]
    .copy()
)

electronics_nlp_top_products_by_bucket_df = (
    product_bucket_risk_df
    .groupby(
        ["bucket_name", "parent_asin", "product_display_name", "price_band", "issue_priority_level"],
        dropna = False
    )
    .agg(dissatisfaction_document_count = ("document_id", "count"))
    .reset_index()
    .merge(bucket_interpretation_df, on = "bucket_name", how = "left")
    .sort_values(["bucket_order", "dissatisfaction_document_count"], ascending = [True, False])
)

electronics_nlp_top_products_by_bucket_df["bucket_product_rank"] = (
    electronics_nlp_top_products_by_bucket_df
    .groupby("bucket_name")["dissatisfaction_document_count"]
    .rank(method = "first", ascending = False)
    .astype(int)
)

electronics_nlp_top_products_by_bucket_df = (
    electronics_nlp_top_products_by_bucket_df
    .loc[lambda df: df["bucket_product_rank"] <= 10]
    .sort_values(["bucket_order", "bucket_product_rank"])
    .reset_index(drop = True)
)

print("Final analytical dataframes created.")

Final analytical dataframes created.

In [90]:
# Uploading final Electronics NLP dashboard tables to BigQuery
final_dashboard_tables = {
    "electronics_nlp_bucket_dictionary": bucket_interpretation_df,
    "electronics_nlp_scope_quality": electronics_nlp_scope_quality_df,
    "electronics_nlp_validation_quality": electronics_nlp_validation_quality_df,
    "electronics_nlp_false_negative_quality": electronics_nlp_false_negative_quality_df,
    "electronics_nlp_bucket_overview": electronics_nlp_bucket_overview_df,
    "electronics_nlp_price_bucket_exposure": electronics_nlp_price_bucket_exposure_df,
    "electronics_nlp_priority_bucket_exposure": electronics_nlp_priority_bucket_exposure_df,
    "electronics_nlp_bucket_cooccurrence": electronics_nlp_bucket_cooccurrence_df,
    "electronics_nlp_multibucket_intensity": electronics_nlp_multibucket_intensity_df,
    "electronics_nlp_top_products_by_bucket": electronics_nlp_top_products_by_bucket_df
}

load_job_config = bigquery.LoadJobConfig(
    write_disposition = bigquery.WriteDisposition.WRITE_TRUNCATE,
    autodetect = True
)

for table_name, dataframe in final_dashboard_tables.items():
    destination_table_id = (
        f"{configuration['gcp_project_id']}."
        f"{configuration['bigquery_core_dataset_id']}."
        f"{table_name}"
    )

    dataframe_to_upload = dataframe.copy()

    load_job = bigquery_client.load_table_from_dataframe(
        dataframe_to_upload,
        destination_table_id,
        job_config = load_job_config,
        location = configuration["bigquery_location"]
    )

    load_job.result()

    print(f"Uploaded {table_name} : {len(dataframe_to_upload):,} rows")

Uploaded electronics_nlp_bucket_dictionary : 10 rows
Uploaded electronics_nlp_scope_quality : 2 rows
Uploaded electronics_nlp_validation_quality : 10 rows
Uploaded electronics_nlp_false_negative_quality : 2 rows
Uploaded electronics_nlp_bucket_overview : 10 rows
Uploaded electronics_nlp_price_bucket_exposure : 50 rows
Uploaded electronics_nlp_priority_bucket_exposure : 20 rows
Uploaded electronics_nlp_bucket_cooccurrence : 90 rows
Uploaded electronics_nlp_multibucket_intensity : 12 rows
Uploaded electronics_nlp_top_products_by_bucket : 100 rows